### ISSUE TITLE
Re-Instate OpenShift access

### ISSUE THREAD

**Issue by LindsayMacfarlane** [BCDevOps/devops-requests#1000]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**
Product Owner

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access (re-instate access)
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Lindsay Macfarlane
* GitHub ID: LindsayMacfarlane
* Business Email Address: Lindsay.Macfarlane@gov.bc.ca
* Organization: ENV, IITD
* Project Role: Product Owner

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @mitovskaol - can you please approve this request?
