### ISSUE TITLE
provision access to WIST 

### ISSUE THREAD

**Issue by tim-gerhardt** [BCDevOps/devops-requests#1004]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**
Product owner, requesting for me and technical lead (with advice from Olena M)

We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request. 

**Do you have a GitHub account?**
Yes

If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Tim Gerhardt and Jack Tang
* GitHub ID: tim-gerhardt and jinchuantang
* Business Email Address: tim.gerhardt@gov.bc.ca and jack.tang@gov.bc.ca
* Organization: AEST
* Project Role: Product owner and Technical Lead

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
The invitations to join bcgov and BCDevOps orgs in GitHub have been sent to the users above. Once the invitations are accepted, the users will be added to the orgs.
