### ISSUE TITLE
Access to OCP3 orphaned project set ido-bceala

### ISSUE THREAD

**Issue by crigdongov** [BCDevOps/devops-requests#1012]
Request access to below namespaces in order to migrate to ocp4.  I have access to tools but require access to dev test and prod.  Thanks

ido-bceala-dev
ido-bceala-prod
ido-bceala-test

Github user: crigdongov
Org: DATABC Devops

**Comment by caggles** [comment]
Hey @crigdongov - there are a couple of people listed as admins in these namespaces. May I ask why they're unable to give you the needed access?

**Comment by crigdongov** [comment]
@caggles   Can you identify those and I will then ask.  No dev ops folks currently in our group has any visibility.  And Looking to migrate this app off OCP3 ASAP.

**Comment by caggles** [comment]
Since some teams like to keep this information fairly private, I will be sending this to you on RC!

**Comment by crigdongov** [comment]
Thanks @caggles , i have reached out to previous admin and they so kindly granted me admin access. closing ticket.
