### ISSUE TITLE
Add Stuart Gendron (Arctiq) to BCDevOps group for OpenShift Access

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/devops-requests#1018]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**
I am the Technical Lead for Arctiq

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Stuart Gendron
* GitHub ID: stu-gee
* Business Email Address: stuart.gendron@arctiq.ca
* Organization: Arctiq
* Project Role: Technical Delivery

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
stu-gee has been invited to bcgov and BCDevOps orgs.
