### ISSUE TITLE
PIMS 

### ISSUE THREAD

**Issue by mbertucci** [BCDevOps/devops-requests#103]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

OpenShift User Access Request:
- Full name: Jeremy Foster
- GitHub ID: fosol
- Email address: jeremy.foster@quartech.com 
- Organization: MoCS
- Project role: Full-stack Developer, DevOps Specialist
- OpenShift projects: PIMS – Property Information Management System

- Full name: Devin Smith
- GitHub ID: devinleighsmith
- Email address: devin.smith@quartech.com 
- Organization: MoCS
- Project role: Full-stack Developer, DevOps Specialist
- OpenShift projects: PIMS – Property Information Management System

- Full name: Alejandro Sanchez Ravelo
- GitHub ID: asanchezr
- Email address: Alejandro.SanchezRavelo@quartech.com
- Organization: MoCS
- Project role: Full-stack Developer, DevOps Specialist
- OpenShift projects: PIMS – Property Information Management System

- Full name: Hari Chodagam
- GitHub ID: harichodagam
- Email address: Hari.Chodagam@quartech.com 
- Organization: MoCS
- Project role: Quality Assurance Tester
- OpenShift projects: PIMS – Property Information Management System

- Full name: Christine Park
- GitHub ID: christinepark1
- Email address: christine.park@quartech.com
- Organization: MoCS
- Project role: UX Designer, Quality Assurance
- OpenShift projects: PIMS – Property Information Management System

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
FYI, Devin Smith and Alejandro Sanchez Ravelo were already in the github org, so should already have access to Openshift!
