### ISSUE TITLE
Request for PIMS Open Shift Project 

### ISSUE THREAD

**Issue by mbertucci** [BCDevOps/devops-requests#104]
****************
**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.
 
## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project
 
 
## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
 
 
## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set
 
## Step 4
Fill out the following fields
 
* Short Team/Organization Name: PIMS
* Product Short Name: PIMS
* Product Full Name: Property Inventory Management System
* Product Description: GeoSpatial Real Estate Inventory System
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/PIMS
 
## Step 5
Submit this ticket and email us the contact information.
 
For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca
 
* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID:  Fosol
  - Business Email Address: jeremy.foster@gov.bc.ca
  - RocketChat Account Username: jeremy.foster
 
* Product Owner
  - Business Email Address: (BCGov employee) Mikaela.bertucci@gov.bc.ca           
  - RocketChat Account Username: Mikaela.Bertucci
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)
 
* BC Government Security Contact Information
  - Ministry Chief Information Officer: Ian Donaldson
 - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)
 
  - Ministry Information Security Officer: Garry Mierzuak
 
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)
 
  - Ministry Privacy Officer: Heather Dunlop
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)
 
 
Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
@mbertucci the request is missing the following for the product owner:
- Organization Code
- Organization Unit Code

**Comment by ShellyXueHan** [comment]
Project set created as `jcxjin-tools`, `jcxjin-dev`, `jcxjin-test`, `jcxjin-prod`. `Fosol` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.
