### ISSUE TITLE
Red Hat SSO Team new member needs BCGov Org Membership

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [BCDevOps/devops-requests#1042]
## Step 0

**Are you looking for access to the Openshift Console?**
Yes. Opened another ticket for that.

**Are you the Technical Lead?**
Yes

**Do you actually need the team member to be a member of the organization?**
Yes, he is a devops engineer on the SSO team and will need access to the platform

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: RedHat SSO Ops Team
* GitHub Org: bcgov
* Full Name: Bezawada, Ravi Kumar
* GitHub ID: @ravibezawada

* GitHub Account 2FA Confirmed: yes
* Email address: 
* Organization: CGI
* Project Role: DevOps Engineer
* GitHub Team to Join (if exists): Already added to sso-ops (by me)
* Existing GitHub Repo: 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
github team invitation includes org membership so you're all good there!
