### ISSUE TITLE
Please Remove Account from Keycloak

### ISSUE THREAD

**Issue by rarmitag** [BCDevOps/devops-requests#1047]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes, 
Richard Armitage  realm Fcf0kpqr

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
He is unable to use our applications. When he tries to login, keycloak doesn't provide our application with any roles for him. 
I have deleted and then added his account without success.
He gets the error message:  "user name already exists." when trying to add his account into keycloak

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes, he's confirmed.

## Step 3
Field the following information.

* Username to be removed: 
* Realm ID where user is having problem login: 
* Environment in which you are facing issue: 

Patrick Heath / paheath 
Fcf0kpqr
dev

**Comment by nvunnamm** [comment]
Account has been removed please verify.
