### ISSUE TITLE
revoke bcgov access for blueQcloud

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#106]
Requesting to:
- [] Invite a user
- [x] Remove a user

* Project Name: CleanBC Industrial Incentive Program
* GitHub Org: bcgov
* Full Name: Helen Liu
* GitHub ID: [@blueQcloud](https://github.com/blueQcloud)
* GitHub Account 2FA Confirmed: yes
* Email address: helen@button.is
* Organization: Button Inc. (for Climate Action Secretariat)
* Project Role: Developer
* GitHub Team to Join (if exists): cas-developers
* Existing GitHub Repo: https://github.com/orgs/bcgov/teams/cas-developers/repositories

**Comment by ShellyXueHan** [comment]
User removed from bcgov and bcdevops.
