### ISSUE TITLE
Request to add Github IDP to existing realm

### ISSUE THREAD

**Issue by sumesh-aot** [BCDevOps/devops-requests#1065]
## Step 0
**Are you the product owner or project admin/team lead?**
Yes

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  
IDIR : SKARIYIL

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.
YES

**Note:** This SSO service is undergoing upgrades in 2021 and is currently not recommended for critical applications. Support is currently available only during business hours and only on a best efforts basis. If your application is critical, please contact Web Access Management (WAM) and/or Provincial Identity Information Management Program (IDIM).

## Step 1
Are you new to Single Sign-On (Keycloak)? 
If so, please indicate that in Step 4, we will setup a meeting with you and your team for an onboarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will create the initial account on Keycloak.

- https://dev.oidc.gov.bc.ca/auth/admin/idir/console
- https://test.oidc.gov.bc.ca/auth/admin/idir/console
- https://oidc.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, the Realm Admin User will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: BC Registries Online Services

* OpenShift Project Set/s Info
  - Project set name:  6e0e49-dev, 6e0e49-test, 6e0e49-prod, 6e0e49-tools
  - Namespace ID: 6e0e49

* For existing Keycloak realm update only
  - Realm ID: fcf0kpqr
  - Identity Provider to Add
    - [ ] BCeID (Basic, Business, Business and Basic)
    - [x] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by nvunnamm** [comment]
New IDP github has been added. Please verify.
