### ISSUE TITLE
Please add Openshift Access for Denis

### ISSUE THREAD

**Issue by jhamidi** [BCDevOps/devops-requests#1068]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**
We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.
YES

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.
YES

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.
YES

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Denis Klein
* GitHub ID: denis-klein
* Business Email Address: denis.klein@maximusbc.ca
* Organization: Maximus
* Project Role: Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
invited to bcdevops :) he should have access to OCP now

**Comment by jhamidi** [comment]
Denis is still having an issue with access to openshift console.  When he tries the url:
https://console.apps.silver.devops.gov.bc.ca
It takes him to github's devops-requests page.  I checked his github settings, looked ok to me (2 step auth).

I have granted him access to our oc4 projects, so that's not the problem.

**Comment by ShellyXueHan** [comment]
@jhamidi I've sent out an invite to `denis-klein` for bcdevops github org.

**Comment by denis-klein** [comment]
FYI:

Apparently 4 (possibly 5) invites have been made, but I received only two of them. Both successful ones have been from Patrick.

The first one was on April 29th. I didn't act on it and it expired. Reasons for not acting on it:
- I didn't know who Patrick was at that time (and his github account doesn't clearly indicate his association with BC government)
- I needed OpenShift access and the invite said nothing about OpenShift. At that time I wasn't aware that being member of BCDevOps is a prerequisite. Besides, the subject of the invite email started with "[Newsletter]"

In the last week or so I have been trying things with my github account, namely adding organization, set up backup email and make primary email public. Yesterday I returned the account to the same settings it was when I received the initial invite.

Today I received a second invite from Patrick and that one worked.

Seems like the primary email address needs to be private for invites to work (Profile > Settings > Emails > Keep my email addresses private).
