### ISSUE TITLE
Grant OpenShift access

### ISSUE THREAD

**Issue by csherman-gov** [BCDevOps/devops-requests#109]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

ull name: Joseph Jin

GitHub ID: josephBelmar
Email address: joseph.jin@belmar.ca
Organization: Belmar
Project role: Full-stack Developer
OpenShift projects: qjtfov - all environments
Full name: Arthur Newman

GitHub ID: arthur-newman-belmar
Email address: arthur.newman@belmar.ca
Organization: Belmar
Project role: Full-stack Developer
OpenShift projects: qjtfov - all environments
Full name: Ryan Draper

GitHub ID: r-draper-pwc
Email address: ryan.w.draper@pwc.com
Organization: PWC
Project role: Admin, Full-stack Developer
OpenShift projects: qjtfov - all environments

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@csherman-gov all users invited to join BCDevOps GitHub organization. This will grant them access to the OpenShift console. Namespace admin user need to further invite them.
