### ISSUE TITLE
Please remove duplicate user IDIR mchaffee.  

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1094]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes I am admin for realm vtkayq4c

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
The user mchaffee is a new user to Service BC and cannot login to The Q Dev/Ops application.  On initial login the keycloak user id will be created in our realm vtkayq4c but this is not happening. The application insists that the user is not setup.  

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes IDIR mchaffee is ready to be removed from Keycloak.

## Step 3
Field the following information.

* Username to be removed: mchaffee
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Production

**Comment by nvunnamm** [comment]
User has been removed. Please verify.
