### ISSUE TITLE
Request User Access

### ISSUE THREAD

**Issue by pdittaro** [BCDevOps/devops-requests#11]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Peggy Zhang
* GitHub ID: @peggy-gov-bc-ca
* Business Email Address: Peggy.Zhang@nttdata.com
* Organization: Sierra Systems
* Project Role: Developer
* OpenShift Projects/Namespaces: 
    frjeow-dev
    frjeow-prod
    frjeow-test
    frjeow-tools

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
hey @pdittaro - peggy is already a member of the bcdevops organization, which is all that's necessary to access openshift. If you would like to add her to your project, your project admin can do that!
