### ISSUE TITLE
Request to remove wlev6y OCP 3 project set

### ISSUE THREAD

**Issue by BrandonSharratt** [BCDevOps/devops-requests#1105]
## Step 0
**Are you the Product Owner or Technical Lead?**
Yes

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
No -- This was a demo workload and no longer needed.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Yes

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
Yes

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

No duplicate exists

## Step 2
Confirm that you are aware that you are requesting to:
- [x] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

## Step 3
Please provide the names of the namespaces to be deleted in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.

wlev6y-dev
wlev6y-test

(To my knowledge tools and prod do not exist for this namespace)

**Comment by patricksimonian** [comment]
@BrandonSharratt tools and prod do exist :) can you confirm that you want those deleted?

**Comment by patricksimonian** [comment]
@BrandonSharratt am i okay to delete all namespaces?

**Comment by mitovskaol** [comment]
@patricksimonian if the prod and tools are empty, please go ahead and delete them.

**Comment by patricksimonian** [comment]
deleted
