### ISSUE TITLE
Request: OpenShift Project for Wildfire Predictive Services

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#111]
## Preemptive TL;DR
- Short team/organization name: ENV
- Product short name: WPS
- Product full name: Wildfire Predictive Services
- Product description: Wildfire Predictive Services to support decision making in prevention, preparedness, response and recovery.
- Desired environments: tools, dev, test, prod
- Product Technical Steward: DerekRoberts / Derek.Roberts@gov.bc.ca / Derek
- Product Owner: Brady.Holliday@gov.bc.ca / brady.holliday
- GitHub repo: -please provide one-

---

## Step 0
**Are you the product owner or technical lead?**
- [x] Sort of!  I'm acting as technical lead for the moment.  Team members are still coming aboard.

**Have you had an alignment meeting?**
- [x] Scheduled for Thursday, January 16th.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project
- [x] Done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
- [x] Done

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields
* Short Team/Organization Name: ENV
* Product Short Name: WPS
* Product Full Name: Wildfire Predictive Services
* Product Description: Wildfire Predictive Services to support decision making in prevention, preparedness, response and recovery.
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): 
- [x] Done! No GitHub repo is known to exist.

## Step 5
Submit this ticket and email us the contact information.
- [x] Done

**Comment by kelpisland** [comment]
@DerekRoberts  - I don't see the alignment meeting in my calendar, did I miss something/the meeting?

**Comment by DerekRoberts** [comment]
@kelpisland It was snowed out.  I'll pass along a reminder to book another.

**Comment by DerekRoberts** [comment]
@kelpisland Now that the meeting happened is this request back on track?

**Comment by ShellyXueHan** [comment]
Project set created as `auzhsi-tools`, `auzhsi-dev`, `auzhsi-test`, `auzhsi-prod`. `DerekRoberts` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.

**Comment by DerekRoberts** [comment]
@ShellyXueHan Thanks for setting that up!  Is a GitHub repo on the way?
