### ISSUE TITLE
OCP4 namespace corrections

### ISSUE THREAD

**Issue by mark-walle** [BCDevOps/devops-requests#1112]
Creating as a generic request per @patricksimonian recommendation in https://chat.developer.gov.bc.ca/channel/devops-how-to?msg=P5ydaktNXa7buuExc 

This project: https://registry.developer.gov.bc.ca/profile/224/overview with namespace prefix `4019aa` can be removed from OCP4. It is no longer being used since the project "CAPS Analytics Gateway" was recently migrated from OCPv3.11 into OCP4 which required @jleach to a new namespace for it.

>_**(this part was done in https://github.com/BCDevOps/devops-requests/issues/1112#issuecomment-849194618):**_
> After deleting that then this project https://registry.developer.gov.bc.ca/profile/381/overview with namespace prefix `8gsiqa`: should have it's:
> - name changed from "CAPS Analytics Gateway Duplicate" to "CAPS Analytics Gateway" 
> - Product Owner changed from "Mark Walle mark.walle@gov.bc.ca @mark-walle " to "Dan Pollock dan.pollock@gov.bc.ca @danpollock "
> - Technical Contact changed from "Dan Pollock dan.pollock@gov.bc.ca @danpollock " to "Mark Walle mark.walle@gov.bc.ca @mark-walle "

**Comment by mark-walle** [comment]
@caggles can any of this be resolved soon?

I feel like at least switching mine and Dan's name as product owner and technical owner in https://registry.developer.gov.bc.ca/profile/381/overview for `8gsiqa` could be perhaps done more easily than deleting the entire `4019aa`.

Should I make this two separate tickets to possibly get parts of this out the door sooner?

**Comment by mitovskaol** [comment]
@mark-walle  We do not have a project deletion feature within the Project Registry yet so can't delete the `4019aa` project just yet.  The ability to update the project name is coming this Sprint and should be implemented by June 8. You can , however, change a PO and a Tech Lead for a project right now on the project details page in the Project Registry. Can you give it a try and let me know if it worked? Please keep in mind, that the removed PO/Tech Lead will lose access to the project namespaces in the Openshift whereas the new PO/Tech Lead will be granted the admin access.

**Comment by mark-walle** [comment]
@mitovskaol 

> Can you give it a try and let me know if it worked?

That did work. Thanks.

**Comment by jleach** [comment]
@mark-walle I'll update the record so that `4019aa` shows up on my dashboard and then update the PO and TC to myself so that you no longer have access. Then, once delete (archive really) is implemented I'll do that. Work for you?

**Comment by mark-walle** [comment]
@jleach that works for me thanks.

**Comment by patricksimonian** [comment]
@mark-walle @jleach is this ticket okay for closure?

**Comment by jleach** [comment]
@patricksimonian Not just yet. I still need to do a bit of work. Tracking it via BCDevOps/developer-experience#1140

**Comment by mitovskaol** [comment]
@jleach I am looking through some old tickets and came across this one , looks like Dan and Mark are shill showing up as PO and TC for this project.

**Comment by jleach** [comment]
Ok. I've moved this to my account and set the PO and TC to myself. This is all we can do to "delete" a project right now. Once we can archive/delete a project I'll remove them from my profile so they no longer exists are are un-provisioned.
