### ISSUE TITLE
Remove BCGOV GitHub Organization Membership 

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevOps/devops-requests#1118]
This request is to remove @parulmishra from bcgov GitHub org membership as she has resigned from the BC Public Service.

**Are you the Technical Lead?**
I am not, but am the acting Product Owner for bcgov/**digital.gov.bc.ca** and bcgov/**bcdevexchange**. I report to @SteveChapmanBCDX who can confirm this request.

Are you requesting to:
- [ ] Invite a user
- [x] Remove a user

* Project Name: digital.gov.bc.ca and bcdevexchange.org
* GitHub Org: bcgov 
* Full Name: Parul Mishra Dubedy
* GitHub ID: @parulmishra 
* GitHub Account 2FA Confirmed: yes
* Email address: Parul.Dubedy@gov.bc.ca
* Organization: CITZ, Strategic Design & Delivery Branch
* Project Role: Developer
* Existing GitHub Repo: bcgov/**digital.gov.bc.ca** and bcgov/**bcdevexchange**

cc @SteveChapmanBCDX @thegentlemanphysicist

**Comment by SteveChapmanBCDX** [comment]
I confirm @mark-a-wilson's request as submitted.

**Comment by NickCorcoran** [comment]
Removal complete.

**Comment by NickCorcoran** [comment]
Also removed from BCDevOps org.  Confirmed with Mark Wilson.
