### ISSUE TITLE
Add and remove users / OCP4 namespace for bcdevexchange site

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevOps/devops-requests#1119]
**Are you the product owner or technical lead?**
I am the product owner for bcdevexchange.org (bcgov/bcdevexchange repo), but I never received or requested access to its OCP4 namespace (so I don't know what the namespace is, sorry -- @jleach will know). It was being managed by our developer @parulmishra and most recently @jleach who jumped in to migrate the project from OCP3 to 4.  @parulmishra has resigned from the public service. 

Request is to:
1. remove @parulmishra 
2. add @thegentlemanphysicist 

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

### Request 1 - remove Parul Dubedy
Are you requesting to:
- [ ] grant user access
- [x] remove user access

* Full Name: Parul Mishra Dubedy 
* GitHub ID: @parulmishra (presume OCP4 username is parulmishra@github)
* Business Email Address: Parul.Dubedy@gov.bc.ca (now expired)
* Organization: CITZ, Strategic Design & Delivery Branch
* Project Role: Developer

### Request 2 - add Jonathan Sharman
Are you requesting to:
- [x] grant user access
- [ ] remove user access

* Full Name: Jonathan Sharman 
* GitHub ID: @thegentlemanphysicist (OCP4 username is thegentlemanphysicist@github)
* Business Email Address: Jonathan.Sharman@gov.bc.ca (now expired)
* Organization: CITZ, Strategic Design & Delivery Branch
* Project Role: Developer

cc @SteveChapmanBCDX

**Comment by ShellyXueHan** [comment]
@mark-a-wilson Jon and Parul has been added/removed from the github organizations already. It's up to the team tech lead (namespace admin user) to manage the namespace access. Let us know if you need further help!

**Comment by SteveChapmanBCDX** [comment]
@ShellyXueHan  - Thanks for following up here.

@thegentlemanphysicist - Can you confirm that you have admin access to the four `bcdevexchange.org` OCP4 namespaces (dev/test/prod/tools)?

**Comment by thegentlemanphysicist** [comment]
@SteveChapmanBCDX  and @ShellyXueHan  I do not have access to the BCDevExchange namespaces.  My OCP4 username is thegentlemanphysicist@github

**Comment by jleach** [comment]
I can do this. I provisioned the namespaces. 

@mark-a-wilson This shows up on my dashboard ATM. Can I transfer it to someone else? That way you can make these changes as needed.

**Comment by SteveChapmanBCDX** [comment]
@jleach - Thanks for your help here.  I'm the incoming PO for this application.  You can transfer admin responsibilities to me and I'll set up access for the tech lead.

My GitHub handle is @SteveChapmanBCDX.
