### ISSUE TITLE
BCPARKS KeyCloak realms logged into by DBAYNE@IDIR

### ISSUE THREAD

**Issue by dbayne** [BCDevOps/devops-requests#112]
DBAYNE has logged into the 3 urls/realms and now needs to be granted full access to the security admin console. Thanks!

**Comment by caggles** [comment]
Hi @dbayne, can you please clarify this request? I'm not sure what you're asking for.

**Comment by dbayne** [comment]
Sorry, process is new to me. So when I log in to the provided realms, I am logged in, but I don't see ability to administer the security console.
example dlvr realm: https://sso-dev.pathfinder.gov.bc.ca/auth/admin/olq53fhr/console/

and I chose IDIR to log in and I just get Manage Account and Server Info options...

**Comment by ShellyXueHan** [comment]
Just double checked on your request, `JECARD` was assigned as the admin of the realms. Any further access request should be managed by the admin user.

**Comment by dbayne** [comment]
JECARD gets the same options as I do, Manage Account, Server Info, and Sign Out.

**Comment by ShellyXueHan** [comment]
could you ask `JECARD` to clear all cache and try again? He's account has the correct setting.
