### ISSUE TITLE
Openshift access for new developer

### ISSUE THREAD

**Issue by SteveMHoward** [BCDevOps/devops-requests#1120]
## Step 0
**Are you the product owner or technical lead?**
Yes

**Do you have a GitHub account?**
yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Craig Robertson
* GitHub ID:  CR-gbc
* Business Email Address: Craig.Robertson@gov.bc.ca
* Organization: GDX
* Project Role:  Full-stack developer

**Comment by mitovskaol** [comment]
The invites have been sent.
