### ISSUE TITLE
Request for BCGOV GitHub Organization Membership: lindamah

### ISSUE THREAD

**Issue by mark-walle** [BCDevOps/devops-requests#1123]
## Step 0

**Are you looking for access to the Openshift Console?**
No

**Are you the Technical Lead?**
Yes

**Do you actually need the team member to be a member of the organization?**
Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation
Done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
Done

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: (there are multiple projects)
* GitHub Org: bcgov
* Full Name: Linda Mah
* GitHub ID: @lindamah
* GitHub Account 2FA Confirmed: yes
* Email address: Linda.Mah@gov.bc.ca
* Organization: GDX Analytics
* Project Role: Business Analyst
* GitHub Team to Join (if exists): gdx-analytics-admin
* Existing GitHub Repo: (see https://github.com/orgs/bcgov/teams/gdx-analytics-admin/repositories )

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by NickCorcoran** [comment]
Invitation sent.
