### ISSUE TITLE
Test Clients for IIT

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/devops-requests#1125]
**PLEASE NOTE THAT WE ARE NOT ONBOARDING NEW TEAMS UNTIL AFTER JUNE 1, 2021**

**If you have an urgent request, please contact our Product Owner at Vardhman.Shankar@gov.bc.ca**

## Step 0
**Are you the product owner or project admin/team lead?**
Yes

**Does the Admin User have an IDIR account?**
Yes.

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.
No.

**Note:** This SSO service is undergoing upgrades in 2021 and is currently not recommended for critical applications. Support is currently available only during business hours and only on a best efforts basis. If your application is critical, please contact Web Access Management (WAM) and/or Provincial Identity Information Management Program (IDIM).

## Step 1
Are you new to Single Sign-On (Keycloak)? 
No, but I'd still like an onboarding meeting (just me, no other team members).

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will create the initial account on Keycloak.

- https://dev.oidc.gov.bc.ca/auth/admin/idir/console
- https://test.oidc.gov.bc.ca/auth/admin/idir/console
- https://oidc.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, the Realm Admin User will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: 
DDS Portfolio

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - Namespace ID:
245e18-dev, 245e18-test, 245e18-prod

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by brycereid73** [comment]
@garywong-bc 
Hi Gary,
I'm the scrum master for the SSO team. 

I had a look and you have several realms. We wanted to confirm what you needed. If you are looking for a new Realm, we have implemented a new policy and are only updating existing realms or add new customers/clients into the standard realms. If you'd like more details, Var posted a notification in the RocketChat SSO channel. 

My apologies for the delay in responding. Can you help me out with the details of your request? I see that you'd like a 1:1 onboarding, but I wasn't sure if you were looking for a realm or client. 

Thanks,
Bryce

**Comment by garywong-bc** [comment]
hi @brycereid73 no worries on the delay.. as the DevOps Chapter Lead for the sector, I'm often trying out thing to prove them out (e.g. Cypress.io that uses a TEST Keycloak account, Metabase SSO integration, Fider SSO integration, Drupal SSO integration)... so for that I need a realm where I'm admin so that I can test things out.. none of my tasks will go directly to PROD but will set the direction for other projects...

**Comment by nvunnamm** [comment]
test client has been provisioned.

**Comment by garywong-bc** [comment]
Hi did this TEST realm end up being `dds-portfolio`?  If so I'd like to request the PROD/DEV levels next... here is the completed submission.  Thanks! Gary 

* Organization Details (Organization/Division/Branch/Program):  FLNRORD/Coast Area/ FrontCounter BC
 
* **Executive Sponsor** Name, Title, & Email: Bagha, Kiran IIT:EX <Kiran.Bagha@gov.bc.ca>
 
* **Project Manager / Business Lead** Name, Title, & Email: Karra Farch, Business Application Analyst  Karra.Farch@gov.bc.ca
* **Technical Lead** (if applicable) Name, Title, & Email:  Chris Cocker, Senior Technical Analyst/Optimization Lead, Chris.Cocker@gov.bc.ca
* Name of service or application: FrontCounterBC Fider
* URL of service or application: https://fcbcfider.apps.silver.devops.gov.bc.ca/
* Estimated volume of initial users:
Stage 1: FLNR FrontCounter BC Technical Support Team – 6 users to populate pre-existing enhancement/feedback data into the system and test out all functionality
Stage 2: Expanding to FLNR FrontCounter BC Provincial Team including Contact Center – 42 additional users
Stage 3: Expanding to FLNR FrontCounter BC All Staff - 458 additional users
Stage 4: Expanding to additional working groups outside of FLNR FrontCounter BC All Staff that have valuable input on the various systems – estimated at an additional 50+ users
 
* Forecast of anticipated growth over the next three years: Up to 1000 internal government staff users
* Date of release in production environment: ASAP – est. September 1st, 2021
* Date of first use by citizens or end users: No citizen use, IDIR verified users only, est. September 1st, 2021
