### ISSUE TITLE
Request for BCGOV GitHub Org Membership - brianna.goulet@gov.bc.ca

### ISSUE THREAD

**Issue by Tariq-C** [BCDevOps/devops-requests#1126]
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

* Project Name: Teams Q&A Bot
* GitHub Org: bcgov
* Full Name: Brianna Goulet
* GitHub ID: @BNGoulet
* GitHub Account 2FA Confirmed: yes
* Email address: brianna.goulet@gov.bc.ca
* Organization: OCIO, Enterprise Communications
* Project Role: Developer
* GitHub Team to Join (if exists): ECS
* Existing GitHub Repo: Teams Q&A Bot

**Comment by NickCorcoran** [comment]
Invitation sent.
