### ISSUE TITLE
OpenShift Project for Dynamics Administration Tool

### ISSUE THREAD

**Issue by ChrisHoban** [BCDevOps/devops-requests#113]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
Yes

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.
Got Full Approval/Alignment 

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project
Done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
None

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

New Project Request:

Short team/organization name: Information Systems Branch
Product short name: Dynamics Administration and Licensing Tool Phase 1
Product full name: Dynamics Administration and Licensing Tool Phase 1
Product description: Phase one would provide a dashboard in Dynamics that makes it easy to add and remove users
Desired environments: tools, dev, test, prod
Product Technical Steward: Ryan Loiselle / Ryan.Loiselle@gov.bc.ca
Product Owner: Marilyn Simpson / Marilyn.Simpson@gov.bc.ca
GitHub repo: https://github.com/bcgov/maltd

**Comment by caggles** [comment]
just waiting on a response to the email thread asking for some additional information.
