### ISSUE TITLE
OpenShift access for new developers

### ISSUE THREAD

**Issue by tschia** [BCDevOps/devops-requests#1130]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**
Yes

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields
_Note: multiple developers requested. If you prefer this to be submitted as separate issues just let me know!_

* Full Name: Anumeha Srivastava
* GitHub ID: AnumehaSrivastava05
* Business Email Address: anumeha.srivastava@cgi.com
* Organization: CGI for Ministry of Health
* Project Role: Developer
----------------------------------------
* Full Name: Pankaj Kathuria
* GitHub ID: pankaj-cgi
* Business Email Address: pankaj.kathuria@cgi.com
* Organization: CGI for Ministry of Health
* Project Role: Developer
----------------------------------------
* Full Name: David Barrett 
* GitHub ID: daveb-hni
* Business Email Address: dave.p.barrett@cgi.com
* Organization: CGI for Ministry of Health
* Project Role: Developer
----------------------------------------
* Full Name: Wes Kubo 
* GitHub ID: weskubo-cgi
* Business Email Address: wesley.kubo@cgi.com
* Organization: CGI for Ministry of Health
* Project Role: Developer
----------------------------------------
* Full Name: Patrick Weckermann 
* GitHub ID: pweckermann
* Business Email Address: patrick.weckermann@cgi.com
* Organization: CGI for Ministry of Health
* Project Role: Architect

**Comment by NickCorcoran** [comment]
Invitations sent for all to BCDevOps org.
