### ISSUE TITLE
Request to join bcgov GitHub org

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#1131]
## Step 0

**Are you looking for access to the Openshift Console?**
**No**

**Are you the Technical Lead?**
**Yes**

**Do you actually need the team member to be a member of the organization?**
**Yes**

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

We would like to add two of our team members to the bcgov GitHub Org:

Person 1: ----
* Project Name: **NO SPECIFIC PROJECT** 
* GitHub Org: **bcgov**
* Full Name: **Lucas O'Neil**
* GitHub ID: **loneil**
* GitHub Account 2FA Confirmed: **yes**
* Email address: **Lucas.Oneil@gov.bc.ca**
* Organization: **IIT**
* Project Role: **Full-stack developer**
* GitHub Team to Join (if exists): **n/a**
* Existing GitHub Repo: **Lucas has been employed  in his current role for over two years and is currently contributing to over 10 repos in the bcgov org.**

Person 2: ----
* Project Name: **NO SPECIFIC PROJECT** 
* GitHub Org: **bcgov**
* Full Name: **Mina Kang**
* GitHub ID: **mkang06**
* GitHub Account 2FA Confirmed: **yes**
* Email address: **Mina.Kang@gov.bc.ca**
* Organization: **IIT**
* Project Role: **UX Researcher**
* GitHub Team to Join (if exists): **n/a**
* Existing GitHub Repo: **Mina has been employed  in her current role for over 1 year and is currently contributing to our team's repos in the bcgov org**

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by NickCorcoran** [comment]
Invitations sent.
