### ISSUE TITLE
Please create storage buckets for rocket chat uploads in corporate object storage

### ISSUE THREAD

**Issue by jleach** [BCDevOps/devops-requests#1133]
## Description

Please create upload buckets for Rocket Chat in the corporate object storage. Looking for something like `rocketchat-uploads-dev/test/prod`. If size matters I think about 12G for prod to start and 1G each for dev/test.

Add prod credentials as a secret with my name it it. I'll put them into kustomize and soon into Vault for safe keeping.

## Done When

- [ ] Three buckets exists, one for each of dev, test and prod. Credentials accessible.

**Comment by caggles** [comment]
Done! You'll find the secret for prod in the prod namespace, and one secret for both dev and test in the test namespace!
