### ISSUE TITLE
Request to add user access to Openshift

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#1134]
Hi there. I'm requesting access for a new contractor who has just joined our team.
Thank you!

## Step 0
**Are you the product owner or technical lead?**
Yes

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Michael Chung
* GitHub ID: MichaelChung123
* Business Email Address: michael.chung@avocette.com
* Organization: Avocette
* Project Role: Full Stack Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by NickCorcoran** [comment]
Invitation sent.
