### ISSUE TITLE
Request for adding or removing OpenShift access for Open school BC

### ISSUE THREAD

**Issue by aamir569** [BCDevOps/devops-requests#1139]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**
We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: 
* GitHub ID: 
* Business Email Address: 
* Organization: 
* Project Role: 

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by aamirislam90** [comment]
Thanks for the quick reply. The answer to those fields are:

Full Name: Aamir Islam
GitHub ID: aamirislam90
Business Email Address: aamir.islam@gov.bc.ca
Organization: OpenSchool BC Ministry of Education
Project Role: Technical Lead

Thanks,
Aamir

**Comment by mitovskaol** [comment]
@aamirislam90 Please accept the invites to the BCDevOps and bcgov orgs in GitHub. BCDevOps Memebership will give you access to the Silver cluster Openshift console.

**Comment by aamirislam90** [comment]
@mitovskaol Thanks. Just accepted the invites.
