### ISSUE TITLE
Shifting ownership

### ISSUE THREAD

**Issue by davidcusack** [BCDevOps/devops-requests#1142]
Hello, I am the owner of several EDUC repositories and I have the ability to create repositories for Education. I want to shift the ownership to another team member.

Thanks,
David

**Comment by ShellyXueHan** [comment]
@davidcusack you should be able to assign another user to be the admin of the repo directly. Please let us know if you need further assist!

**Comment by mitovskaol** [comment]
@davidcusack  Are you all set WRT to this request?
