### ISSUE TITLE
Workbc-tr KeyCloak Realm Request

### ISSUE THREAD

**Issue by jinchuantang** [BCDevOps/devops-requests#1145]
**If you have an urgent request, please contact our Product Owner at Vardhman.Shankar@gov.bc.ca**

## Step 0
**Are you the product owner or project admin/team lead?** Tech Lead
If not, you will need to ask one of those two people in your organization to make this request for you. 
We cannot process realm requests except from individuals in these roles.

**Note:** This SSO service is undergoing upgrades in 2021 and is currently not recommended for critical applications. Support is currently available only during business hours and only on a best efforts basis. If your application is critical, please contact Web Access Management (WAM) and/or Provincial Identity Information Management Program (IDIM).

## Step 1
Are you new to Single Sign-On (Keycloak)?  Yes
If so, please indicate that in Step 4, we will setup a meeting with you and your team for an onboarding meeting. 

## Step 2
Field the following information.

* Project Name: WorkBC - Teacher Resources

* Identity Providers Required
  - [ ] BCeID Basic
  - [ ] BCeID Business
  - [ ] GitHub
  - [x] IDIR

## Step 3
Field the following information.

* Project Name: WorkBC - Teacher Resources

* Identity Providers Required
  - [ ] BCeID Basic
  - [ ] BCeID Business
  - [ ] GitHub
  - [x] IDIR

* A list of redirect URLs for each environment (DEV, TEST, PROD). *These are the URLs that your application is allowed to use after sign-on events are complete. These are the secure "front door" for your application.*
  - DEV redirect URL(s): http://teacher-resources-bdaa18-dev.apps.silver.devops.gov.bc.ca/
  - TEST redirect URL(s): TBD
  - PROD redirect URL(s): TBD

## Step 4
For teams requesting access to BCeID, there is an approval process. Please provide the following information on this ticket. The IDIM team will review this information and will be in touch with you at the email provided.
The OCP-SSO team will provision your DEV and TEST clients right away, and your PROD client will be provisioned when the IDIM team approves your request.

* Organization Details (Organization/Division/Branch/Program): 
* **Exectutive Sponsor** Name, Title, & Email: 
* **Project Manager / Business Lead** Name, Title, & Email: 
* **Technical Lead** (if applicable) Name, Title, & Email: 
* **Privacy Lead** (if applicable) Name, Title, & Email: 
* **Security Lead** (if applicable) Name, Title, & Email: 
* **Communications Lead** (if applicable) Name, Title, & Email: 
* Name of service or application:
* URL of service or application:
* Estimated volume of initial users:
* Forecast of anticipated growth over the next three years:
* Date of release in production environment:
* Date of first use by citizens or end users:

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - Vardhman.Shankar@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Product Owner's IDIR name: 
* Product Owner's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

**Comment by brycereid73** [comment]
@junminahn 

Please create new client in the standard realm. (IDIR) 

Once completed, message me and I'll share how we can send the details over to Jack. 

NOTE: Only create the client in Dev. Jack will submit a new request when he's ready to proceed with Test and Prod.

**Comment by arcshiftsolutions** [comment]
Was provisioned for the team on June 14th.
