### ISSUE TITLE
FOM request for BCeID's (Test & Dev)

### ISSUE THREAD

**Issue by LKILPATR** [BCDevOps/devops-requests#1151]
Updated:

- Request is for hybrid  BUSINESS + BASIC BCeID.
-  Here is our DEV URL
- The URL will be changing, but here's a current URL for the Admin component (protected by Keycloak).
- https://nr-fom-admin-main-dev.apps.silver.devops.gov.bc.ca/admin/

Copy of letter from BCeID authorizing our use.

Good Morning DevExchange | KeyCloak | SSO Team,
 
The Forest Operations Map ( FOM ) Team has been working on their BCeID onboarding deliverables for the legacy ‘Natural Resource Ministries Apps’ KeyCloak Realm that is currently integrated with the  IDIR and GitHub IDp’s.
 
The DevExchange | KeyCloak | SSO Team have our IDIM Consulting authorization to integrate the non-production Client ( ichqx89w  ) realm with our non-production BCeID Client Test environment IDp in the ‘combined’ [Basic BCeID] + [Business BCeID] non-production BCeID KeyCloak common Realm as required.
 
IDIM Consulting will inform the DevExchange | KeyCloak | SSO Team when the Forest Operations Map (FOM) Client KeyCloak realm will be authorized to integrate with our BCeID Production environment.
Forest Operations Map (FOM) Team has some outstanding mandatory (minimum) BCeID onboarding deliverables to complete before they will be authorized for BCeID Production.
 
Does the Forest Operations Map ( FOM ) Team require a fresh GitHub | DevOps Service Request to get this request actioned? [ https://github.com/BCDevOps/devops-requests ]
 
Please advise.

Best Regards,
 
Tim McGuire
Client Onboarding Manager - BCeID
Provincial Identity Information Management – Service BC Division
Ministry of Citizens’ Services
PO Box 9412, Stn B Prov Gov, Victoria BC V8W 9V1
Tim.McGuire@gov.bc.ca
250 507-7685

**Comment by arcshiftsolutions** [comment]
We have completed the setup for DEV & TEST.
