### ISSUE TITLE
Unable to login with IDIR credentials

### ISSUE THREAD

**Issue by thegentlemanphysicist** [BCDevOps/devops-requests#1154]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
I am

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
I am attempting to login using my IDIR credentials on an app that has different workflows for IDIR and GitHub authenticated users. I can successfully login with github credentials, however when I use IDIR I get the following screen:
 
![image](https://user-images.githubusercontent.com/9705602/120398048-4c1e6f00-c2ee-11eb-8e65-b4a4aa33e028.png)

I was told this issue comes from having a pre-existing account by that name. It is possible this account already existed for me when I was a contractor working on the mds project.  When attempting to add to existing account, my idir password did not allow me to proceed.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: jsharman
* Realm ID where user is having problem login: p2zhow64
* Environment in which you are facing issue: test

**Comment by nvunnamm** [comment]
User has been removed in test. Please verify.

**Comment by thegentlemanphysicist** [comment]
It is working now, thank you for the quick action. :)
