### ISSUE TITLE
Request to remove duplicate nkuruba IDIR from Keycloak

### ISSUE THREAD

**Issue by NithinKuruba** [BCDevOps/devops-requests#1157]
## Step 0
**Are you the Keycloak Realm Admin?**
no

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
** I recently joined Citizen Services and I am setting up my access with various apps. I am seeing issues with connecting to Jira and Rocket chat. After I login via siteminder to access either Jira(https://proj.data.gov.bc.ca/jira) or Rocket chat (https://chat.developer.gov.bc.ca), I get a window which says there is already an account with idir **nkuruba** available. I am not able to link to this existing account as well. So I am not able to get past through this error window.

- What result of debugging have you obtained that lead you to request an account removal?
** I am not able to link my current profile to this already existing account. So I am not able to get past through this error window. I suspect that the duplicate IDIR, which is already in Keycloak is associated with email nithin.kuruba@gov.bc.ca but my current email is nithinshekar.kuruba@gov.bc.ca.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: nkuruba
* Realm ID where user is having problem login: not sure about this
* Environment in which you are facing issue: dev, test and prod

**Comment by nvunnamm** [comment]
User has been removed in dev, test and prod. Please verify

**Comment by NithinKuruba** [comment]
Thanks for the changes. Now I am seeing a new screen when I login through siteminder. It asks me to verify my email. But I don't receive any email. Could you please help me with this?

**Comment by nvunnamm** [comment]
@NithinKuruba could you please post what URL you are trying to access?

**Comment by NithinKuruba** [comment]
@nvunnamm here is the URL -> https://chat.developer.gov.bc.ca/, which will redirect me to login through siteminder.

**Comment by nvunnamm** [comment]
Cleared you. Could you try now

**Comment by NithinKuruba** [comment]
@nvunnamm Great, that worked. Thank you so much. I am able to log into Rocket Chat now.

**Comment by nvunnamm** [comment]
Nice so the issue with https://github.com/BCDevOps/devops-requests/issues/1161 can be marked closed ?

**Comment by NithinKuruba** [comment]
@nvunnamm sure, please go ahead and close the ticket. Thanks again.

**Comment by NithinKuruba** [comment]
@nvunnamm There is another realm **ido-all** which has duplicate username nkuruba, due to which I am not able to login in to https://gogs.data.gov.bc.ca/user/login. Could you please remove it from this realm as well?

**Comment by nvunnamm** [comment]
Removed. Please verify.

**Comment by NithinKuruba** [comment]
@nvunnamm it worked, thanks a lot.
