### ISSUE TITLE
Keycloak Request for MoTI Weather and Avalanche System

### ISSUE THREAD

**Issue by brycereid73** [BCDevOps/devops-requests#1159]
@Leajjes commented on [Tue Jun 01 2021](https://github.com/BCDevOps/issues-and-solutions/issues/19)

Hi,

Based off what is newly documented from https://github.com/BCDevOps/devops-requests/blob/master/.github/ISSUE_TEMPLATE/keycloak_standard_client_request.md, I am providing the following information:

•	Project Name: Weather and Avalanche System
•	Identity Providers Required
o	BCeID Business (This one? https://confluence.th.gov.bc.ca/display/WEAV/Authentication+and+Authorization)
o	IDIR
•  A list of redirect URLs for each environment (DEV, TEST, PROD). These are the URLs that your application is allowed to use after sign-on events are complete. These are the secure "front door" for your application.
•	DEV redirect URL(s): https://dev-awp.th.gov.bc.ca/?
•	TEST redirect URL(s): https://tst-awp.th.gov.bc.ca/
•	UAT redirect URL(s): https://uat-awp.th.gov.bc.ca/
•	PROD redirect URL(s): https://awp.th.gov.bc.ca/

•	Organization Details (Organization/Division/Branch/Program): Ministry of Transportation and Infrastructure IMB
•	Executive Sponsor Name, Title, & Email: Stuart Restall, Chief Information Officer & Executive Director, Stuart.Restall@gov.bc.ca
•	Project Manager / Business Lead Name, Title, & Email: Cara Jay, Senior Project Manager, Cara.Jay@gov.bc.ca
•	Technical Lead (if applicable) Name, Title, & Email: James Duyndam, Senior Technical Systems Analyst,  James.Duyndam@gov.bc.ca
•	Privacy Lead (if applicable) Name, Title, & Email: Carlos Caraveo, Director, Carlos.Caraveo@gov.bc.ca
•	Security Lead (if applicable) Name, Title, & Email: Dean Rodgers, Security Architect, Dean.Rodgers@gov.bc.ca
•	Communications Lead (if applicable) Name, Title, & Email: Cara Jay, Senior Project Manager, Cara.Jay@gov.bc.ca

•	Name of service or application: Snow Avalanche Weather Services X
•	URL of service or application: 
o	DEV: https://dev-awp.th.gov.bc.ca/?
o	TEST: https://tst-awp.th.gov.bc.ca/
o	UAT: https://uat-awp.th.gov.bc.ca/
o	PROD: https://awp.th.gov.bc.ca/
•	Estimated volume of initial users: Under 100
•	Forecast of anticipated growth over the next three years: similar load. Ministry use application
•	Date of release in production environment: Alpha June 3rd. Full application: June 2023
•	Date of first use by citizens or end users: September 2021

**Comment by Leajjes** [comment]
I just reached out to Niranchandra about this but I'll post this here too:

Looks like I might have got too ahead of our needs for openshift. We don’t need the 12:30 meeting and you can cancel the devops-requests # 1159. Sorry about that!
