### ISSUE TITLE
Unable to Login with IDIR\NKURUBA as the system finds it as a duplicate one

### ISSUE THREAD

**Issue by NithinKuruba** [BCDevOps/devops-requests#1161]
## Step 0
**Are you the Keycloak Realm Admin?**
No

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
** After I try to login through Siteminder, I get a webpage with error saying that my username already exists and I try to link that to my current account through verification email option. But I never get those emails. PFA SS attached to this ticket. 

- What result of debugging have you obtained that lead you to request an account removal?
** The error message says my username 'nkuruba' already exists but I still not able to login

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: nkuruba
* Realm ID where user is having problem login: databc
* Environment in which you are facing issue: dev, test and prod

![image](https://user-images.githubusercontent.com/81444731/120832886-ffb57800-c515-11eb-83ca-ad91214df737.png)

**Comment by nvunnamm** [comment]
Issue resolved in https://github.com/BCDevOps/devops-requests/issues/1157
