### ISSUE TITLE
thorwolpert for GitHub Org: private

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#1165]
* Project Name: registries-sre
* Technical Lead Github ID: thorwolpert
* GitHub Org: private
* GitHub ID: @ thorwolpert

* Needed for sre activities (gitops and operational tickets)

**Comment by mitovskaol** [comment]
I talked to @thor about this request and it is good to get processed.

**Comment by thor** [comment]
> I talked to @thor about this request and it is good to get processed.

🤔
