### ISSUE TITLE
registries

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#1167]
## Step 1
Make sure no duplicated request exists, search here: **None**
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: **registries-sre**
* GitHub Org: **private**
* Details on choosing private repo: Will not contain PII, but will have business sensitive and pay-wall data. This will hold out run books, Ops Jupyter Notebooks, sensitive configurations, etc.
* Preferred name for repo: registries
* Expected date to move to public: n/a
* GitHub ID for repo owner: @thorwolpert, Will start the process to get Patrick Wei added too (pwei1018)
* GitHub Account 2FA Confirmed: **yes** or no
* Email address: thor@daxiom.com
* Organization: BC Registry
* Project Role: Lead Architect, Developer and SRE
* GitHub Team to Join (if exists): @bcgov/sre

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@thorwolpert you are the admin of the private repo. Once you've accepted the `bcgov-c` gh org invitation, you'll find the repo there.
