### ISSUE TITLE
Access request for krishnan-aot

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#1170]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?** Yes.

**Do you have a GitHub account?** krishnan-aot
**Do you have 2-factor-authentication enabled with your GitHub account?** Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Krishnan Subramanian
* GitHub ID: krishnan-aot
* Business Email Address: krishnan.s@aot-technologies.com
* Organization: AoT Contractor for Service BC
* Project Role: Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
The invites to bcgov and BCDevOps orgs have been sent.
