### ISSUE TITLE
Request for adding OpenShift access for @lclarko and @veenupunyani

### ISSUE THREAD

**Issue by mark-walle** [BCDevOps/devops-requests#1172]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**

>I, @mark-walle, am the technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

> this is not my first time requesting access for new users.

**Do you have a GitHub account?**

> Yes, @mark-walle

**Do you have 2-factor-authentication enabled with your GitHub account?**

> Yes I do, and so do the users I'm requesting access for, who are already part of the bcgov org.

## Step 1
Are you requesting to:
- [x] grant user access (**MW: I am requesting this for *two* users**)
- [ ] remove user access

## Step 2
Fill out the following fields

**MW: User 1**
* Full Name: Lane Clark
* GitHub ID: @lclarko 
* Business Email Address: lane.clark@gov.bc.ca
* Organization: BCGov GDX Analytics
* Project Role: System Analyst

**MW: User 2**
* Full Name: Veenu Veenu
* GitHub ID: @veenupunyani
* Business Email Address: veenu.veenu@gov.bc.ca
* Organization: BCGov GDX Analytics
* Project Role: Business Analyst

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
The invites have been sent.
