### ISSUE TITLE
Delete idir:ASANTOSG

### ISSUE THREAD

**Issue by josekudiyirippil** [BCDevOps/devops-requests#1177]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
New user is using the same IDIR from sister that is no longer with Government

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: ASANTOSG
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Prod

**Comment by nvunnamm** [comment]
User ASANTOSG has been deleted from prod. Please verify.
