### ISSUE TITLE
Accounts for the Operational Support team for the Registry

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#1182]
**Bulk Request** as discussed with @mitovskaol 

* Project Name: registries-sre
* Technical Lead Github ID: thorwolpert
* GitHub Org: private
* Repo: registries

|Role|Name          |Email                   |GH Handle|
|----|--------------|------------------------|---------|
|BA  |Amit Chaurasia|amit.chaurasia@gov.bc.ca|amit4610 |
|Data|Bob  Bowles   |bob.bowles@gov.bc.ca    |bfbowles |
|Data|David Roberts |David.Roberts@gov.bc.ca |droberts27|
|SRE |Doug Lovett   |doug@daxiom.com         |doug-lovett|
|SRE |Eve Deng      |eve.deng@gov.bc.ca      |eve-git  |
|SRE |Gregory R Waters|gregory.waters@gov.bc.ca|gh20s    |
|BA  |Janis Rogers  |janis.rogers@gov.bc.ca  |janisrogers|
|PO  |Jyoti  Kumar  |jyoti.kumar@gov.bc.ca   |jyoti3286|
|CPO |Kaine  Sparks |kaine.sparks@gov.bc.ca  |Kaineatthelab|
|SRE |Kial Jinnah   |kial.jinnah@gov.bc.ca   |kialj876 |
|PO  |Linda  McClung|linda.mcclung@gov.bc.ca |lmcclung |
|BA  |Melissa Stanton|melissa.stanton@gov.bc.ca|mstanton1|
|SRE |Meng Dong     |meng.dong@gov.bc.ca     |mengdong19|
|BA  |Patrick Heath |patrick.1.heath@gov.bc.ca|PatrickAHeath|
|SRE Lead|Patrick Wei   |patrick.wei@gov.bc.ca   |pwei1018 |
|SRE |Richard Armitage|richard.armitage@gov.bc.ca|rarmitag |
|BA  |Sienna Blumstengel|sienna@freshworks.io    |Sienna-Blumstengel|
|SRE |Steven Chen   |steven.chen@gov.bc.ca   |stevenc987|
|SRE |Sumesh Punakkal Kariyil|sumesh.pk@aot-technologies.com|sumesh-aot|
|SRE |Syed Riyazzudin|syed.riyazzudin@gov.bc.ca|riyazuddinsyed|

**Comment by mitovskaol** [comment]
@ShellyXueHan @caggles @patricksimonian This request is for the private org

**Comment by patricksimonian** [comment]
@thorwolpert this request is processing, stand by
