### ISSUE TITLE
Request for private BCGOV GitHub Repository

### ISSUE THREAD

**Issue by will-freshworks** [BCDevOps/devops-requests#1186]
## Step 0

**Are you looking to make a public repository?**
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. 
If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. 
This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. 
Please include a firm date by which you will move your repository to the open organization.

If you feel you cannot move to open-source ever, we strongly encourage you to reconsider.
However, if you are certain that you require a fully closed-source repo permanently, you can speak to the team on RocketChat to discuss your options.
Using the private bcgov GitHub Organization may not be the appropriate solution for your team in this case.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* Details on choosing private repo: 
* Preferred name for repo: 
* Expected date to move to public: MM/YYYY
* GitHub ID for repo owner: @
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
The invite to join bcgoc-c was sent to @will-freshworks

**Comment by will-freshworks** [comment]
Hi @mitovskaol. I have accepted the invitation. Is there anything I need to do now to create the repository or will this be created by your team?

**Comment by mitovskaol** [comment]
@will-freshworks You are now able to create repos in bcgov-c, this part is handled by product teams themselves.

**Comment by will-freshworks** [comment]
@mitovskaol possibly I am doing this incorrectly, but I don't seem to have the right permissions
![image](https://user-images.githubusercontent.com/70539895/122838432-ef89f080-d2aa-11eb-9227-645a63744f1d.png)

**Comment by mitovskaol** [comment]
@will-freshworks It is my bad, I didn't know that only Platform Services Team can create private repos in bcgov-c. Please submit the request using this link: https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+ShellyXueHan%2C+mitovskaol%2C+patricksimonian&labels=github-repo%2C+pending&template=github_repo_request.md&title=

**Comment by will-freshworks** [comment]
Isn't this the same link I used to create this request originally? Sorry I'm a bit confused. Do you mean I should re-open the same request again so it gets looked at by the platform team? 

I forgot to mention - I sent _all_ of the details from the final checklist in the email to pathfinder because this is a confidential and quite sensitive project for the Ministry of Health, and these devops-requests issues are public. Does the Platform Services Team have access to that pathfinder@gov.bc.ca email address and can pull the repo name from there?

**Comment by mitovskaol** [comment]
@will-freshworks  Found the email, we are working on it. No need to submit another request. I am trying to help our Platform Admins today as one of them is on vacation and obviously not doing a very good job. I apologize for the confusion.

**Comment by will-freshworks** [comment]
Ah that's reassuring to hear. I didn't get a lot of sleep last night for baby related reasons so I was worried I was just misunderstanding the situation.

**Comment by patricksimonian** [comment]
@will-freshworks sorry for the delay. You should have access to https://github.com/bcgov-c/ltc-vx as an administrator
