### ISSUE TITLE
HETS KeyCloak Realm Request

### ISSUE THREAD

**Issue by ychung-mot** [BCDevOps/devops-requests#1189]
**If you have an urgent request, please contact our Product Owner at Vardhman.Shankar@gov.bc.ca**

## Step 0
**Are you the product owner or project admin/team lead?**
Yes

**Note:** This SSO service is undergoing upgrades in 2021 and is currently not recommended for critical applications. Support is currently available only during business hours and only on a best efforts basis. If your application is critical, please contact Web Access Management (WAM) and/or Provincial Identity Information Management Program (IDIM).

## Step 1
Are you new to Single Sign-On (Keycloak)? 
No

## Step 2
Field the following information.

* Project Name: HETS (Hired Equipment Tracking System)

* Identity Providers Required
  - [ ] BCeID Basic
  - [X] BCeID Business
  - [ ] GitHub
  - [X] IDIR

## Step 3
Field the following information.

* Project Name: HETS (Hired Equipment Tracking System)

* Identity Providers Required
  - [ ] BCeID Basic
  - [X] BCeID Business
  - [ ] GitHub
  - [X] IDIR

* A list of redirect URLs for each environment (DEV, TEST, PROD). *These are the URLs that your application is allowed to use after sign-on events are complete. These are the secure "front door" for your application.*
  - DEV redirect URL(s): 
     https://hets-e0cee6-dev.apps.silver.devops.gov.bc.ca
     https://dev-hets.th.gov.bc.ca
     http://localhost:3000
  - TEST redirect URL(s): 
     https://hets-e0cee6-test.apps.silver.devops.gov.bc.ca
     https://hets-e0cee6-uat.apps.silver.devops.gov.bc.ca
     https://hets-e0cee6-train.apps.silver.devops.gov.bc.ca
     https://tst-hets.th.gov.bc.ca
     https://uat-hets.th.gov.bc.ca
     https://trn-hets.th.gov.bc.ca
  - PROD redirect URL(s):
     https://hets-e0cee6-prod.apps.silver.devops.gov.bc.ca
     https://hets.th.gov.bc.ca

## Step 4
For teams requesting access to BCeID, there is an approval process. Please provide the following information on this ticket. The IDIM team will review this information and will be in touch with you at the email provided.
The OCP-SSO team will provision your DEV and TEST clients right away, and your PROD client will be provisioned when the IDIM team approves your request.

* Organization Details (Organization/Division/Branch/Program): Ministry of Transportation and Infrastructure
* **Exectutive Sponsor** Name, Title, & Email: Ivan Rincon /  Director AMS / Ivan.Rincon@gov.bc.ca
* **Project Manager / Business Lead** Name, Title, & Email: Clare Allan/ Project Manager/ <Clare.G.Allan@gov.bc.ca>
* **Technical Lead** (if applicable) Name, Title, & Email: Iouri Atavine/ Senior Technical Analyst/<Iouri.Atavine@gov.bc.ca>
* **Privacy Lead** (if applicable) Name, Title, & Email: NA
* **Security Lead** (if applicable) Name, Title, & Email: Dom Kapac/Senior Security Analyst/<Dom.Kapac@gov.bc.ca>
* **Communications Lead** (if applicable) Name, Title, & Email: NA
* Name of service or application: HETS (Hired Equipment Tracking System)
* URL of service or application: https://hets.th.gov.bc.ca
* Estimated volume of initial users: internal ~ 50, external ~300
* Forecast of anticipated growth over the next three years: internal ~ 50, external ~500
* Date of release in production environment: 2021-Oct-27
* Date of first use by citizens or end users: 2021-Oct-27

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - Vardhman.Shankar@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation: Clare.G.Allan@gov.bc.ca
* link to the GitHub ticket you just created:  
* Product Owner's IDIR name: Deepak Mital
* Product Owner's Business Email Address: Deepak.Mital@gov.bc.ca

Please note that we will only start processing your request when the email has been received.

**Comment by nvunnamm** [comment]
@ychung-mot, Please let us know the best suitable date for your team for the onboarding session.

**Comment by ychung-mot** [comment]
@nvunnamm Does 1pm tomorrow (June 30th) work for you?

**Comment by nvunnamm** [comment]
Yeah works for us.. Let me send out an invite

**Comment by ConradBoydElliottGustafson** [comment]
@junminahn @nvunnamm @ychung-mot 

Young-Jin got back to us. They want public client with PKCE. Please update the TerraForm files and make a pull request. Niran may need support from Junmin as this is the first time we have done this. Thank you!

**Comment by ychung-mot** [comment]
@nvunnamm Can you please confirm that the redirect URIs are all registered? I am getting **Invalid parameter: redirect_uri** error when using http://localhost:3000.

**Comment by junminahn** [comment]
@ychung-mot Yes, we updated the `valid_redirect_uris` to have `http://localhost:3000` yesterday.
https://github.com/bcgov/sso_terraform/blob/0e3b3b6d6544dba82f498c4919ae2e5c24e48a5b/terraform/keycloak-dev/realms/onestopauth-business/client-hets.tf#L6

**Comment by ychung-mot** [comment]
@junminahn Can you please also check if the Web Origins is set to +?
![weborigins](https://user-images.githubusercontent.com/44654482/125106316-5aea0580-e094-11eb-90fb-5fbab8a65512.png)

**Comment by junmin-bcgov** [comment]
@ychung-mot thank you for bring that up, yes, that update just got merged.
https://github.com/bcgov/sso_terraform/pull/31/files

**Comment by ychung-mot** [comment]
Can you please let me know token expiration minutes?

**Comment by nvunnamm** [comment]
@ychung-mot Please let me know if the attachment helps
<img width="1023" alt="Screen Shot 2021-07-22 at 1 54 20 PM" src="https://user-images.githubusercontent.com/67395641/126686158-f6c1e735-c1e1-431b-83e5-09d5ce18d456.png">

**Comment by junminahn** [comment]
@ychung-mot  as we don't set any expiry values at the client level, it will fall back to the ones at the realm level.

**Comment by ychung-mot** [comment]
@nvunnamm & @junminahn  Thanks!
