### ISSUE TITLE
GitHub Repository Request for IAM

### ISSUE THREAD

**Issue by sharpedavid** [BCDevOps/devops-requests#119]
GitHub Repository Request:
- Project: Identity Access Management Project (IAM)
- Project description: Setting the foundation for MoH A&A.
- Approver: @kelpisland 
- Repo Owner GitHub ID: sharpedavid 

Depends on #117.

**Comment by sharpedavid** [comment]
I created this request based on [the guide](https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation), but I didn't find a matching issue template at https://github.com/BCDevOps/devops-requests/issues/new/choose

I hope I've done the right thing, but please go ahead and let me know if I haven't.

![image](https://user-images.githubusercontent.com/1767127/72573253-e60c8580-3879-11ea-9cfa-386984f640a0.png)

**Comment by caggles** [comment]
Hi @sharpedavid! Thanks for pointing out the guide - that's actually a bit out of date, so I'll update that asap. You don't need to request a new public repo from us. You can make one of those yourself! If you're unsure, go ahead and ask about it in #devops-howto on rocketchat and we can walk you through the process!
