### ISSUE TITLE
acess to IDIR  -PSHOKAR

### ISSUE THREAD

**Issue by josekudiyirippil** [BCDevOps/devops-requests#1190]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?

new CSR, Perminder Shokar, is having difficulties logging into our application. She was previously an employee of the BC Public Service, and we believe that her old login is impacting her current access.  

•	Error message when logging in: SBC_with_BCEID User with username PSHOKAR already exists. Please login to account management to link the account.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: PSHOKAR
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: prdo

**Comment by nvunnamm** [comment]
User has been removed in prod. Please verify.
