### ISSUE TITLE
Add two users to bcgov-c repo

### ISSUE THREAD

**Issue by will-freshworks** [BCDevOps/devops-requests#1194]
Hi,

I already have a bcgov-c repo, but I need to add two users to it, and there are no more seats. https://developer.gov.bc.ca/User-access-into-Github-or-Openshift led me to this issue template but it didn't fit so here I am.

Repo is https://github.com/bcgov-c/ltc-vx and I'd like @fw-noel and @arranfw. 

Thanks 🙌

**Comment by mitovskaol** [comment]
@will-freshworks The users have been invited to bcgov-c.
