### ISSUE TITLE
Lost Access to OpenShift! - http://console.apps.silver.devops.gov.bc.ca/

### ISSUE THREAD

**Issue by abin-aot** [BCDevOps/devops-requests#1195]
Hi,

Myself Abin and working on FOI project , leading by Loren Mullane.  I was having access to BC DEV Exchange open shift  earlier, but now its redirecting to this request section. Please help! 

Note: I am using my github account(abin-aot) to signin to OC. 

Thanks,
Abin

**Comment by patricksimonian** [comment]
@abin-aot  you can have Loren add you by using the access management tool https://developer.gov.bc.ca/User-access-into-Github-or-Openshift

**Comment by patricksimonian** [comment]
@abin-aot I've added you to the bcdevops org as our tool is experiencing some issues. Please check your email for the invite!
