### ISSUE TITLE
Please provide access

### ISSUE THREAD

**Issue by divyav-aot** [BCDevOps/devops-requests#1196]
Hi Team,

Could you please provide access to my github account (divyav-aot).  I am part of FOI project,  leading by Loren Mullane.

Thanks
Divya

**Comment by patricksimonian** [comment]
@divyav-aot you can have Loren use the github access managment tool to invite you. https://developer.gov.bc.ca/User-access-into-Github-or-Openshift

**Comment by patricksimonian** [comment]
@divyav-aot looks like there is some issues with the invitation tool that i'll work on resolving. In the mean time i've added you to bcdevops org. Please check your email for the invitation
