### ISSUE TITLE
bcgov / CIT Repo Admin Access for Zac Pez

### ISSUE THREAD

**Issue by danielhirner** [BCDevOps/devops-requests#1197]
## Step 0

**DO NOT OPEN A TICKET UNLESS THERE ARE NO ADMINS ASSIGNED TO THE REPO IN QUESTION**
If your repo has an admin, please ask them to provide you with the access you need. This ticket is for the **rare** case in which a repo loses all of its admins - this can occasionally happen when moving repos between different owners. If you have not moved the repo in question to bcgov recently, then this ticket probably does not apply to you. 

**If you open a ticket here and there is an admin user assigned to that repo, this ticket will be closed without action.**

**Are you the Technical Lead?**
Only a team's technical lead my request admin access to a repo.  YES

**Are you a member of the BCGOV org?**
If not, you'll need to be added as member first. Please open a ticket for that, and then come back here once that's finished! YES

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Provide a detailed explanation of the steps which caused your repo to lose all admin users.
Admin access request for Zec Pez.  Zac is from NTT and is providing maintenance support for us on the Community Information Tool: https://github.com/bcgov/CIT

## Step 5
Provide the **name of the admin-less repo** and any other details that may be necessary for us to fix the issue.
Admin access request for Zec Pez.  Zac is from NTT and is providing maintenance support for us on the Community Information Tool: https://github.com/bcgov/CIT
Name: Zachary Pez
IDIR: ZPEZ 
Gov email: Zachary.Pez@gov.bc.ca 
Github: zacpez

Please note that this ticket may take some time to action - we need to ensure that we are providing admin access to the correct user. Keep a close eye on the comments as the team will likely have more questions for you!

**Comment by patricksimonian** [comment]
@danielhirner  you are the admin of the repo. You should be able to assign zac as an admin I do believe!

**Comment by mitovskaol** [comment]
This request has been resolved.
