### ISSUE TITLE
FAIB analysis section joining bcgov

### ISSUE THREAD

**Issue by kdizzard** [BCDevOps/devops-requests#12]
Project name: FAIB Analysis Section
GitHub organization: bcgov
New user's full name: kelly izzard
New user's GitHub ID:51372362
New user's email address associated with the GitHub account:kelly.izzard@gov.bc.ca
New user's organization (gov ministry plus division,branch,etc.) or company:"Ministry of Forests Lands and Natural Resource Operations/Forest Analysis and Inventory Branch/Analysis section
New user's role on the project (e.g. Developer, QA, DevOps specialist, Scrum Master):Facilitator
GitHub repositories if exist: Kelly Izzard
Expiry (optional): NA

**Comment by ShellyXueHan** [comment]
Hi @kdizzard , we do not take access request for new users, you will need to contact the person that on-boarded/introduced you to the BCGov DevOps Platform and BCDevExchange and ask that person to make the request for you. Please refer to details here: https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation
