### ISSUE TITLE
request to update a Keycloak user

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#1200]
## Step 0
**Are you the Keycloak Realm Admin?**
YES

## Step 1
Provide some background on the user account issue.
I’m trying to troubleshoot a log in issue. We manage access to our application ( https://chess-dev.apps.silver.devops.gov.bc.ca/app/email ) - using Keycloak. One of our user’s is unable to sign in to this application. They are shown a dialog informing them that a ‘user with that username already exists’. submitting the ‘review profile’ form takes them back to the first dialog. If they try to ‘add to existing account’ that fails too.
It also seems that no user account is ever created in our Keycloak realm. This seems to be a one-off issue that hasn’t affected any of our other users.
By screen sharing and through chats with the user, we did try the steps outlined in this issue: https://github.com/bcgov/ocp-sso/issues/68 as well as clearing the realm/user cache. but had no luck.
The user did move within the government's staff structure recently but I don't know if that is a relevant factor.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [X] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: IHALL
* Realm ID where user is having problem login: 98r0z7rz, cp1qly2d (both realms please)
* Environment in which you are facing issue: dev, test and prod

**Comment by nvunnamm** [comment]
The user has been removed please verify.

**Comment by TimCsaky** [comment]
That worked. thank you very much for dealing with it so quickly!
