### ISSUE TITLE
Please remove duplicate Keycloak user Amber Flanagan with IDIR AFLANAGA

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1201]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes I am the administrator for Keycloak Realm vtkayq4c

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
We are trying to add a new production user to our Keycloak Realm vtkayq4c.  The user does not exist in our production realm vtkayq4c when I do a keycloak search but our application to add a new user indicates that the user exists in Keycloak. 

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes the user is ready to have the account removed from Keycloak.

## Step 3
Field the following information.

* Username to be removed: AFLANAGA is the IDIR account
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Production Keycloak

**Comment by nvunnamm** [comment]
@jhmccoll I couldn't find the user in IDIR either.

**Comment by nvunnamm** [comment]
@jhmccoll Please reopen the issue if user is still facing the issue.
