### ISSUE TITLE
new invites needed

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#1203]
the following folks let their invites lapse before accepting, could they get re-invited please?

Eventual repo: bcgov-c/registries

|Role|Name          |Email                   |GH Handle|
|----|--------------|------------------------|---------|
|Data|Bob  Bowles   |bob.bowles@gov.bc.ca    |bfbowles |
|SRE |Doug Lovett   |doug@daxiom.com         |doug-lovett|
|PO  |Linda  McClung|linda.mcclung@gov.bc.ca |lmcclung |
|BA  |Melissa Stanton|melissa.stanton@gov.bc.ca|mstanton1|
|BA  |Patrick Heath |patrick.1.heath@gov.bc.ca|PatrickAHeath|
|BA  |Sienna Blumstengel|sienna@freshworks.io    |Sienna-Blumstengel|
|SRE |Steven Chen   |steven.chen@gov.bc.ca   |stevenc987|
|SRE |Syed Riyazzudin|syed.riyazzudin@gov.bc.ca|riyazuddinsyed|

**Comment by patricksimonian** [comment]
@thorwolpert all have pending invitations now
