### ISSUE TITLE
Request to update a Keycloak user

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#1206]
## Step 0
**Are you the Keycloak Realm Admin?**
YES

## Step 1
Provide some background on the user account issue.
I’m trying to troubleshoot a log in issue. We manage access to our application ( https://getok.nrs.gov.bc.ca/app/ ) - using Keycloak. One of our user’s is unable to sign in to this application. 
It sounds like this issue: https://github.com/bcgov/ocp-sso/issues/68.
They are shown a dialog informing them that a ‘user with that username already exists’. submitting the ‘review profile’ form takes them back to the first dialog, etc, etc..

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [X] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: pplatten
* Realm ID where user is having problem login: vehizw2t 
* Environment in which you are facing issue: dev, test and prod

**Comment by nvunnamm** [comment]
@TimCsaky Removed the user from Prod but was not able to find him in Dev and Test. Please let me know if he still has issues in those environments.

**Comment by TimCsaky** [comment]
Hey thanks! that's perfect.. it solved the issue. sorry, I see now that it was only happening in Prod.
This ticket can be closed.
