### ISSUE TITLE
Grant access to new team members to https://github.com/bcgov-c/cats-devops

### ISSUE THREAD

**Issue by WadeBarnes** [BCDevOps/devops-requests#1207]
I have some new team members taking over some things for me. One of which requires access to https://github.com/bcgov-c/cats-devops

Team Mebers:
@seeker25 
@pbolduc 
@danbigthink

**Comment by WadeBarnes** [comment]
@patricksimonian, as requested.

**Comment by patricksimonian** [comment]
@mitovskaol seeking approval for this ^^

**Comment by mitovskaol** [comment]
@patricksimonian Approved!

**Comment by patricksimonian** [comment]
all of them have been invited now. Are you an admin of that repo @WadeBarnes  ?

**Comment by WadeBarnes** [comment]
> Are you an admin of that repo @WadeBarnes ?
Yes

**Comment by patricksimonian** [comment]
you should be able to invite them now into the repo :)  let me know so I can close this

**Comment by WadeBarnes** [comment]
@patricksimonian, It seems I was not set as an admin on the repo.  You able to do that?

**Comment by patricksimonian** [comment]
sorry @WadeBarnes, would you like me to grant you admin access to the repo?

**Comment by WadeBarnes** [comment]
@patricksimonian, yes please

**Comment by patricksimonian** [comment]
done! I noticed there are two outside collaborators that have admin access. May want to doublecheck that

**Comment by WadeBarnes** [comment]
@patricksimonian, Thanks.  The two outside collaborators are legitimate users.
