### ISSUE TITLE
Please remove duplicate IDIR mvansoes from Keycloak production 

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1208]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Tes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
The user is attempting to login to our application and receiving an error saying her idir already exists and to link the account. I have confirmed her account exists in our production realm. 

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes

## Step 3
Field the following information.

* Username to be removed: mvansoes@idir (Michelle Van Soest)
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Production

**Comment by nvunnamm** [comment]
The user has been removed.
