### ISSUE TITLE
Decommission Openshift3 MDS namespaces

### ISSUE THREAD

**Issue by jon-funk** [BCDevOps/devops-requests#1209]
## Step 0
**Are you the Product Owner or Technical Lead?**
If not, you will need to ask one of those two people to make this request.

- I am the tech. lead, Aaron Unger is the PO and has approved this decommission via email.

If you are one of these two people, please ensure that you also request Openshift access if you don't have it already. This request does NOT grant you access to the platform itself - you will find a separate request for that on the issues page of this repo!
However, you may submit both requests at the same time - there's no need to wait until that request has been completed to submit this one.

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
If not, please do so before you submit the request.

- Yes this has been done.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
If not, please do so before you submit the request.

- There are no more pods running in any namespaces.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
If not, please do so before you submit the request.

- All PVCs have been deleted across all namespaces.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

- No duplicates found.

## Step 2
Confirm that you are aware that you are requesting to:
- [x] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

- I understand this request to decommission is not reversible.

## Step 3
Please provide the names of the namespaces to be deleted in the form of a 6 character alphanumeric code followed by the environment, like so: 

empr-mds-dev
empr-mds-test
empr-mds-prod
empr-mds-tools

**Comment by patricksimonian** [comment]
deleted!
