### ISSUE TITLE
Remove IDIR account from SSO

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/devops-requests#1210]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- User worked in gov before and joined again recently. So the IDIR account has been updated and caused the conflicts.

- What result of debugging have you obtained that lead you to request an account removal?
- We've tried new browser and the same result.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: dhofman
* Realm ID where user is having problem login: devhub
* Environment in which you are facing issue: production

**Comment by nvunnamm** [comment]
Removed user from Prod. Please verify.

**Comment by ShellyXueHan** [comment]
@dhofmanMSD for you to track the ticket ^^^

**Comment by ShellyXueHan** [comment]
@dhofmanMSD would you try to login to RocketChat again?

**Comment by dhofmanMSD** [comment]
@ShellyXueHan Sorry Shelly, I should have updated you. I tried yesterday afternoon and was able to log in to RocketChat successfully. Thank you both for your help!
