### ISSUE TITLE
Billy Li Duplicate user remove

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/devops-requests#1211]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
I can not login to https://dev.oidc.gov.bc.ca/auth 
- What result of debugging have you obtained that lead you to request an account removal?
I saw an existing user profile message

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: BillyLi
* Realm ID where user is having problem login: BILLYLI
* Environment in which you are facing issue: https://dev.oidc.gov.bc.ca/auth

**Comment by patricksimonian** [comment]
@nvunnamm i'm fulfilling this request. Billy is on my team.
