### ISSUE TITLE
Please remove user CPITRE

### ISSUE THREAD

**Issue by josekudiyirippil** [BCDevOps/devops-requests#1212]
## Step 0
**Are you the Keycloak Realm Admin?** Yes
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account? unable to log on to the Q application .getting error message "User with username cpitre already exists."
- What result of debugging have you obtained that lead you to request an account removal? User with username cpitre already exists.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes

## Step 3
Field the following information.

* Username to be removed: CPITRE
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Prod

**Comment by nvunnamm** [comment]
The user has been removed. Please verify.

**Comment by josekudiyirippil** [comment]
I can still see the user in keycloak.
