### ISSUE TITLE
Request to gain access to Lab's openshift environment for TAFT project

### ISSUE THREAD

**Issue by shankar-aot** [BCDevOps/devops-requests#1214]
Hello,

I am Shankar Sethuraman - Dev Lead, Scrum Master and Integration Architect for the TAFT project - Tobacco and Fuel Tax Exemption Simplification Project with the Ministry of Finance. In addition, I administer the environments and perform devops functions. 

We are planning to migrate our applications and deployments from our current openshift environment to those at the lab. 

Kindly grant me administrative access to administer these environments.

Thank you

Shankar
250-884-5175

**Comment by patricksimonian** [comment]
Hi there @shankar-aot 

Just a few questions for you to be more clear, you have a a project hosted on your own Openshift cluster or one that is administered by bcgov? Are you asking for a new project set in our Openshift 4 cluster?

And what environments are you asking for? 

In addition, access control requests for any existing environments should be done with the technical lead or product owner of a project.

**Comment by shankar-aot** [comment]
Apologies. I should have been more clear and specific. 

To answer your first question - right now, yes we have the project on our own openshift cluster (in house on prem). 

To answer your second - We've already been allocated a namespace called "TAFT" in the bcgov openshift, and I'm requesting administrative access to that. I believe I've been named Technical Lead for the namespace. 

As for the environments, I believe they've been provisioned as part of the namespace.

Shankar

**Comment by mitovskaol** [comment]
@shankar-aot  I've talked to Chris about this project and approve your request. You should get 2 invites for bcgov and BCDevOps orgs.

**Comment by shankar-aot** [comment]
Hello Olena

Thank you for the response. 

I was able to add myself to both orgs (after setting 2FA at github), but I still cannot get into the openshift console - it still redirects me to the github issues page like it did previously.

Thanks
Shankar

**Comment by mitovskaol** [comment]
@shankar-aot Can you please log out of the Console, clear your cache and log back in with your GitHub ID `shankar-aot` and let me know if you can see the namespaces now.

**Comment by shankar-aot** [comment]
I can now access the console, but I cant see any namespaces. Screenshot:

**Comment by patricksimonian** [comment]
what is the namespace you are trying to access ?  (the licence plate prefix)

**Comment by shankar-aot** [comment]
TAFT

Shankar

**Comment by mitovskaol** [comment]
@shankar-aot You logged in with the wrong GitHub ID in the Openshift Console, you used `shankarsethuraman` while on the project provisioning request it was listed as `shankar-aot`. You must use the GitHub ID that was included in the provisioning request.

**Comment by shankar-aot** [comment]
Hi Olena

I’ve only logged in as shankar-aot. I dont use any other github accounts. 

And now, when I try to login via shankar-aot to the openshift console at: https://console.apps.silver.devops.gov.bc.ca/ <https://console.apps.silver.devops.gov.bc.ca/> I get an Authentication Error. I am not sure what I am missing. 



Thanks
Shankar

**Comment by mitovskaol** [comment]
The access issue has been sorted out.
