### ISSUE TITLE
Requesting access to OpenShift

### ISSUE THREAD

**Issue by IsaacLea** [BCDevOps/devops-requests#1216]
I was told I needed to be added to the BC Gov GitHub org in order to get OpenShift Access

The URL I am trying to access is this:
https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects

I am working with Ian Hallas on this

**Comment by mitovskaol** [comment]
@ihallas Please invite @IsaacLea using the new automated invite tool Just Ask! using this link https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/
