### ISSUE TITLE
Team access

### ISSUE THREAD

**Issue by Nicole-Huard** [BCDevOps/devops-requests#1217]
Good morning! Please add AJ Caruso (arctiqaj) and Lila Wilson (lilawilso) to the org.
AJ will be a delivery consultant who will also require access to OpenShift (Mike Shire will organize) and Lila will be a client advocate, who primarily requires access to Rocket Chat only.

Thank you!

**Comment by Nicole-Huard** [comment]
Are you the product owner or technical lead? Project Manager for Arctiq resources

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

Do you have a GitHub account? Yes -- arctiqaj   and   lilawilso
If not, create one, setup your name and associate it with your business email address.

Do you have 2-factor-authentication enabled with your GitHub account? Yes, for both
If not, configure that first.

**Comment by mitovskaol** [comment]
@Nicole-Huard  The invites to both orgs bcgov and BCDevOps have been sent to the users above.

**Comment by Nicole-Huard** [comment]
Thank you Olena!
