### ISSUE TITLE
User Valerie Williams idir vwilliam is getting a duplicate error attempting to signon to our production application

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1218]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
User Valerie Williams idir vwilliam is getting a duplicate error attempting to signon to our production application,  I deleted the id from our production realm vtkayq4c and had her retry but she encountered the same error.   

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak

Yes 
## Step 3
Field the following information.

* Username to be removed: Valerie G Williams idir vwilliam
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Production

**Comment by nvunnamm** [comment]
@jhmccoll Removed user. Please verify now.
