### ISSUE TITLE
SIMS Business BCeID IDP in Existing Realm

### ISSUE THREAD

**Issue by abschwenker** [BCDevOps/devops-requests#1221]
I spoke with Marco and he directed me for this request. We are looking to add the business BCeID only IDP to our existing keycloak realm.

## Step 0
**Are you the product owner or project admin/team lead?** Yes

## Step 1
Are you new to Single Sign-On (Keycloak)? No

## Step 2
Field the following information.

* Project Name: SIMS
* Existing KeyCloak Realm: jxoe2o46

* Identity Providers Required
  - [ ] BCeID Business

* A list of redirect URLs for each environment (DEV, TEST, PROD). *These are the URLs that your application is allowed to use after sign-on events are complete. These are the secure "front door" for your application.*
  - DEV redirect URL(s): https://dev-aest-sims.apps.silver.devops.gov.bc.ca/
  - TEST redirect URL(s): https://test-aest-sims.apps.silver.devops.gov.bc.ca/
  - PROD redirect URL(s):https://prod-aest-sims.apps.silver.devops.gov.bc.ca/

## Step 3
For teams requesting access to BCeID, there is an approval process. Please provide the following information on this ticket. The IDIM team will review this information and will be in touch with you at the email provided.
The OCP-SSO team will provision your DEV and TEST clients right away, and your PROD client will be provisioned when the IDIM team approves your request.

* Organization Details (Organization/Division/Branch/Program): Please note this request is already in progress and IDIM is aware. Please let me know if you still require details.
* 
* **Exectutive Sponsor** Name, Title, & Email: 
* **Project Manager / Business Lead** Name, Title, & Email: 
* **Technical Lead** (if applicable) Name, Title, & Email: 
* **Privacy Lead** (if applicable) Name, Title, & Email: 
* **Security Lead** (if applicable) Name, Title, & Email: 
* **Communications Lead** (if applicable) Name, Title, & Email: 
* Name of service or application:
* URL of service or application:
* Estimated volume of initial users:
* Forecast of anticipated growth over the next three years:
* Date of release in production environment:
* Date of first use by citizens or end users:

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - Vardhman.Shankar@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Product Owner's IDIR name: 
* Product Owner's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

**Comment by nvunnamm** [comment]
@abschwenker we also have grandfathered BCeID (Basic, Business, Personal) for the realm jxoe2o46. Do you want us to remove that?

**Comment by arcshiftsolutions** [comment]
@nvunnamm - I was working with @abschwenker on this yesterday; will bring you up to speed during scrum.

**Comment by abschwenker** [comment]
It would be ideal if we can keep the grandfathered (Basic/business/personal) until we get everything switched over to the business only way, just so we dont have downtime. Thank you

**Comment by nvunnamm** [comment]
@abschwenker, we have configured Business BCeID IDP for jxoe2o46 in Dev and Test environment please verify.

**Comment by abschwenker** [comment]
@nvunnamm , Thank you very much, I do see them listed there. I will try and get to testing this week to make sure they will work and will be in touch if there are any issues. Thank you again
