### ISSUE TITLE
Realm vtkayq4c User Kendra Coen (kcoen) cannot login into Application 

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1224]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
User receives "InvalidatedFederatedIdentityActionMessage"   when attempting to login.  I have reviewed and application login account and it is fine.  Cleared local storage, and browser cache. 

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes

## Step 3
Field the following information.

* Username to be removed: kcoen  (Kendra Coen)
* Realm ID where user is having problem login: vtkayq4c 
* Environment in which you are facing issue: Production

**Comment by nvunnamm** [comment]
Hi @jhmccoll Looks like username is Kewiens not kcoen could you please confirm?

**Comment by jhmccoll** [comment]
Hi
  Yes I can confirm that Kendra Wiens just changed her name/idir to Kendra Coen/kcoen on Wednesday.  This is the same person.
John

John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”

**Comment by nvunnamm** [comment]
Removed user please verify.

**Comment by jhmccoll** [comment]
This is confirmed and working now.

Thank you so much for the prompt response!!

John

John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”
