### ISSUE TITLE
Pathfinder SSO Documize Space

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1226]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
Yes
## Step 1
Login to Documize with either an IDIR or GitHub account to create a Documize user record:
http://docs.developer.gov.bc.ca/
Done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
Check - good to go :)

## Step 3
Are you requesting to:
- [x] Create a Space
- [ ] Remove a Space

## Step 4
Fill out the following fields

* Ministry: Citizen Services
* Short Team/Organization Name: OCIO Strategic Design and Delivery 
* Team and Product Description: Pathfinder SSO
* Space Visibility: Public / Protected (only invited users could see): Protected

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - platformservicesteam@gov.bc.ca

* link to the GitHub ticket you just created: 
* Space Admin User
  - GitHub or IDIR account:
  - Business Email Address: 
  - RocketChat Account Username: 

Please note that we will only start processing your request when the email has been received.

## Step 6
Once we create the space for you, you will have full control over the space, including:
- space settings
- user access
- content management

Reference: https://docs.documize.com/

**Comment by ShellyXueHan** [comment]
@zsamji space created on Documize. You are hte admin of it, please add some description of the space later on!
