### ISSUE TITLE
Keycloak SSO client setup for CSB SFT

### ISSUE THREAD

**Issue by jennifer-dowd** [BCDevOps/devops-requests#1229]
For detailed information on the service, please reference the [Pathfinder SSO Wiki](https://github.com/bcgov/ocp-sso/wiki).

**This GitHub request process is only applicable for teams looking for integration with BCeID through Pathfinder SSO.** If you only need IDIR login, use the [Pathfinder SSO Client Request Web App](https://bcgov.github.io/sso-requests/). If you are looking for integration for IDIR login the process is completely self-serve and takes only minutes. You will need an IDIR to log in and you _should_ be a product owner, product admin, or team lead for a project. Once the automated provisioning is complete, your client details will be available securely through the web app. 

**If you have an urgent request, please contact the Pathfinder SSO Product Owner at bcgov.sso@gov.bc.ca**

## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people in your organization to make this request for you. 
We cannot process realm requests except from individuals in these roles.

**Note:** This SSO service is undergoing upgrades in 2021 and is currently not recommended for critical applications. Support is currently available only during business hours and only on a best efforts basis. If your application is critical, please contact Web Access Management (WAM) and/or Provincial Identity Information Management Program (IDIM).

## Step 1
Field the following information.

Project Name: CSB Nextcloud Project

## Step 2
Select BCeID identity provider flavour: IDIR only 

(Note: GitHub integration is available in all standard realms for developer convenience. It is not in Production).

(Note: If you are not looking for BCeID integration use the [Pathfinder SSO Client Request Web App](https://bcgov.github.io/sso-requests/) instead of submitting this issue)
  - [ ] BCeID Basic
  - [ ] BCeID Business
  - [ ] Both BCeID Basic AND BCeID Business
  - [X] IDIR (provided by default in all standard realms)

## Step 3
Provide a list of redirect URLs for each environment (DEV, TEST, PROD). *These are the URLs that your application is allowed to use after sign-on events are complete. These are the secure "front door" for your application.* If you do not know the URLs for all your environments, you can use a temporary one such as "http://localhost:5000" and change it later.
  - DEV redirect URL(s):  https://court-sft-dev.apps.silver.devops.gov.bc.ca
  - TEST redirect URL(s): https://court-sft-test.apps.silver.devops.gov.bc.ca
  - PROD redirect URL(s): https://court-sft.apps.silver.devops.gov.bc.ca

## Step 4
For teams requesting access to BCeID, there is an approval process. Please provide the following information on this ticket. The IDIM team will review this information and will be in touch with you at the email provided.
The OCP-SSO team will provision your DEV and TEST clients right away, and your PROD client will be provisioned when the IDIM team approves your request.

* Organization Details (Organization/Division/Branch/Program): Ministry of Attorney General
* **Exectutive Sponsor** Name, Title, & Email: 
* **Project Manager / Business Lead** Name, Title, & Email: 
* **Technical Lead** (if applicable) Name, Title, & Email: 
* **Privacy Lead** (if applicable) Name, Title, & Email: 
* **Security Lead** (if applicable) Name, Title, & Email: 
* **Communications Lead** (if applicable) Name, Title, & Email: 
* Name of service or application: CSB Nextcloud
* URL of service or application: see above URL's in Dev, Test and PROD
* Estimated volume of initial users: 10
* Forecast of anticipated growth over the next three years: 10-200+
* Date of release in production environment: Sept 1
* Date of first use by citizens or end users: Aug 24

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - bcgov.sso@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Product Owner's IDIR name: 
* Product Owner's Business Email Address: 
* Are you new to Single Sign-On (Keycloak)? If so, we will setup a meeting with you and your team for an onboarding meeting. 

Please note that we will only start processing your request when the email has been received.

**Comment by zsamji** [comment]
Hi @jennifer-dowd 

We are always looking for “real user” feedback and this presents as an opportunity. The good news of giving us feedback, is that you will have your IDIR configuration details by the end of our observation

As your team is seasoned with Pathfinder SSO requests, **would you be willing to try our pilot app and have a few of our teams observe your interaction?** . If this approach works for you, I’ll find 30-45 mins in your calendar. 

Thanks in advance!

**Comment by jennifer-dowd** [comment]
Sure! Not sure what that entails but happy to give it a go. Please include my Technical Lead – David Agahchen.

Cheers,
Jennifer Dowd
Senior Product Owner
Chief Technology Office/Information Systems Branch
Ministry of Attorney General and Public Safety Sector
Cell: 778-677-7078
Email: ***@***.******@***.***>
Offering acknowledgement in respect of the Lekwungen-speaking peoples, traditional keepers of this land, and the Songhees, Esquimalt, and WSÁNEĆ peoples whose historical relationships with this land continue today.

**Comment by jennifer-dowd** [comment]
Greetings - just an FYI. I am away Friday and Monday but @agahchen  is acting on my behalf for this request while I'm away.

**Comment by jennifer-dowd** [comment]
Greetings Platform Team - I've been advised by my Technical Lead, @agahchen  that we no longer need this request to be processed. If you could cancel that would be great.

**Comment by jlangy** [comment]
Thanks jennifer, we can cancel that request
