### ISSUE TITLE
Remove Personal BCeID support for Keycloak realm

### ISSUE THREAD

**Issue by fwkendall** [BCDevOps/devops-requests#1230]
## Step 1
Make sure no duplicated request exists ✅ 

## Step 2
Please answer the following questions about the new request type:

1. **What is it?**
Please provide an overview of what the request should do.

Please remove *only* Personal BCeID as an IDP off our realm: 4qjrpzzl.  Please start with Dev/Test first before moving to Prod so we can verify.

2. **Why should this be a new request type?**
A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!

Must be performed by a team with Keycloak realm config permissions.

3. **What information is required to fulfill this request?**
Do you best here - the Platform Services team can help if you're not sure!

I believe we need to provide info:

Keycloak realm: 4qjrpzzl
IDPs currently supported: IDIR, Business BCeID, Personal BCeID, Basic BCeID, BCSC in dev/test
IDPs to remove: Personal BCeID only
Contact: This GitHub ticket or @kendall on Rocket.Chat or kendall@freshworks.io
Request: please let me know once removed from dev/test so we can verify before proceeding to production changes

4. **What is the end result?**
Please provide plenty of details about what the end result should look like.

Keycloak realm 4qjrpzzl should support: IDIR, Business BCeID, Basic BCeID, BCSC in dev/test
Keycloak realm 4qjrpzzl should NOT support: Personal BCeID

**Comment by ConradBoydElliottGustafson** [comment]
@fwkendall This is a ticket for the Pathfinder SSO team. In the future, we have a generic request issue type for that: https://github.com/BCDevOps/devops-requests/issues/new?assignees=jlangy%2C+junminahn%2C+brycereid73%2C+arcshiftsolutions%2C+zsamji%2C+nvunnamm&labels=keycloak-realm%2C+pending%2C+sso%2C+standard+realm%2C+configuration&template=keycloak_configuration_change.md&title=

**Comment by ConradBoydElliottGustafson** [comment]
@caggles @patricksimonian @ShellyXueHan You three may remove yourselves from this if you like. We got it. ;-)

**Comment by nvunnamm** [comment]
@fwkendall, We have now added Basic and Business IDP. You will notice that there is still Grandfathered BCeID (Basic, Business, Personal) attached to the realm as we want you to test the new implementation is working and your team is comfortable removing Grandfathered BCeID and start using Basic and Business IDP.
Please let us know after testing so that we can remove Grandfathered BCeID.

**Comment by fwkendall** [comment]
Thanks for the update @nvunnamm 

We've been testing today on dev/test and have noticed that we are receiving a completely different *Provider User ID* for the same user account (Basic BCeID test accounts). Is this expected?

**Comment by ConradBoydElliottGustafson** [comment]
Part of it is done. We added the basic+business IDP. Marco and Niran spent some time troubleshooting the issue and came to the solution that there is a client login flow where we need to turn it off. There is an email chain between Niran and Kendall.

**Comment by fwkendall** [comment]
@ConradBoydElliottGustafson I don't have an email from Niran separate to this ticket, should I?

**Comment by ConradBoydElliottGustafson** [comment]
@fwkendall @nvunnamm I was just recording what Niran said at stand-up today. If there is anything you are missing just ping here and we will deal with it. Thanks Kendall!

**Comment by arcshiftsolutions** [comment]
Hi @fwkendall - you will get a new provider user ID for this user since it's using a new parent BCeID IDP. Most teams key on the user's GUID since it's always the same from IDIM. The Provider User ID is generated by Keycloak and will be different for other IDPs (which this new BCeID IDP is).

**Comment by nvunnamm** [comment]
@fwkendall I have used Kendall.A.OlsenMaier@gov.bc.ca to communicate. Please let me know if we need to use any other email.

**Comment by arcshiftsolutions** [comment]
Niran and I met with @fwkendall and discussed the situation overall. Kendall noted that she has some items to discuss with her team as far as identifiers being used from Keycloak/SSO. She also noted that she would likely be making some changes around the current BCeID IDP to pull the GUID (additional mapper). For now we're going to close this ticket until the team has made some decisions and are ready to proceed; we're going to open another ticket then.
