### ISSUE TITLE
Remove Personal BCeID from realm

### ISSUE THREAD

**Issue by rafasbcgov** [BCDevOps/devops-requests#1234]
## Step 1
Confirm that you are submitting the right issue type. 
* If you are wanting to onboard to Pathfinder SSO, please read the [Onboarding Documentation](https://github.com/bcgov/ocp-sso/wiki/SSO-Onboarding).
* If you are asking for a duplicate user to be removed from KeyCloak, please use the issue type: [Request to remove a duplicate user from Keycloak](https://github.com/BCDevOps/devops-requests/issues/new?assignees=jlangy%2C+junminahn%2C+brycereid73%2C+arcshiftsolutions%2C+zsamji%2C+nvunnamm&labels=keycloak-user%2C+sso&template=keycloak_user_removal_request.md&title=)
* If you are asking for a KeyCloak realm to get deleted, please use the issue type: [Request for delete a Pathfinder SSO Realm](https://github.com/BCDevOps/devops-requests/issues/new?assignees=jlangy%2C+junminahn%2C+brycereid73%2C+arcshiftsolutions%2C+zsamji%2C+nvunnamm&labels=keycloak-realm%2C+pending%2C+sso&template=keycloak_realm_removal.md&title=)

## Step 2
Description of the problem or change that is required.
Detailed description of the configuration change required (if known).
Change BCeID Identity Provider to remove Personal BCeID from authentication

## Step 3
Provide the following information:

* Project Name: Business Modernization and Analytics

If this is a request related to a dedicated realm (created before summer 2021)
* Keycloak realm ID: 4piqfpfu

**Comment by nvunnamm** [comment]
@rafasbcgov We have now added Basic and Business IDP in Dev and Test environments. You will notice that there is still Grandfathered BCeID (Basic, Business, Personal) attached to the realm as we want you to test the new implementation is working and your team is comfortable removing Grandfathered BCeID and start using Basic and Business IDP.
Please let us know after testing so that we can remove Grandfathered BCeID.

**Comment by rafasbcgov** [comment]
@nvunnamm Thanks! I've tested the new implementation and is working perfectly fine. All good to remove grandfathered BCeID. Once you do this can the _bceid-basic-and-business_ idp be renamed to _bceid_ ?

**Comment by nvunnamm** [comment]
@rafasbcgov Removed grandfathered BCeID from your realm. Yes, It can be renamed, and is up to the realm administrator of the realm to change it :)

**Comment by rafasbcgov** [comment]
Awesome thanks, I've changed the display name and we'll adapt our code to use the new idp alias :) 

Feel free to close this one.
