### ISSUE TITLE
remove personal BCeID from upstream IDP

### ISSUE THREAD

**Issue by ll911** [BCDevOps/devops-requests#1236]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

Please remove Personal BCeID from upstream IDP for following realm 
`j3nwwef1`

**Comment by ConradBoydElliottGustafson** [comment]
@caggles @patricksimonian @ShellyXueHan Looks like this should have been tagged "sso". I created a new issue type for generic SSO requests, but people don't seem to be finding it: https://github.com/BCDevOps/devops-requests/blob/master/.github/ISSUE_TEMPLATE/keycloak_configuration_change.md

I've tagged this one now and the Pathfinder SSO team has it on our board and will deal with it. Feel free to unassign yourselves. Peace and love -- Conrad

**Comment by nvunnamm** [comment]
@ll911 
We have now added Basic and Business IDP in Dev and Test environments. You will notice that there is still Grandfathered BCeID (Basic, Business, Personal) attached to the realm as we want you to test the new implementation is working and your team is comfortable removing Grandfathered BCeID and start using Basic and Business IDP.
Please let us know after testing so that we can remove Grandfathered BCeID.

**Comment by zsamji** [comment]
@nvunnamm will look through realmomatic logs to find out who @ll911 is. Friendly ask @ll911 could you ping us in sso channel in rocket chat as we'd like to follow up with you

**Comment by ConradBoydElliottGustafson** [comment]
@nvunnamm @zsamji Looks to me like that realm pre-dates realm-o-matic (records are here: https://github.com/bcgov-c/realm-o-matic-records/tree/master/records). 

There are 4 realm admins for that realm. Might be worth sending them an email. https://dev.oidc.gov.bc.ca/auth/admin/master/console/#/realms/j3nwwef1/groups/62617a7f-cf5e-47ff-86b8-ad950ac159b2/members

**Comment by zsamji** [comment]
sent Leo an email. will keep open for another week or so

**Comment by zsamji** [comment]
sent an email to @ll911 --- hoping for a response before the end of the month

**Comment by zsamji** [comment]
received "feel free to close the ticket, all works as expected. Thx."
