### ISSUE TITLE
Sonar Cloud - Project addition 

### ISSUE THREAD

**Issue by vyasworks** [BCDevOps/devops-requests#1237]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**

Yes - https://github.com/bcgov/hcap

**Are you the admin user of the GitHub repositories?**

Yes also @fwkendall 

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: HCAP - Health Career Access Program
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/hcap
- 

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
@vyasworks project created, you are the admin!
