### ISSUE TITLE
HETS team cookie SSO Issue

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [BCDevOps/devops-requests#1238]
AC:
Document the issue adequately and educate teams (Conrad) - DONE
Turn on cookies in standard realms. - Niran

The HETS team reached out to Junmin directly with an interesting problem/behaviour in a standard BCeID realm.

Original Trello ticket: https://trello.com/c/aJbolTo2/155-debugging-issues-of-refreshing-keycloak-token-in-hets-teams-single-page-applications

Background: HETS team reported issues of validating/refreshing Keycloak tokens in HETS team's single-page applications with clients in standard realms.
- They have single-page applications following the Keycloak-js example code.
- keycloak-documentation/javascript-adapter.adoc at 8436c1866b67a420e44e467229f1042f335713b2 · keycloak/keycloak-documentation
- Expected behaviour: Keycloak server returns the existing session token to the application.
- Current behaviour: User needs to authenticate Keycloak server every time clicking the menus.
- It only happens with the Keycloak clients in standard realms.
- HETS team has a sample application to test the behaviours.
- GitHub - ychung-mot/kctest

We originally created the standard realms with cookies disabled. The intention was to prevent "accidental" cross-IDP SSO between apps within the same realm. Unfortunately, with cookies turned off, the standard keycloak client-side libraries (like keycloak-js) end up initiating a new authentication handshake with every request. In the case of the HETS team, this was causing the Keycloak login page to show up. They could click "IDIR" and get SSO at the IDIR level (no credential input required), but that's not good UX.

Decision: Turn the cookies back on and educate the users that they really need to check the IDP of the authenticated user if they are in a realm with multiple IDPs and that is something that matters to them. Documented on the wiki here: https://github.com/bcgov/ocp-sso/wiki/Using-Your-SSO-Client (section: Do Validate the IDP in the JWT)

**Comment by nvunnamm** [comment]
@ychung-mot Cookies has been enabled now in all environments. Please let us know if you face any issues.

**Comment by ConradBoydElliottGustafson** [comment]
Email from Clare (PO). Meeting today at 1 to clarify and understand.

**Comment by zsamji** [comment]
Confirmed with @ychung-mot no outstanding development technical issues. Provided recommendation to [skip keycloak login page ](https://github.com/bcgov/ocp-sso/wiki/Using-Your-SSO-Client#do-skip-the-keycloak-login-page). Recognized/aligned on all players involved in BC Gov IDP space. please do reach out on rocketchat or email if there's anything more we can help with(subsequent new ticket). thanks!
