### ISSUE TITLE
access for the 4c2ba9-* namespaces

### ISSUE THREAD

**Issue by dragancolic-bcgov** [BCDevOps/devops-requests#1239]
Hi there,

I would need access for the 4c2ba9-* namespaces. I am on the MDS team with Aaron Unger as mine PO.

Thank you,
Dragan Colic

**Comment by patricksimonian** [comment]
Hi there Dragan,

Namespace level access is acquired through your project lead or other namespace administrators.  It does look like you need access to the Openshift cluster its self however. If you can have one of your teammembers invite you into the bcgov/bcdevops github organizations using https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/ that would be awesome. From there you will have access into Openshift and then will require one of your administrators to grant you access into the namespaces.
