### ISSUE TITLE
Setup integration between Azure AD & SSO for IDIR 

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1248]
Internall tracking:
Is your feature request related to a problem? Please describe.
Setup integration between Azure AD & SSO for IDIR. IDIM has setup a test instance which we can use to ensure we get the attributes we need in the token payload.

We have completed this integration. Chris was able to provide the IDIR GUID & user ID; after we added mappers to the identity provider, the attributes are now available.

**Comment by zsamji** [comment]
https://github.com/bcgov/ocp-sso/issues/471

**Comment by arcshiftsolutions** [comment]
https://github.com/BCDevOps/developer-experience/issues/1193
