### ISSUE TITLE
Add user to realm uicn0kkh 

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1249]
on behalf of @garywong-bc, I'm submitting this ticket, can we please add him as admin to realm uicn0kkh and notify him once he's been added. 

Thanks in advance.

**Comment by arcshiftsolutions** [comment]
Have reached out to @garywong-bc to log into the realms so we can add him as an admin.

**Comment by arcshiftsolutions** [comment]
@garywong-bc is now an administrator in these realms.
