### ISSUE TITLE
Azure AD as part of KeyCloak realm that allows openshift access

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1252]
copying to our zenhub board. all details captured here
https://github.com/BCDevOps/developer-experience/issues/1609

**Comment by arcshiftsolutions** [comment]
Meeting with Nick & Chris around this later today.

**Comment by arcshiftsolutions** [comment]
Have created the DEV & TEST realms (_azureidir). Provided the redirectURIs and are now waiting for config from IDIM.

**Comment by arcshiftsolutions** [comment]
We have added the configuration in DEV and it's fully working. We believe the client secret is off in TEST & PROD...Chris and I will regenerate new secrets and test it on Monday (he's off today).

**Comment by arcshiftsolutions** [comment]
This implementation is now working in DEV/TEST/PROD.
