### ISSUE TITLE
Please remove IDIR PAWSANDH (Pawan Sandhu) access required in Production realm vtkayq4c

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1256]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes for realm vtkayq4c

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account? IDIR PAWSANDH was prematurely deleted last week. It has been recreated but user cannot access applications. She is receiving message: username already exists. 
- What result of debugging have you obtained that lead you to request an account removal?
I deleted the IDIR in our Keycloak realm but she received the same error and it did not recreate which it normally does on the first access to The Q.  She has cleared cache in her browser.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes she is ready to have her Keycloak entry removed

## Step 3
Field the following information.

* Username to be removed: IDIR:  PAWSANDH for Pawan Sandhu
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue:  Production

**Comment by arcshiftsolutions** [comment]
User has been removed from the parent IDIR realm. Please ask the user to log in again.

**Comment by jhmccoll** [comment]
Hi Marco,
  The user was able to successfully login now.

  Thanks so much for you help!

John

John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”
