### ISSUE TITLE
API Call & UPtime robot

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1257]
currently uptime for SSO Keycloak Only several longer than usually response time. this happens to several other services that we monitor, where the service url works but once user try to login or other actions, it’s not responding
It was still alive but no DB connections so it was likely throwing errors in the background.
An API call would be better

**Comment by arcshiftsolutions** [comment]
I've just provided @ShellyXueHan with the credentials/URLs in DEV for testing.

**Comment by arcshiftsolutions** [comment]
These have now been completed with @ShellyXueHan ; we have our new URL.
