### ISSUE TITLE
Delete deactivated idir user account with user name PMITRA

### ISSUE THREAD

**Issue by fwpushan** [BCDevOps/devops-requests#1258]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
`This account was deactivated account for InvaisvesBC project, no longer in use.`
- What result of debugging have you obtained that lead you to request an account removal?
`Recently I get a new IDIR for MoH (HLTH) with same user name. when I tried to login I get following error. Possibly this is conflicting with my old account. For your information, login with siteminder is succeful`
<img width="1440" alt="IDIIR" src="https://user-images.githubusercontent.com/46456190/132573812-44a3dce8-089b-4c90-bb86-45b6daf1c202.png">

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: 
      PMITRA | pmitra
* Realm ID where user is having problem login: 
     idir 
* Environment in which you are facing issue: 
  - https://oidc.gov.bc.ca/
  - https://test.oidc.gov.bc.ca/
  -  https://dev.oidc.gov.bc.ca/

**Comment by arcshiftsolutions** [comment]
I've now removed Pushan's user in all three instances.
