### ISSUE TITLE
OpenShift Access Request for ECAS system - Hoang.Le@cgi.com

### ISSUE THREAD

**Issue by bcgov-hl** [BCDevOps/devops-requests#1259]
Hi there,

I am from CGI developer supporting ECAS system. Could you please grant me the access to OpenShift?
I have a couple of support tickets to deal with

Thanks!
Hoang

**Comment by ShellyXueHan** [comment]
@bcgov-hl we don't handle access request from someone for themselves. Please have your product owner or technical lead to get you the access needed. They can find the link to access management app from issue template in this repo, or head over directly: https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/
