### ISSUE TITLE
Onboard 3 new EPIC devs to OpenShift

### ISSUE THREAD

**Issue by ActionAnalytics** [BCDevOps/devops-requests#126]
## Step 0
**Are you the product owner or project admin?**
Yes

**Do you have a GitHub account?**
ActionAnalytics

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

OpenShift User Access Request:
* Full name: Dylan Hemsworth
* GitHub ID: dhlevi
* Email address: mondopotato_77@hotmail.com
* Organization: EAO, EPIC
* Project role: Full-stack Developer
* OpenShift projects: esm, esm-dev, esm-test, esm-prod 

OpenShift User Access Request:
* Full name: Sergey Fedyanin
* GitHub ID: vesalink
* Email address: vesalink@gmail.com
* Organization: EAO, EPIC
* Project role: Full-stack Developer
* OpenShift projects: esm, esm-dev, esm-test, esm-prod 

OpenShift User Access Request:
* Full name: Cody Bergin
* GitHub ID: CEBergin
* Email address: cbergin@vividsolutions.com
* Organization: EAO, EPIC
* Project role: Full-stack Developer
* OpenShift projects: esm, esm-dev, esm-test, esm-prod 

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
Users invited to BCDevOps GitHub org. Access to namespaces could be further grant by admin user.
