### ISSUE TITLE
Remove user: 

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1260]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

**As per Rockethchat request**
## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
**remove a user from Openshift’s Keycloak instance. I think this is the problem, basically we have a developer who has changed his github ID but has had access to openshift projects in the past. When logging in with his newly changed ID, he has access to his old projects which in rolebindings has his old ID. I can’t recall who helped me before with a similar issue,Thanks! 

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.
Old userID: dheepakramanathan
new userid: dheepak-aot

**Comment by junminahn** [comment]
@zsamji I believe we don't have the information of the realm itself?

**Comment by junminahn** [comment]
@zsamji I removed the user `dheepakramanathan` from `_idir` realm in the prod instance.

**Comment by zsamji** [comment]
@junminahn thank yoU!

**Comment by zsamji** [comment]
asking client to confirm to close

**Comment by abschwenker** [comment]
Issue is resolved. user is now logging into Openshift without issues. Thank you!
