### ISSUE TITLE
SSO for RoadSafety's Digital Forms Project

### ISSUE THREAD

**Issue by jonathan-longe** [BCDevOps/devops-requests#1261]
For detailed information on the service, please reference the [Pathfinder SSO Wiki](https://github.com/bcgov/ocp-sso/wiki).

**This GitHub request process is only applicable for teams looking for integration with BCeID through Pathfinder SSO.** If you only need IDIR login, use the [Pathfinder SSO Client Request Web App](https://bcgov.github.io/sso-requests/). If you are looking for integration for IDIR login the process is completely self-serve and takes only minutes. You will need an IDIR to log in and you _should_ be a product owner, product admin, or team lead for a project. Once the automated provisioning is complete, your client details will be available securely through the web app. 

## Step 0
**Are you the product owner or project admin/team lead?**
I am submitting this request on behalf of and with the full knowledge of the project owner as set out below.  The product owner does not have a GitHub account.

## Step 1
Project Name: RoadSafety Digital Forms

## Step 2
Select BCeID identity provider flavour

  - [ ] BCeID Basic
  - [X] BCeID Business
  - [ ] Both BCeID Basic AND BCeID Business
  - [X] IDIR (provided by default in all standard realms)

## Step 3
Provide a list of redirect URLs for each environment (DEV, TEST, PROD). *These are the URLs that your application is allowed to use after sign-on events are complete. These are the secure "front door" for your application.* If you do not know the URLs for all your environments, you can use a temporary one such as "http://localhost:5000" and change it later.
  - DEV redirect URL(s): https://rsbc-dh-prohibition-web-app-dev.apps.silver.devops.gov.bc.ca/redirect
  - TEST redirect URL(s): https://rsbc-dh-prohibition-web-app-test.apps.silver.devops.gov.bc.ca/redirect
  - PROD redirect URL(s): [TBD]

## Step 4
For teams requesting access to BCeID, there is an approval process. Please provide the following information on this ticket. The IDIM team will review this information and will be in touch with you at the email provided.
The OCP-SSO team will provision your DEV and TEST clients right away, and your PROD client will be provisioned when the IDIM team approves your request.

* Organization Details (Organization/Division/Branch/Program):   PSSG / RoadSafetyBC / RSI / Digital Forms
* **Exectutive Sponsor** Mary LaBoucane, Executive Director - Strategic Initiatives
* **Project Manager / Business Lead** Brad Truswell, Director - Road Safety Systems Service Delivery
* **Project Owner** Anna Mantel, Product Owner - Digital Forms
* **Developer**  Jonathan Longe, Developer
* **Technical Lead** Eric Wright, Technical Architect
* **Privacy Lead** Karine Bordua, Ministry Privacy Officer - Information Systems Branch

* Name of service or application:  **Digital Forms Web Application**
* URL of service or application:  **DRAFT:  https://rsbc-dh-prohibition-web-app-dev.apps.silver.devops.gov.bc.ca/**
* Estimated volume of initial users:  **25**
* Forecast of anticipated growth over the next three years:  **100**
* Date of release in production environment:   **November 2021**
* Date of first use by citizens or end users:  **January 2022**

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - bcgov.sso@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Product Owner's IDIR name: 
* Product Owner's Business Email Address: 
* Are you new to Single Sign-On (Keycloak)? If so, we will setup a meeting with you and your team for an onboarding meeting. 

Please note that we will only start processing your request when the email has been received.

**Comment by zsamji** [comment]
requesting meeting with client on Sept 14 11 am

**Comment by jonathan-longe** [comment]
Wow, that was fast!  Thanks for setting up a meeting so quickly Zorin.

**Comment by jonathan-longe** [comment]
@zsamji Adding some information that was missing above:

Executive Sponsor Name, Title, & Email:
Mary LaBoucane, Executive Director - Strategic Initiatives, mary.laboucane@gov.bc.ca

Project Manager / Business Lead Name, Title, & Email:
Brad Truswell, Director - Road Safety Systems Service Delivery, brad.truswell@gov.bc.ca

Anna Mantel, Product Owner - Digital Forms, anna.mantel@gov.bc.ca

Technical Architect (if applicable) Name, Title, & Email:
Eric Wright, Technical Architect, eric.wright@quartech.com

Privacy Lead (if applicable) Name, Title, & Email:
Karine Bordua, Ministry Privacy Officer - Information Systems Branch, karine.bordua@gov.bc.ca

**Comment by jlangy** [comment]
The dev and test environments have been setup

**Comment by zsamji** [comment]
@jonathan-longe we've provided the details via email. please do reach out via #sso if you have any additional q. All the best for your project
