### ISSUE TITLE
Remove ANOJSZEW

### ISSUE THREAD

**Issue by josekudiyirippil** [BCDevOps/devops-requests#1262]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
User came from another ministry and getting user already exists issue

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
yes

## Step 3
Field the following information.

* Username to be removed: ANOJSZEW
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: prod

**Comment by junminahn** [comment]
@zsamji The user associated with username `anojszew` is removed from the parent realm `idir` in the production environment.
