### ISSUE TITLE
Chromatic App Integration Request

### ISSUE THREAD

**Issue by jTendeck** [BCDevOps/devops-requests#1265]
## Step 0
**Do you have repos on bcgov GitHub Organization?**
If yes, please proceed with the request.

**If there is similar applications/tools available in the community, have you tried them out?**
There are many well supported community tools for various purposes, such SonarCube and BDDStack. 
Before you start with the new tools, have you consider trying out those that are available and widely adopted by the other application teams? 
If you have done so and do found that the existing ones does not match your need, please proceed.

**Have you tested out this GitHub application already?**
We understand that there are a lot of new and cool GitHub Applications out there that teams could like to try out. 
However, we cannot just enable the integration without evaluating the app, as those are open to all application teams. 
We believe you have tested out the GitHub apps and had good reasoning for the preference before making this request.

## Step 1
Please fill out the team and project info so we know how to contact you:

* Product Name: API Services Portal
* Team Name: API Program Services (APS)
* GitHub Repositories on bcgov: api-services-portal

## Step 2
Please provide details about the requested GitHub App. Take a look here for a [good example](https://github.com/BCDevOps/platform-services/issues/120/)

1. Brief introduction of the app:

To develop React components within our project we use a tool called Storybook. Essentially, Storybook allows developers to create React components in an isolated environment. It also enables developers to create documentation for these components. It has proven to be a valuable tool for front-end development.

One of the issues with it is there is not an easy and intuitive way to share our Storybook out of the box. If, for instance, a developer wanted a UI/UX designer to review a new component, the designer would need to clone the repo, set up the development environment, and then run Storybook locally to review the components. This is a cumbersome process, compounded by the fact that the designer requires the dependencies and technical know-how to complete this task.

This is where Chromatic comes in. At its core, Chromatic is a tool that adds a lot of extremely useful features to Storybook. Not only does it allow us to easily build and share our Storybook online, it also has a built-in feedback and visual regression testing system.

It also integrates easily with CI tools such as GitHub Actions. Essentially, when a push is made to the repo, Chromatic builds the Storybook and visual regression testing occurs for each component. After testing, team members can go to the Chromatic console and inspect each test, comparing the new component changes to the old, add comments, and then approve/deny the design changes. In summary, it is like code review, but for UI, and we feel that it will facilitate our issues with Storybook sharing and collaboration with everyone on our team.

2. General Criteria:
  - How Easy / Fast / Repeatable is it to use and maintain for both Development Teams and Platform Services Teams:
    - Cloud-based: minimal setup and maintenance required
    - Application UI is simple and intuitive
    - Commenting and reviewing tests is easy. Changes to components are highlighted, and it is easy to compare old components to new changes
    - Easily integrates with GitHub actions
  - Customizable:
    - The actual application itself is fairly rigid with minimal customization
  - User Access Model:
    - Chromatic projects sync with collaborators from the GitHub project repo
    - Collaborators must login in to Chromatic, which they can do using their GitHub credentials
    - Collaborators can also be invited via email
    - Collaborators can then be assigned different roles with a set of permissions (ie: owner, developer, viewer, reviewer, etc)
    - Chromatic requests the following OAuth scopes when first signing in: ['user:email', 'read:user', 'read:org', 'repo:status']
  - License:
    - I'm not 100% sure if this is relevant but the CLI appears to have an [MIT License](https://github.com/chromaui/chromatic-cli/blob/next/LICENSE)
  - BCGov STRA:
  - Price Model:
    - Free for open source. Paid subscriptions are available as well.

3. Comparison between Existing Tools Used by the Community

One option is to just use GitHub Pages for sharing our Storybook build. A link comparing Chromatic to other services is also provided below.

  - pros:
    - Provides us with a shareable link
    - Built right in to GitHub
    - Easy to build, deploy with GitHub Actions
  - cons:
    - No built-in visual regression testing
    - No built-in commenting/feedback system, making UI/component reviews more difficult between designers, developers, and other team members

4. Relevant Resources and Links
  - [Storybook](https://storybook.js.org/)
  - [Chromatic](https://www.chromatic.com/)
  - [Chromatic Alternatives](https://www.chromatic.com/compare/chromatic)
  - [Chromatic Pricing and Features Overview](https://www.chromatic.com/pricing)

**Comment by jTendeck** [comment]
Hi there!

It looks like it has been approved but it doesn't seem like we are able to use the application within the repo yet... it still says it is pending under authorized apps:

![image](https://user-images.githubusercontent.com/34200068/133864589-e0f55f78-cd45-4cf8-8103-2d9fdd9a0518.png)

Are there additional steps that are required?

Thanks for your help!

**Comment by ShellyXueHan** [comment]
@jTendeck I've approved the github app. Please check now. Thx!

**Comment by jTendeck** [comment]
Perfect, thank you!
