### ISSUE TITLE
FOM Production BCeID  [ KeyCloak Realm ID ( ichqx89w ) ]

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1266]
See email/internal rocketchat for details

**Comment by zsamji** [comment]
team reviewed and will configure with ansible

**Comment by zsamji** [comment]
RC LINK: https://chat.developer.gov.bc.ca/group/Pathfinder-SSO-Team?msg=jAbHHxn6QhCw4J6Qm

**Comment by jlangy** [comment]
Added the BCeID IDP to the prod environment

**Comment by zsamji** [comment]
for reference: https://github.com/BCDevOps/devops-requests/issues/1151

**Comment by zsamji** [comment]
@jlangy  moving to done on our behalf --- let me know if im wrong
