### ISSUE TITLE
Offboard Kathy Do 

### ISSUE THREAD

**Issue by MaxWardle** [BCDevOps/devops-requests#127]
## Step 0
**Are you the product owner or project admin?**
admin

**Do you have a GitHub account?**
MaxWardle

**Do you have 2-factor-authentication enabled with your GitHub account?**
yes

## Step 1
Are you requesting to:
- [ ] grant user access
- [x] remove user access

## Step 2
Fill out the following fields

* Full Name: Kathy Do
* GitHub ID: @kathydo
* Business Email Address: Kathy.Do@gov.bc.ca
* Organization: EAO, EPIC
* Project Role: Full-stack Developer Co-op
* OpenShift Projects/Namespaces: esm, esm-dev, esm-test, esm-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
See you @kathydo :(
