### ISSUE TITLE
Install Renovate automated dependency Github App

### ISSUE THREAD

**Issue by conbrad** [BCDevOps/devops-requests#1271]
## Step 0
**Do you have repos on bcgov GitHub Organization?**
If yes, please proceed with the request.

**If there is similar applications/tools available in the community, have you tried them out?**
We have been using Github's built in [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) tool, but have been overwhelmed by dependency PRs for devs to review for any breaking changes, which affects our product velocity.

**Have you tested out this GitHub application already?**
Yes, https://github.com/conbrad/renovate-test/pull/3

## Step 1
Please fill out the team and project info so we know how to contact you:

* Product Name: Wildfire Predictive Services
* Team Name: Predictive Services Unit
* GitHub Repositories on bcgov: https://github.com/bcgov/wps

## Step 2
Please provide details about the requested GitHub App. Take a look here for a [good example](https://github.com/BCDevOps/platform-services/issues/120/)

1. Brief introduction of the app: Automated dependency updates with configuration for grouping updates.

2. General Criteria:
  - How Easy / Fast / Repeatable is it to use and maintain for both Development Teams and Platform Services Teams: [Easy, it's a Github App.](https://github.com/marketplace/renovate)
  - Customizable: Yes (https://docs.renovatebot.com/configuration-options/)
  - User Access Model: Repository contributors can configure it
  - License: GNU Affero General Public License [repo link](https://github.com/renovatebot/github-action/blob/main/license), [wikipedia description](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License)
  Key license difference from GPL from Wikipedia: 
  
 "The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.

The purpose of the GNU Affero GPL is to prevent a problem that affects developers of free programs that are often used on servers."

  - BCGov STRA: Unknown (Similar to other Github Apps I presume)
  - Price Model: Free

3. Comparison between Existing Tools Used by the Community
  - pros: Allows for grouped dependency updates. This is important because devs spend a lot of time babysitting individual Dependabot PR dev deployments.
  - cons: Not built into Github

4. Relevant Resources and Links
- [Dependabot does not support grouping updates](https://app.zenhub.com/workspaces/wildfire-predictive-services-5e321393e038fba5bbe203b8/issues/bcgov/wps/1354), the reason for this request.
- Renovate Github Action: https://github.com/marketplace/renovate
- Documentation: https://docs.renovatebot.com

**Comment by conbrad** [comment]
@mitovskaol thanks for approval! Is the app installation a separate step? I still don't see it in our integrations tab under settings.

**Comment by mitovskaol** [comment]
Our Platform Admins will have to install it first. They usually process the DevOps requests on Tue and Thu. Can you wait until Thursday or you need it before then?

**Comment by conbrad** [comment]
> Our Platform Admins will have to install it first. They usually process the DevOps requests on Tue and Thu. Can you wait until Thursday or you need it before then?

All good, Thursday works! Thanks again!

**Comment by ShellyXueHan** [comment]
Hi @conbrad I don't see an app request from bcgov. Please start a install request and I'll proceed and approve.

**Comment by conbrad** [comment]
Hi @ShellyXueHan thanks for following up. For some reason I can't request the Renovate Github app for the bcgov org or our wps repository within it. I'm going to see if they have an action I can schedule instead and I'll keep you posted. 

Thanks, again!

**Comment by conbrad** [comment]
Hi @ShellyXueHan, we've got the action working in our pipeline now instead so I'll close this issue now. Thanks again for following up!
