### ISSUE TITLE
Request to remove a duplicate user (BillyLi) from Keycloak

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/devops-requests#1272]
Step 0
Are you the Keycloak Realm Admin?
If not, you will need to ask one of the admin user in your realm to make this request instead.

Step 1
Provide some background on the user account issue.

What is the issue with the user account?
I can not login to https://oidc.gov.bc.ca/auth
What result of debugging have you obtained that lead you to request an account removal?
I saw an existing user profile message
Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

 Confirm that user is ready to have the account removed from Keycloak
Step 3
Field the following information.

Username to be removed: BillyLi
Realm ID where user is having problem login: BILLYLI
Environment in which you are facing issue: https://oidc.gov.bc.ca/

**Comment by w8896699** [comment]
![](https://chat.developer.gov.bc.ca/file-upload/naewoNEw2akSNpPLr/Screen%20Shot%202021-09-21%20at%204.14.07%20PM.png)

**Comment by junminahn** [comment]
@w8896699 I see `billy.li@gov.bc.ca` in `idir` realm in prod environment. can you confirm that this is the one?

**Comment by w8896699** [comment]
Yes, This is my email.

**Comment by junminahn** [comment]
@w8896699 the user associated with the username `BillyLi` in `idir` realm in the prod environment.

**Comment by junminahn** [comment]
@w8896699 Hi Billy, can you confirm that you are not blocked anymore so that we can close this ticket? :)

**Comment by w8896699** [comment]
Hi @junminahn , I am still seeing the same error message😂. and still can not login

**Comment by junminahn** [comment]
@w8896699 I removed from `idir` and `devhub` both realms. can you try again?

**Comment by w8896699** [comment]
Error msg change! is now : User with username billyli@idir already exists. How do you want to continue?

**Comment by arcshiftsolutions** [comment]
@w8896699 - Can you please post a screenshot of the error along with the URL in the browser bar when the error occurs?

**Comment by w8896699** [comment]
<img width="1575" alt="Screen Shot 2021-09-22 at 2 05 54 PM" src="https://user-images.githubusercontent.com/22565041/134421942-9c0ae747-dd63-40dd-bb0f-69e6de27862e.png">
@arcshiftsolutions

**Comment by junminahn** [comment]
@w8896699 I remove the users based on the email address this time. can you try again?

**Comment by w8896699** [comment]
I can log in now! Thank you! You may close this issue now.

**Comment by zsamji** [comment]
moving to done on behalf of @junminahn (until his access is cleared)
