### ISSUE TITLE
Request to create private bcgov-c repo for CDDS

### ISSUE THREAD

**Issue by seeker25** [BCDevOps/devops-requests#1273]
Hello, 

I am requesting to create a private repo bcgov-c for CDDS (Court Digital Displays)

* Project Name: cdds
* GitHub Org: bcgov-c

I've emailed the other details.

**Comment by rloisell** [comment]
Please create this repo, with the owner being the @ag-pssg-isb-sa  GitHub account.

**Comment by ShellyXueHan** [comment]
Repo created, @ag-pssg-isb-sa is the admin.
