### ISSUE TITLE
FOI-Flow Request for import GitHub repository on SonarCloud

### ISSUE THREAD

**Issue by acoard-aot** [BCDevOps/devops-requests#1274]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
Yes.

**Are you the admin user of the GitHub repositories?**
Yes, I have admin access to repository.

## Step 1

> Login to SonarCloud console with your GitHub accounthttps://github.com/bcgov/foi-flow. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.
> 
> ***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

I completed the above and the org appeared as expected.

## Step 2
Fill out the following fields

* Project Name: FOI Modernization
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/foi-flow
- https://github.com/bcgov/foi-file-conversion

## Step 3

Please include:

- acoard-aot (myself)
- divya-aot
- abin-aot
- sumathi-aot
- lmullane (if sonar account exists).

(Note: If I'm able to add users after, feel free to ignore, I'm happy to add them)

Thanks in advance,
Adam

P.S.  The `.sonarcloud.properties` file is not yet in the `main` branch, it's only in a feature branch (`dev-AC-58`).  Please let me know if it has to be merged in prior to onboarding.  Thanks.

**Comment by ShellyXueHan** [comment]
@acoard-aot projects created in sonarcloud. You are the admin and can invite the rest of the team.

**Comment by acoard-aot** [comment]
Thanks a ton!
