### ISSUE TITLE
Pleaes fix the audience claim of HETS client in PROD and add a temprorary redirect URL for testing

### ISSUE THREAD

**Issue by ychung-mot** [BCDevOps/devops-requests#1276]
## Step 1
Confirm that you are submitting the right issue type. 
Yes, I confirm.

## Step 2
1. The audience claim of hets client in PROD is supposed to be "hets" but currently it's "account". Please fix the value.
2. I would like to do a full test before go-live, so please add the following temprory redirect URL to the PROD Keycloak client. After testing I will make another request to remove it.
   http://localhost:3000

## Step 3

- Project Name:  HETS
- Confirmation and date of IDIM approval for BCeID Prod : <please fill out>
- Technical contact person: 2021-09-28
- Dev/Test Onboarding link: https://app.zenhub.com/workspaces/sso-ops-support-60490daf31a4370010920b0a/issues/bcdevops/devops-requests/1189
- Go live date: Oct 14.

**Comment by junminahn** [comment]
this issue is closed as the client in the production environment for the HETS team is created and confirmed working.

**Comment by ychung-mot** [comment]
I confirm that the client is working properly. Can you please remove the http://localhost:3000 from the redirect URL list?
