### ISSUE TITLE
Request access to Grafana dashboard

### ISSUE THREAD

**Issue by pturnbul** [BCDevOps/devops-requests#1279]
Working with Justin Hewitt and extended DevExchange team on utilization of current Openshift 4.x private cloud implementation.. need to review overall SILVER cluster utilization dashboard for reference.

**Comment by juhewitt** [comment]
@StevenBarre I think we'll need your help on this one this week.

**Comment by pturnbul** [comment]
Thanks Justin.

**Comment by pturnbul** [comment]
@juhewitt @StevenBarre confirmed that I need access to the OCP console in order to gain access to the Grafana Dashboards as the oauth in Grafana leverages the RBAC controls in the OCP cluster.. obviously I don't need access to the OCP Console nor do I want it... is there an easy way to provide say RO to the console so I can see the Grafana dashboards? When I try to access https://console.apps.silver.devops.gov.bc.ca/ by BC-Gov Github credentials don't provide me access..

Thoughts/comments?

Thanks all.

P.

**Comment by mitovskaol** [comment]
The changes in Silver will be applied at the CCM run on Oct 21.
