### ISSUE TITLE
Request for new BCGOV Membership for user: LL-scj-gov

### ISSUE THREAD

**Issue by GovtRyan** [BCDevOps/devops-requests#128]
Hi, I would like to request that my lead developer, Lorne Lovett, have BCGov membership:

Project name: SCJ-Online-Booking
GitHub organization: BCGOV
New user's full name: Lorne Lovett
New user's GitHub ID: LL-scj-gov
New user's email address associated with the GitHub account: lorne.lovett@courts.gov.bc.ca
New user's organization: Superior Courts Judiciary, Application Service Development (SCJ, ASD)
New user's role on the project: Full-stack developer
GitHub repositories: https://github.com/bcgov/SCJ-Online-Booking

**Comment by ShellyXueHan** [comment]
@GovtRyan I see that Lorne is already admin on the repo as Collaborator, please specify the reason for GitHub org membership.

**Comment by GovtRyan** [comment]
Thanks Shelly.  And Sorry about this, you are right - I need to get him access to a different group, and I got mixed up.  Sorry, and Thanks again.  You can close this.
