### ISSUE TITLE
Cluster Reader - Bruce Li

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/devops-requests#1282]
1. **What is it?** Please provide an overview of what the request should do.
Cluster reader for all clusters for Bruce Li

2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!

3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
GitHub Account is:
bruce-wh-li 

4. **What is the end result?** Please provide plenty of details about what the end result should look like.
Bruce has read access to all clusters (CLAB, KLAB, Silver, Gold, Gold-DR)

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/278

Will be pushed to clusters next week

**Comment by ShellyXueHan** [comment]
@NickCorcoran @bruce-wh-li this should be done already, please double check and close the ticket. Thx!
