### ISSUE TITLE
Private Repos for BCPRS

### ISSUE THREAD

**Issue by JLWade** [BCDevOps/devops-requests#1293]
## Step 0

**Are you looking to make a public repository?**
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. 
If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. 
This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. 
Please include a firm date by which you will move your repository to the open organization.

If you feel you cannot move to open-source ever, we strongly encourage you to reconsider.
However, if you are certain that you require a fully closed-source repo permanently, you can speak to the team on RocketChat to discuss your options.
Using the private bcgov GitHub Organization may not be the appropriate solution for your team in this case.

Github Issue content:
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - platformservicesteam@gov.bc.ca

Details have been sent by email.

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
hello @JLWade I see that you are requesting for 3 repos for the project. We usually recommend team to go with mono repo where you can put the different micro-services code based into directories, that way makes your CICD setup and search easier. Please let us know if you have specific reason for splitting repos. If there are any sensitive information, feel free to respond to our team email instead. Thank you!
