### ISSUE TITLE
Remove user jmuri  from Keycloak

### ISSUE THREAD

**Issue by ychung-mot** [BCDevOps/devops-requests#1297]
## Step 0
**Are you the Keycloak Realm Admin?**
No but the realm is one of the standard realm.

## Step 1
Provide some background on the user account issue.
- The user is experiencing the following duplicate user error when logging in.
   "User with username jmuri already exists. How do you want to continue?"

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [X] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: jmuri
* Realm ID where user is having problem login: onestopauth-business
* Environment in which you are facing issue: prod

**Comment by junminahn** [comment]
@ychung-mot the user associated with username `jmuri` has been removed from `idir` realm in prod environment.
can you confirm that the issue has been resolved?
