### ISSUE TITLE
Realm clean up & BCeiD Prod approval (formerly Remove Personal BCeID support from our realm)

### ISSUE THREAD

**Issue by victorchong** [BCDevOps/devops-requests#1299]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Allow user to request that Personal BCeIDs be removed from selected realm. For example, IDIM has directed my team to remove Personal BCeIDs from our Universal Keycloak realm as we do not have a business need for Personal BCeIDs.
2. **Why should this be a new request type?** As Personal BCeIDs become progressively deprecated, IDIM will likely request projects to start removing Personal BCeID support from Keycloak realms.
3. **What information is required to fulfill this request?** Name of realm from which Personal BCeID support should removed.
4. **What is the end result?** Support for Personal BCeIDs will be removed from the realm. Users will no longer be able to authenticate into the given Keycloak realm using a Personal BCeID.

![No more Personal BCeIDs](https://user-images.githubusercontent.com/62109882/137545530-e5bfc8a7-906d-4ca0-a7cf-92f980373703.png)

**Comment by zsamji** [comment]
@victorchong please remind me the name of the realm you have where we should remove BCeID Personal. thanks!

**Comment by zsamji** [comment]
@victorchong thanks for your note

Pathfinder SSO team,I'll post more/confirm at standup. Summary we need to do two things

1.  we need to remove BCeiD Personal from the following realms 
•	0jjhl1lc
•	srmm7sdn

2. and add Prod BCeID Basic + BCeID Business to srmm7sdn

**Comment by arcshiftsolutions** [comment]
Following has been completed:

- Removed BCeID from srmm7sdn in DEV & TEST
- Added Business/Basic IDP to srmm7sdn in DEV/TEST/PROD
- BCeID IDP was not present in 0jjhl1lc

**Comment by arcshiftsolutions** [comment]
We've now done the following:

- Removed Business & Basic IDPs in DEV/TEST/PROD
- Added Business BCeID IDP in DEV/TEST/PROD

**Comment by victorchong** [comment]
@arcshiftsolutions It looks like we're good for srmm7sdn , but we are missing Business BCeID in DEV/TEST/PROD for **0jjhl1lc**.

**Comment by arcshiftsolutions** [comment]
Hey @victorchong - we've now added Business BCeID to 0jjhl1lc (DEV/TEST/PROD). Thanks man!

**Comment by zsamji** [comment]
Nov 10 from Client:
For srmm7dsn, we only need IDIRs and Business BCeIDs.
to remove Basic and Personal BCeIDs for realm srmm7dsn 

Nov 9 from IDIM
Please implement a Production [Business BCeID] + [ Basic BCeID ] + [ Personal BCeID ] integration with Production BCeID for TRACKS(srmm7sdn) at your earliest convenience.

**Comment by zsamji** [comment]
Nov 9 from client
Could you please remove Personal BCeIDs from the following two realms: 0jjhl1lc – BCTW
Nov 9 from IDIM TRACKS srmm7sdn - dedicated split from BCTW 0jjhl1lc  [translation 0jjhl1lc   and srmm7sdn  to be the same]

**Comment by victorchong** [comment]
Thanks kindly to the team! Everything looks awesome-possum now. Cheers! @zsamji, let's close this ticket up. :-)
