### ISSUE TITLE
Grant GIT-HUB User bsouthby access to this organization so he can be added to rsbc-bi repo please

### ISSUE THREAD

**Issue by jennifer-dowd** [BCDevOps/devops-requests#13]
## Step 4
Are you requesting to:
- [x] Invite a user

## Step 5
Fill out the following fields

* Project Name: rsbc-bi
* GitHub Org: bcgov 
* Full Name: @bcgov-c/rsbc-bi
* GitHub ID: @bsouthby 
* GitHub Account 2FA Confirmed: yes 
* Email address: Brian.Southby@gov.bc.ca
* Organization: Public Safety and Solicitor General - Road Safety Inititiative
* Project Role:  Developer
* GitHub Team to Join (if exists):  @bcgov-c/rsbc-bi
* Existing GitHub Repo: @bcgov-c/rsbc-bi

**Comment by ShellyXueHan** [comment]
bcgov-c GitHub organization invitation sent, Brian will receive it with the email associated with his account. Once he's in the org, @jennifer-dowd you could invite him to join the GitHub team.
