### ISSUE TITLE
Request to enable a GitHub integration for a trial period: percy.io

### ISSUE THREAD

**Issue by matthieu-foucault** [BCDevOps/devops-requests#130]
cc: @wenzowski @Maralsotoudehnia 
The CAS team is investigating the use of visual snapshots in the code review process, to make it faster and more robust. 

We are currently in the process of enabling end-to-end testing of the `cas-ciip-portal` application using https://www.cypress.io/ (free for open-source, doesn't require any integration). 
There is a cypress plugin for `percy.io`  (https://docs.percy.io/docs/cypress-tutorial), which would allow us to take automated screenshots of our application as part of our continuous integration process, and, when these screenshots fail, the reviewer of a pull request would have to approve the screenshots on the Percy website (here's a cool video to explain what Percy does: https://youtu.be/1Sr_h9_3MI0). In short, it stores snapshots and would allow us to review the differences between them.

In its free version, Percy would allow us to take 5,000 snapshots a month. Our goal with this trial is to evaluate the number of monthly snapshots that would be required by the CAS project and to look into getting a paid plan in the future if this trial is successful.

I sent a request to the bcgov org to add the integration. I think all that would be required on your end in terms of configuration is to accept that request.

* Project Name: CAS
* GitHub Org: bcgov
* Existing GitHub Repo: cas-ciip-portal

**Comment by wenzowski** [comment]
@lukegonis or @ShellyXueHan could we document here why this ticket is blocked? (no problem that it is; shooting for transparency with team here if possible)

**Comment by caggles** [comment]
hey @wenzowski ! I think we should move forward by having a short meeting with you, me and @ShellyXueHan  - we can discuss a few more details and then we can proceed with approval. Please book a meeting and let us know!

**Comment by matthieu-foucault** [comment]
Hi :wave: I would like to attend that meeting if possible (so that we have more than a single team member aware of the status of this request).

If more details are needed regarding Percy's usage, it would be preferable for us to know ahead of time so that we can collect the necessary information.

Overall it would be very valuable for us if the information was recorded here, if possible, so that we know the requirements/constraints with this kind of requests (for future reference). I imagine that this information could be valuable to other teams as well.

**Comment by caggles** [comment]
Hey @matthieu-foucault and @wenzowski - I've been poking through the resources you've provided again and I'm planning to permit access to your repo for percy, but the listed repo name doesn't seem to exist?

**Comment by matthieu-foucault** [comment]
Curious, it's here though: https://github.com/bcgov/cas-ciip-portal

**Comment by caggles** [comment]
So weird. I found it! Thanks for the link! 

Percy has been approved. I still wanna have that meeting though - we would like to know how you guys are using it once you've had a chance to get it working for a while. Let us know when :)

**Comment by matthieu-foucault** [comment]
@caggles thanks! unfortunately, it looks like something did not work on Percy's end. Maybe the user that connects the Percy org to the Github one has to be an admin of both. I contacted the Percy team and I'll get back to you on that.

So far we have been taking snapshots on our "develop" branch only, but when the integration works we will be able to use them as part of the peer-review process. The snapshots are publicly visible [here](https://percy.io/bcgov-cas/cas-ciip-portal) (I believe it asks you to login if it detects a github cookie), which also makes it a great tool to share application screenshots with the govt business area.
