### ISSUE TITLE
GitHub Repo Request

### ISSUE THREAD

**Issue by WRLloyd** [BCDevOps/devops-requests#1301]
### Step 1

**Are you the Technical Lead?**
Yes, I am the Technical Lead.
Will be following up with contact @mitovskaol (Olena Mitovska) with a link to the ticket so she can approve it.

### Step 2
* Project Name: License Tracking
* Project Description: Development of a User License Tracking application using the Open Shift platform.
* Technical Lead Github ID: @WRLloyd
* GitHub Org: bcgov
* GitHub ID: @WRLloyd

**Comment by WRLloyd** [comment]
@mitovskaol: Hello Olena, could you please review and approve this request. Please let me know if there is any information that I have missed providing - this is my first of these requests. Thanks.

**Comment by mitovskaol** [comment]
@WRLloyd  All members of `bcgov` org can create their own public repos. I have emailed you an invite to join the bcgov org, once you join the org, you will be able to create your repo yourself.
