### ISSUE TITLE
Remove user account

### ISSUE THREAD

**Issue by rarmitag** [BCDevOps/devops-requests#1303]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: 
* Realm ID where user is having problem login: 
* Environment in which you are facing issue: 

Step 0:
Yes, I am a realm admin.

Step 1:
User gets "Forbidden"  message always when logging into keycloak.

Step 2: 
User is aware and ready to have her account removed.

Step3:
idir\edeng
Fcf0kpqr
test and prod

**Comment by junminahn** [comment]
@rarmitag I removed `edeng` from `test` environment again. please let us know if the issue is persistent.

**Comment by rarmitag** [comment]
Strange, I still see it in the UI.

**Comment by junminahn** [comment]
> I've asked her to do so, but she may be on lunch.

no worries, please let us know if the issue is persistent.

**Comment by rarmitag** [comment]
OK she logged out and back in and still see's "User already exists".
