### ISSUE TITLE
SonarCloud - Add foi-requests repo

### ISSUE THREAD

**Issue by acoard-aot** [BCDevOps/devops-requests#1304]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
Yes

**Are you the admin user of the GitHub repositories?**
Yes
## Step 1
Done.

## Step 2
Fill out the following fields

* Project Name: foi-requests (also related to foi-flow which you have already added 😄  )
* GitHub repositories to add to SonarCloud:
-  https://github.com/bcgov/foi-requests
- 

## Step 3
I will invite users later.  Just add this github account and I can setup.  Thank you.

A side note: I'm sure you're very busy, but I would greatly appreciate getting to this soonish (day or two?) as we are trying to comply with security requirements for a rush job.  Thank you in advance.

**Comment by acoard-aot** [comment]
Hi there, would anyone be able to help with this?  I'm already in the sonarcloud system but we need a new repository added.  This is kind of a rush job and involves a security audit, so if this can be handled quickly it would be greatly appreciated.  If there is anything you need from my side please don't hesitate to reach out.  Thank you.

**Comment by ShellyXueHan** [comment]
@acoard-aot project setup on sonarcloud now! Sorry about for the late response. Not sure how your request slip through our regular check up time (usually Tuesdays and Thursdays). If this happen again, please poke us directly on the ticket for response!

**Comment by acoard-aot** [comment]
Thanks Shelly, no worries, appreciate the response.
