### ISSUE TITLE
Please delete user

### ISSUE THREAD

**Issue by rarmitag** [BCDevOps/devops-requests#1305]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: 
* Realm ID where user is having problem login: 
* Environment in which you are facing issue: 

Step 0: 
Yes I am a realm admin.

Step 1:
When this user tries to login she gets a "User already Exist" error.

Step 2:
Yes, user confirms she would like her account removed.

Step 3:
idir\ccarlson
Fcf0kpqr
test

Thanks,
Rich

**Comment by junminahn** [comment]
@rarmitag I removed `ccarlson` from `test` environment. please let us know if the issue has been resolved.

**Comment by rarmitag** [comment]
I had left a message for her to try and login. Doesn't look like she has. I will ask her again and keep you updated. Thanks.
