### ISSUE TITLE
Openshift silver cluster access for me

### ISSUE THREAD

**Issue by bburciaga** [BCDevOps/devops-requests#1307]
Hi my name is Brian Burciaga I work with @micheal-w-wells I need OpenShift cluster access. I don't need access to a specific project Micheal will do that. My IDIR is BBURCIAG

**Comment by caggles** [comment]
Please head to https://developer.gov.bc.ca/User-access-into-Github-or-Openshift and have your PO follow the instructions for adding you to the appropriate github org, if this issue is still outstanding!
