### ISSUE TITLE
New namespace for Learning Curator

### ISSUE THREAD

**Issue by dsandor716** [BCDevOps/devops-requests#1315]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
We are looking for a sandbox namespace.
2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!
We want to try new dev ops tools but not in a current space.
3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
Warren Christian is the tech lead for this request so please direct questions to him regarding this.
4. **What is the end result?** Please provide plenty of details about what the end result should look like.
We have a new namespace under the Learning Curator to test our new dev ops tools.

**Comment by caggles** [comment]
Hi! This template is typically used to request new ticket templates be added to this repo - if you're looking for a new namespace, you should head over to https://registry.developer.gov.bc.ca/public-landing and request a new project set there!
