### ISSUE TITLE
Follow up on openshift access 

### ISSUE THREAD

**Issue by pagustinqt20** [BCDevOps/devops-requests#1318]
Hello,

I would like to follow up the request for openshift. I already sent request last week.

thanks,
Princess

**Comment by caggles** [comment]
Please have your PO or tech lead go to https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/ and add you to the appropriate github orgs! You can find more information here: https://developer.gov.bc.ca/User-access-into-Github-or-Openshift
