### ISSUE TITLE
Keycloak Shared Realm for CSRS project

### ISSUE THREAD

**Issue by NovaVic** [BCDevOps/devops-requests#1325]
## Step 1
Field the following information.

Project Name:  JSB Child Support Recalculation Services

## Step 2
Select BCeID identity provider flavour

  - [X] BCeID Basic
  - [ ] BCeID Business
  - [ ] Both BCeID Basic AND BCeID Business
  - [] IDIR (provided by default in all standard realms)

## Step 3
Provide a list of redirect URLs for each environment (DEV, TEST, PROD). *These are the URLs that your application is allowed to use after sign-on events are complete. These are the secure "front door" for your application.* If you do not know the URLs for all your environments, you can use a temporary one such as "http://localhost:5000" and change it later.
 - DEV redirect URL(s): http://localhost:5000
-TEST redirect URL(s): http://localhost:5000
- PROD redirect URL(s): http://localhost:5000

Going to send the rest of information via email as suggested in the template. Thanks!

**Comment by zsamji** [comment]
scheduled for Nov 4th

**Comment by zsamji** [comment]
CSS APP Request - 991
