### ISSUE TITLE
Add Basic BCeID to dev/test realm zdw7o87 & Update details

### ISSUE THREAD

**Issue by ckayfish** [BCDevOps/devops-requests#1329]
## Step 1
Not onboarding, removing a duplicate user or deleting a realm.

## Step 2
We need Basic BCeID authentication added as a federated identity for our dedicated realm. I understand you can only add this to dev & test right now, and we will need to engage IDIM before we can use it in prod.

We also want to update the contact and other details you have for this realm. Rather than being used just for one app, it will be used for any GCPE app that requires SSO and could be supported

Keycloak client name: GCPE
Product Name: GCPE SSO Apps
OpenShift Name Space: 9b301c (others may be added later, 47ba99 no longer using Keycloak)
Product Owner: Jeremy Burbee, Jeremy.Burbee@gov.bc.ca
Technical Contact: Curtis Kayfish, Curtis.Kayfish@gov.bc.ca

## Step 3

* Keycloak client name: GCPE News (Change to just "GCPE")
* Project (product) Name: GCPE News Web App (Change to "GCPE SSO Apps")

If this is a request related to a dedicated realm (created before summer 2021)
* Keycloak realm ID: zdw7o87

**Comment by arcshiftsolutions** [comment]
Thanks @ckayfish - let me process this for you now.

**Comment by arcshiftsolutions** [comment]
Hi @ckayfish - we've made a change to the realm name and have made you an administrator. 

We've also added the basic BCeID IDP in the dev & test envs. Please let us know if you have any issues. Thanks!
