### ISSUE TITLE
Request an installation of an Operator

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#1330]
## Step 1
Make sure no duplicated request exists, search here: Confirmed.
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** I am looking to install an operator to run NIFI.  https://orange-opensource.github.io/nifikop/docs/1_concepts/1_introduction
2. **Why should this be a new request type?** Developers do not have access to install operators.
3. **What information is required to fulfill this request?** Install NIFI CRDs, I believe.  I am hoping to try this in the LAB area first. 
4. **What is the end result?** We need a way to transfer data between applications, this application allows us to this and is key for our digital transformation.  This allows us to produce valuable insights from data coming from various data sources within our openshift workspaces.  The main requirement is to transfer data from an operational system running mongodb to our analytics database (sqlserver) without interrupting operations.  This system will also be used to transfer data from another operational system running postgres to our analytics database (sqlserver)..  In the future, we will use this to receive and send data to our ministry partners from our systems and theirs.

**Comment by mitovskaol** [comment]
This work is now scheduled for action and will be tracked in [this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2122). Once we and ServiceBC had a chance to evaluate the operator in the LAB, we will decide if it will be installed in Silver.
