### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by lbenso** [BCDevOps/devops-requests#1332]
Hi there, I am having difficulties accessing our OpenShift namespace here: https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects/ca94a8-tools but am not having any luck getting in. Scott has added me as an admin to all four namespaces, but whenever I click the link it takes me to this github page to create a help ticket.

https://console.apps.silver.devops.gov.bc.ca/

I'm thinking I need some access at a higher level. my github username is lbenso 

Thanks!

![image](https://user-images.githubusercontent.com/71719580/140823120-54fe7cc1-8bb4-4e34-9dda-6d21b83c56a6.png)

**Comment by caggles** [comment]
Please have your PO or tech lead go to https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/ and add you to the appropriate github orgs!
