### ISSUE TITLE
Realm itrjxgs9 

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1333]
Technical Lead is @abschwenker and it seems like this realm is no longer needed. 
Team should chat about this and if we need, we can ask questions or set up time with @abschwenker 

This was the only other reference i could find: https://github.com/BCDevOps/devops-requests/issues/1221

**Comment by arcshiftsolutions** [comment]
Realms have now been removed in DEV/TEST/PROD.
