### ISSUE TITLE
Request to remove a duplicate user (LMALLIKA) from keycloak

### ISSUE THREAD

**Issue by pwei1018** [BCDevOps/devops-requests#1338]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
Lekshmi is a contactor. She had two idir account before LMALLIKA and  LEMALLIK during previous jobs. Currently, 77000 re-assign the LMALLIKA to her. However, when she login to keycloak and got the following error:
![image](https://user-images.githubusercontent.com/44277752/143134000-8750dbce-2617-400e-831f-61b36540a5bc.png)

- What result of debugging have you obtained that lead you to request an account removal?
We removed all her idir id in our keycloak realms. However, she still got the login error

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: LMALLIKA
* Realm ID where user is having problem login:  fcf0kpqr
* Environment in which you are facing issue: dev/test

**Comment by arcshiftsolutions** [comment]
Hi @pwei1018 - we've removed Lekshmi's account in DEV/TEST. Please ask her to log in again. Thanks!

**Comment by pwei1018** [comment]
Thanks, Lekshmi can login with her idir now.
