### ISSUE TITLE
Please remove IDIR SROGINA from realm vtkayq4c

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1339]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
yES

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?  User account SROGINA cannot login to production application The Q realm vtkayq4c . 
- What result of debugging have you obtained that lead you to request an account removal?
I have confirmed that all access setup requirements are present both in keycloak and the application.  She has cleared browser data and still no access. 

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes

## Step 3
Field the following information.

* Username to be removed: SROGINA (Shona Rogina)
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Production

**Comment by jlangy** [comment]
@jhmccoll The user is removed from the production realm. Please let me know if that solves their issue

**Comment by jhmccoll** [comment]
Confirmed successful login to The Q with CSR. 

Thanks so much!
