### ISSUE TITLE
Request to remove duplicate user CCOTTON

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1340]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
IDIR CCOTTON cannot login to The Q production application in realm vtkayq4c.  I have confirmed all access in the application and Keycloak realm.  This user was previously at Health.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes

## Step 3
Field the following information.

* Username to be removed: IDIR CCOTTON ..  Carly Cotton
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Production

**Comment by jlangy** [comment]
@jhmccoll I removed the user from production. Please let me know if that fixes their issues

**Comment by jhmccoll** [comment]
Hello,
  Access confirmed with CSR after removal of duplicate.
Thanks so much!
John
