### ISSUE TITLE
Onboarding Dave Briand

### ISSUE THREAD

**Issue by Nicole-Huard** [BCDevOps/devops-requests#1341]
**Are you the product owner or technical lead?** Yes

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and thencontact **[@mitovskaol](https://github.com/mitovskaol)** (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?** davebriand

**Do you have 2-factor-authentication enabled with your GitHub account?** yes

**Comment by ShellyXueHan** [comment]
@Nicole-Huard do you need any help onboarding Dave?
