### ISSUE TITLE
Request to have flow modified teacher-resources

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1343]
As discussed during the Nov 25, meeting with @jinchuantang regarding flow config change to only show one IDP
1.	Client: work-bc-teacher-resources
o	Environment: Prod (internal gov staff use at this time not “real teachers”

**Comment by jlangy** [comment]
@jinchuantang  I added that config change into the dev/test/prod **work-bc-teacher-resources** clients. Please let me know if that redirection is working for you (should go straight to idir with no IDP selection screen)

**Comment by jlangy** [comment]
@jinchuantang sorry jumped the gun a bit there, updates to our clients will override the configuration and we will have to make some changes to our application to prevent that before the new configuration will last long term. I will let you know when those are in place so the config change will stay

**Comment by zsamji** [comment]
@jinchuantang we've implemented our automation for the idp hint and configured such that your integration should not be negatively impacted. COuld you please do a sanity test for us and let us know either here or RC and we will work to resolve for your asap.

**Comment by zsamji** [comment]
note sent to client
