### ISSUE TITLE
Please remove Personal BCeID as an IDP off of our realm: j94mtfjj

### ISSUE THREAD

**Issue by Kyle-UL** [BCDevOps/devops-requests#1347]
Hi,

We would like Personal BCeID removed as an IDP option for our Keycloak realm, j94mtfjj.  We understand that the shared Keycloak realm does not allow Personal BCeID as a sign-in option, and we would like our realm to have parity with the shared realm for security purposes.

This request comes from UrbanLogiq, who is working on an integrated application with the BC Government that allows single sign-on for IDIR and BCeID users.  Please feel free to reach me at kyle@urbanlogiq.com, or on RocketChat at kyle.ivens if you need any further details.

Thank you!

**Comment by arcshiftsolutions** [comment]
Hi @Kyle-UL - are you looking for Business & Basic BCeID? Or just Business? Just Basic? 

To clarify, we're going to add a new IDP to your realm which will provide this functionality (in addition) to your existing BCeID IDP. You can remove the existing BCeID when your team is ready.

**Comment by Kyle-UL** [comment]
Thanks for the quick reply @arcshiftsolutions !  We are looking for just Business & Basic BCeID (same as the shared realm).

**Comment by Kyle-UL** [comment]
Of course, I'd be happy to.  I've accepted Zorin's meeting invite.

**Comment by zsamji** [comment]
met with client and this is now closed. BCeID Personal removed
