### ISSUE TITLE
Remove duplicate user malhassa in cp1qly2d

### ISSUE THREAD

**Issue by loneil** [BCDevOps/devops-requests#1350]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
**Yes**

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?
IDIR user **malhassa** is getting the "User with username already exists" error. They don't exist in our KC realm. 

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
Yes

## Step 3
Field the following information.

* Username to be removed: **malhassa**
* Realm ID where user is having problem login:  **cp1qly2d**
* Environment in which you are facing issue: **prod**

**Comment by zsamji** [comment]
@loneil  we may have a self service feature and curious if you'd be willing to try and we'd like to do a user observation --- can we set up a quick 15/20 min chat today -- i'll find you on RC

**Comment by zsamji** [comment]
@loneil please close this ticket once user has confirmed.thansk!

**Comment by loneil** [comment]
Can see user malhassa has logged in as needed. Thanks!
