### ISSUE TITLE
Please add these Github repositories to SonarCloud

### ISSUE THREAD

**Issue by kamal-mohammed** [BCDevOps/devops-requests#1351]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** Yes
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** Yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: GRAD
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/EDUC-GRAD-ADMIN 
- https://github.com/bcgov/EDUC-GRAD-ALGORITHM-API
- https://github.com/bcgov/EDUC-GRAD-ASSESSMENT-API
- https://github.com/bcgov/EDUC-GRAD-BATCH-GRADUATION-API
- https://github.com/bcgov/EDUC-GRAD-COURSE-API
- https://github.com/bcgov/EDUC-GRAD-DATA-CONVERSION-API
- https://github.com/bcgov/EDUC-GRAD-GRADUATION-API
- https://github.com/bcgov/EDUC-GRAD-GRADUATION-REPORT-API
- https://github.com/bcgov/EDUC-GRAD-PROGRAM-API
- https://github.com/bcgov/EDUC-GRAD-REPORT-API
- https://github.com/bcgov/EDUC-GRAD-STUDENT-API
- https://github.com/bcgov/EDUC-GRAD-STUDENT-GRADUATION-API
- https://github.com/bcgov/EDUC-GRAD-TRAX-API
- https://github.com/bcgov/EDUC-RULE-ENGINE-API

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
@kamal-mohammed repos added to sonarcloud and you are the admin of them!

**Comment by kamal-mohammed** [comment]
Thank You @ShellyXueHan

**Comment by kamal-mohammed** [comment]
Hi @ShellyXueHan, the last one is missing in Sonarcloud. Can you please add it when you get a chance?

- https://github.com/bcgov/EDUC-RULE-ENGINE-API

**Comment by ShellyXueHan** [comment]
got it!
