### ISSUE TITLE
need o meet to remove duplicate chrobins

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1352]
Selecting each of the options doesn’t seem to work ….. I have a feeling this is related to my IDIR being deleted accidentally a month ago, then reinstated. I encountered this with some of the other lab Keycloak logins, there is some caching happening which links (probably ) IDIR to email to Git – however , my idir (chrobins) is the same name, but now probably with a different GUID. \

**Comment by junminahn** [comment]
SSO team had a brief meeting with Chris and unblocked the issue he had.
