### ISSUE TITLE
Can't log in with IDIR

### ISSUE THREAD

**Issue by rgreensp** [BCDevOps/devops-requests#1353]
## Description

When I try to log in to services like Rocket Chat and Realmomatic, I get a message that says I am using an existing user name.
When I try to merge with existing account, I get message asking for password
When I type my IDIR password, it says invalid password
I believe my IDIR account my still be connected to my previous employment email rachel@button.is

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!
3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
4. **What is the end result?** Please provide plenty of details about what the end result should look like.

**Comment by zsamji** [comment]
@rgreensp realmomatic is decommissioned and replaced with https://bcgov.github.io/sso-requests

try looking here for rocketchat https://developer.gov.bc.ca/Steps-to-join-Rocket.Chat

**Comment by wenzowski** [comment]
@zsamji the context of this request is that @rgreensp also cannot access https://registry.developer.gov.bc.ca/public-landing in order to request a namespace set. Any objections to asking @jlangy or @junminahn to delete her identity from the keycloak realm so her IDIR works again?

**Comment by wenzowski** [comment]
I can replicate this issue via my ENV IDIR:
![registry developer gov bc ca_public-landing](https://user-images.githubusercontent.com/597920/147162934-2e085854-2281-4249-acba-ac429a24e3aa.png)
![logon7 gov bc ca_clp-cgi_int_logon cgi_flags=1000_1,0 TYPE=33554433 REALMOID=06-fb0eaeef-4838-47c5-9181-09e15ecf282e GUID= SMAUTHREASON=0 METHOD=GET SMAGENTNAME=$SM$uf%2bzUAKb1uzEJ8LH6tuAK9htvmdDn2PYWGJwPALEcR%2fQJY%2bgGkrIRkwOH9JfjYi5 TARG](https://user-images.githubusercontent.com/597920/147162937-9052d283-d46e-495c-92d0-44ee50fa7759.png)
![logon7 gov bc ca_clp-cgi_int_logon cgi_flags=1000_1,0 TYPE=33554433 REALMOID=06-fb0eaeef-4838-47c5-9181-09e15ecf282e GUID= SMAUTHREASON=0 METHOD=GET SMAGENTNAME=$SM$uf%2bzUAKb1uzEJ8LH6tuAK9htvmdDn2PYWGJwPALEcR%2fQJY%2bgGkrIRkwOH9JfjYi5  (1)](https://user-images.githubusercontent.com/597920/147162939-e786ec45-cb58-4cd8-8a13-a9f0b1fee06b.png)
![oidc gov bc ca_auth_realms_idir_login-actions_first-broker-login_client_id=https%3A%2F%2Foidc gov bc ca%2Fauth%2Frealms%2Fdevhub tab_id=rmDgxoQ5yf0](https://user-images.githubusercontent.com/597920/147162942-801bc5a6-c3f5-4934-89d1-baf4618bd235.png)
![oidc gov bc ca_auth_realms_idir_login-actions_first-broker-login_session_code=khZ4uS7wuC0QbZ9_aEdD9VDXealZiD4vjB1-p3TIrmk execution=a389089e-a652-4e8c-83f2-bce000411b80 client_id=https%3A%2F%2Foidc gov bc ca%2Fauth%2Frealms%2Fdevhub tab_id=](https://user-images.githubusercontent.com/597920/147162944-5cd11a26-6c82-443f-ae5d-104c87397419.png)
![oidc gov bc ca_auth_realms_idir_login-actions_first-broker-login_session_code=DtBt4Pa9GUEnQdiFSg47bMWXtcZv2dJCRTRlKWEEQ60 execution=933ea5ce-3f58-4cab-9374-6c66721c2b1e client_id=https%3A%2F%2Foidc gov bc ca%2Fauth%2Frealms%2Fdevhub tab_id=](https://user-images.githubusercontent.com/597920/147162946-f3667582-a492-48b5-a7d4-c73b19747f37.png)
![oidc gov bc ca_auth_realms_idir_login-actions_first-broker-login_session_code=aTDJthMk1GWOjvN8z2OLZ8ddSkxg3zzjQ1QNpPfLjXU execution=a389089e-a652-4e8c-83f2-bce000411b80 client_id=https%3A%2F%2Foidc gov bc ca%2Fauth%2Frealms%2Fdevhub tab_id=](https://user-images.githubusercontent.com/597920/147162948-23c763f3-677e-41d4-a065-d58d90415488.png)
![oidc gov bc ca_auth_realms_idir_login-actions_first-broker-login_session_code=aTDJthMk1GWOjvN8z2OLZ8ddSkxg3zzjQ1QNpPfLjXU execution=a389089e-a652-4e8c-83f2-bce000411b80 client_id=https%3A%2F%2Foidc gov bc ca%2Fauth%2Frealms%2Fdevhub tab (1)](https://user-images.githubusercontent.com/597920/147162951-d8d3e689-82bd-420a-8f79-38c2874def41.png)
![oidc gov bc ca_auth_realms_idir_login-actions_first-broker-login_session_code=5yOcmrR2Q9wPQw2MqjK2Jw09Cz5A3aRo4iOz8aDE-sY execution=bed384fc-f7b7-490c-acaa-eed55f0de610 client_id=https%3A%2F%2Foidc gov bc ca%2Fauth%2Frealms%2Fdevhub tab_id=](https://user-images.githubusercontent.com/597920/147162953-88b50074-2fb9-4e2c-8bfd-a57d83887f0e.png)

**Comment by zsamji** [comment]
@wenzowski No issues to have our team remove here old idir :)

**Comment by jlangy** [comment]
@wenzowski I removed rachel's old account, let me know if that solves the issue

**Comment by wenzowski** [comment]
@rgreensp we'll need the `username` you're getting from the error message (shouldn't be case sensitive...but just in case) so the team can delete the old conflicting IDIR

**Comment by rgreensp** [comment]
@jlangy - Doesn't look like this worked. Anything else you can try? 

I'm trying to access https://registry.developer.gov.bc.ca/public-landing

![Screenshot (51)](https://user-images.githubusercontent.com/13056177/147173666-c0864445-7313-4ae5-ab6a-4b375a5b29c3.png)

**Comment by jlangy** [comment]
Hey @rgreensp I will try one other thing shortly and let you know

**Comment by junminahn** [comment]
> Hey @rgreensp I will try one other thing shortly and let you know

I believe that the conflict in the devhub realm not in the parent realm.

**Comment by jlangy** [comment]
Yes @junminahn I was just going to check if we could get that through the realm registry app, I don't have admin access to it though

**Comment by jlangy** [comment]
@rgreensp can you try out logging into devhub again and see if that is fixed?

**Comment by rgreensp** [comment]
@jlangy - It worked! Thank you!
