### ISSUE TITLE
KeyCloak login issue: user already exists

### ISSUE THREAD

**Issue by kevinginley** [BCDevOps/devops-requests#1354]
Hello,

I am getting an error when I try to log into Keycloak and applications that use Keycloak. After inputting my IDIR (KGINLEY) and password, I get a message:

"User with <email/username> already exists. How do you want to continue?" with the options:
Review profile
Add to existing account

(neither do anything)

I've tried clearing my cache, reopening the browser, and trying different browsers. I had this same IDIR a few years ago, which may be causing a conflict.

There is documentation on how to fix this issue here: 
[](https://github.com/bcgov/ocp-sso/issues/68)

IDIR: KGINLEY

Thank you

**Comment by jlangy** [comment]
Hello @kevinginley, we could remove the old idir account to fix this. I should note that deleting the user account from Keycloak will also remove records with any other application using Keycloak that you have logged into. Would that be okay for you?

**Comment by kevinginley** [comment]
Yes that is OK, please proceed. Thank you for checking.

**Comment by jlangy** [comment]
Sounds good, I removed the old account. Please let me know if that fixes the issue

**Comment by zsamji** [comment]
@kevinginley can you please confirm this issue can be closed?
