### ISSUE TITLE
Configure to only use Business BCeID

### ISSUE THREAD

**Issue by ikethecoder** [BCDevOps/devops-requests#1356]
## Step 1
Confirm that you are submitting the right issue type. 
* If you are wanting to onboard to Pathfinder SSO, please read the [Onboarding Documentation](https://github.com/bcgov/ocp-sso/wiki/SSO-Onboarding).

* If you are asking for a duplicate user to be removed from KeyCloak, please use the issue type: [Request to remove a duplicate user from Keycloak](https://github.com/BCDevOps/devops-requests/issues/new?assignees=jlangy%2C+junminahn%2C+arcshiftsolutions%2C+zsamji&labels=sso-delete-user%2C+sso&template=keycloak_user_removal_request.md&title=)

* If you are asking for a KeyCloak realm to get deleted, please use the issue type: [Request for delete a Pathfinder SSO Realm](https://github.com/BCDevOps/devops-requests/issues/new?assignees=jlangy%2C+junminahn%2C+arcshiftsolutions%2C+zsamji&labels=sso-delete-realm%2C+pending%2C+sso&template=keycloak_realm_removal.md&title=)

## Step 2
Description of the problem or change that is required.

> Our realm is currently setup to use the BCeID Broker that supports Personal, Basic and Business BCeID, but we want BCeID to only go to the Business BCeID login flow.  Currently BCeID is only enabled on our Dev and Test environments.

## Step 3
Provide the following information:

* Project Name: API Programme Services

If this is a request related to a dedicated realm (created before summer 2021)
* Keycloak realm ID: xtmke7ky

**Comment by zsamji** [comment]
Pathfinder sso team - as this is a clean up to remove personal bceid from this custom team, we can go ahead and do this as I know this is a priority from our friends at idim

**Comment by jlangy** [comment]
Hello @ikethecoder, I switched over the IDP to just bceid-business for the DEV and TEST realms. Please let me know if that is all that you needed, cheers!

**Comment by zsamji** [comment]
@ikethecoder please advise if you've got that you needed

**Comment by gjlawran** [comment]
@zsamji   - I can confirm this is correct - we do no require the use of personal BCEIDs and would not encourage their adoption in the future.


Thanks!
cc @ikethecoder

**Comment by ikethecoder** [comment]
Yes @jlangy thanks, our dev and test both work correctly with just the Business BCEID.
