### ISSUE TITLE
IDIR JBROWN cannot login to our production realm vtkayq4c applications

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1358]
## Step 0
**Are you the Keycloak Realm Admin?**
Yes
Not sure --> log in to the [Keycloak Custom Realm Registry](https://realm-registry.apps.silver.devops.gov.bc.ca/) and if you see your realm, go to STEP 1. If you don't see it, ask the product owner to submit this request or go to STEP 2

Yes--> go to STEP 1

No --> you will need to ask one of the admin user in your realm to make this request instead.

## STEP 1
Log in to our [Keycloak Custom Realm Registry](https://realm-registry.apps.silver.devops.gov.bc.ca/) and select the DUPLICATE USER tab
- Type the IDIR of the user who is having issue with the account. See the message per environment for the specified user
- If you see the button to delete --> this will remove the duplicate account. Note you will only be able to delete the user if the user is not associated with other products realms
- If you still have issues --> go to STEP 2
- Otherwise --> follow the instructions on the screen (this type of request) and go to STEP 2

## STEP 2
A.  Provide some background on the user account issue.
- What is the issue with the user account? Duplicate user (IDIR) found in realm I do not own 
- What result of debugging have you obtained that lead you to request an account removal? Using Step 1 attempted to delete IDIR jbrown and the message displayed indicate the account was present in another realm which I do not own

Note: Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

B. [ ] Confirm that user is ready to have the account removed from Keycloak
Yes
C. Provide the following information: 

* Username to be removed: JBROWN  (IDIR for Jaime Brown)
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Prod

**Comment by jlangy** [comment]
Hello @jhmccoll, we have a new app to help realm owners clear out users. Would you mind trying out visiting [this app](https://realm-registry.apps.silver.devops.gov.bc.ca/my-dashboard) and let me know if you were able to find and delete the user?

**Comment by jhmccoll** [comment]
Hi Jonathon
  I did use the application as per the instruction and it returned the following message:

      The user was found in a realm that you do not own. Please fill out this Github issue <https://github.com/BCDevOps/devops-requests/issues/new?assignees=jlangy%2C+junminahn%2C+arcshiftsolutions%2C+zsamji%2CConradBoydElliottGustafson&labels=sso-delete-user%2C+sso&template=keycloak_user_removal_request.md&title=> , message <https://chat.developer.gov.bc.ca/channel/sso>  us on rocketchat or ***@***.***> the SSO team to delete the user.

As such I was unable to delete the duplicate user.

John


John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”

**Comment by jlangy** [comment]
Oh sorry, I missed that you had tried that already. I removed them from the realm, would you mind seeing if that fixed their issue? Their may be a clash in the parent realm that is still causing some problems

**Comment by jhmccoll** [comment]
Hi Jonathan,
  I have emailed the CSR.. she is in a call right now but I have asked her to try to login again to production.

  I will keep you posted.

Thanks for you quick response.. much appreciated!

John

John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”

**Comment by jhmccoll** [comment]
Hi Jonathan,
  Jaime is still unable to login with her IDIR JBROWN.

John


John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”

**Comment by jlangy** [comment]
It is clashing with another IDIR I believe, I am just looking into if the other one is good to remove to fix that and will get back

**Comment by jhmccoll** [comment]
Sounds goods.. thanks Jonathan.



John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”

**Comment by jlangy** [comment]
I removed the old account that I suspect was causing the conflict. The user should be good to login now, but please let me know if there are still issues

**Comment by jhmccoll** [comment]
Thanks Jonathan.  I was able to help the CSR get connected now. She is very happy.
All the best!

**Comment by jhmccoll** [comment]
Hi Jonathan,
  All good now.. thanks for all your help.

I have updated the Issue ticket and closed now.

  Take care!

John

John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”
