### ISSUE TITLE
OpenShift User Access Request

### ISSUE THREAD

**Issue by charlottekelso** [BCDevOps/devops-requests#136]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Alison LeDuc
* GitHub ID: @TestLTA64
* Business Email Address: aleduc@bcorl.ca
* Organization: Office of the Registrar of Lobbyists (ORL)
* Project Role: Project Stakeholder
* OpenShift Projects/Namespaces: asuazq-dev, asuazq-test, asuazq-prod

**Comment by ShellyXueHan** [comment]
@charlottekelso I noticed that you too don't have access to openshift yet. Please get @kevinji1 (the original admin user for the namespaces) to update/re-create this issue to include both you and Alison.

**Comment by kevinji1** [comment]
@ShellyXueHan Alison has already been added to asuazq-dev, asuazq-test, but because she's not yet in the BCDevOps group, she can't log in any of the OpenShift environments. Can you please add her to the BCDevOps group? Thanks!

**Comment by ShellyXueHan** [comment]
`TestLTA64` invited, thanks @kevinji1
