### ISSUE TITLE
Please remove Personal and Basic BCeID as IDP for the j94mtfjj realm (Business BCeID only)

### ISSUE THREAD

**Issue by Kyle-UL** [BCDevOps/devops-requests#1360]
Hi,

A few weeks ago I submitted a request to remove Personal BCeID as an IDP option for our realm (j94mtfjj).  The request can be found here - [https://github.com/BCDevOps/devops-requests/issues/1347](https://github.com/BCDevOps/devops-requests/issues/1347) .

I would like to expand this request to also remove Basic BCeID accounts as a valid IDP sign-in option to that same realm, in addition to Personal BCeID accounts.  Ultimately, we would like to only allow SSO from Business BCeID accounts.

Thank you!

**Comment by arcshiftsolutions** [comment]
We've now:

- Removed Basic & Business IDP (DEV & TEST)
- Removed Basic, Personal & Business IDP (DEV & TEST)
- Added Business only IDP (DEV & TEST)

**Comment by arcshiftsolutions** [comment]
@Kyle-UL - Please confirm everything is as you expect. 🙂

**Comment by Kyle-UL** [comment]
@arcshiftsolutions Thank you, looks good to me!
