### ISSUE TITLE
Addition of Business BCeID and Basic BCeID to KeyCloack realm jgwhdzgs for DEV and Test 

### ISSUE THREAD

**Issue by jengibbens** [BCDevOps/devops-requests#1361]
We are looking to evaluate the use of BCeIDs to access the WebEOC application, which is currently enabled for SSO through IDIR only. Requesting addition of BCeID integration to our KeyCloak realm for dev and test only in order to determine its applicability. Thanks!

**Comment by zsamji** [comment]
@jengibbens can you confirm that your team is using this on the SSO custom realm jgwhdzgs?

**Comment by zsamji** [comment]
confirmed with client's product owner on this request.

**Comment by zsamji** [comment]
going forward with ticket  https://github.com/BCDevOps/devops-requests/issues/1368 and closing this one
