### ISSUE TITLE
Duplicate user Justine Matheson causing login issue in production real vtkayq4c

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#1363]
## Step 0
**Are you the Keycloak Realm Admin?**
Yes
Not sure --> log in to the [Keycloak Custom Realm Registry](https://realm-registry.apps.silver.devops.gov.bc.ca/) and if you see your realm, go to STEP 1. If you don't see it, ask the product owner to submit this request or go to STEP 2

Yes--> go to STEP 1

No --> you will need to ask one of the admin user in your realm to make this request instead.

## STEP 1
Log in to our [Keycloak Custom Realm Registry](https://realm-registry.apps.silver.devops.gov.bc.ca/) and select the DUPLICATE USER tab
- Type the IDIR of the user who is having issue with the account. See the message per environment for the specified user
- If you see the button to delete --> this will remove the duplicate account. Note you will only be able to delete the user if the user is not associated with other products realms
- If you still have issues --> go to STEP 2
- Otherwise --> follow the instructions on the screen (this type of request) and go to STEP 2

## STEP 2
A.  Provide some background on the user account issue.
- What is the issue with the user account? User had a name change and new idir.  Old idir was showing new name, email before I deleted.  I have cleared cache in browser and deleted old idir from realm vtkayq4c. When I searched old IDIR using Step 1 above it was found in another realm outside my control. 
- What result of debugging have you obtained that lead you to request an account removal?  I have had the user try to login with new IDIR account but it was not successful. 

Note: Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

B. [ ] Confirm that user is ready to have the account removed from Keycloak
yes
C. Provide the following information: 

* Username to be removed: jswindel (Justine Swindel) 
* Realm ID where user is having problem login: vtkayq4c
* Environment in which you are facing issue: Production

**Comment by jlangy** [comment]
Hello @jhmccoll, I removed the user account. Please let me know if that fixes the issue

**Comment by jhmccoll** [comment]
Hello, 
  The CSR just verified that she has access with her new IDIR account now.  Everything is working now.
  
   Thank you so much for the quick response!
Jhn

**Comment by jhmccoll** [comment]
Hi Jonathan
  I just wanted to let you know that this resolved the issue.

  Thanks for your prompt attention to this issue.

Regards,
John

John McColl
Team Lead| SBC Technical Support
Strategic Services Branch | Service BC Division| Ministry of Citizens’ Services
T: 778 698-2702 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”
