### ISSUE TITLE
Lost my admin role on my repos

### ISSUE THREAD

**Issue by TylerMuhly** [BCDevOps/devops-requests#1365]
Hi there!

Sorry, but I can't seem to push to any of my repos, and I don't seem to have access to the "Settings" tab anymore. I thought maybe I needed to update my PAT, but that seems all good. 

How do I get back an admin role on my repos? Or am I missing something?

These are my repos:
https://github.com/bcgov/FAIB_wildlife
https://github.com/bcgov/CaribouBC
https://github.com/bcgov/FAIB_org
https://github.com/bcgov/FAIB
https://github.com/bcgov/clus
https://github.com/bcgov/telemetry

Thanks!

**Comment by mitovskaol** [comment]
Hi Tyler, you will need to contact the owner of each repo to get your access back, most likely it was removed when your account was removed from the org because it was missing the 2FA. Our team has no control over access to individual repos that belong to Ministries.

**Comment by TylerMuhly** [comment]
Hi Olena - the problem is that I am the owner on most of these. How do I get that back? Thanks.

**Comment by mitovskaol** [comment]
@TylerMuhly Unfortunately  I do not have the power to make you Owner of these repos again (there is no such option in the role dropdown in GitHub)  but you can contract the people who are currently Admins for these repo to have you added as Admin.

**Comment by TylerMuhly** [comment]
@mitovskaol - so what do I do in this case: I'm the only contributor to this repo ->https://github.com/bcgov/FAIB_wildlife. I still need it, I can't delete it and create a new one. Do I need to create one from scratch and this becomes orphaned then?

**Comment by mitovskaol** [comment]
@TylerMuhly I was able to add you as Admin to this repo, other repos in your list should have Admins that can give you access back for those repos.

**Comment by TylerMuhly** [comment]
@mitovskaol - ok thanks Olena!
