### ISSUE TITLE
SonarCloud connect for new repo: https://github.com/bcgov/ehpr2

### ISSUE THREAD

**Issue by arranfw** [BCDevOps/devops-requests#1366]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
Yes

**Are you the admin user of the GitHub repositories?**
Yes

## Step 1
Verified `bcgov-sonarcloud` is attached to my sonarcloud account

## Step 2

* Project Name: EHPR (Emergency Health Provider Registry)
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/ehpr2

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
@arranfw  repo created on sonarcloud and you are the admin.
