### ISSUE TITLE
Remove user ychung from Keycloak

### ISSUE THREAD

**Issue by jduyn** [BCDevOps/devops-requests#1369]
## Step 0
No but the realm is one of the standard realm.

## STEP 2
The user is experiencing the following duplicate user error when logging in.
"User with username ychung already exists. How do you want to continue?"

Note: Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

B. [X] Confirm that user is ready to have the account removed from Keycloak
Confirmed

C. Provide the following information: 

Username to be removed: ychung
Realm ID where user is having problem login: onestopauth-business
Environment in which you are facing issue: dev, tst and prod

**Comment by junminahn** [comment]
@jduyn IDIR user `ychung` has been removed in `idir`, `onestopauth-business` realms of dev, test, and prod environments.

**Comment by zsamji** [comment]
@ychung-mot @jduyn can you please confirm this issue resolved for you and close this card?

**Comment by jduyn** [comment]
Yes, it can be closed.

Thanks,
James
