### ISSUE TITLE
GitHub Repo for Wildfire Predictive Services

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#137]
GitHub Repository Request:
- Project: wps
- Project description: Wildfire Predictive Services to support decision making in prevention, preparedness, response and recovery
- Approver: @Todd.Wilson
- Repo Owner GitHub ID: DerekRoberts

**Comment by ShellyXueHan** [comment]
@DerekRoberts hey Derek, you are a member of bcgov org already, could go ahead and create the repo yourself.

**Comment by DerekRoberts** [comment]
@ShellyXueHan I have insufficient permissions.  Please advise.

**Comment by ShellyXueHan** [comment]
what type of repo are you creating in the `bcgov` Github organization? as a org member, you should be able to create public repos.

**Comment by DerekRoberts** [comment]
@ShellyXueHan  It's working now.  Thanks for whatever you corrected!
