### ISSUE TITLE
Request Sonarcloud for BC Symptom Checker 

### ISSUE THREAD

**Issue by vyasworks** [BCDevOps/devops-requests#1371]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
Yes - https://github.com/bcgov/myhealthBC-symptom-checker

**Are you the admin user of the GitHub repositories?**
Yes I am the admin 

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. 

Yes

## Step 2
Fill out the following fields

* Project Name: BC Symptom Checker
* GitHub repositories to add to SonarCloud: 
- https://github.com/bcgov/myhealthBC-symptom-checker

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ninosamson** [comment]
@ShellyXueHan Gentle nudge on this one as well.

**Comment by ShellyXueHan** [comment]
Repo added in sonarcloud. @vyasworks is the admin now!
