### ISSUE TITLE
Request: Import GitHub Repository to SonarCloud

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1373]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

Admin User, GitHub ID: DerekRoberts

* Project Name: 
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/forest-client-api (admin request in place)
- https://github.com/bcgov/greenfield-pipeline (already admin)

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by DerekRoberts** [comment]
@ShellyXueHan bcgov-nr is a stop-gap and testbed. Please add to bcgov.

**Comment by ShellyXueHan** [comment]
@DerekRoberts the repo can only belong to one sonarcloud org, so I'll need you to first remove it from `bcgov-nr` and let me know when it's ready to proceed!

**Comment by DerekRoberts** [comment]
@ShellyXueHan Done!  Please don't let me hold us up any further.  :)

**Comment by ShellyXueHan** [comment]
@DerekRoberts added now! you are also admin of it, all good to go!
