### ISSUE TITLE
35r1iman

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1376]
@victorchong requires realm 35r1iman to have both a **Production** [Business BCeID] + [ Basic BCeID ] integration  

If dev and test realms do not have NO Personal BCeID can you please ensure production also does not have this

Thanks

**Comment by arcshiftsolutions** [comment]
@victorchong - We've now added Business/Basic to `35r1iman` in PROD. Please let us know if you have any issues!

@zsamji - Confirmed only IDIR was in place in PROD.
