### ISSUE TITLE
RE: Request for OpenShift Project Set: Driver Fitness Management 

### ISSUE THREAD

**Issue by juhewitt** [BCDevOps/devops-requests#138]
Hello Gatekeepers and Key masters!

As per email with the subject line: RE: Request for OpenShift Project Set: Driver Fitness Management, we are look to create a new OpenShift Project Set for this important initiative!  We've had our alignment meeting with the lab, and have all of the required information you need in the aforementioned email.

Cheers!

**Comment by juhewitt** [comment]
just a reminder... it's SUPPOSED to be **Driver Medical Fitness**.  We've been having some fun there.  Everything in the email form submitted is correct.  The title of this issue is not, nor is the title in the RE: Subject handle of the email

**Comment by ShellyXueHan** [comment]
Project set created as `yalhhm-tools`, `yalhhm-dev`, `yalhhm-test`, `yalhhm-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.
