### ISSUE TITLE
update Product Owner name in dedicated Keycloak realm

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#1380]
there.
I'm trying to update the Product Owner associated with the 4 'dedicated ' Keycloak realms used by the Common Services Showcase team.
Sorry.. there may be a way for me to do this that I am unaware of.
I found the awesome dashboard here: https://realm-registry.apps.silver.devops.gov.bc.ca/my-dashboard
and I have updated the 'product Owner Email' but I don't seem to have permission to update the name and IDIR.

The realms are: `98r0z7rz`,`cp1qly2d`,`jbd6rnxw`,`vehizw2t` 
And the new Product owner is:
Sharolyn Hurley
sharolyn.hurley@gov.bc.ca
IDIR: shurley

Can I ask someone there to do this for me?

Thanks,
-Tim

**Comment by zsamji** [comment]
Hi @TimCsaky ive updated the back end for you so you should be good to go. lmk either way :)

 You may have found a bug for us, so could you email me a screencap at my gov email with the product owner name dithered out for you? thanks so much

**Comment by zsamji** [comment]
received response from client. closing
