### ISSUE TITLE
Remove custom realm named classy

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1381]
As part of our upgrade conversations @Krocodial , this realm (**classy**) is not being used (no active sessions that I see since Oct 2021). We need @Krocodial to confirm either here or via email (ask zorin or lada for update)

**Comment by zsamji** [comment]
received confirmation from client - @arcshiftsolutions and @thegentlemanphysicist  can the two of you cross train on this. thanks!

**Comment by thegentlemanphysicist** [comment]
The classy realm was only present in prod, and has been deleted
