### ISSUE TITLE
Add GitHub Repositories to SonarCloud for Pipeline Integration

### ISSUE THREAD

**Issue by rafasbcgov** [BCDevOps/devops-requests#1382]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
Yes

**Are you the admin user of the GitHub repositories?**
Yes

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: access-to-technology
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/access-to-technology

* Project Name: workbc-wage-subsidy
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/workbc-wage-subsidy

* Project Name: workbc-small-grants
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/workbc-small-grants

* Project Name: workbc-eod-resume-bundler
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/workbc-eod-resume-bundler

* Project Name: workbc-survey
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/workbc-survey

* Project Name: elmsd-analytics-workbooks
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/elmsd-analytics-workbooks

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
@rafasbcgov repos added, you are made the admin of them.
