### ISSUE TITLE
Add GitHub Repositories to SonarCloud for CI Pipeline

### ISSUE THREAD

**Issue by sumesh-aot** [BCDevOps/devops-requests#1383]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
YES

**Are you the admin user of the GitHub repositories?**
YES

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: EAO Project Tracker
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/eao-project-tracker

* Project Name: EAO Project Reports
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/eao-project-reports

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by mitovskaol** [comment]
@ShellyXueHan @caggles ^^^

**Comment by sumesh-aot** [comment]
Could you please give an update on this ?

**Comment by ShellyXueHan** [comment]
project created on sonarcloud, you are the admin!
