### ISSUE TITLE
RE: Empty Form Field: GitHub Repo

### ISSUE THREAD

**Issue by juhewitt** [BCDevOps/devops-requests#139]
Hello hello!  

I was about to put in a new request for a repo for the Drive Medical Fitness app, and noticed the GitHubRepo request form is now blank. :(  Can you have a look see?

Cheers, 
J

**Comment by juhewitt** [comment]
@caggles @ShellyXueHan

**Comment by ShellyXueHan** [comment]
@juhewitt please start a `Request for BCGOV GitHub Organization Membership`, org member can then create repos.
