### ISSUE TITLE
Repo Transfer, admin request

### ISSUE THREAD

**Issue by rafasdc** [BCDevOps/devops-requests#1390]
## Step 0

**DO NOT OPEN A TICKET UNLESS THERE ARE NO ADMINS ASSIGNED TO THE REPO IN QUESTION**
If your repo has an admin, please ask them to provide you with the access you need. This ticket is for the **rare** case in which a repo loses all of its admins - this can occasionally happen when moving repos between different owners. If you have not moved the repo in question to bcgov recently, then this ticket probably does not apply to you. 

**If you open a ticket here and there is an admin user assigned to that repo, this ticket will be closed without action.**

**Are you the Technical Lead?**
Yes

**Are you a member of the BCGOV org?**
Yes

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Transferring private repo from other org. 

## Step 5
Provide the **name of the admin-less repo** and any other details that may be necessary for us to fix the issue.
https://github.com/bcgov/workbc-mobile-notifications-api
https://github.com/bcgov/workbc-mobile-app-website
https://github.com/bcgov/workbc-jobs-api
https://github.com/bcgov/workbc-file-scanner-api
https://github.com/bcgov/workbc-helpbot

Please note that this ticket may take some time to action - we need to ensure that we are providing admin access to the correct user. Keep a close eye on the comments as the team will likely have more questions for you!

**Comment by ShellyXueHan** [comment]
done!
