### ISSUE TITLE
AppCenter Integration

### ISSUE THREAD

**Issue by rafasdc** [BCDevOps/devops-requests#1391]
## Step 0
**Do you have repos on bcgov GitHub Organization?**
If yes, please proceed with the request.

**If there is similar applications/tools available in the community, have you tried them out?**
There are many well supported community tools for various purposes, such SonarCube and BDDStack. 
Before you start with the new tools, have you consider trying out those that are available and widely adopted by the other application teams? 
If you have done so and do found that the existing ones does not match your need, please proceed.

**Have you tested out this GitHub application already?**
Yes, currently using it.

We understand that there are a lot of new and cool GitHub Applications out there that teams could like to try out. 
However, we cannot just enable the integration without evaluating the app, as those are open to all application teams. 
We believe you have tested out the GitHub apps and had good reasoning for the preference before making this request.

## Step 1
Please fill out the team and project info so we know how to contact you:

* Product Name: WorkBC Mobile App
* Team Name: WorkBC App (551bf1)
* GitHub Repositories on bcgov: workbc-mobile-app (to be created/transferred)

## Step 2
Please provide details about the requested GitHub App. Take a look here for a [good example](https://github.com/BCDevOps/platform-services/issues/120/)

1. Brief introduction of the app:
https://appcenter.ms/
From App Center:
The App Center Build service helps you build Android, iOS, macOS, and UWP apps using a secure cloud infrastructure. Connect to your repo in App Center and start building your app in the cloud on every commit. With Build you can forget about configuring build servers locally, complicated configurations, and code that builds on a coworker's machine but not yours.

Currently using App Center to manage our builds, integrated with current private repo outside bcgov. Intention is to migrate to bcgov public, but will require App Center to keep managing our builds.

2. General Criteria:
  - How Easy / Fast / Repeatable is it to use and maintain for both Development Teams and Platform Services Teams: Very easy, connect to GitHub repo, setup, build and start. Support Android, iOS, React Native, etc. Initial setup might take some trial and error to get it working. 
  - Customizable: Yes
  - User Access Model: Free/Paid. Login through Azure
  - License: AppCenter Repo License are MIT and Attribution 4.0 International. 
  - BCGov STRA: WorkBC App STRA
  - Price Model: Free 240 build minutes/month, one concurrent build. Paid option available. 

4. Comparison between Existing Tools Used by the Community
  - pros: Able to build Android and iOS apps on one platform. Allows iOS builds without a Mac. Not using computer resources for builds. 
  - cons: Might require a paid subscription if doing several builds a month. UI Tests are not free. 

5. Relevant Resources and Links

https://docs.microsoft.com/en-us/appcenter/
https://appcenter.ms/#pricing
https://appcenter.ms/
https://github.com/microsoft/appcenter

**Comment by NickCorcoran** [comment]
Have requested review by Social Sector security team.

**Comment by ramdulam** [comment]
@NickCorcoran Thanks for your follow-up.

@JeffDorian77 @rafasdc: May I please request a quick meeting? so that, I can understand better about the Azure tenancy and related the dataflows (to/from) the Auzure tenancy.

**Comment by NickCorcoran** [comment]
Since we have no Azure tenancy yet (not one that's supported by an officially signed contract w/ BCGov), we do not have any details on dataflows to a tenancy.  This was submitted over a year ago and I'm not sure what official decision was. If still needed please submit a new ticket.
