### ISSUE TITLE
We are testing our backup/restore procedures. 

### ISSUE THREAD

**Issue by ASpiteri-BCGov** [BCDevOps/devops-requests#1395]
## Restore a backup Persistent Volume (PV)
Please read through the documentation about [OCP4 Backup and Restore](https://developer.gov.bc.ca/OCP4-Backup-and-Restore) before proceeding with this request!

> Note that only the `netapp-file-backup` type of Persistent Volume can be restored from OpenShift.

### Step 1
Fill out the following fields

* Date: April 07, 2022
* Cluster: Silver
* Source PV: pvc-d23e80a5-6ae3-4055-bbfa-9093b4c69990
* Destination PV: pvc-cd5bfd81-6850-4fb7-9a79-c1cd55ad3104/restore

> Note that the Source and destination can be the same PVC or separate. You can specify sub-folders instead of the whole volume.

> Note that we need the PV not the PVC name. ie: `pvc-<uuid>`

**Comment by StevenBarre** [comment]
Ticket RITM0115726 entered with the Backup team to action the restore. Congrats on being the first to request a restore!

**Comment by StevenBarre** [comment]
@ASpiteri-BCGov the restore has been completed. Can you please take a look and verify everything showed up?

**Comment by ASpiteri-BCGov** [comment]
Hi @StevenBarre,

The restore was complete success! Thanks again!!

Cheers,
Adam
