### ISSUE TITLE
JADE-859 - AG/PSSG BCGov-C memebership

### ISSUE THREAD

**Issue by rloisell** [BCDevOps/devops-requests#1397]
details sent by email to platformservices team.

Following instructions: 

bcgov-c:

Is used for private repositories and contains code for closed-source projects.
Org membership is required to create private reports and all requests require Platform Services Team's approval as a new user license needs to be procured. **Submit a request for a private org membership [here](https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+ShellyXueHan%2C+mitovskaol%2C+patricksimonian&labels=github-repo%2C+pending&template=github_repo_request.md&title=)**

**Comment by rloisell** [comment]
cc: @jennifer-dowd

**Comment by rloisell** [comment]
Bump @caggles / @ShellyXueHan / @mitovskaol - sent a follow up email with an addition to the request for BCGov-c membership.

**Comment by mitovskaol** [comment]
This request has been processed.
