### ISSUE TITLE
Sonar cloud 

### ISSUE THREAD

**Issue by vyasworks** [BCDevOps/devops-requests#1398]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

Yes -   https://github.com/bcgov/internationally-educated-nurses

**Are you the admin user of the GitHub repositories?**

Yes. 

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Internationally Educated Nurses
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/internationally-educated-nurses

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by vyasworks** [comment]
@caggles @patricksimonian @ShellyXueHan Hello! Looking forward to having this soon. Can you please let me know when we can expect this. Our STRA depends on sonar cloud

**Comment by pmcdonne** [comment]
Hi @caggles @patricksimonian @ShellyXueHan - could we please move forward with this scan so that we can complete the STRA for the IEN application.

Thanks for your help with this.
Paul McDonnell, IEN Project Manager

**Comment by ShellyXueHan** [comment]
@vyasworks Sorry for the delay! repo added to sonarcloud, you are the admin!

**Comment by vyasworks** [comment]
Thank you!
