### ISSUE TITLE
Request for BCGOV GitHub Organization Membership

### ISSUE THREAD

**Issue by TylerMuhly** [BCDevOps/devops-requests#14]
Rrequesting to:
- [x] Invite a user
- [ ] Remove a user

* Project Name:  FAIB
* GitHub Org: bcgov 
* Full Name: Gordon Nienaber
* GitHub ID: @gnienaber
* GitHub Account 2FA Confirmed: yes
* Email address: gordon.nienaber@gov.bc.ca
* Organization: FLNRORD FAIB
* Project Role: Analyst
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: FAIB_TSR_DATASETS

**Comment by ShellyXueHan** [comment]
Hi @TylerMuhly if Gordon does not need to join a GitHub team in bcgov, then repo admin could invite the user as a `Collaborator`. Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).
