### ISSUE TITLE
Add private repo for FINtranet

### ISSUE THREAD

**Issue by victoriazou** [BCDevOps/devops-requests#1400]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - platformservicesteam@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* Details on choosing private repo: 
* Preferred name for repo: 
* Expected date to move to public: MM/YYYY
* GitHub ID for repo owner: @
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by victoriazou** [comment]
Emailing the Platform team with details.

**Comment by caggles** [comment]
Done! FYI, your invite to the org is pending - you'll need to accept that before you have access!
