### ISSUE TITLE
Request access to bcgov-c for FIN IMB

### ISSUE THREAD

**Issue by victoriazou** [BCDevOps/devops-requests#1403]
Hello Platform Services Team,

Can I please add the following members to bcgov-c?

- chrislaick
- jer3k

They are internal government developers on my project team (fin-exec-support-system). So far, chrislaick is accessing as an outside collaborator, and jer3k is unable to access our repo.

Our GitHub Team is [FIN IMB](https://github.com/orgs/bcgov-c/teams/fin-imb).

Thanks!

**Comment by mitovskaol** [comment]
The invites to bcgov-c have been sent to these users.
