### ISSUE TITLE
Reqeust to disable and then delete custom realm vig3jzsu

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1405]
Through email communication with client, requesting to disable and then 5 days later delete this realm
@vesselofgold @mohammedalhassan

**Comment by vesselofgold** [comment]
@zsamji my GitHub id is @vesselofgold

**Comment by mohammedalhassan** [comment]
@zsamji confirming request, thanks

**Comment by thegentlemanphysicist** [comment]
Deleted

**Comment by thegentlemanphysicist** [comment]
Deleted
