### ISSUE TITLE
Grant admin access to https://github.com/bcgov/organizations-api

### ISSUE THREAD

**Issue by sharpedavid** [BCDevOps/devops-requests#1407]
## Step 0

**DO NOT OPEN A TICKET UNLESS THERE ARE NO ADMINS ASSIGNED TO THE REPO IN QUESTION**
If your repo has an admin, please ask them to provide you with the access you need. This ticket is for the **rare** case in which a repo loses all of its admins - this can occasionally happen when moving repos between different owners. If you have not moved the repo in question to bcgov recently, then this ticket probably does not apply to you. 

**If you open a ticket here and there is an admin user assigned to that repo, this ticket will be closed without action.**

**Are you the Technical Lead?**

Yes.

**Are you a member of the BCGOV org?**

Yes.

## Step 1
_Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues_

This is not a duplicate request.

## Step 2
_Provide a detailed explanation of the steps which caused your repo to lose all admin users._

I started the repo as a personal repo (sharpedavid). I later [transferred](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) the repo to the bcgov organization. I did not realize I would lose admin privileges.

## Step 5
_Provide the **name of the admin-less repo** and any other details that may be necessary for us to fix the issue._

https://github.com/bcgov/organizations-api

**Comment by sharpedavid** [comment]
When I created this repo as a personal repo, my thought process was "This is just a work in progress. I'll 'publish' it to bcgov when I'm ready." In hindsight this was unnecessary. I'm sorry for the inconvenience, but please restore my admin access to this repo.

**Comment by ShellyXueHan** [comment]
done!
