### ISSUE TITLE
Request to import ITVR repo on SonarCloud

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#1409]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**. Yes
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** Yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: ITVR - Income Tax Verification Rebates
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/itvr.git

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by NickCorcoran** [comment]
https://sonarcloud.io/project/configuration?id=bcgov_itvr

You are setup as admin for this space.  You should be able add other users to control this project in SonarCloud too.  You will have to setup the scanning configuration.

**Comment by NickCorcoran** [comment]
@kuanfandevops Please update and close ticket when working.

**Comment by kuanfandevops** [comment]
@NickCorcoran yes, I can see our project is added to SonarCloud. One question here, I tried to grant permission to several our team members, but they are not in the users list, could you add them? their github ids are:
emi-hi
naomiaro
tim738745

**Comment by NickCorcoran** [comment]
@kuanfandevops 
1) each of the additional users (emi-hi, naomiaro, tim738745) need to be members of the BCGov GitHub org (you can add them via JustAsk - https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/, https://www.youtube.com/watch?v=IvdPyx2-qm0), and then 
2) each user will need to attempt to login to SonarCloud before they can be assigned the role.  Once they have, their names will show up in the users list for SonarCloud
3) Then you will be able to add them from the permissions tab.

**Comment by kuanfandevops** [comment]
Thanks Nick. I'm closing the issue.
