### ISSUE TITLE
Requesting a BCGov-c private repo for the BCPS DEMS project

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1412]
This is a request to:

[x] Create a private repo
[ ] Remove a private repo and go public

Requesting a BCGov-c private repo for the BCPS DEMS project

Separate email to follow with relevant details.

This is related to AG's JIRA ticket BCPSDEMS-253.

**Comment by ShellyXueHan** [comment]
closing ticket as this will be handled from another provisioning process!

**Comment by mitovskaol** [comment]
@ShellyXueHan I spoke with Ryan and at this moment they still need a private repo in bcgov-c. Can you please create the repo for them.

**Comment by ShellyXueHan** [comment]
okay repo created! https://github.com/bcgov-c/BCPSDEMS
