### ISSUE TITLE
Add FIN IMB team members to bcgov-c

### ISSUE THREAD

**Issue by victoriazou** [BCDevOps/devops-requests#1418]
Hello Platform Services Team,

Can you please add the following team members to the bcgov-c org?

- Jonwells44
- Rossen2002
- ntirukovela

These are members of FIN IMB who need access to our private repo "fin-exec-support-system". Thanks,

Victoria Zou

**Comment by mitovskaol** [comment]
@victoriazou Any user with admin access to the repo can add this users. Our team does not manage access to individual repos that belong to other teams (for security reasons). We only step in if the number of available users licenses for bcgov-c needs to be increased. I have just checked and there are 4 licenses available so you should be able to add 3 users without any issues.

**Comment by victoriazou** [comment]
Hi Olena, I am trying to add these users to my team here: https://github.com/orgs/bcgov-c/teams/fin-imb/members but I cannot add members that are not a part of the bcgov-c organization. We are all internal BC gov employees. I was trying to avoid adding them as outside collaborators, which our vendors are. Are you suggesting I should invite users internal to my organization as outside collaborators?

**Comment by mitovskaol** [comment]
@victoriazou I apologize for the confusion, I confirmed that yes, new users have to be added to the bcgov-c org first before the teams can add them to the private repos. I've sent the invites to the 3 users listed above to join the org.

**Comment by victoriazou** [comment]
Thanks @mitovskaol much appreciated! Hopefully the invites stay valid into next week. If not, I'll let you know.

**Comment by victoriazou** [comment]
@mitovskaol Hi Olena, apologies, can you please resend the invitation to ntirukovela ? He did not accept the invitation in time.
