### ISSUE TITLE
Request for a public BCGov GitHub repository

### ISSUE THREAD

**Issue by fwkendall** [BCDevOps/devops-requests#142]
---
name: Request for a public BCGov GitHub repository
about: Public repo for the Common Components team
title: 'common-components-wiki'
labels: github-repo
assignees: caggles, ShellyXueHan
---

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Are you requesting to:
- [ ] transition existing private repo in `bcgov-c` GitHub organization to public repo in `bcgov` GitHub organization
- [x] create a temporary public repo in `bcgov-c` GitHub organization

## Step 3
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Fill out the following fields

* Project: common-components-wiki
* Project Description: Research and resources related to common components within the BC Gov
* Approver: @
* Repo Owner GitHub ID: @fwkendall 
* Approval from Enterprise DevOps branch leadership: @

## Step 5:
Make the GitHub User Access Requests for your team members.

**Comment by ShellyXueHan** [comment]
@fwkendall Hi Kendall, please create a `Request for BCGOV GitHub Organization Membership`. The organization member will be able to create repos. As we need different set of information, I will close this one. Thanks!
