### ISSUE TITLE
CDDS-156 - AG/PSSG BCGov-C membership - Add user

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1420]
Details will be sent by email to Platform Services team.

Following instructions:

bcgov-c:

Is used for private repositories and contains code for closed-source projects.
Org membership is required to create private reports and all requests require Platform Services Team's approval as a new user license needs to be procured. Submit a request for a private org membership [here](https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+ShellyXueHan%2C+mitovskaol%2C+patricksimonian&labels=github-repo%2C+pending&template=github_repo_request.md&title=)

**Comment by mitovskaol** [comment]
I believe this request has been completed. Please let me know otherewise.
