### ISSUE TITLE
Request to import bcgov/CONN-CCBC-portal repo on SonarCloud

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#1422]
* Project Name: `CONN-CCBC-portal`
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/CONN-CCBC-portal
* Team will add `.sonarcloud.properties` config once SonarCloud is enabled for this repo

**Comment by NickCorcoran** [comment]
@wenzowski I have added the project and assigned you the Administer and Execute Analysis roles.  This should allow you to add other users to the project.
https://sonarcloud.io/project/overview?id=bcgov_CONN-CCBC-portal
