### ISSUE TITLE
RSI-1647 - AG/PSSG - Create new bcgov-c private repo 

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1427]
A separate email will be sent to the Platform Services Team with details of this request 

Are you requesting to (leave this in to GitHub issue):
	[x] Create a private repo
	[ ] Remove a private repo and go public

Thanks! :)
Zubin Akolawala
AG ISB Application Management

**Comment by caggles** [comment]
closing as per the email response!
