### ISSUE TITLE
MDYNAMICS-1188 - AG/PSSG - Add user to BCGOV-c pool 

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1428]
Hello Platform Services Team, 

A follow-up email will be sent with required details to add a new user to the bcgov-c pool.

Thank you!
Zubin Akolawala
AG ISB Application Management

**Comment by mitovskaol** [comment]
The invite to join the bcgov-c org has been sent to leewrigh’s email.
