### ISSUE TITLE
Please add maven-remote to b16795-tools-map-artifacts

### ISSUE THREAD

**Issue by michaelpnelson** [BCDevOps/devops-requests#1433]
Artifactory project:
b16795-tools-map-artifacts
Repository name:
[mb16-]maven-remote
Repository URL:
https://artifacts.developer.gov.bc.ca/artifactory/maven-remote/
Maven layout: version 2

Originally requested in chat https://chat.developer.gov.bc.ca/channel/devops-artifactory?msg=nrA4RRsxT2apiP5Bf. 

Cheers!

**Comment by michaelpnelson** [comment]
Nudge nudge :) Just checking in on this - do you need anything from me? Thanks ...

**Comment by caggles** [comment]
Sorry for the delay! This is now done!
Remember to add a virtual repo that includes both this and any local maven repos you have!
