### ISSUE TITLE
Uninstall GitHub App

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#1436]
I don't seem to have permission to uninstall a github app from my team repo.
Help please?

* Product Name: CONN-CCBC-portal
* Team Name: [CITZ Connectivity](https://github.com/orgs/bcgov/teams/citz-connectivity)
* GitHub Repositories on bcgov: https://github.com/bcgov/CONN-CCBC-portal

I'm trying to remove the Cocogitto-bot from https://github.com/bcgov/CONN-CCBC-portal as we've implemented the [cocogitto-action](https://github.com/cocogitto/cocogitto-action) in its place for better control. Someone with adequate permissions should be able to uninstall `Cocogitto-bot` from the [Installed GitHub Apps page on our repo](https://github.com/bcgov/CONN-CCBC-portal/settings/installations) without affecting any other `bcgov` users of this app.

ref: bcgov/CONN-CCBC-portal#564

**Comment by wenzowski** [comment]
There's only a template for installing apps not uninstalling them, so please let me know if I've missed any crucial information in this ticket.

**Comment by wenzowski** [comment]
Is `requestron` asking for a `client-response` or confirmation that one has been received?

**Comment by ShellyXueHan** [comment]
hi Alec @wenzowski  i've removed it and got the message: `A job has been queued to uninstall Cocogitto-bot` So it might take some time for the uninstallation to complete. But you should be all set!
