### ISSUE TITLE
Please add OSGeo remote repo to b16795-tools-map-artifacts 

### ISSUE THREAD

**Issue by michaelpnelson** [BCDevOps/devops-requests#1441]
Hi! We'd like to consume some org.geotools dependencies that don't seem to be in Maven Central. 

Artifactory project:
b16795-tools-map-artifacts

Repository name:
[mb16-]maven-osgeo-remote

Repository URL:
https://repo.osgeo.org/repository/release/

Maven layout: version 2

No credentials are needed for this repository.

Thanks :)

**Comment by michaelpnelson** [comment]
Nudge :) Just checking in on this request. Please let me know if there's anything else you need from me. 

Cheers

**Comment by caggles** [comment]
Done!

**Comment by michaelpnelson** [comment]
Thanks Cailey! I've confirmed I can see the new local repository and have added it to a virtual repository. Cheers
