### ISSUE TITLE
Request: Artifactory Repository For NextGenSecurityProject

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/devops-requests#145]
## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Using-Artifactory

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Ensure that you have already logged into Artifactory at least once via Keycloak to create your personal account name:
https://artifacts.developer.gov.bc.ca

## Step 4
Fill out the following fields

* Requester: j-pye@github
* Team Name: security (based on namespace labels)
* Repo Type: Docker
* Repo Location: local
* Repo Description: Repository to Store Images Relating to Security Projects
* Primary OpenShift Project: devops-security-tools

**Comment by caggles** [comment]
Cancelled as per chat with Justin.

**Comment by j-pye** [comment]
@caggles Please reopen so I can beta test :P Thanks!

**Comment by caggles** [comment]
done!
