### ISSUE TITLE
I used the Self Serve to add jennyschan for openshift access.

### ISSUE THREAD

**Issue by ozamani9gh** [BCDevOps/devops-requests#1450]
Hello,

I tried to give Open shift Access to one of our BC Registries Contractors    Jenny Chan   (Github @jennyschan )

using Self Serve.    https://just-ask-web-bdec76-prod.apps.silver.devops.gov.bc.ca/requests

she cannot see the openshift console when she goes to this link.   Any help would be much appreciated, can you confirm she has access to Openshift.

(https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects)

**Comment by ShellyXueHan** [comment]
@ozamani9gh Jenny is already a member of our github organizations. please ask her to clear cache and try to login again via the Github account!

**Comment by jennyschan** [comment]
I will provide the updates this week.  Thanks again for the help

Regards,
Jen

On Nov 7, 2022, at 12:29 PM, requestron[bot] ***@***.***> wrote:

﻿

It has been 2 weeks or more since this ticket was last updated. This issue will be closed if it is not updated in the next 1 week.

**Comment by jennyschan** [comment]
@ShellyXueHan good morning, I'm working on the last step for setting the console.  will provide the update within this week.  Thanks in advance for your help.

**Comment by ShellyXueHan** [comment]
@jennyschan the github organization membership is only to let you login to openshift console, which you have already. But it does not include RBAC to a specific namespace. Please contact your project's technical lead or product owner to give you required access to the namespaces. See here for more instruction: https://docs.developer.gov.bc.ca/grant-user-access-openshift/#grant-namespace-access

**Comment by jennyschan** [comment]
Thanks again.  will chat with them.
