### ISSUE TITLE
onroutebc sonarcloud request

### ISSUE THREAD

**Issue by cberg-aot** [BCDevOps/devops-requests#1458]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: onRouteBC
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/onroutebc

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by NickCorcoran** [comment]
@cberg-aot I have setup the repo for scanning but your GitHub account was not within the BCGov org so I couldn't add you as an admin.  
I have sent you an invitation to that account.  
Once accepted, and you're part of the org, I can add you as an admin on your project analysis on SonarCloud.

**Comment by cberg-aot** [comment]
Hi Nick, I have accepted the invite to bcgov

**Comment by NickCorcoran** [comment]
@cberg-aot. Great.  If you could login here w/ your GitHub ID, then I can assign your permissions: https://sonarcloud.io/organizations/bcgov-sonarcloud/projects

**Comment by NickCorcoran** [comment]
You are now all setup.  You can manage access here: https://sonarcloud.io/project/roles?id=bcgov_onroutebc and manage scan details here: https://sonarcloud.io/project/overview?id=bcgov_onroutebc

**Comment by cberg-aot** [comment]
TyVm!  Confirmed!
