### ISSUE TITLE
Remove user from BCGov/BCDevOps

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1460]
## Removing Access

If you are removing access please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request on your behalf. 
This person must already be a member of the bcgov GitHub Organization in order for us to process this request.

If you are a technical lead and you've come here to request access for yourself, please go ahead and create this ticket, and then 
contact @mitovskaol (Olena Mitovska) with a link to the ticket so she can approve it.

### Step 2
Fill out the following fields

* Project Name: Org only
* Technical Lead Github ID: Unsure
* GitHub Org: bcgov, BCDevops
* GitHub ID: @dogivalfer
* Reason for removal: Left project

**Note** that the Platform Services Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
user removed from github orgs!
