### ISSUE TITLE
Request to restore the backup for PVC pvc-4f168477-43b0-4392-bfe1-93281ee2a3e9 in e52f12-prod namespace

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#1468]
## Restore a backup Persistent Volume (PV)
Please read through the documentation about [OCP4 Backup and Restore](https://developer.gov.bc.ca/OCP4-Backup-and-Restore) before proceeding with this request!

> Note that only the `netapp-file-backup` type of Persistent Volume can be restored from OpenShift.

### Step 1
Fill out the following fields

* Date: Sep 22, 2022 or the earliest you have ( 90 days ago )
* Cluster: Silver
* Source PV: /backups/minio-backup on  PV: pvc-4f168477-43b0-4392-bfe1-93281ee2a3e9
* Destination PV: /backups/minio-backup-from-tap on same PV

Notes:
1. The PVC backup-zeva-prod is mounted to /backups on pod patroni-backup-3-c4t45
2. Request to restore the directories/files under /backups/minio-backup to /backups/minio-backup-from-tap

> Note that the Source and destination can be the same PVC or separate. You can specify sub-folders instead of the whole volume.

> Note: both PVC source and destination must be a netapp-file-backup PVC on the same cluster.

> Note that we need the PV not the PVC name. ie: `pvc-<uuid>`

**Comment by StevenBarre** [comment]
RITM0135483 opened with the Backup team.

**Comment by StevenBarre** [comment]
Restore completed
