### ISSUE TITLE
Request to remove one member access for the Github orgs and Openshift

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#1472]
## Removing Access

If you are removing access please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?** Yes, I'm the devops in Zelda team.
If not, you need to ask your team's Technical Lead role to make this request on your behalf. 
This person must already be a member of the bcgov GitHub Organization in order for us to process this request.

If you are a technical lead and you've come here to request access for yourself, please go ahead and create this ticket, and then 
contact @mitovskaol (Olena Mitovska) with a link to the ticket so she can approve it.

### Step 2
Fill out the following fields

* Project Name: Zelda
* Technical Lead Github ID: kuanfandevops
* GitHub Org: bcgov, BCDevops, or private: All of the three
* GitHub ID: @amichard 
* Reason for removal: Richard Tan has left public service

**Note** that the Platform Services Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
the GitHub ID has been removed.

**Comment by kuanfandevops** [comment]
Hi,

The request was asking to remove GitHub account amichard but I just found my account was removed. I’m migrating production database this morning. The just sent a new request to rejoin the two organization.  Could please any one help to approve it ASAP.

Thanks
Kuan

From: Olena Mitovska ***@***.***>
Reply-To: BCDevOps/devops-requests ***@***.***>
Date: Tuesday, January 31, 2023 at 1:41 PM
To: BCDevOps/devops-requests ***@***.***>
Cc: "Fan, Kuan X LWRS:EX" ***@***.***>, Author ***@***.***>
Subject: Re: [BCDevOps/devops-requests] Request to remove one member access for the Github orgs and Openshift (Issue #1472)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


Closed #1472<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBCDevOps%2Fdevops-requests%2Fissues%2F1472&data=05%7C01%7Ckuan.fan%40gov.bc.ca%7C44a51d279f9e4ad2f09108db03d3e381%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638107980804231637%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h43XIhNCoE5V2uyZZi8x1ShBFtD9GawCu3LVhgEsKKc%3D&reserved=0> as completed.
