### ISSUE TITLE
Request for a Private BCGOV GitHub Repository for MFIN IMB

### ISSUE THREAD

**Issue by GBrittonIMB** [BCDevOps/devops-requests#1479]
## Step 0

**Are you looking to make a public repository?** No, we require a private repository, to begin.
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.

**Are you a member of the private BCGOV GitHub Organization already?** Yes
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?** Yes, initially we do until our MISO has given us approval. This should occur before our project work ends on May 31, 2024.  
We highly recommend open source, secrets and any sensitive information should never be part of your code based. 
If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**  May 31, 2024 or earlier when our MISO approves.
All projects in the private organization are required to be there temporarily. 
This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. 
Please include a firm date by which you will move your repository to the open organization.

If you feel you cannot move to open-source ever, we strongly encourage you to reconsider. The project is being created with open-source as the foundation. The project intention is to move this to the open-source repo when we can.
 
However, if you are certain that you require a fully closed-source repo permanently, you can speak to the team on RocketChat to discuss your options.
Using the private bcgov GitHub Organization may not be the appropriate solution for your team in this case.

## Step 1
Make sure no duplicated request exists, search here: Confirmed, no duplicated request exists.
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo: Yes
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - platformservicesteam@gov.bc.ca

* Project Name: Finance Data Catalogue
* GitHub Org: bcgov
* Details on choosing private repo: 
* Preferred name for repo: MFIN Data Catalogue
* Expected date to move to public: MM/YYYY: 05/2024
* GitHub ID for repo owner: @GBrittonIMB
* GitHub Account 2FA Confirmed: yes
* Email address: Greg.Britton@gov.bc.ca
* Organization: Ministry of Finance, IMB
* Project Role: Product Owner
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
hello @GBrittonIMB please email us or response in this ticket the `Details on choosing private repo`. In addition, we can't have a repo name with spaces, so the repo name is probably going to be `MFIN-Data-Catalogue`. let us know if you'd like it to be something else!

**Comment by GBrittonIMB** [comment]
Hi Shelly,
Understood, the repo name as  “MFIN-Data-Catalogue” is fine.
Thank you

Best regards,
Greg

Greg Britton | Director of Digital Strategy and Services
Information Management Branch
Ministry of Finance
Ph: 250-883-4650

**Comment by GBrittonIMB** [comment]
I am trying to find the repo that was created from this request MFIN-Data-Catalogue. 
Could you please confirm that this repo was created.
