### ISSUE TITLE
Provide API Support for Attachments in CHEFS

### ISSUE THREAD

**Issue by MichaelCampb** [BCDevOps/devops-requests#1480]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.

Provide support for the CHEFS API to handle attachments in CHEFs forms.

2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!

This is a new request which does not fall under the existing request types.

4. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!

We are able to provide the specifics of our implementation of CHEFs upon request.

A brief overview is that we are using CHEFs as a front end for applicants to submit grant proposals. Once the application has been submitted, it is loaded into a custom application used by Ministry staff to adjudicate the grants. These grant proposals require attachments which are added to the CHEFS forms. Currently, loading the form attachments is done manually which is time consuming, error prone, and inefficient. Having the API permit loading of attachments directly into our adjudication application via API would greatly improve the current process.

5. **What is the end result?** Please provide plenty of details about what the end result should look like.

The end result would be adding functionality to the CHEFS API to support attachments, so we can load attachments into our adjudication application without having a clunky manual process.

**Comment by caggles** [comment]
The CHEFs application isn't maintained by the platform services team. Check out the CHEFs repo here: https://github.com/bcgov/common-hosted-form-service and open a ticket with them!
