### ISSUE TITLE
Request for adding .NET 6 (Linux based .NET core V6) , Python 3.10 and node:14.17.0-alpine to artifactory

### ISSUE THREAD

**Issue by abin-aot** [BCDevOps/devops-requests#1483]
1. **What is it?** 

As part of FOI Modernisation Project's Emerald cluster based apps, there are certain requirements for below image artifact's availability on our artificatory repo - artifacts.developer.gov.bc.ca

> 1.  mcr.microsoft.com/dotnet/sdk:6.0 
> 2. python:3.10-slim
> 3. node:14.17.0-alpine 

3. **Why should this be a new request type?** 
This is as per the directions from @caggles . https://chat.developer.gov.bc.ca/channel/devops-artifactory?msg=RXu2scazg2Lq5tRpr

5. **What information is required to fulfill this request?** 

Little of bit context here : As mentioned above we are building certain apps from our Emerald Cluster's Project/NS, and since there are security limitations(firewall ?) to pull images from  public image repo endpoint. hence we are trying our best to pull these from our artifactory 
 For more details : https://chat.developer.gov.bc.ca/channel/nsx-early-adopters?msg=y9kqTbE3wN86nRGMZ

7. **What is the end result?** 

Our expectation is like the above mentioned images will be available at artifacts.developer.gov.bc.ca and can be pulled on  our Emerald Project's build . Please let us know the location once added. 

cc: @lmullane

**Comment by caggles** [comment]
Mkay, done! Try pulling from `artifacts.developer.gov.bc.ca/microsoft-docker-remote` instead of `mcr.microsoft.com` and it should work! Let me know if you have any troubles!

**Comment by lmullane** [comment]
Thank you @caggles! We appreciate it.

cc @abin-aot

**Comment by abin-aot** [comment]
@caggles : Could you please confirm whether this path exists in artifactory ? 
`artifacts.developer.gov.bc.ca/microsoft-docker-remote/dotnet/sdk:6.0` . I can see aspnet one, but not .NET6.0

**Comment by caggles** [comment]
If it exists in MCR, it exists in artifactory. It will not show up in artifactory until after it's cached the first time, so please pull it and let me know if that doesn't work.
