### ISSUE TITLE
Invite me to the bcgov-c org

### ISSUE THREAD

**Issue by GBrittonIMB** [BCDevOps/devops-requests#1487]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!
3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
4. **What is the end result?** Please provide plenty of details about what the end result should look like.

**Comment by GBrittonIMB** [comment]
Can I please add the following members to bcgov-c?
1. I have a private github 
2.  I could not find any other request to do this change.
3. I thought this would be part of the normal request for a repo
4. I have access to bcgov-c and I can interact with my mfin team.

**Comment by caggles** [comment]
done!
