### ISSUE TITLE
RE: GitHub Repo Access Request - Admin - RSI Courts

### ISSUE THREAD

**Issue by juhewitt** [BCDevOps/devops-requests#149]
Are you requesting to:
- [x] Update Admin Access

* Project Name: RSI Courts Integration
* GitHub Org: bcgov-c/private

Email in the pathfinder inbox: 
RE: GitHub Repo Access Request - Admin - RSI Courts
Time roughly: January 28, 11:43

**Comment by caggles** [comment]
just waiting on clarification through email to action this request.
