### ISSUE TITLE
add repo: pay-digital-gov-site to sonarcloud

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#1490]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** Yes
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: pay-digital-gov-site
* GitHub repositories to add to SonarCloud: 
- pay-digital-gov-site
- 

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by MonicaG** [comment]
Hi @gil0109,

The project has been setup in SonarCloud. The `SONAR_TOKEN` secret has been added to the repository.

To use SonarCloud, create a configuration file in the root directory of the project and name it 
`sonar-project.properties`:

```sonar.projectKey=bcgov_pay-digital-gov-site
sonar.organization=bcgov-sonarcloud

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=pay-digital-gov-site
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8```
