### ISSUE TITLE
Private Repo Request for River Forecast Centre Wiki

### ISSUE THREAD

**Issue by franTarkenton** [BCDevOps/devops-requests#1493]
## Step 0

**Are you looking to make a public repository?** - YES

**Are you a member of the private BCGOV GitHub Organization already?** - YES

**Are you sure you need to have your project code close-sourced?** - YES

**What date will you move your project to open-source?** - UNDETERMINED

### Background on request

I am working with the River Forecast Centre (RFC), and ultimately trying to modernize their data pipelines.  Modernization is a vague term that can mean so much, in this context it would entail:
1. Migrate storage of data off of on prem. Shared File and Print (SFP) servers to object storage
2. Migrate data processing scripts from windows scheduler scripts to Git hub actions and eventually to AWS serverless functions (lambda / fargate / etc)
3. Pivot from cronjob based processing to event based processing, tieing into the federal governments advanced message queue (AMQP)
4. ETC... there is so much more but that hopefully gives you the high level picture.

The RFC wants to set up a wiki that describes their operational practices.  Initially they would like this wiki to be available only to RFC staff, but after content gets added, have a review and discussion around whether the wiki could be made public.  This is the purpose of the requested repository.  

We are still determining whether we will use the built in wiki functionality that comes with the wiki, or the github pages / Jeykll functionality.  Not sure yet.

## Step 1
Make sure no duplicated request exists, search here: - No other duplicate requests exist
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - platformservicesteam@gov.bc.ca

* Project Name: River Forecast Wiki
* GitHub Org: private
* Details on choosing private repo: See above section - Background on request
* Preferred name for repo: nr-rfc-wiki
* Expected date to move to public: Undetermined
* GitHub ID for repo owner: @franTarkenton 
* GitHub Account 2FA Confirmed: yes
* Email address: kevin.netherton@gov.bc.ca
* Organization: River Forecast Center (Ministry of Forests)
* Project Role: Technical Lead
* GitHub Team to Join (if exists): @bcgov/rfc

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
HI @franTarkenton 

I've created the repo at https://github.com/bcgov-c/nr-rfc-wiki. I have made you an admin so you can add users to the repo. I have not associated it with the @bcgov/rfc team as that exists in the bcgov organization. Please let me know if you would like a team setup in the private organization.

Cheers,

Monica

**Comment by franTarkenton** [comment]
Thanks @MonicaG appreciated... 

We can do the user admin ourselves as the team is small.  Thanks again we are good to go...

cheers

Kevin
