### ISSUE TITLE
Request to remove a Zelda team member's access to Openshift and BCGOV GitHub Organization membership

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#1497]
## Removing Access

If you are removing access please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?** Yes, I'm the devops specialist in Zelda team
If not, you need to ask your team's Technical Lead role to make this request on your behalf. 
This person must already be a member of the bcgov GitHub Organization in order for us to process this request.

If you are a technical lead and you've come here to request access for yourself, please go ahead and create this ticket, and then 
email platformservicesteam@gov.bc.ca with a link to the ticket so the team can approve it.

### Step 2
Fill out the following fields

* Project Name: Zelda Team
* Technical Lead Github ID: kuanfandevops
* GitHub Org: bcgov, BCDevops, or private, Openshift
* GitHub ID: @vibhiquartech
* Reason for removal: Vibhi is not contracting to us any more

**Note** that the Platform Services Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Removed from BCGov and BCDevOps orgs. This will remove their access to RocketChat and OpenShift.
