### ISSUE TITLE
SonarCloud token request for nr-compliance-enforcement

### ISSUE THREAD

**Issue by barrfalk** [BCDevOps/devops-requests#1498]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
Yes (https://github.com/bcgov/nr-compliance-enforcement)

**Are you the admin user of the GitHub repositories?**
Yes (user barrfalk)

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Compliance and Enforcement Digital Services
* GitHub repositories to add to SonarCloud: 
- https://github.com/bcgov/nr-compliance-enforcement
- 

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by MonicaG** [comment]
Added nr-compliance-enforcement to sonar cloud. Github userid barrfalk was granted admin privileges for the project. They should be able to add/remove users to the project.
