### ISSUE TITLE
bcgov-c membership request for NicoledeGreef

### ISSUE THREAD

**Issue by NicoledeGreef** [BCDevOps/devops-requests#1499]
**Are you the Technical Lead?**
I am the Product Owner for MFIN-Data-Catalogue.  The Technical Lead is a vendor at the moment.

**Do you have a private repository already?**
Yes

### Step 2
Done

**Comment by ShellyXueHan** [comment]
@NicoledeGreef I've invited you to bcgov-c now. Also changed the project to be public!

**Comment by NicoledeGreef** [comment]
Thank you @ShellyXueHan
