### ISSUE TITLE
Request for BCGOV GitHub Organization Membership

### ISSUE THREAD

**Issue by itchison** [BCDevOps/devops-requests#15]
## Step 0

**Are you a member of the BCGOV GitHub Organization already?**
Yes

**Do you actually need the team member to be a member of the organization?**
Yes - mostly for rocketchat

**Are you the admin of your project's BCGOV GitHub Repository?**
Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name:  PRIME
* GitHub Org: bcgov
* Full Name: Pilar Guinea
* GitHub ID: @ pilarguinea
* GitHub Account 2FA Confirmed: yes
* Email address:  Pilar.Guinea@nttdata.com
* Organization:  MoH / Sierra Systems Group
* Project Role: UX Designer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@itchison invitation sent. For Rocketchat access, they could be invited by email with https://reggie.pathfinder.gov.bc.ca in the future.

**Comment by itchison** [comment]
@ShellyXueHan 

>  For Rocketchat access, they could be invited by email with https://reggie.pathfinder.gov.bc.ca in the future.

Really? I can invite github accounts via reggie without the account belonging to a bcgov organization?

**Comment by ShellyXueHan** [comment]
yes you can invite the user by the email (it has to match the GitHub email) while the user does not need to be a bcgov member.
