### ISSUE TITLE
Request to create a new sonar project for forest client

### ISSUE THREAD

**Issue by paulushcgcj** [BCDevOps/devops-requests#1500]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

    yes it is

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

    yes I am

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name:  Forest Client Processor
* GitHub repositories to add to SonarCloud:  https://github.com/bcgov/nr-forest-client  (but just the **/processor** folder)

    Same was done to the **forest-client-backend** and **forest-client-legacy** application on [this sonar repo](https://sonarcloud.io/project/information?id=forest-client-backend). This repository is a monorepo.

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

Other team members would be @DerekRoberts @brunoMarchiEncora @mamartinezmejia

**Comment by paulushcgcj** [comment]
Any news regarding this request? Been waiting since May 5th.

**Comment by NickCorcoran** [comment]
Added nr-forest-client-processor to monorepo.  Granted admin to @paulushcgcj and @DerekRoberts.  If that works let me know and I will close.  If you need something more done on my side, also let me know.

**Comment by paulushcgcj** [comment]
Perfect, thanks @NickCorcoran
