### ISSUE TITLE
Request a Project's visibility to be Public

### ISSUE THREAD

**Issue by NicoledeGreef** [BCDevOps/devops-requests#1502]
## Step 1
Done

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** 
Set a Project to be Visible in bcgov or bcgov-c Orgs

3. **Why should this be a new request type?** 
Repo admins encounter a blocker because they cannot set visibility of a Project they created to Public

4. **What information is required to fulfill this request?** 
The subject Project URL which includes the Org already: 
e.g. https://github.com/orgs/bcgov/projects/40/

5. **What is the end result?** 
The Visibility of the Project is set to Public rather than Private (see screenshot of blocker to non-Org owners).

![image](https://github.com/BCDevOps/devops-requests/assets/26335003/3ed01fec-0868-478f-a5db-7c0498b85b29)

**Comment by MonicaG** [comment]
Project changed from private to public.
