### ISSUE TITLE
gba_jeometry and gba_revolsys admin access

### ISSUE THREAD

**Issue by pauldaustin** [BCDevOps/devops-requests#1503]
## Step 2
Provide a detailed explanation of the steps which caused your repo to lose all admin users.

I moved 2 repositories from bcgov-geobc org which I am the owner of to the bcgov org. I moved rather than creating new then import as we have forks that I wanted to maintain the links to the moved repository.

## Step 5

bcgov/gba_jeometry
bcgov/gba_revolsys

You will see that I am the committer on these repositories

Thanks,
Paul

**Comment by MonicaG** [comment]
Hi @pauldaustin 

Do you want just yourself as the admin or use the [GEOBC-ADMIN](https://github.com/orgs/bcgov/teams/geobc-admin) team as admins? Thank you!

**Comment by MonicaG** [comment]
Added GEOBC-ADMIN as admin access to both bcgov/gba_jeometry and bcgov/gba_revolsys
