### ISSUE TITLE
private repo gba

### ISSUE THREAD

**Issue by pauldaustin** [BCDevOps/devops-requests#1504]
## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3

I would like to transfer ownership rather than create an existing repository from bcgov-geobc/gba to bcgov/gba. I can add you as an admin on the bcgov-geobc/gba project to facilitate this.

I have sent the private details to platformservicesteam@gov.bc.ca

**Comment by MonicaG** [comment]
Hi @pauldaustin - would you please add me to the bcgov-geobc/gba to transfer ownership. Thank you!

**Comment by MonicaG** [comment]
Repo transferred to bcgov-c. I've made @pauldaustin an admin on the repo. You will be able to add other users and setup a team as necessary.
