### ISSUE TITLE
Letourneau - Request - Private GitHub Organization Membership

### ISSUE THREAD

**Issue by daneletourneau** [BCDevOps/devops-requests#1505]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request on your behalf.

**Do you have a private repository already?**
If your team has the private repo already, please list it in the next step. If not, please request for the repo first!

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - platformservicesteam@gov.bc.ca

* Project Name: Indicator Data Pipeline
* GitHub Org: private
* GitHub ID for the team members: @daneletourneau
* GitHub Account 2FA Confirmed: yes
* Email address: letourneau.dane@gmail.com, dane.letourneau@gov.bc.ca 
* Organization: Population & Performance Data Team, Performance, Partnerships & Methodologies Branch, Health Sector Information, Analysis and Reporting Division | Ministry of Health
* Project Role: Senior Data Analyst
* GitHub Team to Join (if exists): kelvin.li@gov.bc.ca

**Note** that the Platform Services Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Invitation sent
