### ISSUE TITLE
Request from Pathfinder SSO

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#1517]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
I'm the product owner

**Do you have a private repository already?**
If your team has the private repo already, please list it in the next step. If not, please request for the repo first!
Yes

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - platformservicesteam@gov.bc.ca
sending via rocketchat

**Comment by MonicaG** [comment]
done, please let me know if they are not able to access the repo
