### ISSUE TITLE
SonarCloud Monorepo: nr-forests-access-management

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1519]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

Project Name:
bcgov/nr-forests-access-management

GitHub repositories to add to SonarCloud:
https://github.com/bcgov/nr-forests-access-management

Please set up a monorepo with these components:
- frontend
- backend
- auth

Notes:
- @NickCorcoran has been very helpful/knowledgeable with this in the past.
- I made this request for the wrong repo (bcgov/nr-fam-idim-lookup-proxy) and will delete those projects if recommended.  See https://github.com/BCDevOps/devops-requests/issues/1518

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ConradBoydElliottGustafson** [comment]
@NickCorcoran @DerekRoberts I don't understand the monorepo setup (yet) but I'm sure we don't need or want it for nr-fam-idim-lookup-proxy. Could the scope for this issue include cleaning that one up?

**Comment by DerekRoberts** [comment]
@ConradBoydElliottGustafson That's been mentioned in the issue/ticket body.  I can delete projects, but want to let this team have first crack at a solution.  They may want to rename rather than replace, but (hopefully a short amount of) time will tell.

**Comment by NickCorcoran** [comment]
I'll see what I can figure out.  @DerekRoberts @ConradBoydElliottGustafson

**Comment by NickCorcoran** [comment]
@DerekRoberts @ConradBoydElliottGustafson I have created the mono-repo for the requested project.  You can manage access to each of the separate pieces here:
https://sonarcloud.io/project/roles?id=nr-forests-access-management_frontend
https://sonarcloud.io/project/roles?id=nr-forests-access-management_backend
https://sonarcloud.io/project/roles?id=nr-forests-access-management_auth

I also deleted the _frontend, _backend and _auth for https://github.com/BCDevOps/devops-requests/issues/1518
