### ISSUE TITLE
JIRA# - CCSSRED-1602 - AG/PSSG – Request for private bcgov-c repo

### ISSUE THREAD

**Issue by pbolduc** [BCDevOps/devops-requests#1529]
Hello Platform Services Team, an email will follow with required details. 

This is a request to:
[x] Create a private repo
[ ] Remove a private repo and go public

Please note, we want to import existing git repositories, so the the new repositories must not be initialized with a README or other files.

Thank you,

Phil Bolduc

**Comment by MonicaG** [comment]
Repos created as per email
