### ISSUE TITLE
Set Parks Data Register GitHub Project to Public

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1530]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!
3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
4. **What is the end result?** Please provide plenty of details about what the end result should look like.

Answers:
1. Please set the project for Parks Data Register to public.
2. It's something we don't have permission to do.
3. Just the links below.
4. Project will be publicly viewable.

Repo:
https://github.com/bcgov/parks-data-register

Project:
https://github.com/orgs/bcgov/projects/49/views/2

cc: @ashley-dhillon

**Comment by MonicaG** [comment]
I have made the project public. Anyone is able to view it.
