### ISSUE TITLE
AG/PSSG - CCSSRED-1606 - Add user to BCGOV-C org

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1531]
Hello Platform Services team,

AG Jira ticket CCSSRED-1606

A separate email will follow with the required details to add a user to the BCGOV-C org.

Thank you,
Zubin Akolawala
AG/PSSG - ISB 
Application Management

**Comment by MonicaG** [comment]
User added as per details in email
