### ISSUE TITLE
sonar cloud request for fin-pay-transparency

### ISSUE THREAD

**Issue by sukanya-rath** [BCDevOps/devops-requests#1534]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** yes 
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Pay Transparency
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/fin-pay-transparency
- This is a mono repo. We need to analyze both backend and frontend. They are on TypeScript/JavaScript stack.

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by oomIRL** [comment]
@sukanya-rath Hi,
I need a couple of additional details to complete this setup in SonarCloud. For monorepos project keys are required to uniquely identify different projects within the repo, so something like "fin-pay-transparency_backend".  


Also, SonarCloud just adding a new setting for defining "New Code". New code can be either defined as code that has changed since the previous version, or code that has changed in the last x days. More can be found [here](https://docs.sonarcloud.io/improving/new-code-definition/)

**Comment by sukanya-rath** [comment]
Hi @oomIRL ,
Thanks for the quick response.
1. Yes, we would go with `fin-pay-transparency_backend` and `fin-pay-transparency_frontend`
2. we would like the definition of `New Code` as `that has changed since the previous version`

**Comment by oomIRL** [comment]
I've setup the following projects:
- Pay Transparency Backend - Project key: fin-pay-transparency_backend
- Pay Transparency Frontend - Project key: fin-pay-transparency_frontend

@sukanya-rath you've been setup with admin permissions for both projects.

Please let me know if there are any issues.
