### ISSUE TITLE
Request Sonar Cloud

### ISSUE THREAD

**Issue by jazzgrewal** [BCDevOps/devops-requests#1537]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** Yes
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** Yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: SILVA Web Application
* GitHub repositories to add to SonarCloud: nr-silva-webapp
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/))

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by MonicaG** [comment]
@jazzgrewal - please let me know how you want the code definition set for the project. Please refer to [sonar cloud's documentation](https://docs.sonarcloud.io/improving/new-code-definition/) for info on the setting.

**Comment by DerekRoberts** [comment]
@MonicaG Lots going on here!  Please help with:
- Definition: previous version
- Monorepo: frontend and backend (backend on the way)
- New repo name: bcgov/nr-silva (https://github.com/bcgov/nr-silva)

Note: Collaborating with @jazzgrewal (but sorry for stepping on your toes!)

**Comment by DerekRoberts** [comment]
Because we made such a mess of this request the associated projects are bound to the wrong repository.  Currently being addressed by @MonicaG.

**Comment by MonicaG** [comment]
@DerekRoberts - should be fixed now. I used the same keys as before and gave both you and @jazzgrewal  admin permissions
