### ISSUE TITLE
AG/PSSG - AGMT-1535 - Add members to BCGOV-C (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1538]
Hello Developer Experience Team, 

An email will follow with the required details to add members to the bcgov-c (private) space.

Thank you,
Zubin Akolawala
AG ISB Application Management

**Comment by MonicaG** [comment]
@ag-pssg-isb-sa - I've invited the team members as requested in the email.
