### ISSUE TITLE
FOI Modernization - SonarCloud

### ISSUE THREAD

**Issue by m-prodan** [BCDevOps/devops-requests#1540]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Yes - all of our repos are a part of BCGov Org**

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

**I am an admin of our repo, and I have made an account on sonar cloud.**

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

Done (m-prodan)

## Step 2
Fill out the following fields

* Project Name: FOI Modernization Project
* GitHub repositories to add to SonarCloud:
1. https://github.com/bcgov/foi-flow
2. https://github.com/bcgov/foi-docreviewer
3. https://github.com/bcgov/foi-help
4. https://github.com/bcgov/foi-requests

* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/))
New Code Definition - Previous Version

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by MonicaG** [comment]
Hi @m-prodan 

Repos foo-flow and foo-requests were already setup. I added foi-docreviewer and foi-help. I gave you admin permissions on all 4 repos.

Cheers,
Monica
