### ISSUE TITLE
Please add our new project to Github Repository

### ISSUE THREAD

**Issue by Harry0589** [BCDevOps/devops-requests#1542]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** yes
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: 
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/EDUC-SDCI
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/)) we have added the definition.

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by MonicaG** [comment]
Hi @Harry0589,

Please let me know what "New Code Definition" you would like for the project. The options are "Previous Version" and "Number of days". Please refer to [SonarCloud's documentation](https://docs.sonarcloud.io/improving/new-code-definition/) for more details on these options.

Thanks

**Comment by Harry0589** [comment]
@MonicaG Number of days.
