### ISSUE TITLE
AG/PSSG - SCTASK0154683 - Remove user from bcgov, bcdevops, and bcgov-c orgs. 

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1546]
Hello Developer Experience Team,

An email will follow with the required details to remove a user from bcgov, bcdevops, and bcgov-c orgs. 

Thank you,
Zubin Akolawala
AG ISB Application Management

**Comment by MonicaG** [comment]
User removed as per email. Thank you for letting us know they are no longer part of the organization.
