### ISSUE TITLE
Request for Admin Add to SonarCloud project (MOH-PIDP)

### ISSUE THREAD

**Issue by rshourou** [BCDevOps/devops-requests#1552]
## Step 1

I have admin access to moh-pidp GitHub Repository and the repo has been imported on SonarCloud and it's running for every PR. However, we want to to change the automatic analysis setting to only scan the code once is merged to the main branch, not for every PR. I need an admin access to the project in SonarCloud as well as as request #1548 .

**Comment by MonicaG** [comment]
HI @rshourou 

I have given you access
