### ISSUE TITLE
Disable Automatic Analysis for bcgov_moh-pidp project in SonarCloud

### ISSUE THREAD

**Issue by rshourou** [BCDevOps/devops-requests#1553]
1. **The automatic analysis is not working and SonarScanner doesn't scan the codes for new PRs** 
2. **I would like to enable CI-based analysis to integrate scanning into builds/pipelines** 
3. **Please disable automatic analysis for sonar.projectKey=bcgov_moh-pidp**

**Comment by rshourou** [comment]
https://community.sonarsource.com/t/last-analysis-failed-analysis-id-ayqz53n30vnbeurjiehg/99665?u=rshourou


ALM used (GitHub)
Automatic Analysis for .NET
Languages of the repository (c#, typescript, css)
URL : [moh-pidp - Province of British Columbia (sonarcloud.io)](https://sonarcloud.io/project/information?id=bcgov_moh-pidp)

For this project, the Automatic Analysis for .NET is enabled and  .sonarcloud.properties file exists in the root directory of the project. However, I am not getting any scans at all. PRs don’t trigger it, and merges in to “main” don’t trigger it.

.sonarcloud.properties file is in the root directory of the project and sonar.sources and sonar.test is as following:

sonar.sources= workspace/apps,workspace/libs,backend/services.plr-intake/Data/,backend/services.plr-intake/PlrIntakeConfiguration.cs,backend/services.plr-intake/Program.cs,backend/webapi/Extensions/,backend/webapi/Models/,backend/web-api/PidpConfiguration.cs,backend/webapi/Program.cs,backend/webapi/Startup.cs

sonar.tests=workspace/jest.config.ts,workspace/jest.preset.js,backend/webapi.tests,backend/services.plr-intake.tests,backend/utilities.plr-manual-intake.tests

**Comment by MonicaG** [comment]
Hi,

I took a quick look at the .sonarcloud.properties file in the moh-pidp repo. I noticed the `sonar.projectName=pidp` but the project in Sonar Cloud is `moh-pidp`. Maybe try:

- change line to `sonar.projectName=moh-pidp`
- It may also be `sonar.projectName=bcgov_moh-pidp` as that is the project key (https://sonarcloud.io/project/information?id=bcgov_moh-pidp)

**Comment by rshourou** [comment]
I changed the project name to sonar.projectName=bcgov_moh-pidp and it  doesn't scan any codes. 0 New Lines

**Comment by rshourou** [comment]
Please take a look at https://sonarcloud.io/summary/new_code?id=bcgov_moh-pidp&pullRequest=363

**Comment by rshourou** [comment]
following is the screenshot of the .sonarcloud.properties file in the root directory of the project. Although, package.json is in ./workspace folder and I am scanning the code in different folders as specified in sonar.sources.

![image](https://github.com/BCDevOps/devops-requests/assets/52804311/cc0dff43-31f1-408d-9b16-3fd83ab48e8a)

**Comment by MonicaG** [comment]
It looks like it progressed with the sonar cloud file removed. Although it now has a "The last analysis has failed. See details" message. Maybe follow up in the community forums as suggested in the "details" link?

**Comment by rshourou** [comment]
The scan is passed without sonarCloud.properties file, although it doesn't identify any line of codes

**Comment by rshourou** [comment]
Can you please de-activate automatic analysis to try CI-based analysis. It might resolve the issue

**Comment by MonicaG** [comment]
I've turned off automatic analysis

**Comment by rshourou** [comment]
What's the concept of 0 new lines? Does the scanner compare the files with the main branch for every new PR?

**Comment by MonicaG** [comment]
Where are you seeing 0 new lines?

**Comment by MonicaG** [comment]
Hi @rshourou - just following up on this. Did you get this working? Is there anything you need from us?

**Comment by rshourou** [comment]
Hi @MonicaG , yes thank you so much for your assistance
