### ISSUE TITLE
SonarCloud Monorepo for bcgov/nr-results-exam - backend, frontend

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1554]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: NR RESULTS Exam
* GitHub repositories to add to SonarCloud: bcgov/nr-results-exam
* New Code Definition: Previous version
* Monorepo:
  * backend
  * frontend

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by MonicaG** [comment]
@DerekRoberts - what value would you like for the New Code Definition: "Previous version" or "Number of days"?

Please refer to [SonarCloud's documentation](https://docs.sonarcloud.io/improving/new-code-definition/) for more details on this field.

**Comment by DerekRoberts** [comment]
> @DerekRoberts - what value would you like for the New Code Definition: "Previous version" or "Number of days"?
> 
> Please refer to [SonarCloud's documentation](https://docs.sonarcloud.io/improving/new-code-definition/) for more details on this field.

Previous version please.  Sorry, I didn't realize you were serious, since we can set this ourselves.

Answer/description edited.

**Comment by MonicaG** [comment]
I've setup the mono repo project:
[nr-results-exam-backend](https://sonarcloud.io/project/overview?id=nr-results-exam-backend)
[nr-results-exam-frontend](https://sonarcloud.io/project/overview?id=nr-results-exam-frontend)


The interface doesn't let me create a new project without specifying a New Code Definition.

**Comment by DerekRoberts** [comment]
@MonicaG I don't see to have admin over those two projects.  Please verify?

**Comment by MonicaG** [comment]
@DerekRoberts - sorry about that, should be fixed now
