### ISSUE TITLE
admin access for https://github.com/bcgov/eao-nginx? 

### ISSUE THREAD

**Issue by saravanpa-aot** [BCDevOps/devops-requests#1564]
## Step 0

**DO NOT OPEN A TICKET UNLESS THERE ARE NO ADMINS ASSIGNED TO THE REPO IN QUESTION**
If your repo has an admin, please ask them to provide you with the access you need. This ticket is for the **rare** case in which a repo loses all of its admins - this can occasionally happen when moving repos between different owners. If you have not moved the repo in question to bcgov recently, then this ticket probably does not apply to you. 

**If you open a ticket here and there is an admin user assigned to that repo, this ticket will be closed without action.**

Dont know who is the admin and there is no way to know this.
For EAO , we need a PR to be merged in.

**Are you the Technical Lead?**
Only a team's technical lead or product owner may request admin access to a repo. This information will be verified with Project Registry.

**Are you a member of the BCGOV org?**
If not, you'll need to be added as member first. Please open a ticket for that, and then come back here once that's finished!
Yes

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Provide a detailed explanation of the steps which caused your repo to lose all admin users.

Not a very active repo.This was one of the oldest project .Last commit was 2020.Because of some issues , we need to do a new build with a code change.No way to merge a Pull Request now.

## Step 5
Provide the **name of the admin-less repo** and any other details that may be necessary for us to fix the issue.

https://github.com/bcgov/eao-nginx

Please note that this ticket may take some time to action - we need to ensure that we are providing admin access to the correct user. Keep a close eye on the comments as the team will likely have more questions for you!

**Comment by MonicaG** [comment]
Closing ticket as repo has admins. Send an email to developer experience team with additional information if you need further help.
