### ISSUE TITLE
JIRA#  JPP-181 AG/PSSG – Request for private bcgov-c repo

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1568]
Description:  Hello Developer Experience Team, an email will follow with  required details. 

This is a request to:

[x] Create a private repo
[ ] Remove a private repo and go public

Thank you,
Ian Kinnon
AG ISB Application Management

**Comment by MonicaG** [comment]
Repo added as per email
