### ISSUE TITLE
Request for OpenShift Project set for Truck Route Planner (TRP)

### ISSUE THREAD

**Issue by NicoledeGreef** [BCDevOps/devops-requests#157]
## Step 0
**Are you the product owner or technical lead?**
Yes; Product Owner.

**Have you had an alignment meeting?**
For other apps.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
[x] Create a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name:   OCIO, DSSB (DataBC)
* Product Short Name: TRP
* Product Full Name:  Truck Route Planner
* Product Description:  The Truck Route Planner is a web mapping application built by DataBC for Translink.
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists):  https://github.com/bcgov/smk-tlink

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by ll911** [comment]
@caggles @NicoledeGreef @ShellyXueHan smk project set already exist under smk and managed by david kelsey
[dev](https://console.pathfinder.gov.bc.ca:8443/console/project/dbc-mapsdk-dev)
[test](https://console.pathfinder.gov.bc.ca:8443/console/project/dbc-mapsdk-test)
[prod](https://console.pathfinder.gov.bc.ca:8443/console/project/dbc-mapsdk-dev)
[tools](https://console.pathfinder.gov.bc.ca:8443/console/project/dbc-mapsdk-tools)

**Comment by NicoledeGreef** [comment]
request is for smk-tlink

**Comment by kelpisland** [comment]
Let’s find a time tomorrow @NicoledeGreef  got an alignment chat.

**Comment by NicoledeGreef** [comment]
thx - i am pretty open from 10 to 2:30 today.

**Comment by ShellyXueHan** [comment]
@NicoledeGreef please provide a complete list of the contact info, including RocketChat accounts (RC is the platform service's  main communication tool, where you will find alerts/notification/help).

**Comment by ShellyXueHan** [comment]
Project set created as `wvmyix-tools`, `wvmyix-dev`, `wvmyix-test`, `wvmyix-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Platform-Services-Security/Developer-Guide-to-Zero-Trust-Security-Model-on-the-Platform
