### ISSUE TITLE
Add Repos to Renovate App

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1574]
There are requests to add the following repos to the Renovate App.  Please approve!

- bcgov/nr-forest-client
- bcgov/nr-forest-client-api
- bcgov/nr-forest-client-commons

![Screenshot_20231109_145607](https://github.com/BCDevOps/devops-requests/assets/4391600/f4ae9197-0dbc-4af2-82d2-cb9e399b3b64)

BC on Mend.io
https://developer.mend.io/github/bcgov

**Comment by MonicaG** [comment]
The repos have been given access to the Renovate app
