### ISSUE TITLE
Add Repos to Renovate App

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1575]
There are requests to add the following repos to the Renovate App. Please approve!

- bcgov/nr-old-growth
- bcgov/nr-silva
- bcgov/nr-spar
- bcgov/nr-results-exam
- bcgov/nr-oracle-service

BC on Mend.io
https://developer.mend.io/github/bcgov

**Comment by MonicaG** [comment]
The above apps have been given access to the app. Cheers!
