### ISSUE TITLE
SonarCloud Monorepo for bcgov/onroutebc - frontend, dops, vehicles

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1578]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: OnRouteBC
* GitHub repositories to add to SonarCloud: bcgov/onroutebc
* New Code Definition: Previous version
* Monorepo:
  * frontend
  * dops
  * vehicles

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

cc: @cberg-aot

**Comment by oomIRL** [comment]
Hi @DerekRoberts 

I setup the following projects, and gave you admin permissions:

frontend => onroutebc_frontend
dops => onroutebc_dops
vehicles => onroutebc_vehicles

Let me know if anything else is required.
