### ISSUE TITLE
Access for CAP team to Azure OpenShift cluster

### ISSUE THREAD

**Issue by ActionAnalytics** [BCDevOps/devops-requests#158]
## Step 0
**Are you the product owner or project admin?**
Project Admin

**Do you have a GitHub account?**
Yes, all team members listed below have GitHub accounts

**Do you have 2-factor-authentication enabled with your GitHub account?**
Confirmed yes to all

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Stuart Cayzer
* GitHub ID: @scayzer
* Business Email Address: stuart.cayzer@gov.bc.ca
* Organization: OCIO
* Project Role: Product Owner
* OpenShift Projects/Namespaces: we need a standard set in the usual license plate format: xyz123-tools, xyz123-dev, xyz123-test, xyz123-prod

* Full Name: Julian Subda
* GitHub ID: @ActionAnalytics
* Business Email Address: julian.subda@gov.bc.ca
* Organization: OCIO
* Project Role: Admin
* OpenShift Projects/Namespaces: we need a standard set in the usual license plate format: xyz123-tools, xyz123-dev, xyz123-test, xyz123-prod

* Full Name: Mike Han
* GitHub ID: @mikeyhan1
* Business Email Address: mike.han@gov.bc.ca
* Organization: OCIO
* Project Role: Product Owner
* OpenShift Projects/Namespaces: we need a standard set in the usual license plate format: xyz123-tools, xyz123-dev, xyz123-test, xyz123-prod

* Full Name: Steven Shaw
* GitHub ID: @daveram
* Business Email Address: steve.shaw@gov.bc.ca
* Organization: OCIO
* Project Role: Developer
* OpenShift Projects/Namespaces: we need a standard set in the usual license plate format: xyz123-tools, xyz123-dev, xyz123-test, xyz123-prod

* Full Name: Clement Onawole
* GitHub ID: @murpheux
* Business Email Address: clement.onawole@gov.bc.ca
* Organization: OCIO
* Project Role: Developer
* OpenShift Projects/Namespaces: we need a standard set in the usual license plate format: xyz123-tools, xyz123-dev, xyz123-test, xyz123-prod

* Full Name: Andy Teppin
* GitHub ID: @ateppin
* Business Email Address: andy.teppin@gov.bc.ca
* Organization: OCIO
* Project Role: Developer
* OpenShift Projects/Namespaces: we need a standard set in the usual license plate format: xyz123-tools, xyz123-dev, xyz123-test, xyz123-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ActionAnalytics** [comment]
FYI @sheaphillips

**Comment by ShellyXueHan** [comment]
@ActionAnalytics please also make a request for the project set on Azure cluster.

**Comment by ShellyXueHan** [comment]
@ActionAnalytics all users have been invited to the azure-sandbox-user-team github team. If you haven't join the Github organization, accept the invitation first. The you should be able to login to the console with your GitHub account here: https://console-openshift-console.apps.ocp4lab.clearwater.devops.gov.bc.ca
