### ISSUE TITLE
Grant JIRA GitHub App Access to repos

### ISSUE THREAD

**Issue by rafasdc** [BCDevOps/devops-requests#1583]
## Step 0
**Do you have repos on bcgov GitHub Organization?**
If yes, please proceed with the request.

**If there is similar applications/tools available in the community, have you tried them out?**
There are many well supported community tools for various purposes, such SonarCube and BDDStack. 
Before you start with the new tools, have you consider trying out those that are available and widely adopted by the other application teams? 
If you have done so and do found that the existing ones does not match your need, please proceed.

**Have you tested out this GitHub application already?**
We understand that there are a lot of new and cool GitHub Applications out there that teams could like to try out. 
However, we cannot just enable the integration without evaluating the app, as those are open to all application teams. 
We believe you have tested out the GitHub apps and had good reasoning for the preference before making this request.

## Step 1
Please fill out the team and project info so we know how to contact you:

* Product Name: JIRA
* Team Name: Connectivity Division - Network BC
* GitHub Repositories on bcgov: 
- https://github.com/bcgov/CONN-CCBC-portal
- https://github.com/bcgov/conn-metabase
- https://github.com/bcgov/CONN-ClamAV-scan

## Step 2
Please provide details about the requested GitHub App. Take a look here for a [good example](https://github.com/BCDevOps/platform-services/issues/120/)

1. Brief introduction of the app: JIRA Software

2. General Criteria:
GitHub App is already added to org.

4. Comparison between Existing Tools Used by the Community
  - pros:
  - cons:

5. Relevant Resources and Links

Approval by org owner needed, message from JIRA: 

I want to connect the GitHub organization bcgov to the Jira site https://connectivitydivision.atlassian.net, and I need your approval as an organization owner.

If you approve, can you go to this link and complete the connection?

https://github.atlassian.com/spa/deferred?requestId=283a0a13-5a05-4fef-846a-c4ef55d1f238

**Comment by rafasdc** [comment]
Thanks @oomIRL . I can now see the bcgov repos on the JIRA project toolchain, but when attempting to connect to any of them I get the error "Failed to connect to GitHub repository" 

When I attempt to configure JIRA through either of the repos GitHub App Configure integration, or through JIRA directly I get the following screens: 

From JIRA:
![image](https://github.com/BCDevOps/devops-requests/assets/61289255/b3eeab30-1ede-411c-b5ec-542f6a09610c)

From the repos: 
<img width="787" alt="image" src="https://github.com/BCDevOps/devops-requests/assets/61289255/81d08a43-c2c2-4e0c-8e03-ab977632b320">

 
Any help would be greatly appreciated.

**Comment by oomIRL** [comment]
@rafasdc I failed to click the connection link initially.
Can you retry configuring?

**Comment by rafasdc** [comment]
Working perfectly, thank you so much!
