### ISSUE TITLE
Requesting a new private bcgov-c GitHub repository

### ISSUE THREAD

**Issue by chrislaick** [BCDevOps/devops-requests#1586]
## Step 0

**Are you looking to make a public repository?**
No.

**Are you a member of the private BCGOV GitHub Organization already?**
Yes.

**Are you sure you need to have your project code close-sourced?**
For the time being, it would be close-sourced with the end goal of becoming open-source once the product is stable and has the necessary open-source approvals from the organization.

**What date will you move your project to open-source?**
Start of April 2025

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
Done.

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca
Sent email.

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Repo created as per email. @chrislaick - you have been set as the administrator of the repo
