### ISSUE TITLE
CAP standard 4 project set on Azure cluster

### ISSUE THREAD

**Issue by ActionAnalytics** [BCDevOps/devops-requests#159]
## Step 0
**Are you the product owner or technical lead?**
Technical Lead

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.
Met with @sheaphillips 

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project
Visited

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
No dups

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: Cloud Adoption Patterns Azure
* Product Short Name: CAP Azure
* Product Full Name: Cloud Adoption Patterns Azure
* Product Description: OCIO team taking the EPIC application using non-PI generated data only to cloud deployments in order to generate quasi-realistic billing by simulating representative usage
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/cap-eagle-api

## Step 5
Submit this ticket and email us the contact information.
Submitting right after ticket

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

Will not do next steps as this is a temporary ephemeral deployment using mock data.  We understand that the Azure cluster will be reset frequently during this early stage and we will handle any rebuilds we need using our own resources.

* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
Project set created as `tnhlex-tools`, `tnhlex-dev`, `tnhlex-test`, `tnhlex-prod`. `ActionAnalytics` is the admin of all four namespaces.
Please check at https://console-openshift-console.apps.ocp4lab.clearwater.devops.gov.bc.ca.
