### ISSUE TITLE
AG/PSSG - MDYNAMICS-1449 - Add admin users/teams to repo

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1590]
Hello Developer Experience Team, 

We have located an 'orphaned' repo in bcgov, and the admin is unknown.  

Are you able to assist? Requesting to add the following teams and user accounts to this repo, with Admin privileges.

Repo: 

- https://github.com/bcgov/jag-digitalforms-client

Provide admin role to: 

- ag-pssg-nttdata (team)
- ag-pssg-isb (team)
- ag-pssg-isb-sa (people/user account)

Thank you,

Zubin Akolawala
AG/PSSG 
ISB 
Application Management Team

**Comment by oomIRL** [comment]
I setup the specified user & teams as admins.

Let me know if anything else is required!
