### ISSUE TITLE
CITZ IMB Jira Cloud Integration Request with BC GOV Github

### ISSUE THREAD

**Issue by abin-aot** [BCDevOps/devops-requests#1591]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
As part of grandfathering Zenhub(Project work dashboard) with our project, FOI Modernization. We are planning to migrate our tasks, issues, user stories to CITZ's JIRA cloud. Basically these are Github Issues even though we manage them using ZenHub.  So as part of that we connected with CITZ IMB, to move our task list to JIRA Cloud. From their team,  Alex Sharpe, John Dion provide us access to Jira . But to connect/integrate BC GOV repo with Jira, Github Org Owners  has to approve the request.

3. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? 
I am unable to find a request type from the list

5. **What information is required to fulfill this request?** Do your best here - the Developer Experience team can help if you're not sure!
Below is the message I am getting from jira application to pass to Github Org. owner . So could you please try this ? if not working, will you be able to get into a call and solve this

"I want to connect the GitHub organization bcgov to the Jira site https://citz-imb.atlassian.net, and I need your approval as an organization owner.

If you approve, can you go to this link and complete the connection?

https://github.atlassian.com/spa/deferred?requestId=cad76737-0c7a-4d60-a656-af842431e0ea   "

7. **What is the end result?** Please provide plenty of details about what the end result should look like.
I will be able to connect with BC Github Org and should be able to import issues from my various repos to CITZ IMB JIRA. These are my repos.
https://github.com/bcgov/foi-flow
https://github.com/bcgov/foi-docreviewer
https://github.com/bcgov/foi-requests
https://github.com/bcgov/foi-reporting
https://github.com/bcgov/foi-help

**Comment by MonicaG** [comment]
I've given access to the above repos to the existing GitHub Jira app installed in the bcgov organization. Please let me know if this does or does not work for you. If it doesn't work we can discuss the link you provided.

**Comment by MonicaG** [comment]
@abin-aot and I connected. We connected the repos with the link above. @abin-aot and team will work at integrating their GitHub repos and Jira.
