### ISSUE TITLE
Request to restore a backup Persistent Volume (PV) from OpenShift | Testing of DigitalGov backup/restore procedures

### ISSUE THREAD

**Issue by codewise-nicolas** [BCDevOps/devops-requests#1592]
## Restore a backup Persistent Volume (PV)
Please read through the documentation about [OCP4 Backup and Restore](https://developer.gov.bc.ca/OCP4-Backup-and-Restore) before proceeding with this request!

> Note that only the `netapp-file-backup` type of Persistent Volume can be restored from OpenShift.

### Step 1
Fill out the following fields

* Date: Dec 18, 2023
* Cluster: Silver
* Source PV: pvc-3a409b69-ac12-4238-9d2e-0afac0efc977/ai1wm-backups
* Destination PV: pvc-3a409b69-ac12-4238-9d2e-0afac0efc977/ai1wm-backups-restore

> Note that the Source and destination can be the same PVC or separate. You can specify sub-folders instead of the whole volume.

> Note: both PVC source and destination must be a netapp-file-backup PVC on the same cluster.
Check.

> Note that we need the PV not the PVC name. ie: `pvc-<uuid>`
Check.

**Comment by tbaker1313** [comment]
Submitted request for restore in RITM0168143 - it will be processed shortly.

**Comment by codewise-nicolas** [comment]
We grabbed the restored file and were able to follow the procedures and the backup worked perfectly.
Thank you very much @tbaker1313 and the team at BCDevOps.
