### ISSUE TITLE
Request for BCGOV-C Private GitHub Organization Membership

### ISSUE THREAD

**Issue by chrislaick** [BCDevOps/devops-requests#1597]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
Yes.

**Do you have a private repository already?**
Yes. (bcgov-c/cas-intranet)

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* GitHub ID for the team members: 
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

Thanks, will email these details to the email provided.

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Completed. Email sent with details.

**Comment by chrislaick** [comment]
@MonicaG I see that you've created new duplicate repository (https://github.com/bcgov-c/CASIntranet). As mentioned in Step 1 of the GitHub issue template, we already have our repository (https://github.com/bcgov-c/cas-intranet). I will go ahead and delete the duplicate repository.

**Comment by MonicaG** [comment]
@chrislaick - my apologies! I've emailed you. I've invited the members as requested and deleted the duplicate repo I created.

**Comment by chrislaick** [comment]
@MonicaG Thank you for your quick reponse!
