### ISSUE TITLE
Request - Draw.io App Integration with Github

### ISSUE THREAD

**Issue by ashley-dhillon** [BCDevOps/devops-requests#1598]
## Step 0
**Do you have repos on bcgov GitHub Organization?**
If yes, please proceed with the request.

**If there is similar applications/tools available in the community, have you tried them out?**
There are many well supported community tools for various purposes, such SonarCube and BDDStack. 
Before you start with the new tools, have you consider trying out those that are available and widely adopted by the other application teams? 
If you have done so and do found that the existing ones does not match your need, please proceed.

**Have you tested out this GitHub application already?**
We understand that there are a lot of new and cool GitHub Applications out there that teams could like to try out. 
However, we cannot just enable the integration without evaluating the app, as those are open to all application teams. 
We believe you have tested out the GitHub apps and had good reasoning for the preference before making this request.

## Step 1
Please fill out the team and project info so we know how to contact you:

* Product Name: BC Parks Data Register
* Team Name: Team Osprey
* GitHub Repositories on bcgov: https://github.com/bcgov/parks-data-register 

## Step 2
Please provide details about the requested GitHub App. Take a look here for a [good example](https://github.com/BCDevOps/platform-services/issues/120/)

1. Brief introduction of the app: 

Draw.io is an technology stack for building diagramming applications, and the world’s most widely used browser-based end-user diagramming software. 

We are specifically looking to allow authorization to drawio to integrate with our repository. Source code can be found here: [jgraph/drawio-github: Drawio GitHub Integration](https://github.com/jgraph/drawio-github?tab=readme-ov-file)

3. General Criteria:
  - How Easy / Fast / Repeatable is it to use and maintain for both Development Teams and Developer Experience Teams: It’s a single click to authorize. There is no need to maintain. 
  - Customizable: It’s a drawing tool. No need to customize. 
  - User Access Model: If you have access to the Github repo that has drawio integrated on, it should work for you
  - License: N/A
  - BCGov STRA: N/A
  - Price Model: Free

4. Comparison between Existing Tools Used by the Community
  - pros: Free to use compared to Figma. Faster to create technical diagrams. 
  - cons: None

5. Relevant Resources and Links
https://www.drawio.com/

**Comment by oomIRL** [comment]
Hi @ashley-dhillon 
I approved the Drawio app for the parks-data-register repo.
Let me know if anything else is required.
