### ISSUE TITLE
AG/PSSG - MDYNAMICS-1459 - Remove a user 's GitHub access

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1599]
Hi Developer Experience Team, 

An email will follow with the required details to remove a user from bcgov, bcgov-c and bcdevops.

Thank you,
Zubin Akolawala
ISB Application Management
AG/PSSG

**Comment by oomIRL** [comment]
The specified user has been removed from bcgov, bcgov-c and bcdevops.
