### ISSUE TITLE
Add BCeID to realm v4mbqqas

### ISSUE THREAD

**Issue by itchison** [BCDevOps/devops-requests#16]
## Step 0
Yes

**Do you have an IDIR account?**
Yes.  

**Are you requesting for Identity Provider Update?**
Yes

## Step 4
Fill out the following fields for IDP update:

* Project Name:  PRIME
* Realm ID:  v4mbqqas
* Admin of Realm: jaaitchi / jbaitchi Jason.B.Aitchison@gov.bc.ca Jason.Aitchison@nttdata.com (I already have admin on this realm)
* Identity Provider: BCeID

**Comment by ShellyXueHan** [comment]
First thing next Monday.

**Comment by ShellyXueHan** [comment]
@itchison you could now go create a request at https://realm-o-matic.pathfinder.gov.bc.ca To make it specific, name the realm request as `Add BCeID to realm v4mbqqas`. After obtaining IDIM's approval, I'll link the IDP to `v4mbqqas` realms.

**Comment by itchison** [comment]
@ShellyXueHan Do you mean that I should create a new realm request (that also gives me a new unique realm id)? I don't see where I'd name the realm request, unless I do that as the display name?

**Comment by ShellyXueHan** [comment]
yes, we don't have the feature on realm-o-matic yet. For now you could just start the request with the display name there, so that you could initiate the conversation with IDIM team. I'll manually link the IDP to your existing realm.

**Comment by ShellyXueHan** [comment]
@itchison BCeID has been enabled on dev and test realms. Production idp will be enabled (from both your realm and the IDP realm) once approved from IDIM.
