### ISSUE TITLE
Require sonar token for additional modules of mono repo fin-pay-transparency 

### ISSUE THREAD

**Issue by sukanya-rath** [BCDevOps/devops-requests#1604]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** `Yes`
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**` Yes`
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: `Pay Transparency`
* GitHub repositories to add to SonarCloud:`doc-gen-service` module in  [(https://github.com/bcgov/fin-pay-transparency)]
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field] - (https://docs.sonarcloud.io/improving/new-code-definition/)) -  `New Code` as that `has changed since the previous version`

* Issue to add the other modules was raised before [(https://github.com/BCDevOps/devops-requests/issues/1534)]

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by oomIRL** [comment]
Hi @sukanya-rath 
I added a new sonar cloud project for the fin-pay-transparency mono repo.
Project Name: Pay Transparency doc-gen-service
Project Key: fin-pay-transparency_doc-gen-service
You've been setup as an admin for the project

Let me know if anything else is required.
