### ISSUE TITLE
AG/PSSG - DIAM-71 - Create new repo in bcgov-c (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1607]
Hello Developer Experience Team,

A separate email will follow with the required details to create a new bcgov-c (private) repo and add members to it.

Thank you,
Zubin Akolawala
AG ISB Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 
The repo has been created.
