### ISSUE TITLE
Add ERA repository to sonarcloud

### ISSUE THREAD

**Issue by ytqsl** [BCDevOps/devops-requests#1608]
* Project Name: EMCR ERA
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/embc-ess-mod
* New Code Definition: 90 days

**Comment by oomIRL** [comment]
Hi @ytqsl 
The project has been created: https://sonarcloud.io/project/overview?id=bcgov_embc-ess-mod
You've been setup as the admin.

Let me know if anything else is required.
