### ISSUE TITLE
Please add SonarCloud to our project (HOUS Permit Portal)

### ISSUE THREAD

**Issue by derekyau** [BCDevOps/devops-requests#1610]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

Yes

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

Yes

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

Verified.

## Step 2
Fill out the following fields

* Project Name: HOUS Permit Portal
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/HOUS-permit-portal
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/)). Lets set this at the default for the time being (48 days)

Note that the file `.sonarcloud.properties` exists on this branch right now (`feature/BPHH-567/setup-sonarcloud`). Will merge this in with our gitflow when everything is verified to be setup properly.

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by oomIRL** [comment]
Hi @derekyau 
The new SonarCloud project has been created: https://sonarcloud.io/project/overview?id=bcgov_HOUS-permit-portal
You've been setup as an admin for the project.

Let me know if any followup is required.
