### ISSUE TITLE
admin access to https://github.com/bcgov/bc_freshwater_fish_habitat_accessibility_model

### ISSUE THREAD

**Issue by smnorris** [BCDevOps/devops-requests#1612]
## Step 0
confirmed

**Are you the Technical Lead?**
yes

**Are you a member of the BCGOV org?**
yes

## Step 1
confirmed

## Step 2
I transferred ownership of the repository from my personal account to the bcgov org - I did not know I would lose admin access to the repository.  Admin access is required to set up GHA build of gh-pages documentation, allow serving the docs on gh-pages, update the repo link, etc.

## Step 5
https://github.com/bcgov/bc_freshwater_fish_habitat_accessibility_model

Thanks!

**Comment by oomIRL** [comment]
Hi @smnorris 

I restored your admin access.

Let me know if anything else is required.
