### ISSUE TITLE
Add nr-omrr-transparency to Renovate App

### ISSUE THREAD

**Issue by mishraomp** [BCDevOps/devops-requests#1613]
Please add nr-data-hub to the Renovate GitHub App.

Product Name: OMRR Transparency
Team Name: OMRR
GitHub Repositories on bcgov: [nr-omrr-transparency](https://github.com/bcgov/nr-omrr-transparency)
cc: @DerekRoberts  @AmanBhathal

**Comment by MonicaG** [comment]
I've added [nr-omrr-transparency](https://github.com/bcgov/nr-omrr-transparency) repo to the renovate app
