### ISSUE TITLE
Renovate App - add quickstart-openshift-helpers

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1615]
Please add quickstart-openshift-helpers to the Renovate GitHub app.  Thanks!  :)

Product Name: QuickStart for OpenShift Helpers
Team Name: TBD
Repository: https://github.com/bcgov/quickstart-openshift-helpers
cc: @mishraomp

**Comment by oomIRL** [comment]
@DerekRoberts 
Added quickstart-openshift-helpers!
