### ISSUE TITLE
SonarCloud request for digital marketplace

### ISSUE THREAD

**Issue by bdolor** [BCDevOps/devops-requests#1617]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
yes

**Are you the admin user of the GitHub repositories?**
yes

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

yes, bcgov is the current org

## Step 2
Fill out the following fields

* Project Name: digital-marketplace
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/digital_marketplace
* New Code Definition: Previous version

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

will do!

**Comment by MonicaG** [comment]
HI @bdolor - I've added the repo https://github.com/bcgov/digital_marketplace to sonar cloud. I've made you an admin on the project so you can configure it and add other people as needed.
