### ISSUE TITLE
Add Nancy Zacharias to BCDevOps Group

### ISSUE THREAD

**Issue by charlottekelso** [BCDevOps/devops-requests#162]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Nancy Zacharias
* GitHub ID: @nancymz
* Business Email Address: nancy.zacharias@gov.bc.ca
* Organization: Sierra Systems / ISB
* Project Role: Developer
* OpenShift Projects/Namespaces: If Nancy is added to the BCDevOps group, we can add her to the OpenShift project ourselves.

Note: Chris Hoban is the technical architect for this project.

**Comment by caggles** [comment]
Nancy appears to already be a member of the org - if she's having problems logging in, please ask questions in #devops-how-to!
