### ISSUE TITLE
private repo

### ISSUE THREAD

**Issue by kmarshgov** [BCDevOps/devops-requests#1620]
## Step 0

**Are you looking to make a public repository?**
No

**Are you a member of the private BCGOV GitHub Organization already?**
This is our first private repo

**Are you sure you need to have your project code close-sourced?**
Yes, we are migrating from a private repo and need a staging private repo

**What date will you move your project to open-source?**
2024-08-01

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
No duplicate

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* Details on choosing private repo: 
* Preferred name for repo: 
* Expected date to move to public: MM/YYYY
* GitHub ID for repo owner: @
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
repo created as per email
