### ISSUE TITLE
Requesting Private repo in BCGOV-C 

### ISSUE THREAD

**Issue by vishreddy01** [BCDevOps/devops-requests#1624]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
Yes

**Do you have a private repository already?**
No 

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: NR Data Analytics Platform
* GitHub Org: bcgov-c ( private)
* GitHub ID for the team members: vishreddy01,abimichel,vikasgrover2,rparfig,danagerous
* GitHub Account 2FA Confirmed: yes 
* Email address: NRM.DataFoundations@gov.bc.ca
* Organization: NRIDS
* Project Role: 
* GitHub Team to Join (if exists): iit-arch/data foundations

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Email sent to [NRM.DataFoundations@gov.bc.ca](mailto:NRM.DataFoundations@gov.bc.ca) requesting additional info.

**Comment by MonicaG** [comment]
closing as it was not needed as argocd setup the required repo
