### ISSUE TITLE
AG/PSSG - CORNETJAM-6 - Create new bcgov-c repo

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1629]
Hi Developer Experience Team, 

An email will follow with the required details to create a new BCGOV-C repo 

Thank you,
Zubin Akolawala
AG/PSSG 
Application Management

**Comment by oomIRL** [comment]
Hi @ag-pssg-isb-sa 

The bcgov-c repo has been created and setup as specified.
