### ISSUE TITLE
Add bcgov/nr-hydrometric-rating-curve to Renovate GitHub App

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1630]
Please add this repository to the Renovate GitHub App.  Thanks!

https://github.com/bcgov/nr-hydrometric-rating-curve

cc: @mishraomp @tobiasmllr

**Comment by oomIRL** [comment]
@DerekRoberts 

Added nr-hydrometric-rating-curve to the Renovate app.

Let me know if anything else if required.
