### ISSUE TITLE
AG/PSSG - CDDS-176 - Add 1 user to BCGOV-C (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1634]
Hello Developer Experience Team, 

An email will follow with the required details to add 1 user to bcgov-c (private)

Thank you,
Zubin Akolawala
AG/PSSG 
Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 

A bcgov-c invite has been sent to the specified user.
