### ISSUE TITLE
AG/PSGS - EA-280 - Create 2 new bcgov-c (private) repos

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1635]
Hello Developer Experience Team,

An email will follow with the required details to create two (2) new bcgov-c (private) repos. 

Thank you,
Zubin Akolawala
AG/PSSG 
ISB Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 

The two bcgov-c repos have been created as specified.
