### ISSUE TITLE
AG/PSSG - EA-280 - Add 2 users to BCGOV-C (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1636]
Hi Developer Experience Team,

An email will follow with the required details to add 2 users to bcgov-c.

Thank you,
Zubin Akolawala
AG/PSSG 
ISB Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 

Invites have been sent to both users.
