### ISSUE TITLE
New Repository Request 

### ISSUE THREAD

**Issue by EAWright** [BCDevOps/devops-requests#164]
GitHub Repository Request:
- Project: RSBC DataHub
- Project description: This is a new repo for the RoadSafetyBC DataHub (formerly RSI BI) project source that will be used going forward instead of the current private RSI-BI repo
- Approver (bcgov-c): @Todd.Wilson
- Repo Owner GitHub ID: @jennifer-dowd

**Comment by ShellyXueHan** [comment]
@EAWright are you requesting to move the private repo to a public one?

**Comment by EAWright** [comment]
If that is possible, it’s easier to create a new one then by all means I can work with that.

Eric Wright

**Comment by jennifer-dowd** [comment]
Shelley - I would prefer private please

Sent from my iPhone

On Feb 12, 2020, at 5:29 PM, Eric Wright <notifications@github.com> wrote:

﻿If that is possible, it’s easier to create a new one then by all means I can work with that.

Eric Wright

**Comment by EAWright** [comment]
We currently have a private BI repository which, from conversation with Justin, Ryan and Todd it is preferred to have it on the public side since we don't have any secret sauce ingredients in our solution.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jennifer-dowd** [comment]
Hi Eric – understood however, until I know the implications of having things public, I would prefer private please. Thank you.

**Comment by jennifer-dowd** [comment]
Hi Shelly,

My apologies, Eric and I have discussed this further, we would like a public repo please.

Thank you
Jennifer

From: Dowd, Jennifer PSSG:EX
Sent: Wednesday, February 12, 2020 7:03 PM
To: 'BCDevOps/devops-requests' <reply@reply.github.com>; 'BCDevOps/devops-requests' <devops-requests@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [BCDevOps/devops-requests] New Repository Request (#164)

Hi Eric – understood however, until I know the implications of having things public, I would prefer private please. Thank you.

**Comment by ShellyXueHan** [comment]
@jennifer-dowd @EAWright are you requesting to transfer the private repo a public one in bcgov? If so, please provide the repository name.

**Comment by jennifer-dowd** [comment]
Greetings @Han, Shelly CITZ:EX<mailto:Shelly.Han@gov.bc.ca>,

I want to keep the -C BI repo for things that we want private, and have a new Data-API repo created. Can we call the new public report RSBC DataHub-API?


Cheers
Jennifer

**Comment by ShellyXueHan** [comment]
both of you could create repos in bcgov. lmk if you are having issues.

**Comment by jennifer-dowd** [comment]
Are there instructions on how to do that?
