### ISSUE TITLE
SonarCloud Mono Repo

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1642]
Please setup a SonarCloud monorepo project

* Project Name:  nr-data-hub
* GitHub repositories to add to SonarCloud: bcgov/nr-data-hub
* GitHub component/app: data-hub
* New Code Definition: Previous Version

NOTE: Please make this a monorepo even though we only have one component/app!  More are expected to be added using the same repository.

cc: @pinkyandthekane

**Comment by oomIRL** [comment]
@DerekRoberts 

I've added bcgov/nr-data-hub as a monorepo with one project: nr-data-hub
https://sonarcloud.io/project/information?id=nr-data-hub

And you've been setup as a project admin.

Please let me know if anything else required.
