### ISSUE TITLE
Need a private repo ASAP

### ISSUE THREAD

**Issue by jinchuantang** [BCDevOps/devops-requests#1643]
## Step 0

**Are you looking to make a public repository?**
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. 
If you still think your code needs to be private, please provide the details in the request.

We need to recover a system from a disastrous human mistake. We need to gain speed in order to get business back, we don't have time to scrape off all hardcoded credentials/passwords/tokens in short term. We plan to do that though after we restored the business application. We need this one year interim period, after that, we have no problem making this repo public.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. 
This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. 
Please include a firm date by which you will move your repository to the open organization.

We can go public as soon as we restored our system and scraped off all sensitive information from the repo. I don't think it would be that long but if you need a date, let's put 2024-12-31.
One question is that, if we go public, will the whole repo be made public somehow or we need to destroy it and recreate? We plan to do devops pipelines and if we're going to lose any runner that we create in that repo, then this is not the solution for us. 

If you feel you cannot move to open-source ever, we strongly encourage you to reconsider.
However, if you are certain that you require a fully closed-source repo permanently, you can speak to the team on RocketChat to discuss your options.
Using the private bcgov GitHub Organization may not be the appropriate solution for your team in this case.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: CIMS Portal(Contract Information Management System)
* GitHub Org: private
* Details on choosing private repo: We need to recover a system from a disastrous human mistake. We need to gain speed in order to get business back, we don't have time to scrape off all hardcoded credentials/passwords/tokens in short term. We plan to do that though after we restored the business application. We need this one year interim period, after that, we have no problem making this repo public. 
We can go public as soon as we restored our system and scraped off all sensitive information from the repo. I don't think it would be that long but if you need a date, let's put 2024-12-31.
One question is that, if we go public, will the whole repo be made public somehow or we need to destroy it and recreate? We plan to do devops pipelines and if we're going to lose any runner that we create in that repo, then this is not the solution for us, and don't create the repo.
* Preferred name for repo: cims-portal
* Expected date to move to public: 12/2024
* GitHub ID for repo owner: @jinchuantang 
* GitHub Account 2FA Confirmed: yes
* Email address: jack.tang@gov.bc.ca
* Organization: Ministry of Post-Secondary Education and Future Skills
* Project Role: Solution Architect
* GitHub Team to Join (if exists): psfs-imb-wdst

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
@jinchuantang 

I created a private repo in bcgov-c: https://github.com/bcgov-c/cims-portal
You've been setup as an admin.

Please let me know if anything further is required.
