### ISSUE TITLE
pvc-restore

### ISSUE THREAD

**Issue by ll911** [BCDevOps/devops-requests#1645]
## Restore a backup Persistent Volume (PV)
Please read through the documentation about [OCP4 Backup and Restore](https://developer.gov.bc.ca/OCP4-Backup-and-Restore) before proceeding with this request!

> Note that only the `netapp-file-backup` type of Persistent Volume can be restored from OpenShift.

### Step 1
Fill out the following fields

* Date: 2024-04-16
* Cluster: Silver
* Source PV: pvc-061faa4b-36e0-4ead-a372-11485f1f5727
* Destination PV: pvc-84874101-0458-4cb7-8890-82faa587380c\20240416

> Note that the Source and destination can be the same PVC or separate. You can specify sub-folders instead of the whole volume.

> Note: both PVC source and destination must be a netapp-file-backup PVC on the same cluster.

> Note that we need the PV not the PVC name. ie: `pvc-<uuid>`

**Comment by StevenBarre** [comment]
> Note that only the `netapp-file-backup` type of Persistent Volume can be restored from OpenShift.

`pvc-061faa4b-36e0-4ead-a372-11485f1f5727` is a `netapp-file-standard` volume, and is not backed up. It cannot be restored.
