### ISSUE TITLE
AG/PSSG - MDYNAMICS-1534 - Add 3 users to BCGOV-C (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1649]
Hello Developer Experience Team,

An email will follow with the required details to get 3 users added to bcgov-c (private).

Thank you,
Zubin Akolawala
AG/PSSG 
ISB Application Management

**Comment by MonicaG** [comment]
Hi!
 The people have been invited as per the email.

Cheers,
Monica
