### ISSUE TITLE
Request to grant OpenShift access for user Milan Meet Kaur

### ISSUE THREAD

**Issue by pwei1018** [BCDevOps/devops-requests#165]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Milan Meet Kaur
* GitHub ID: @Milan-Freshworks
* Business Email Address: milan@freshworks.io
* Organization: BC Registries
* Project Role:  QA
* OpenShift Projects/Namespaces: 
SBC-AUTH, SBC-PAY

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by pwei1018** [comment]
The invitation got expired. Can you please re-send the invitation link. Thanks.

**Comment by ShellyXueHan** [comment]
invitation sent.
