### ISSUE TITLE
AG/PSSG - MDYNAMICS-1529 - Add 1 user to BCGOV-C (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1650]
Hi Developer Experience Team,

An email will follow with the required info to add 1 member to bcgov-c (private)

Thank you,
Zubin Akolawala
AG/PSSG
ISB Application Management

**Comment by MonicaG** [comment]
Hi, the user has been invited as per the email

Cheers,
Monica
