### ISSUE TITLE
Add multiple nr-rfc repos to the Renovate GitHub App

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1653]
Please add the following RFC apps to the Renovate GitHub App.  Thanks!  :)

Update: list reduced as requested.

cc: @franTarkenton 

https://github.com/bcgov/nr-rfc-alertauthoring

https://github.com/bcgov/nr-rfc-climate-obs

https://github.com/bcgov/nr-rfc-dischargeobs

https://github.com/bcgov/nr-rfc-ensweather

https://github.com/bcgov/nr-rfc-grib-copy

https://github.com/bcgov/nr-rfc-processing

https://github.com/bcgov/nr-rfc-snowfrontend

**Comment by franTarkenton** [comment]
update, only these repos:

https://github.com/bcgov/nr-rfc-alertauthoring

https://github.com/bcgov/nr-rfc-climate-obs

https://github.com/bcgov/nr-rfc-dischargeobs

https://github.com/bcgov/nr-rfc-ensweather

https://github.com/bcgov/nr-rfc-grib-copy

https://github.com/bcgov/nr-rfc-processing

https://github.com/bcgov/nr-rfc-snowfrontend

**Comment by MonicaG** [comment]
I've added the above repos to renovate.
