### ISSUE TITLE
Request for BCGOV-C Private GitHub Organization Membership

### ISSUE THREAD

**Issue by ychung-mot** [BCDevOps/devops-requests#1655]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
Yes.

**Do you have a private repository already?**
Yes.  https://github.com/bcgov-c/tenant-gitops-b0471a

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* GitHub ID for the team members: 
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Users invited as per email
