### ISSUE TITLE
Integrating JIRA to Github Project 

### ISSUE THREAD

**Issue by sukanya-rath** [BCDevOps/devops-requests#1662]
## Step 0
**Do you have repos on bcgov GitHub Organization?** `Yes`
If yes, please proceed with the request. 

**If there is similar applications/tools available in the community, have you tried them out?**
There are many well supported community tools for various purposes, such SonarCube and BDDStack. 
Before you start with the new tools, have you consider trying out those that are available and widely adopted by the other application teams? 
If you have done so and do found that the existing ones does not match your need, please proceed.

**Have you tested out this GitHub application already?**
We understand that there are a lot of new and cool GitHub Applications out there that teams could like to try out. 
However, we cannot just enable the integration without evaluating the app, as those are open to all application teams. 
We believe you have tested out the GitHub apps and had good reasoning for the preference before making this request.

## Step 1
Please fill out the team and project info so we know how to contact you:

* Product Name:  Pay Transparency Reporting Tool
* Team Name:   [Fin-Pay-Transparency](https://github.com/orgs/bcgov/teams/fin-pay-transparency),[FIN_IMB_AMD](https://github.com/orgs/bcgov/teams/fin_imb_amd)
* GitHub Repositories on bcgov: https://github.com/bcgov/fin-pay-transparency

## Step 2
Please provide details about the requested GitHub App. Take a look here for a [good example](https://github.com/BCDevOps/platform-services/issues/120/) - Integrate Github with JIRA 

1. Brief introduction of the app: We want to integrate project JIRA with our Github project to be able to link the Stories with the PRs and improve our SDLC - particularly - release management process  https://finrms.atlassian.net/jira/software/projects/GEO/boards/70

2. General Criteria:
  - How Easy / Fast / Repeatable is it to use and maintain for both Development Teams and Developer Experience Teams: Easy
  - Customizable: Jira seems to provide the connection out of the box - needs approval from bcgov to connect to github repo
  - User Access Model: 
  - License:
  - BCGov STRA:
  - Price Model:

3. Comparison between Existing Tools Used by the Community
  - pros: Improving SDLC for our project 
  - cons: Using github issues is not an option

4. Relevant Resources and Links

**Comment by MonicaG** [comment]
Hi @sukanya-rath, I have added the Jira GitHub app to the https://github.com/bcgov/fin-pay-transparency repo.

Cheers,

Monica

**Comment by sukanya-rath** [comment]
@MonicaG  - When we try to connect Jira we get this to be approved by one of the Github bcgov owners - https://github.atlassian.com/spa/deferred?requestId=56251cc4-1f2d-427d-a2d3-24b4c9557351

**Comment by MonicaG** [comment]
@sukanya-rath - I've authorized it. Please let me know if it doesn't work. After authorizing it, it displayed the following documentation page. I'm passing along to you for your info: [Reference issues in your development work](https://support.atlassian.com/jira-software-cloud/docs/reference-issues-in-your-development-work/)
