### ISSUE TITLE
Request removal of access

### ISSUE THREAD

**Issue by pdittaro** [BCDevOps/devops-requests#1663]
* Project Name(s): 269007, a5cf88
* Technical Lead Github ID: unknown for 269007, @dhaselhan for a5cf88
* GitHub Org: bcgov, BCDevops
* GitHub ID: @pdittaro 
* Reason for removal:
No longer working on the platform. Happy to remain a member of the github orgs if that facilitates collaboration, but I have no need of access to internal resources.

**Comment by pdittaro** [comment]
Also, please update the platform email notifications for these resources to not be sent to my email address.

**Comment by MonicaG** [comment]
Hi @ShellyXueHan and @caggles - We've (@sheaphillips) removed @pdittaro from the bcgov and BCDevOps orgs. However, he is still listed in the registries. Can you remove him from there please. Thanks.

**Comment by MonicaG** [comment]
@ShellyXueHan and @caggles - bumping this issue. Can you please remove  @pdittaro from the registries. Thanks

**Comment by ShellyXueHan** [comment]
We don't manage project set access for teams, they need to make the update on Registry directly. For this case, I can see that Paul is still listed as technical lead for project `269007`. I'll let their PO know!
