### ISSUE TITLE
MDYNAMICS-1562 - AG/PSSG - Add 1 user to bcgov-c (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1664]
Hi Dev Experience Team, 

An email will follow with the required details to add 1 user to BCGOV-C (private).

Thank  you,
Zubin Akolawala
AG/PSSG ISB Application Management

**Comment by MonicaG** [comment]
Completed on May10. Forgot to close this issue at that time. Closing now.
