### ISSUE TITLE
Allow automation integration from Jira to Github

### ISSUE THREAD

**Issue by sukanya-rath** [BCDevOps/devops-requests#1665]
## Step 1
Make sure no duplicated request exists, search here: 
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do. ` We want to use automations available from Jira to Github integrations like create branch when issue is moved to inprogress and move issues to TEST once PR is merged`
2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead! - `Yes`
3. **What information is required to fulfill this request?** Do your best here - the Developer Experience team can help if you're not sure!
4. **What is the end result?** Please provide plenty of details about what the end result should look like.

Github code base : https://github.com/bcgov/fin-pay-transparency
Jira url : https://finrms.atlassian.net/jira/software/projects/GEO/boards/70
We want to automate our workflows. There was a request raised before to allow integration of our JIRA to Github but it doesn't seem to allow to add the automation of our workflows.
Previous request : https://github.com/BCDevOps/devops-requests/issues/1662

**Comment by MonicaG** [comment]
The automation workflow integration has been added
