### ISSUE TITLE
CBCCCM-1064 - AG/PSSG – Request for private bcgov-c repo

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1667]
Hello Developer Experience Team, 

An email will follow with required details to: 
[x] Create a private repo in the bcgov-c (private) org
[ ] Remove a private repo and go public

Thank you,

Rafiul Nion
AG ISB Application Management

**Comment by MonicaG** [comment]
Repo created as per email
