### ISSUE TITLE
Requesting admin access to github.com/bcgov/moh-fax 

### ISSUE THREAD

**Issue by MeganWeston** [BCDevOps/devops-requests#1669]
## Step 0

**DO NOT OPEN A TICKET UNLESS THERE ARE NO ADMINS ASSIGNED TO THE REPO IN QUESTION**
If your repo has an admin, please ask them to provide you with the access you need. This ticket is for the **rare** case in which a repo loses all of its admins - this can occasionally happen when moving repos between different owners. If you have not moved the repo in question to bcgov recently, then this ticket probably does not apply to you. 

**If you open a ticket here and there is an admin user assigned to that repo, this ticket will be closed without action.**

**CGI has attempted to be assigned admin, but since that team is not internal to BC gov, I am requesting admin access for myself**

**Are you the Technical Lead?**
**I am SAT product owner**

**Are you a member of the BCGOV org?**
**Yes**

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

**No dups**

## Step 2
Provide a detailed explanation of the steps which caused your repo to lose all admin users.

All admin access was provided to a previous contractor, and that entire company has left the project. I was never added as admin. We are now in operational phase, and now need internal admin access to manage this repo. 

## Step 5
Provide the **name of the admin-less repo** and any other details that may be necessary for us to fix the issue.
**github.com/bcgov/moh-fax**

Please note that this ticket may take some time to action - we need to ensure that we are providing admin access to the correct user. Keep a close eye on the comments as the team will likely have more questions for you!

**Comment by MonicaG** [comment]
@MeganWeston - I've added you as an admin to the repo.
