### ISSUE TITLE
sonar cloud request for nr-omrr-transparency

### ISSUE THREAD

**Issue by mishraomp** [BCDevOps/devops-requests#1670]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** yes
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Organics Info (ORI) 
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/nr-omrr-transparency
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/))
* This is a mono repo. We need to analyze both backend and frontend. They are on TypeScript/JavaScript stack.

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by mishraomp** [comment]
fyi @DerekRoberts @AmanBhathal @dawnbcgov

**Comment by MonicaG** [comment]
Hi @mishraomp - I've created [nr-omrr-transparency-backend](https://sonarcloud.io/project/overview?id=nr-omrr-transparency-backend) and [nr-omrr-transparency-frontend](https://sonarcloud.io/project/configuration?id=nr-omrr-transparency-frontend). I've made you an administrator so you can configure and add other people as needed.
