### ISSUE TITLE
AG/PSSG - MDYNAMICS-1596 - Add a user to BCGOV-C (private)

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1671]
Hello Developer Experience Team, 

An email will follow with the required details to add a user to BCGOV-C (private) org.

Thank you,
Zubin Akolawala
AG/PSSG - ISB 
Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 

An invite has been sent to the specified user.
