### ISSUE TITLE
SonarCloud Replace Old GWells Project

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1674]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Groundwater Wells and Aquifers
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/gwells
* New Code Definition: Previous Version
* Monorepo: 
  * frontend
  * backend

NOTE: There is already an existing project called [bcgov_gwells](https://sonarcloud.io/login?return_to=%2Fproject%2Froles%3Fid%3Dbcgov_gwells&error=authorization).  Please delete it?

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

cc: @fergmac

**Comment by oomIRL** [comment]
Hi @DerekRoberts 

I removed the previous bcgov_gwells project.

[gwells](https://github.com/bcgov/gwells) has been setup in SonarCloud as a monorepo:

- [gwells frontend](https://sonarcloud.io/project/overview?id=bcgov-gwells_frontend) Project key: bcgov-gwells_frontend
- [gwells backend](https://sonarcloud.io/project/overview?id=bcgov-gwells_backend) Project key: bcgov-gwells_backend
