### ISSUE TITLE
Requesting Access

### ISSUE THREAD

**Issue by jhughescomputronix** [BCDevOps/devops-requests#1677]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
Yes

**Do you have a private repository already?**
We do not have a private repo yet. will require one.

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

Requested! 

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Done! I've sent you an email
