### ISSUE TITLE
Please add the following GitHub repos to Sonar (these were there prior but seem to be removed)

### ISSUE THREAD

**Issue by arcshiftsolutions** [BCDevOps/devops-requests#1679]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

Yes.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

Yes.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

Yes.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: PEN
* GitHub repositories to add to SonarCloud: 

- https://github.com/bcgov/EDUC-MACRO-API
- https://github.com/bcgov/EDUC-PEN-REQUEST-API

* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/))

**Please note these repositories were already in place but were removed. This seems to be re-occurring with a number of repositories which are untouched for an extended period of time.**

**Comment by MonicaG** [comment]
Hi,
I've imported [EDUC-MACRO-API](https://github.com/bcgov/EDUC-MACRO-API). It is at:
[https://sonarcloud.io/project/configuration?id=bcgov_EDUC-MACRO-API](https://sonarcloud.io/project/configuration?id=bcgov_EDUC-MACRO-API). I've made you an administrator so you can set them up.

[https://github.com/bcgov/EDUC-PEN-REQUEST-API](https://github.com/bcgov/EDUC-PEN-REQUEST-API) was already imported and is at [https://sonarcloud.io/project/overview?id=bcgov_EDUC-PEN-REQUEST-API](https://sonarcloud.io/project/overview?id=bcgov_EDUC-PEN-REQUEST-API).  Was it in GitHub that you did not see it imported or on sonar cloud?

There is an [ongoing issue with sonar cloud and GitHub](https://community.sonarsource.com/t/github-sonarcloud-is-reporting-errors-check-the-sonarcloud-status-page-for-help/112630/34) w.r.t. to GitHub reporting that sonar cloud is not configured properly. 

However, repo removal is new. Maybe open an issue on the Sonar Cloud support forum and see if anyone is having the same issue?

**Comment by MonicaG** [comment]
@arcshiftsolutions - I'm closing this issue. Please reopen if needed.
