### ISSUE TITLE
ZEVA project requests to add BCeID as Identity Provider in KeyCloak

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#168]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.
I'm DevOps role in Zeva.

**Do you have an IDIR account?**
We use IDIR authentication for realm admin users, so you *must* have one in order to become a realm admin.  
My idir is kfan

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 2.
Yes.

## Step 1
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**. There will show a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this stpe, he/she will not be granted the role for the realms._

## Step 2
Field the following information.

* Project Name: Zeva (Zero-Emission Vehicles)
* For existing KeyCloak realm update only:
  - Realm ID: rzh2zkjq
  - Identity Provider to add: BCeID (in sso-dev and sso-test for now)

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@kuanfandevops dev and test enabled, prod created but will not be enabled until IDIM approves.
