### ISSUE TITLE
Add DCO app integration to bcgov/indy-vdr-proxy-server

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/devops-requests#1683]
Please enable/add [DCO](https://github.com/dcoapp) app to [bcgov/indy-vdr-proxy-server](https://github.com/bcgov/indy-vdr-proxy-server)

NOTE: This app integration is already enabled for some repositories (including [bc-wallet-mobile](bcgov/bc-wallet-mobile))

**Comment by oomIRL** [comment]
@cvarjao 

The DCO app has been enabled for [bcgov/indy-vdr-proxy-server](https://github.com/bcgov/indy-vdr-proxy-server)

Let me know if anything else is required.
