### ISSUE TITLE
MDYNAMICS-1638 - AG/PSSG - Remove github bcgov org access for 2 users

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1685]
Hello Developer Experience Team,

An email will follow with the required details to remove 2 users from the bcgov org.

Thank you,
Zubin Akolawala
AG ISB Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa

The users specified in the email have been removed from the bcgov org.
