### ISSUE TITLE
SonarCloud: add Policy to existing monorepo

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1687]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: 
  * Monorepo: onroutebc
  * New project: policy
* GitHub repositories to add to SonarCloud: bcgov/onroutebc (already a monorepo)
* New Code Definition: Previous Version

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

cc: cberg-aot

**Comment by MonicaG** [comment]
@DerekRoberts - It looks like onroutebc has been removed from SonarCloud. @arcshiftsolutions noted in #1680 that his team was having issues with repos being removed as well. He was following up with the SonarCloud community, but I'm not sure what that status is.

I noticed in the [security tab on the onroutebc repo](https://github.com/bcgov/onroutebc/security/code-scanning/tools/SonarCloud/status) that SonarCloud is reporting an error there as well.

Do you want me to setup the repo again in SonarCloud? If so, are there other projects in the monorepo to include beside "policy"?

**Comment by DerekRoberts** [comment]
@MonicaG Oh!  Looks like the repo hasn't been firing properly for some time.  If you could setup the monorepo again with components for `dops`, `frontend`, `vehicles` and `policy` it would be apprecaited!  :)

cc: @cberg-aot

**Comment by MonicaG** [comment]
@DerekRoberts - I think I've got things set back up. I've made you admin on the projects. Please let me know if anything is missing or misconfigured.

**Comment by MonicaG** [comment]
@DerekRoberts  - Adding: It looks like the dops, frontend, vehicles and tps_migration projects showed back up when you reran the analysis? I added in policy and scheduler projects.

**Comment by DerekRoberts** [comment]
@MonicaG Confusing!  Thanks for getting this set up.  I'm sure things will start to make sense or break horribly soon enough.  ;)
