### ISSUE TITLE
add an admin to a sonarcloud project

### ISSUE THREAD

**Issue by rshourou** [BCDevOps/devops-requests#1689]
Hello Developer Experience Team,

Can you please add nick-mailhot@github as an admin for [moh-pidp SonarCloud](https://sonarcloud.io/project/overview?id=bcgov_moh-pidp) project.

Thank you,
Roya Shourouni

**Comment by oomIRL** [comment]
Hello @rshourou 

I can certainly add an admin to the project, however, nick-mailhot is not listed as a user in SonarCloud.
They'll need to be a member of the bcgov GitHub org, and then sign up for SonarCloud with that GitHub account.

Let me know if you have any questions.
