### ISSUE TITLE
tenant-gitops-a1b9b - Request for BCGOV-C Private GitHub Organization Membership

### ISSUE THREAD

**Issue by abimichel** [BCDevOps/devops-requests#1690]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
Yes

**Do you have a private repository already?**
Yes, bcgov-c/tenant-gitops-a1b9b 

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: NRM Data Analytics Platform
* GitHub Org: private
* GitHub ID for the team members: **Please leave the existing members in bcgov-c/tenant-gitops-a1b9b and add: jujaga, krishna-r-bc, abcgovn**
* GitHub Account 2FA Confirmed: Yes
* Email address: abigail.michel@gov.bc.ca
* Organization: Natural Resource Information and Digital Services Division
* Project Role: Data Solutions Architect 
* GitHub Team to Join (if exists): https://github.com/orgs/bcgov/teams/data-foundations

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
Hi @abimichel 
I've sent you a bcgov-c invite. 
Just to confirm, you also want bcgov-c invites for: jujaga, krishna-r-bc, abcgovn?

**Comment by abimichel** [comment]
@oomIRL Yes please! I was unable to add them to our repo and kept getting this error: 
![image](https://github.com/user-attachments/assets/5476c2cc-cbc5-40c2-83b7-c298d80aa04c)

**Comment by oomIRL** [comment]
@abimichel The invites are sent!

Let me know if anything additional is required.
