### ISSUE TITLE
JASPER-61 - AG/PSSG – Request for private bcgov-c repo and Add member to bcgov-c repo

### ISSUE THREAD

**Issue by rafiul-nion** [BCDevOps/devops-requests#1693]
Hello Developer Experience Team, 

An email will follow with required details to: 
[x] Create a private repo in the bcgov-c (private) org and with the required details to add member(s).

Thank you,

Rafiul Nion
AG ISB Application Management

**Comment by oomIRL** [comment]
@rafiul-nion 

The specified users have been invited to bcgov-c, and the new repo has been created.
I'll close this issue once everyone has accepted their invite, and been added to the repo.

**Comment by rafiul-nion** [comment]
Hello, 

I believe all the **7 users** are not part of **BCGOV-C**. Please proceed with the next stage of **adding** all the users to the **created repo**.
