### ISSUE TITLE
Request to add the STRR repo to SonarCloud

### ISSUE THREAD

**Issue by rstens** [BCDevOps/devops-requests#1694]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
Yes

**Are you the admin user of the GitHub repositories?**
Yes

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: **STRR**
* GitHub repositories to add to SonarCloud: **https://github.com/bcgov/strr**
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/)) **Previous Version**

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by oomIRL** [comment]
@rstens 

I've added the STRR repo to SonarCloud. The new project is available [here](https://sonarcloud.io/project/overview?id=bcgov_STRR)
I've added you as an admin for the project.

Let me know if anything additional is required.

**Comment by rstens** [comment]
Thanks, all good
