### ISSUE TITLE
MDYNAMICS-1675 - AG/PSSG - Remove access for 1 user

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1697]
Good morning Dev Experience Team, 

An email will follow with the required details to remove 1 user from BCGOV, BCDEVOPS, and BCGOV-C.

Thank  you,

Zubin Akolawala
AG ISB Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 

The specified user has been removed from BCGOV, BCDEVOPS, and BCGOV-C.
