### ISSUE TITLE
MDYNAMICS-1673 - Add 1 user to BCGOV-C (private) org

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1698]
Good morning Dev Experience Team,

An email will follow with the required details to add 1 member to BCGOV-C (private).

Thank you,
Zubin Akolawala
AG ISB Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 

A bcgov-c org invite has been sent to the specified user
