### ISSUE TITLE
Request for membership - CTB

### ISSUE THREAD

**Issue by katerinkus** [BCDevOps/devops-requests#1699]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request on your behalf.

_Yes_

**Do you have a private repository already?**
If your team has the private repo already, please list it in the next step. If not, please request for the repo first!

_Request for the repo is here: [GitHub Issue](https://github.com/BCDevOps/devops-requests/issues/1695)_

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* GitHub ID for the team members: 
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by SHIHO-I** [comment]
User has been added.
