### ISSUE TITLE
Grant user access - OpenShift - Sheriff Scheduling 

### ISSUE THREAD

**Issue by ronald-garcia** [BCDevOps/devops-requests#17]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
**- [x] grant user access**
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Lucas Lopatka
* GitHub ID: **bcdevlucas**
* Business Email Address: lucas.lopatka@cgi.com
* Organization: CGI
* Project Role: Full stack developer
* OpenShift Projects/Namespaces: **jag-shuber-tools, jag-shuber-dev, jag-shuber-test**

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@ronald-garcia Lucas has been invited to `BCDevOps` GitHub organization. He will need to join the org for OpenShift access. Namespace admin could then invite him to the corresponding namespaces.
