### ISSUE TITLE
Remove Chris Callendar from BCGov github org

### ISSUE THREAD

**Issue by mishraomp** [BCDevOps/devops-requests#1703]
### Step 1

**Are you the Technical Lead?**
`Yes`

### Step 2
Fill out the following fields

* Project Name: ORI, https://github.com/bcgov/nr-epd-organics-info
* Technical Lead Github ID: mishraomp
* GitHub Org: bcgov,
* GitHub ID: ccallendar
* Reason for removal: contract finished.

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mishraomp** [comment]
cc @dawnbcgov @kdbelair

**Comment by oomIRL** [comment]
Hi @mishraomp 

The GitHub user ccallendar has been removed from the bcgov org.

Let me know if anything additional is required.

**Comment by mishraomp** [comment]
Thanks @oomIRL , all done.
