### ISSUE TITLE
Please remove PMAKIA1 from github membership

### ISSUE THREAD

**Issue by webgismd** [BCDevOps/devops-requests#1704]
## Removing Access

If you are removing access please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?** yes
If not, you need to ask your team's Technical Lead role to make this request on your behalf. 
This person must already be a member of the bcgov GitHub Organization in order for us to process this request.

If you are a technical lead and you've come here to request access for yourself, please go ahead and create this ticket, and then 
email Developer.Experience@gov.bc.ca with a link to the ticket so the team can approve it.

### Step 2
Fill out the following fields

* Project Name: Forestry Digital Services
* Technical Lead Github ID: webgismd
* GitHub Org: bcgov, BCDevops, or private all
* GitHub ID: @PMAKIA1 
* Reason for removal: TA has ended

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
Hi @webgismd 

I've removed the GitHub user PMAKIA1 from the bcgov and BCDevops orgs.

Let me know if anything else is required.

**Comment by webgismd** [comment]
Thank you!
