### ISSUE TITLE
Create new projects for PLR Team in the private bcgov-c org

### ISSUE THREAD

**Issue by camilleEsti** [BCDevOps/devops-requests#1708]
## Step 0

**Are you looking to make a public repository?** 
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.
**_No, we need a private repo_**

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

 **_A request has been sent at the same time_**

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. 
If you still think your code needs to be private, please provide the details in the request.
 **_Yes, at this time we are requesting a private repository, we are not opposed to open the code later but it is a project with a lot of history, and even though we fixed most of its security concerns, we need to revise it a bit more._**

**What date will you move your project to open-source?** 
All projects in the private organization are required to be there temporarily. 
This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. 
Please include a firm date by which you will move your repository to the open organization.

If you feel you cannot move to open-source ever, we strongly encourage you to reconsider.
However, if you are certain that you require a fully closed-source repo permanently, you can speak to the team on RocketChat to discuss your options.
Using the private bcgov GitHub Organization may not be the appropriate solution for your team in this case.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] **Create a private repo**
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - [Developer.Experience@gov.bc.ca](mailto:Developer.Experience@gov.bc.ca)

* Project Name: PLR
* GitHub Org: private
* Details on choosing private repo: 
* Preferred name for repo: We need a few repo for our projects to be created:
- moh-plr-esb
- moh-plr-core
- moh-plr-database
- moh-terminology-service

* Expected date to move to public: TBD
* GitHub ID for repo owner: @kh-sekhon Khushwinder Sekhon is PLR MoH Project Manager
* GitHub Account 2FA Confirmed: yes or no
* Email address: Khushwinder.Sekhon@gov.bc.ca
* Organization: Ministry of Health
* Project Role: Product Owner / Project Manager
* GitHub Team to Join (if exists):  need to be created, request has been sent

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
@camilleEsti 

The repos have been created. I'll add @kh-sekhon as an admin once they've accepted the bcgov-c invite.

**Comment by camilleEsti** [comment]
Hi @oomIRL.
kh-sekhon just confirmed me that he has accepted the invite to bcgov-c. 
He cannot see any invite to any projects yet.
Let us know if you need anything else from us
Thanks
Camille

**Comment by oomIRL** [comment]
Hi @camilleEsti 

I can confirm that kh-sekhon was added as an admin to the 4 repos that were created.

- moh-plr-esb
- moh-plr-core
- moh-plr-database
- moh-terminology-service

Let me know if there are additional repos to include.
