### ISSUE TITLE
AG/PSSG - MDYNAMICS-1702 - Remove all access for 1 user

### ISSUE THREAD

**Issue by ag-pssg-isb-sa** [BCDevOps/devops-requests#1710]
Hello Dev Experience Team, 

An email will follow with the required details to remove access for 1 user from BCGOV, BCDEVOPS, and BCGOV-C.

Thank you,
Zubin Akolawala
AG ISB Application Management

**Comment by oomIRL** [comment]
@ag-pssg-isb-sa 

The specified user has been removed from BCGOV, BCDEVOPS, and BCGOV-C.
