### ISSUE TITLE
Add nr-bcws-wfprev to BCGov SonarCloud

### ISSUE THREAD

**Issue by ssylver93** [BCDevOps/devops-requests#1712]
* Project Name: nr-bcws-wfprev
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/nr-bcws-wfprev
* New Code Definition: Previous version

**Comment by MonicaG** [comment]
HI @ssylver93 

I've created https://sonarcloud.io/project/configuration?id=bcgov_nr-bcws-wfprev

I've made you an admin so you can add other users and configure the project as you wish

Cheers,

Monica
