### ISSUE TITLE
Request for BCGOV-C Private GitHub - Daniel and Adrienne 

### ISSUE THREAD

**Issue by JL-CTB** [BCDevOps/devops-requests#1713]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?** - Yes
If not, you need to ask your team's Technical Lead role to make this request on your behalf.

**Do you have a private repository already?** Yes, https://github.com/bcgov-c/ctb_telematics_dap.git 
If your team has the private repo already, please list it in the next step. If not, please request for the repo first!

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* GitHub ID for the team members: 
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Added as per email
