### ISSUE TITLE
need to convert public in-development repo into private

### ISSUE THREAD

**Issue by JulieHawkins** [BCDevOps/devops-requests#1718]
## Step 0

**Are you looking to make a public repository?**
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. 
If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. 
This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. 
Please include a firm date by which you will move your repository to the open organization.

If you feel you cannot move to open-source ever, we strongly encourage you to reconsider.
However, if you are certain that you require a fully closed-source repo permanently, you can speak to the team on RocketChat to discuss your options.
Using the private bcgov GitHub Organization may not be the appropriate solution for your team in this case.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo (actually, I would like the one I started in public to be moved to private)
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: external-wes  (existing public repo: https://github.com/bcgov/external-wes)
* GitHub Org: private
* Details on choosing private repo: this project is in-development, and also includes proprietary info (how we run the program)
* Preferred name for repo: external-wes
* Expected date to move to public: 12/2025
* GitHub ID for repo owner: @JulieHawkins
* GitHub Account 2FA Confirmed: yes
* Email address: julie.hawkins@gov.bc.ca
* Organization: BC Stats
* Project Role: I don't know what you mean by this.
* GitHub Team to Join (if exists): bcgov-c\bcstats

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
Hi @JulieHawkins - I can transfer the repo from the bcgov org to the bcgov-c org. Is there a time when I should do the transfer? I don't want to interrupt anyones workflow.

**Comment by JulieHawkins** [comment]
Hi Monica, any time is fine. I pushed this morning, and no one else is working in it. I won't do any more in Git until it has been moved.

Thanks!

**Comment by MonicaG** [comment]
Hi @JulieHawkins 

I've transferred the repo. It is available at [https://github.com/bcgov-c/external-wes](https://github.com/bcgov-c/external-wes)

The team [bcgov-c -bcstats team](https://github.com/orgs/bcgov-c/teams/bcstats) has been assigned admin status to it. One thing to note, the [bcgov bcstats team](https://github.com/orgs/bcgov/teams/bcstats) has an additional person in it, karmour. They will lose access to the moved repo. If they need access, they will need to create an account on bcgov-c. They can do so by [following these instructions](https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/use-github-in-bcgov/bc-government-organizations-in-github/#directions-to-link-your-account-for-bcgov-c). Once they are a member of the org you can add the to the team. 

The team [bcgov dsp team](https://github.com/orgs/bcgov/teams/dsp) that had admin on the repo does not exist in bcgov-c. You will need to recreate it in bcgov-c if you want it to have access to the repo as well.

Cheers,

Monica

**Comment by JulieHawkins** [comment]
Hi, I have been notified that this repo is still public. It needs to be set as private. How do I do that?

~ Julie

**Comment by MonicaG** [comment]
Hi @JulieHawkins ,

Sorry, I missed the step of setting it to private. You can change it to private by:

1.	 Go to [https://github.com/bcgov-c/external-wes/settings](https://github.com/bcgov-c/external-wes/settings)
2.	Scroll down to the bottom to the “Danger Zone” section
3.	Click the “Change visibility” button
4.	Change it to private.

GitHub has more information on how to do this in their “[Setting repository visibility](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)” documentation 

Cheers,

Monica

**Comment by MonicaG** [comment]
@JulieHawkins - Ok, sorry about that.  I've switched it to private.

**Comment by JulieHawkins** [comment]
Thank you!
