### ISSUE TITLE
Create private repo for ltrack

### ISSUE THREAD

**Issue by macarrig** [BCDevOps/devops-requests#1720]
This is the first on-premise (legacy) repo we're setting up in bcgov-c enterprise on behalf of NRIDS
We anticipate a minimum of 50 legacy apps being transferred over once we confirm that legacy apps on shared infrastructure are supported, and NRIDS Teams and Developers have been successfully onboarded to work in GitHub.

Create a private repo

* Project Name: ltrack
* GitHub Org: bcgov-c (private)
* Details on choosing private repo: 
* Preferred name for repo: ltrack or nr-ltrack
* Expected date to move to public: 10/2024
* GitHub ID for repo owner: @macarrig 
* GitHub Account 2FA Confirmed: yes
* Email address: mary.carrigan@gov.bc.ca
* Organization: WLRS, NRIDS
* Project Role: Product Owner
* GitHub Team to Join (if exists):

**Comment by MonicaG** [comment]
I've created the repo. Please refer to the email for more details.
