### ISSUE TITLE
Please add the following 3 repositories to SonarCloud

### ISSUE THREAD

**Issue by arcshiftsolutions** [BCDevOps/devops-requests#1721]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.
Yes

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.
Yes

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.
Yes

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Graduation Data Collection
* GitHub repositories to add to SonarCloud:
- * EDUC-EAS-API
- * EDUC-GRAD-DATA-COLLECTION-API
- * EDUC-SCHOLARSHIPS-API

* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/))

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by MonicaG** [comment]
Hi @arcshiftsolutions - I've added the 3 repos to Sonar Cloud. I made you the admin on the projects so you can configure and invite others as needed.

Cheers,
Monica

**Comment by MonicaG** [comment]
@arcshiftsolutions - Oh and I set the "New Code Definition" to "number of days 30". You [can change this](https://docs.sonarsource.com/sonarcloud/administering-sonarcloud/setting-up-clean-as-you-code/#setting-a-new-code-definition) if you want

**Comment by arcshiftsolutions** [comment]
Thanks so much @MonicaG !
