### ISSUE TITLE
move bcgov/bc-small-business to bcgov-c temporarily

### ISSUE THREAD

**Issue by stephanieyurchak** [BCDevOps/devops-requests#1722]
## Step 0

**Are you looking to make a public repository?**
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.

**Are you a member of the private BC Gov-managed organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your codebase. 
If you still think your code needs to be private, please provide the details in the request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and/or move to public BC Gov-managed org

## Step 3
Fill out the following fields. For security purposes, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: bc-small-business
* GitHub Org: private (bcgov-c) 
* Details on choosing private repo: Working on a new annual data release to be released after the election. I would like to switch the repo to private until the refreshed dashboard is released publicly.
* Preferred name for repo: bc-small-business
* GitHub ID for repo owner: @stephanieyurchak
* GitHub Account 2FA Confirmed: yes
* Email address: Stephanie.Yurchak@gov.bc.ca
* Organization: BC Stats
* Project Role: admin
* GitHub Team to Join (if exists): BC Stats

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by MonicaG** [comment]
@stephanieyurchak - I have transferred the repo to bcgov-c where it is now private. I have made the BCStats team admin of the repo. 

Cheers,
Monica
