### ISSUE TITLE
Add bcgov/nr-fds-pyetl to Renovate App

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1725]
Please add bcgov/nr-fds-pyetl to the Renovate App. Thanks! :)

bcgov/nr-fds-pyetl

cc: @franTarkenton

**Comment by MonicaG** [comment]
HI @DerekRoberts - I've added bcgov/nr-fds-pyetl to the renovate app. 

Cheers,

Monica
