### ISSUE TITLE
Copy of Migrate CDT repositories from the DCO app to the DCO-2 app

### ISSUE THREAD

**Issue by caggles** [BCDevOps/devops-requests#1727]
Request from the Cyber Security and Digital Trust (CDT) Team:

The CDT team utilizes [dcoapp/app](https://github.com/apps/dco) to enforce DCO sign-off on all commits.  This is in place due to our heavy involvement with groups within the [Linux Foundation](https://www.linuxfoundation.org/), such as [Linux Foundation Decentralized Trust](https://www.lfdecentralizedtrust.org/) (Hyperledger), the [Open Wallet Foundation](https://openwallet.foundation/), and the [Trust Over IP Foundation](https://trustoverip.org/) along with many other open source groups such as the [Decentralized Identity Foundation](https://identity.foundation/).  We frequently contribute code and entire projects to these organizations and they enforce DCO sign-off, so we follow suite.

The [dcoapp/app](https://github.com/apps/dco) has not been maintained in some time and the [Cloud Native Computing Foundation (CNCF)](https://github.com/cncf) has created the [DCO-2](https://github.com/apps/dco-2) app as a replacement.

We'd like the assistance of the Developer Experience team to migrate from [DCO](https://github.com/apps/dco), to [DCO-2](https://github.com/apps/dco-2).  The approach taken by the Linux Foundation is to enable DCO-2 alongside DCO, with the plan to then remove DCO once DCO-2 is deemed working.

The DCO app is currently enabled on a repo by repo basis so as not to overwhelm other BC Gov teams with the DCO requirements (although relatively trivial).  As such we do not have direct access to the configuration and therefore require organization owner assistance.

Personally I think it would be a good idea to enable the DCO-2 app organization wide, but that would require other teams to get used to adding the DCO sign-off (`-s` or `--signoff`, which can be automated) to their commits.  DCO sign-off should not be confused with digitally signing (`-S` or `--gpg-sign`) commits with a gpg signing key, they are functionally very different.  DCO does not require a gpg signing key.  I think the legal intent of DCO sign-off would be beneficial to BC Government projects.

**Comment by MonicaG** [comment]
closing as duplicate
