### ISSUE TITLE
AG/PSSG User Access Request - Enabling Dev Teams within GitHub

### ISSUE THREAD

**Issue by rloisell** [BCDevOps/devops-requests#173]
## Step 0

**Are you a member of the BCGOV GitHub Organization already?**
Please note that **new users may not request access for themselves**. If you are not a member already, please talk to whoever that performed the onboarding/introduction of the BCGov DevOps Platform and BCDevExchange, and ask that contact to create this request for you.

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

**Are you the admin of your project's BCGOV GitHub Repository?**
If not, you need to ask your project repo's admin to make this request. 

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation - done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues - none

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Attorney General and Public Safety sector projects
* GitHub Org: bcgov and bcgov-c
* Full Name: <provided in email to pathfinder@gov.bc.ca>
* GitHub ID: <provided in email to pathfinder@gov.bc.ca>
* GitHub Account 2FA Confirmed: yes for all
* Email address: <provided in email to pathfinder@gov.bc.ca>
* Organization: Ministry of Attorney General, Ministry of Public Safety and Solicitor General
* Project Role: <provided in email to pathfinder@gov.bc.ca>
* GitHub Team to Join (if exists): <provided in email to pathfinder@gov.bc.ca>
* Existing GitHub Repo: Attorney General and Public Safety sector projects

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by rloisell** [comment]
@caggles / @ShellyXueHan - did you guys also send off the requests to join @BCGov-C as a part of this request?

**Comment by ShellyXueHan** [comment]
you could include the bcgov-c users in this request for now. I'd like to have a separate list of them to run my scripts. In addition, there are some invalid github usernames, refer to my email for detail.

**Comment by rloisell** [comment]
@ShellyXueHan - no email as of yet. Could you resend? I will reply with a list of BCGov-C users to make your life easier.

**Comment by ambarnhill** [comment]
@ShellyXueHan @rloisell Can you please let me know the status of this? We urgently need bcgov-c user access for Karthik. Thanks.

**Comment by rloisell** [comment]
@ShellyXueHan - resent email with list of specific users that need BCGov-C access. As mentioned by @ambarnhill, we are blocked as a number of developers require this access for releases and work planned for this week, into next week.

**Comment by ShellyXueHan** [comment]
@rloisell just to clarify on this request a bit more in addition to the email thread. As previously discussed, we are working on these user access requests for your project teams on oc platform so that you could better manage any existing users via the `GitHub teams`, but not to provision any new resources, including repositories. For example, the bcgov-c user access request for Karthik from @ambarnhill should be a separate request of a GitHub repository instead.

**Comment by rloisell** [comment]
> @rloisell just to clarify on this request a bit more in addition to the email thread. As previously discussed, we are working on these user access requests for your project teams on oc platform so that you could better manage any existing users via the `GitHub teams`, but not to provision any new resources, including repositories. For example, the bcgov-c user access request for Karthik from @ambarnhill should be a separate request of a GitHub repository instead.

@ShellyXueHan  - the request for Karthik is for access to existing repos, he a new member of the team. Do you also mean it should be a separate request for a GitHub User Access request as well? We don't need a new repo.

**Comment by ShellyXueHan** [comment]
@rloisell user Karthik (`karthikmsqa`) is in all three GitHub organization already, team admins could invite him to the repos.

**Comment by ambarnhill** [comment]
@rloisell Karthik has confirmed that he's in all the repos now. thanks!!

**Comment by rloisell** [comment]
@ShellyXueHan / @caggles  - GitHub User JohanLotzIDIR does not see any GitHub requests to join the BCGov org as a part of this request.

**Comment by rloisell** [comment]
@ShellyXueHan / @caggles - GitHub User JohanLotzIDIR does not see any GitHub requests to join the BCGov org as a part of this request.

**Comment by ShellyXueHan** [comment]
updated, pls double check

**Comment by rloisell** [comment]
thx - will check and confirm

**Comment by rloisell** [comment]
@ShellyXueHan - checked and now confirmed and accepted.

**Comment by rloisell** [comment]
@ShellyXueHan / @caggles  / @juhewitt - there is one Developer from this request that is still missing access to BCGov-C repositories. Could you please resend BCGov-C request for "bcdevlucas"??
