### ISSUE TITLE
Link Github To Jira

### ISSUE THREAD

**Issue by sukanya-rath** [BCDevOps/devops-requests#1730]
## Step 0
**Do you have repos on bcgov GitHub Organization?** `Yes`
If yes, please proceed with the request.

**If there is similar applications/tools available in the community, have you tried them out?**  `Yes`
There are many well supported community tools for various purposes, such SonarCube and BDDStack. 
Before you start with the new tools, have you consider trying out those that are available and widely adopted by the other application teams? 
If you have done so and do found that the existing ones does not match your need, please proceed.

**Have you tested out this GitHub application already?** `Yes`
We understand that there are a lot of new and cool GitHub Applications out there that teams could like to try out. 
However, we cannot just enable the integration without evaluating the app, as those are open to all application teams. 
We believe you have tested out the GitHub apps and had good reasoning for the preference before making this request.

## Step 1
Please fill out the team and project info so we know how to contact you:

* Product Name: Pay Transparency 
* Team Name: 
* GitHub Repositories on bcgov: https://github.com/bcgov/fin-pay-transparency

## Step 2
Please provide details about the requested GitHub App. Take a look here for a [good example](https://github.com/BCDevOps/platform-services/issues/120/)

1. Brief introduction of the app: Would like the Github project to be linked with Jira. It was previously connected but the link seems to have broken after recent changes. 
2. Jira URL : https://finrms.atlassian.net/jira/software/projects/GEO/boards/70

3. General Criteria:
  - How Easy / Fast / Repeatable is it to use and maintain for both Development Teams and Developer Experience Teams:
  - Customizable:
  - User Access Model:
  - License:
  - BCGov STRA:
  - Price Model:

4. Comparison between Existing Tools Used by the Community
  - pros:
  - cons:

5. Relevant Resources and Links

**Comment by MonicaG** [comment]
Hi, JIRA has been added to  https://github.com/bcgov/fin-pay-transparency as well.  Please see the comments in #1729 for the process for linking JIRA and GitHub

**Comment by MonicaG** [comment]
Hi,
I'm closing this issue. Please feel free to reopen or create a new issue if anything isn't working.

Cheers,
Monica
