### ISSUE TITLE
Sonar Request for bcgov/nr-site-registry

### ISSUE THREAD

**Issue by mishraomp** [BCDevOps/devops-requests#1734]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: NR Site Registry
* GitHub repositories to add to SonarCloud: bcgov/nr-site-registry
* New Code Definition: Previous version
* This is a mono repo. We need to analyze both backend/sites and frontend/site-registry . They are on TypeScript/JavaScript stack.

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

cc @acoard-aot @nikhila-aot @bolny

**Comment by MonicaG** [comment]
Hi @mishraomp 

I've set up the mono repo in sonar cloud and made you the admin so you can configure and add other users as needed.

The two projects are:
- https://sonarcloud.io/project/overview?id=bcgov-sonarcloud_nr-site-registry-backend
- https://sonarcloud.io/project/overview?id=bcgov-sonarcloud_nr-site-registry-frontend

Cheers,

Monica

**Comment by mishraomp** [comment]
> Hi @mishraomp
> 
> I've set up the mono repo in sonar cloud and made you the admin so you can configure and add other users as needed.
> 
> The two projects are:
> 
> * https://sonarcloud.io/project/overview?id=bcgov-sonarcloud_nr-site-registry-backend
> * https://sonarcloud.io/project/overview?id=bcgov-sonarcloud_nr-site-registry-frontend
> 
> Cheers,
> 
> Monica

Thank you so much for such a quick response :)
