### ISSUE TITLE
SonarCloud Monorepo for bcgov/nr-silva

### ISSUE THREAD

**Issue by DerekRoberts** [BCDevOps/devops-requests#1736]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: NR Silva
* GitHub repositories to add to SonarCloud: bcgov/nr-silva
* New Code Definition: Previous Version
* Monorepo:
  * backend
  * frontend

Note: There's an existing frontend project that isn't in use.  Please feel free to delete.
https://sonarcloud.io/project/overview?id=nr-silva-frontend

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

cc: @paulushcgcj

**Comment by oomIRL** [comment]
@DerekRoberts There's also an existing backend project: https://sonarcloud.io/project/overview?id=nr-silva-backend
Should that be removed as well, or is it in use?

**Comment by DerekRoberts** [comment]
@oomIRL Good catch! Yes please, also remove. :)

**Comment by oomIRL** [comment]
@DerekRoberts The previous projects have been removed and the bcgov/nr-silva repo has been setup as a monorepo with you as the admin for the projects.

- [frontend](https://sonarcloud.io/project/overview?id=nr-silva-frontend)
- [backend](https://sonarcloud.io/project/overview?id=nr-silva-backend)

Let me know if there's anything else!
