### ISSUE TITLE
Request: open TWO private repos in bcgov-c

### ISSUE THREAD

**Issue by stephhazlitt** [BCDevOps/devops-requests#1738]
Create TWO new private repos in `bcgov-c`:

`bcstats-cip-noc-translation`
`bcstats-cmslite-web-statistics`

Please add the [BCStats team](https://github.com/orgs/bcgov-c/teams/bcstats) as `Admin` on both repos.

Contact email address: stephanie.hazlitt@gov.bc.ca

**Comment by oomIRL** [comment]
- [bcstats-cip-noc-translation](https://github.com/bcgov-c/bcstats-cip-noc-translation)
- [bcstats-cmslite-web-statistics](https://github.com/bcgov-c/bcstats-cmslite-web-statistics)
