### ISSUE TITLE
Integrating NRIDS Jira with BCGOV Github (DVCS)

### ISSUE THREAD

**Issue by paul-goodman-pgoodman** [BCDevOps/devops-requests#1739]
Attn: Monica Granbois

Our test from yesterday seems to be functioning perfectly, looking forward to getting this into production.

We talked before about the possibility of a Service Account, but im thinking thats not necessary based on our configuration, I believe itll just be a matter of granting you admin in our Jira temporarily so you can grant access under the BCGOV account like you did in our TEST environment, but happy to proceed however you think is best.

Please:
A) Create an Oauth application for 'NRIDS Jira - PROD' under the BCGOV organization
B) Let me know when you are available to,register the application in our DVCS configuration and grant access to the organization.

Ill give you admin whenever youre available...

https://apps.nrs.gov.bc.ca/int/jira/secure/admin/ConfigureDvcsOrganizations!default.jspa?page=1

As a reminder for the configuration window, 
![image](https://github.com/user-attachments/assets/7f7a84eb-0319-4136-8473-9c940f9435c4)

Cheers, 
Paul.

**Comment by MonicaG** [comment]
@paul-goodman-pgoodman - Do you need both a TEST and PROD OAuth app in bcgov? Can I remove the test app once the prod one is setup? 

Is the JIRA URL different between test/prod?

I sent you  a calendar invite to do the integration.

**Comment by paul-goodman-pgoodman** [comment]
@MonicaG - Ideally id like the two instances to be in sync, so having both would be preferable. Is there a reason to not have both?
PROD URL: https://apps.nrs.gov.bc.ca/int/jira/

Cheers, 
P.

**Comment by MonicaG** [comment]
Done. Please let me know if you encounter any issues
