### ISSUE TITLE
Requesting membership to bcgov-c for a private repo.

### ISSUE THREAD

**Issue by aloffler** [BCDevOps/devops-requests#1740]
## Request Access

If you are request for access to the private GitHub organization for yourself or a team member, please **provide responses to all the steps below**. All questions are mandatory.

### Step 1

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request on your behalf.
Yes I am the technical lead for this project.

**Do you have a private repository already?**
If your team has the private repo already, please list it in the next step. If not, please request for the repo first!
No we do not have a private repo yet.

### Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: The hive
* GitHub Org: bcgov or private Both, please
* GitHub ID for the team members: aloffler
* GitHub Account 2FA Confirmed: yes or no
* Email address: securityanalytics@gov.bc.ca
* Organization: OCIO (CDT)
* Project Role: Principal Security Architect
* GitHub Team to Join (if exists): Not at this time

**Note** that the Developer Experience Team will be removing GitHub Org access **automatically** for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
Hi @aloffler 

It looks like you belong to bcgov & bcgov-c. Is there anything else your looking for beyond membership to bcgov-c?

**Comment by aloffler** [comment]
Hi Galen,

Nope, no idea how I was added historically, but that's great I'll create a repo in both public and private areas and start the migration process.

If I want to add other idir users to the project, can I do that directly or do they also need to be granted membership to bcgov-c before they can access the project?

Thanks for making this such an easy service to start using!

Speak soon,
-Alex.

Alex Loffler
Principal Security Architect

**Comment by oomIRL** [comment]
@aloffler No prob. Happy to help out.

Other idir users will need to be granted membership to access a bcgov-c project. I can do that now if you know the required users GitHub IDs, if not you can create a new devops request at a later date.

Also, members can create new bcgov repos but not bcgov-c repos. However, we have a devops request for that as well, just select "Request for private BCGOV GitHub Repository" from the request types when you're ready to make the private repo.
