### ISSUE TITLE
Request open a private repository in bcgov-c

### ISSUE THREAD

**Issue by OskarEscobar** [BCDevOps/devops-requests#1741]
Create a private repository in bcgov-c:
bcstats-housing-affordability
Please add the [BCStats team](https://github.com/orgs/bcgov-c/teams/bcstats) as Admin on the repository.
* Project Name: bcstats-housing-affordability
* GitHub Org: private
* Preferred name for repo: bcstats-housing-affordability
* GitHub ID for repo owner: @OskarEscobar
* GitHub Account 2FA Confirmed: yes 
* Email address: Oskar.EscobarSossa@gov.bc.ca
* Organization: BC STATS
* Project Role: Economic Analyst Coop
* GitHub Team to Join (if exists): [BC Stats Team](https://github.com/orgs/bcgov-c/teams/bcstats)

**Comment by oomIRL** [comment]
@OskarEscobar 

I've created the new repo: [bcstats-housing-affordability](https://github.com/bcgov-c/bcstats-housing-affordability)
You've been added as a repo admin, as well as the BC Stats Team.

Let me know if anything additional is required.
