### ISSUE TITLE
Request for private BCGOV GitHub Repository

### ISSUE THREAD

**Issue by chrislaick** [BCDevOps/devops-requests#1742]
## Step 0

**Are you looking to make a public repository?**
No.

**Are you a member of the private BC Gov-managed organization already?**
Yes.

**Are you sure you need to have your project code close-sourced?**
Yes.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and/or move to public BC Gov-managed org

## Step 3
Fill out the following fields. For security purposes, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

Emailed.

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
@chrislaick The repo has been created
