### ISSUE TITLE
Private Repository for Mule Deer Cumulative Effects Analysis

### ISSUE THREAD

**Issue by censlow** [BCDevOps/devops-requests#1744]
## Step 0

**Are you looking to make a public repository?**
Not at this time, I would very much like a version to eventually become public

**Are you a member of the private BC Gov-managed organization already?**
yes

**Are you sure you need to have your project code close-sourced?**
This project is being developed in collaboration with First Nations in our Region. I hope to have a closed code source to work on collaboratively, and then publish a version that could be used across the range of mule deer  (components that have sensitive traditional ecological knowledge will not be made part of the repo, and closed data and code sources are expected to be held by the Nations). 

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

There are no duplicate requests. 

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and/or move to public BC Gov-managed org

## Step 3
Fill out the following fields. For security purposes, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: Mule Deer Cumulative Effects Analysis
* GitHub Org: bcgov or private - PRIVATE
* Details on choosing private repo: Collaborative work with Nations, if we reach agreement hope to make public 
* Preferred name for repo: MuleDeerCE
* GitHub ID for repo owner: @censlow 
* GitHub Account 2FA Confirmed: yes or no: YES
* Email address:  chelsea.enslow@gov.bc.ca
* Organization:  WLRS
* Project Role: lead
* GitHub Team to Join (if exists): [TOR-CE](https://github.com/orgs/bcgov-c/teams/tor-ce)

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
@censlow 

I've created the new private repo [MuleDeerCE](https://github.com/bcgov-c/MuleDeerCE)
You've been added as an admin, as well as the tor-ce team.

Let me know if anything else is required.
