### ISSUE TITLE
Restore a back Persistent Volume

### ISSUE THREAD

**Issue by JacobWang-bc** [BCDevOps/devops-requests#1746]
Hi Team, 

Could you please assist with restoring the following volume?

* Date:  Aug 3rd, 2024 
* Cluster: Silver
* Source PV: pvc-098546ed-3afb-4295-aa86-67417cb46985
* Destination PV: pvc-498d3d22-f3ef-4efa-8776-f9b212f01a21

Thanks in advance!

Jacob

**Comment by StevenBarre** [comment]
Hey Jacon, we've only got 90 day retention of backups, and Aug 3rd is outside that window. I'll request the storage team restore the oldest copy they have for you.

**Comment by JacobWang-bc** [comment]
> Hey Jacon, we've only got 90 day retention of backups, and Aug 3rd is outside that window. I'll request the storage team restore the oldest copy they have for you.

Thank you for your help, let's see the result.

**Comment by StevenBarre** [comment]
Passed to the backup team via RITM0197114

**Comment by StevenBarre** [comment]
Restore failed after it ran out of space. Please resize the PVC to be larger, or specify a subfolder you'd like restored to reduce the data size.

The oldest full backup is Aug 31st

**Comment by JacobWang-bc** [comment]
> Restore failed after it ran out of space. Please resize the PVC to be larger, or specify a subfolder you'd like restored to reduce the data size.
> 
> The oldest full backup is Aug 31st

It seems we’ll have to cancel this request. We do have the backup files from August 31, so perhaps we missed the opportunity to restore them. Thank you.
