### ISSUE TITLE
Request for new repository

### ISSUE THREAD

**Issue by OskarEscobar** [BCDevOps/devops-requests#1749]
Hello
Please, Create one new private repository in bcgov-c:

bcstats-wildfire-areas

Please add the [BCStats team](https://github.com/orgs/bcgov-c/teams/bcstats) as Admin .

Contact email address: [Oskar.EscobarSossa@gov.bc.ca@gov.bc.ca](mailto:Oskar.EscobarSossa@gov.bc.ca)

* Project Name: BCSTATS Wildfire areas
* GitHub Org: private
* Preferred name for repo: bcstats-wildfire-areas
* GitHub ID for repo owner: @OskarEscobar
* GitHub Account 2FA Confirmed: yes 
* Email address: Oskar.EscobarSossa@gov.bc.ca
* Organization: BCStats
* Project Role: Economic Analyst Coop

**Comment by oomIRL** [comment]
@OskarEscobar 

I've created the new private repo [bcstats-wildfire-areas](https://github.com/bcgov-c/bcstats-wildfire-areas)
You've been added as an admin, as well as the BCStats team.

Let me know there's anything else I can do.
