### ISSUE TITLE
Add bcgov/nr-rec-resources to SonarCloud

### ISSUE THREAD

**Issue by mishraomp** [BCDevOps/devops-requests#1751]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: RST (Rec Sites and Trails)
* GitHub repositories to add to SonarCloud: bcgov/nr-rec-resources
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/)) Previous version
* This is a mono repo. We need to analyze both backend and frontend. They are on TypeScript/JavaScript stack.

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.
cc @marcellmueller

**Comment by oomIRL** [comment]
@mishraomp 

I've created a new SonarCloud project for the nr-rec-resources monorepo. You've been added as an admin.

- [nr-rec-resources frontend](https://sonarcloud.io/project/overview?id=bcgov-sonarcloud_nr-rec-resources-frontend)
- [nr-rec-resources backend](https://sonarcloud.io/project/overview?id=bcgov-sonarcloud_nr-rec-resources-backend)

Let me know if you need anything else.
