### ISSUE TITLE
Private Repo at BCGOV-C

### ISSUE THREAD

**Issue by averma2k** [BCDevOps/devops-requests#1753]
Hi Monica,

I hope you’re doing well.

I’m Amit Verma, Senior Technical Architect at Service BC & Government Digital Experience (GDX) in the Business and Communication Department. I’m reaching out to request your assistance in creating a private repository at BCGOV and assigning me as the owner. This is to ensure our code is securely stored in compliance with government policies.

**Comment by MonicaG** [comment]
Hi Amit,

Please let me know what you would like the repo to be called. 

You will need to be a member of the bcgov-c organization before I can assign you as the admin.  You can join the organization by following [these instructions](https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/use-github-in-bcgov/bc-government-organizations-in-github/#directions-to-link-your-account-for-bcgov-c).

Thanks!

Monica

**Comment by MonicaG** [comment]
Also, just FYI for next time, please ensure you submit new repo requests [through this issue template](https://github.com/BCDevOps/devops-requests/issues/new?assignees=MonicaG%2C+oomIRL%2C+SHIHO-I&labels=github-repo%2C+pending&projects=&template=github_repo_request.md&title=). This will assure the issue gets assigned to my team and we see it in our queue. Thank you! 😄

**Comment by MonicaG** [comment]
> Also, just FYI for next time, please ensure you submit new repo requests [through this issue template](https://github.com/BCDevOps/devops-requests/issues/new?assignees=MonicaG%2C+oomIRL%2C+SHIHO-I&labels=github-repo%2C+pending&projects=&template=github_repo_request.md&title=). This will assure the issue gets assigned to my team and we see it in our queue. Thank you! 😄

Hmmm..it looks like you used a template, but it didn't assign it to anyone. @averma2k - Would you mind letting me know the steps you took when creating this issue. I would like to investigate why it wasn't assigned to anyone (I've since assigned myself). Thanks!

**Comment by averma2k** [comment]
BCSMMI and BCSHUB

**Comment by averma2k** [comment]
Hi Monica,

I opened the form and filled in the necessary information. However, I noticed that no assignee name was displayed, so I went ahead and submitted it. I've also attached a screenshot for your reference.

**Comment by MonicaG** [comment]
Hi @averma2k - would you add yourself to the bcgov-c organization please? That way I can create the repos and add you as the admin. Here are the [instructions on how to join the organization](https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/use-github-in-bcgov/bc-government-organizations-in-github/#directions-to-link-your-account-for-bcgov-c). Thank you!

**Comment by MonicaG** [comment]
> Hi Monica,
> 
> I opened the form and filled in the necessary information. However, I noticed that no assignee name was displayed, so I went ahead and submitted it. I've also attached a screenshot for your reference.

Hmm... that is strange, there should have been assignees. Did the form look like the following:

<img width="1436" alt="Screenshot 2024-11-28 at 12 55 17 PM" src="https://github.com/user-attachments/assets/24f218e3-35bb-4b7f-962a-ed364a8b8cf1">

**Comment by averma2k** [comment]
It was like: 
screen_shot_1 and I have access to BCGOV-C. 
![Screen_Shot_1](https://github.com/user-attachments/assets/9e05f316-aadb-4fed-b707-57681688f1f3)
![Accessto BCGOV-C](https://github.com/user-attachments/assets/90e8d6ee-0b97-488e-821c-aad60c1a436f)

**Comment by MonicaG** [comment]
@averma2k - Hmm it didn't seem to work, I've sent you an invitation. You should get an email from GitHub. Please accept the invitation, then I can create the repos and add you as admin. 

If you don't get an email, then you can accept the invite through the GitHub website:
- Go to GitHub.com
- Click on your profile picture
- Select Your organizations
- Accept the invite for 'bcgov-c' organization

**Comment by averma2k** [comment]
Thanks Done, Invitation Accepted

**Comment by MonicaG** [comment]
@averma2k - I've created the following repos:

- https://github.com/bcgov-c/BCSMMI
- https://github.com/bcgov-c/BCSHUB


I've made you the admin on both so you can add your team members. They will need to be members of the bcgov-c organization before you can add them.

Cheers!

Monica

**Comment by averma2k** [comment]
thanks a lot Monica !!

**Comment by averma2k** [comment]
Hi Monica,

Could you please check my access? For some reason, I’m unable to add government employees to the repo.  

![Image](https://github.com/user-attachments/assets/21e2f514-dac5-4d8a-bb60-0afdd88c43de)

**Comment by MonicaG** [comment]
Hi @averma2k - they will need to join the bcgov-c organization first. They can do so by following [these instructions](https://developer.gov.bc.ca/docs/default/component/bc-developer-guide/use-github-in-bcgov/bc-government-organizations-in-github/#directions-to-sign-up-and-link-your-account-for-bcgov-c). 

You will be able to add them to your repo once they have joined.

Cheers,
Monica

**Comment by averma2k** [comment]
Thanks Monica

Amit Verma

The information transmitted herein is intended only for the named recipient(s) above, and may contain information that is privileged, confidential, or exempt from disclosure under applicable law. If you have received this message in error, or are not the named recipient(s), please immediately notify the sender by replying to this email and delete this message from all computers. Thank you.
