### ISSUE TITLE
Request for Private repository for PSA Data and Insights Office

### ISSUE THREAD

**Issue by MNair3385** [BCDevOps/devops-requests#1754]
## Step 0

**Are you looking to make a public repository?**
_No_

**Are you a member of the private BC Gov-managed organization already?**
_Yes_

**Are you sure you need to have your project code close-sourced?**
_Yes_

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
_No duplicate requests exist_

## Step 2
Are you requesting to:
- [x] Create a private repo

## Step 3
Fill out the following fields. For security purposes, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

Sent to the email address

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`! _Yes_

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
@MNair3385 The repo has been created as specified
