### ISSUE TITLE
request: open 11 repos in bcgov-c

### ISSUE THREAD

**Issue by BonnieJRobert** [BCDevOps/devops-requests#1755]
Create the following 11 new private repos in bcgov-c:

arda-ecc
arda-ecc-weighting
arda-map
bcds-dip-compare
dsp-us-hitech-bls-rewrite
hl-crisis-supports
idac-distinctions
climate-service-use-results
hl-service-use
homelessness-analytics-results
tech-docs

Please add the [BCStats team](https://github.com/orgs/bcgov-c/teams/bcstats) as Admin on both repos.

Contact email address: bonnie.robert@gov.bc.ca

FYI: we will be adding prefixes to the names of the repos once they are added.  Please email me prior to moving if this is not ideal/possible.

**Comment by oomIRL** [comment]
The following new private repos have been created with the BCStats team as Admin:

* [arda-ecc](https://github.com/bcgov-c/arda-ecc)
* [arda-ecc-weighting](https://github.com/bcgov-c/arda-ecc-weighting)
* [arda-map](https://github.com/bcgov-c/arda-map)
* [bcds-dip-compare](https://github.com/bcgov-c/bcds-dip-compare)
* [dsp-us-hitech-bls-rewrite](https://github.com/bcgov-c/dsp-us-hitech-bls-rewrite)
* [hl-crisis-supports](https://github.com/bcgov-c/hl-crisis-supports)
* [idac-distinctions](https://github.com/bcgov-c/idac-distinctions)
* [climate-service-use-results](https://github.com/bcgov-c/climate-service-use-results)
* [hl-service-use](https://github.com/bcgov-c/hl-service-use)
* [homelessness-analytics-results](https://github.com/bcgov-c/homelessness-analytics-results)
* [tech-docs](https://github.com/bcgov-c/tech-docs)
