### ISSUE TITLE
Request for private BCGOV GitHub Repository: Vehicle Forecast Generation (Clean Transportation Branch)

### ISSUE THREAD

**Issue by danclancy85** [BCDevOps/devops-requests#1759]
## Step 0

**Are you looking to make a public repository?**
If you are a member of the public bcgov GitHub Organization, you are already able to make a new repo there yourself!
If you are not a member, please request membership using the appropriate ticket template instead of using this one.
This template is for **private** repos only.

No

**Are you a member of the private BC Gov-managed organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

Yes, bcgov-c.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your codebase. 
If you still think your code needs to be private, please provide the details in the request.

Yes. This work involves sensitive data that has been procured from a third party. Sharing it is not allowed. The data will not be stored in the repo. 

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

No duplicate requests exist.

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and/or move to public BC Gov-managed org

## Step 3
Fill out the following fields. For security purposes, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* Details on choosing private repo: I work with proprietary data that is not available for distribution beyond my immediate team. As part of the work with this data, there will be occasional data outputs included in this code. This will usually be removed after inspection, but based on the risk of accidental data publication, having a private repo will help manage this risk. 
* Preferred name for repo: ctb_forecast_nvr_vio
* GitHub ID for repo owner: @danclancy85
* GitHub Account 2FA Confirmed: yes or no: yes
* Email address: daniel.clancy@gov.bc.ca
* Organization: Clean Transportation Branch
* Project Role: Senior Engineer
* GitHub Team to Join (if exists): 

## Step 4
Once you have a private repo and would like to invite more team members to work on it, please create a `Request for BCGOV-C Private GitHub Organization Membership`!

**Note** that the Developer Experience team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by oomIRL** [comment]
@danclancy85 

I've created a new private repo: [ctb_forecast_nvr_vio](https://github.com/bcgov-c/ctb_forecast_nvr_vio)
You've been added as an admin.

Let me know if anything additional is required.
