### ISSUE TITLE
Private Repo for CVSE Automated Testing (Katalon)

### ISSUE THREAD

**Issue by rogene-bcgov** [BCDevOps/devops-requests#1761]
## Step 0

We need a private repo to host the automated tests we are developing for the CVCS suite of applications for MOTT (previously MOTI.)
These automated test cases are testing both web application functionalities and API calls. We deem that we need a private repo for this to avoid potential exposure of the inner workings of the software.

## Step 1
No existing request for this project.

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and/or move to public BC Gov-managed org

## Step 3
Fill out the following fields. For security purposes, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca - contact info email sent

* Project Name: CVCS 
* GitHub Org: private
* Details on choosing private repo: We need a private repo to host the automated tests we are developing for the CVCS suite of applications for MOTT (previously MOTI.)
These automated test cases are testing both web application functionalities and API calls. We deem that we need a private repo for this to avoid potential exposure of the inner workings of the software.
* Preferred name for repo: cvcs-core-katalon

**Comment by oomIRL** [comment]
@rogene-bcgov 

I've created a new private repo: [cvcs-core-katalon](https://github.com/bcgov-c/cvcs-core-katalon)

You've been added as an admin. Let me know if anything else is needed.
