### ISSUE TITLE
Add Supreme Court Viewer repo to Sonar

### ISSUE THREAD

**Issue by BronzBierd** [BCDevOps/devops-requests#1763]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Supreme Court Viewer
* GitHub repositories to add to SonarCloud:  https://github.com/bcgov/supreme-court-viewer
* New Code Definition: [Number of Days](https://docs.sonarsource.com/sonarcloud/core-concepts/clean-as-you-code/about-new-code/#number-of-days), set to 1 day

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by oomIRL** [comment]
@BronzBierd 

I've created a new SonarCloud project for the Supreme Court Viewer repo [here](https://sonarcloud.io/project/overview?id=bcgov_supreme-court-viewer)

You've been added as a project admin. Let me know if anything else is needed

**Comment by BronzBierd** [comment]
Thank you very much
