### ISSUE TITLE
Please add my repo to SonarCloud - Quickstart Openshift Demo

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#1764]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.
**YES**

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.
**YES**

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: **Quickstart Openshift Demo** 
* GitHub repositories to add to SonarCloud: **quickstart-openshift-demo** (https://github.com/bcgov/quickstart-openshift-demo)
* New Code Definition: (Refer to [SonarCloud's documentation on the possible values for this field](https://docs.sonarcloud.io/improving/new-code-definition/)) **Previous version**

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by TimCsaky** [comment]
Oh I've been asked to aslo.. 'request a monorepo with component names (e.g. backend, frontend)'
I'm not quite sure what that means.

**Comment by oomIRL** [comment]
@TimCsaky 

No problem. Setting up a monorepo in SonarCloud means that there are multiple SonarCloud projects for the one repo.

* [quickstart-openshift-demo backend](https://sonarcloud.io/project/overview?id=bcgov-quickstart-openshift-demo-backend)
* [quickstart-openshift-demo frontend](https://sonarcloud.io/project/overview?id=bcgov-quickstart-openshift-demo-frontend)

I've added you as an admin to both projects

Let me know if anything else is required.
