### ISSUE TITLE
Please add my repo to SonarCloud - Quickstart One

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#1765]
Hi there. 
Due to un-forseen circumstances, I have had to choose a different github repo name from 'quickstart-openshift-demo' (requested yesterday). Can I please ask for another SonarCloud project (see below)? The one I requested yesterday can be deleted. 
I appreciate the extra work!

## Step 0
**Is your repository on `bcgov` GitHub Organization?**
**YES**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
**YES**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: **Quickstart One**
* GitHub repositories to add to SonarCloud: **qs1** (https://github.com/bcgov/qs1)
* New Code Definition: **Previous version**
Please make it a **monorepo configuration** with component names: 'backend' and 'frontend'

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by oomIRL** [comment]
@TimCsaky 

The quickstart-openshift-demo SonarCloud projects have been deleted, and I've created the following SonarCloud projects for the qs1 repo:
* [Quickstart One Frontend](https://sonarcloud.io/project/overview?id=bcgov-quickstart-one-frontend)
* [Quickstart One Backend](https://sonarcloud.io/project/overview?id=bcgov-quickstart-one-backend)

You've been added to the projects as admin.
