### ISSUE TITLE
Create a new private repo in bcgov-c

### ISSUE THREAD

**Issue by ateucher** [BCDevOps/devops-requests#1767]
## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and/or move to public BC Gov-managed org

## Step 3
Fill out the following fields. For security purposes, please provide the following contact information to the email address - Developer.Experience@gov.bc.ca

* Project Name: Ministry of Housing DIP 19-g07: Preventing and Reducing Homelessness
* GitHub Org: private (bcgov-c)
* Details on choosing private repo: Analysis of approved, exported results from DIP Secure Research Environment; sensitive information
* Preferred name for repo: `DIP-19-g07-crisis-interventions`
* GitHub ID for repo owner: @ateucher (please make the `housing-analytics` team Admin on the repo)
* GitHub Account 2FA Confirmed: yes
* Email address: andy@andyteucher.ca
* Organization: Ministry of Housing and Municipal Affairs, Homelessness and Supportive Housing Policy Branch
* Project Role: Data Scientist (contract)
* GitHub Team to Join (if exists): [housing-analytics](https://github.com/orgs/bcgov-c/teams/housing-analytics)

Thank you!
Andy

**Comment by oomIRL** [comment]
@ateucher 

I've created a new private repo [DIP-19-g07-crisis-interventions](https://github.com/bcgov-c/DIP-19-g07-crisis-interventions)

You've been added as admin, as well as the housing-analytics team.

Let me know if anything else is required

**Comment by ateucher** [comment]
Thank you so much @oomIRL!
