### ISSUE TITLE
request private repo for MSHU  Virtual Clinic - Foundry backend

### ISSUE THREAD

**Issue by sleroy1016** [BCDevOps/devops-requests#177]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Please note that **new users may not request access for themselves**. If you are not a member already, please talk to whoever that performed the onboarding/introduction of the BCGov DevOps Platform and BCDevExchange, and ask that contact to create this request for you.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: MHSU Virtual Clinic
* GitHub Org: bcgov or private: private
* Details on choosing private repo:  request by MOH CIO Paul Shrimpton to keep it private so some SME ( Steven Laws / Brad Head) can be do a feasibility assessment for OpenShift deployment
* GitHub ID for repo owner: @  sleroy1016
* GitHub Account 2FA Confirmed: yes or no: yes
* Email address: stephane.leroy@gov.bc.ca
* Organization:  MoH
* Project Role: Architect
* GitHub Team to Join (if exists): bradhead  and sslaws from the healthgateway bcgov project

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by sleroy1016** [comment]
Hi,

Just wondering how long it typically takes to get the repo created and if I am supposed to check on this request regularly for an update or if am going to receive email notification on the progress?

Our PM has been assuming that the creation of a repo is done quite rapidly ( a day or two) and I was wondering if that's a realistic expectation ( I don't think you have any published OLA , it's best effort, is it?)

Thanks

**Comment by caggles** [comment]
Hi @sleroy1016 - most requests are quite quick, but private repo requests in particular require approval from @kelpisland. Please speak to him before we can proceed!

**Comment by kelpisland** [comment]
@sleroy1016 - the private repos are meant to be a stepping stone to moving code into the open.
So to that end once the eval of this code base is complete is there the intention to move it to the open BCGov org? Because BCGov-C is not supposed to be a long term home.

**Comment by ShellyXueHan** [comment]
@sleroy1016 As mentioned in the email from Jane London, please provide the expected date for the repo to go public (month and year) so we could create the repo for you. Thanks!

**Comment by sleroy1016** [comment]
Hi Shelly, sorry I was off yesterday. 
The expected date for the repot to go public is July 1st 2020.
I'll create a separate request for access to the repo.

**Comment by sleroy1016** [comment]
I see there is no request specific to the access to the repo. So I suppose the repo will be created so that I have rights to  invite contributors to the repo, correct?

**Comment by ShellyXueHan** [comment]
yes, the repo has been created for you. You will get the GitHub invitation with your GitHub account's email. For other users to work on the repo, you will need to create the request with type `Request for BCGOV GitHub Organization Membership`.

**Comment by sleroy1016** [comment]
Hi Shelly, 
Do we actually need them to be member of the BCGOV GitHub organization?

When creating a request, the instruction warns us that for most part we can simply invite users as collaborators as per per [github instructions](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository) 

from request request:
_**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator._

**Comment by ShellyXueHan** [comment]
Yes for your case the users need to join the Github organization first as the repo is private.

**Comment by sleroy1016** [comment]
Thanks, I created the request to add 3 users.
I believe Brad Head is already a member of BCGOV GitHub org but the 2 others are not ( Stephen laws & Adam dubicki)

**Comment by ShellyXueHan** [comment]
Invitation sent out. BCGOV is the public GitHub organization which they don't need to join. The repo is requested to be a private one, so invitations are sent from the private GitHub org.

**Comment by ShellyXueHan** [comment]
your repo is created here: https://github.com/bcgov-c/mhsu-virtual-clinic
