### ISSUE TITLE
bcregistry private repo for operations tasks

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#178]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Yes

**Are you sure you need to have your project code close-sourced?**
Yes, it will track operational data

## Step 1
Make sure no duplicated request exists, search here:
None prior

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* Details on choosing private repo: 
* GitHub ID for repo owner: @
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @thorwolpert  - have you spoken to @kelpisland about this? You need his approval before we can give you a private repo!

**Comment by kelpisland** [comment]
Team has four a work around - reason for declining is we don't want to have operational dependency on BCGov-C
