### ISSUE TITLE
Add Brian Southby to rsbc-bi openshift environment

### ISSUE THREAD

**Issue by jennifer-dowd** [BCDevOps/devops-requests#18]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Brian Southby
* GitHub ID: @bsouthby
* Business Email Address: Brian.Southby@gov.bc.ca
* Organization: Public Safety and Solicitor General > RoadSafety Initiative
* Project Role: Developer
* OpenShift Projects/Namespaces:  iowaey-tools, iowaey-dev, iowaey-test

**Comment by ShellyXueHan** [comment]
@jennifer-dowd Brian has been invited to BCDevOps GitHub organization. He will need to join the org for OpenShift access. Namespace admin could then invite him to the corresponding namespaces.
