### ISSUE TITLE
Please sent users invite to bcdevops org for OpenShift Access

### ISSUE THREAD

**Issue by ll911** [BCDevOps/devops-requests#186]
# OpenShift Access Requests
## Step 0
**Are you the product owner or project admin?**
yes

**Do you have a GitHub account?**
yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: rafael solorzano, debbie tarry
* GitHub ID: rafasbcgov, dtarrybcgov
* Business Email Address: rafael.solorzano@gov.bc.ca, debbie.tarry@gov.bc.ca
* Organization: SDPR-ELMSD
* Project Role: edit
* OpenShift Projects/Namespaces: rpjtzt-tools,rpjtzt-dev,rpjtzt-test,rpjtzt-prod
* Please just sent invite to bcdevops org only, I will do the grant on those project spaces.

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by rafasbcgov** [comment]
@ShellyXueHan @caggles  I see this issue is now closed, nevertheless we have not received invitation to join the organization, and not able to see it at the organization page either, are you able to resend?

**Comment by ShellyXueHan** [comment]
@rafasbcgov try now, should be there.
