### ISSUE TITLE
Grant OpenShift Access to for Content Management Framework to Rob Delange 

### ISSUE THREAD

**Issue by ihallas** [BCDevOps/devops-requests#189]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Rob Delange
* GitHub ID: @RobdeLange
* Business Email Address: rob.delange@gov.bc.ca
* Organization: CITX:GDX
* Project Role: Infrastructure Architect
* OpenShift Projects/Namespaces: 

All of Content Management Framework
crmnaw-tools,crmnaw-dev,crmanw-test,crmanw-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@ihallas the user @RobdeLange has openshift console access already. The namespace admin user could further invite him by managing membership in the namespace.
