### ISSUE TITLE
Grant Openshift Access to Craig Stuart, Raymond Lee and Kevin Cao

### ISSUE THREAD

**Issue by ihallas** [BCDevOps/devops-requests#190]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Craig Stuart
* GitHub ID: @cstua
* Business Email Address: craig.stuart@gov.bc.ca
* Organization: CITZ:GDX
* Project Role: Developer
* OpenShift Projects/Namespaces: 
crmnaw-tools,crmnaw-dev,crmanw-test

-----------------
* Full Name: Raymond Lowe
* GitHub ID: @raylowe
* Business Email Address: raymond.lowe@gov.bc.ca
* Organization: CITZ:GDX
* Project Role: Developer
* OpenShift Projects/Namespaces: 
crmnaw-tools,crmnaw-dev,crmanw-test

------------------------------------

* Full Name: Kevin Cao
* GitHub ID: @kcao2006
* Business Email Address: Kevin.Cao@gov.bc.ca
* Organization: CITZ:GDX
* Project Role: QA/Tester
* OpenShift Projects/Namespaces: 
crmnaw-tools,crmnaw-dev,crmanw-test

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@ihallas BCDevOps GitHub organization invitation sent to `kcao2006` and `raylowe`. User `cstua` already have access.
