### ISSUE TITLE
Typo in name of our project

### ISSUE THREAD

**Issue by ihallas** [BCDevOps/devops-requests#191]
Not sure where to ask for this but our new Openshift project has a typo in the Name
It is is currently Content Mangement Framework (*)

Instead of Content Management Framework
The ( a ) is missing in the word Management

Thanks
Ian

## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

If you're looking to update the product owner or technical lead information, the person *currently* listed as product owner or technical lead needs to make this request, rather than the new person.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What annotations/labels need to be changed? (Select all that apply)
- [ ] Product Owner
- [ ] Technical Steward
- [ ] Security Contacts

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Link to the GitHub ticket you just created

*Product Technical Steward*
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username:
   
*Product Owner*
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

*BC Government Security Contact Information*
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)
  
  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
@ihallas please make this comment in the original request. I'll fix it for you there.
