### ISSUE TITLE
WebEOC Keycloak Realm SAML SSO

### ISSUE THREAD

**Issue by dbayne** [BCDevOps/devops-requests#196]
## Step 0
**Are you the product owner or project admin/team lead?**
YES.

**Do you have an IDIR account?**
IDIR\DBAYNE  

**Are you requesting for Identity Provider Update?**
NO

## Step 1
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**. There will show a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this stpe, he/she will not be granted the role for the realms._
DONE

## Step 2
Field the following information.

* Project Name: WebEOC

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address:

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
You could start the realm request here: https://realm-o-matic.pathfinder.gov.bc.ca now. If your developers who need to manage the keycloak resource do not have IDIR accounts, then please also pick GitHub as one of the identity provider.
