### ISSUE TITLE
OpenShift Access for Ronald Garcia

### ISSUE THREAD

**Issue by GregFPoirier** [BCDevOps/devops-requests#198]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Ronald Garcia
* GitHub ID: @ronald-rgr
* Business Email Address: Ronald.Garcia@quartech.com
* Organization: Quartech
* Project Role: Developer
* OpenShift Projects/Namespaces: 
project/pvpywj-tools, project/pvpywj-dev, project/pvpywj-test, project/pvpywj-prod

**Comment by ronald-rgr** [comment]
Hi @ShellyXueHan, 

Thanks for quick response. I am able to access the OpenShift console, however I can only see the pvpywj-dev project. Could you please confirm that I have access to TEST, TOOLS, and PROD.

Thanks,
Ron

**Comment by GregFPoirier** [comment]
I think that this is on our end.  I’ve just added you to test and will work on the others.
