### ISSUE TITLE
HMCR Project request

### ISSUE THREAD

**Issue by jamesmunro-BCGOV** [BCDevOps/devops-requests#2]
## Step 0
**Are you the product owner or technical lead?**
Product Owner: Nadia Yatsenko
Technical Lead: James Munro (jamesmunro-BCGOV)
Lead Developer: Neal Li (BcGovNeal)

**Have you had an alignment meeting?**
Yes, the project team met with Todd Wilson on Monday November 4 and described our project.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: HMCR - Ministry of Transportation and Infrastructure
* Product Short Name: HMCR
* Product Full Name: Highway Maintenance and Contractor Reporting
* Product Description: Build a system that contractors can upload their activity for highway maintenance, validate the GPS locations, provide summary reports.  The system is to reject invalid uploads.
* Desired Environments: tools, dev, test, prod
* Product Technical Steward
  - GitHub ID: @ jamesmunro-BCGOV
  - Business Email Address: james.munro@gov.bc.ca
  - RocketChat Account Username:  James Munro
* Product Owner: Nadia Yatsenko
  - Business Email Address: nadia.yatsenko@gov.bc.ca
  - RocketChat Account Username: nadia.yatsenko
* GitHub Repository: bcgov/HMCR

**Comment by kelpisland** [comment]
All good - we had our alignment chat yesterday

**Comment by ShellyXueHan** [comment]
@jamesmunro-BCGOV 
- Project set created as `txkggj-tools`, `txkggj-dev`, `txkggj-test`, `txkggj-prod`. `jamesmunro-BCGOV` is the admin of all four namespaces.
- Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
- For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.
