### ISSUE TITLE
OpenShift User Access Request

### ISSUE THREAD

**Issue by charlottekelso1** [BCDevOps/devops-requests#20]
Are you requesting to:
- [x] grant user access
- [ ] remove user access

- Full name: Morag Ross
- GitHub ID: moragross
- Email address: MRoss@bcorl.ca
- Organization: Office of the Registrar of Lobbyists (ORL)
- Project role: Project Stakeholder
- OpenShift projects: asuazq-dev, asuazq-test, asuazq-prod

**Comment by ShellyXueHan** [comment]
@charlottekelso1 Morag has been invited to BCDevOps GitHub organization. He/she will need to join the org for OpenShift access. Namespace admin could then invite him/her to the corresponding namespaces.
