### ISSUE TITLE
Access to EDUC-CAPS - Stephen Price

### ISSUE THREAD

**Issue by GregFPoirier** [BCDevOps/devops-requests#203]
## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Capital Asset Planning System
* GitHub Org: bcgov 
* Full Name: stephenewardprice
* GitHub ID: @ITKdoug
* GitHub Account 2FA Confirmed: yes
* Email address: stephenedwardprice@outlook.com
* Organization: ITK Consulting
* Project Role: Developer
* GitHub Team to Join (if exists): EDUC-CAPS-ITK
* Existing GitHub Repo: https://github.com/bcgov/EDUC-CAPS
**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by GregFPoirier** [comment]
Apologies, too many at one time.  The Git hub account for Stephen is actually stephenedwardprice

**Comment by ShellyXueHan** [comment]
does @itkdoug need to join the team as well?

**Comment by GregFPoirier** [comment]
Yes

**Comment by GregFPoirier** [comment]
* Project Name: Capital Asset Planning System
* GitHub Org: bcgov 
* Full Name: Doug McLachlan
* GitHub ID: @ITKdoug
* GitHub Account 2FA Confirmed: yes
* Email address: Doug.Mclachlan@itk.email
* Organization: ITK Consulting
* Project Role: Developer
* GitHub Team to Join (if exists): EDUC-CAPS-ITK
* Existing GitHub Repo: https://github.com/bcgov/EDUC-CAPS

**Comment by ShellyXueHan** [comment]
done
