### ISSUE TITLE
New user to project embc-ess (jhnamn)

### ISSUE THREAD

**Issue by rafaelponcedeleon** [BCDevOps/devops-requests#208]
## Step 0
**Are you the product owner or project admin? Yes

**Do you have a GitHub account? Yes rafaelponcedeleon
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account? Yes

## Step 1
Are you requesting to:
- [x] grant user access

## Step 2
Fill out the following fields

* Full Name: Wes Reid
* GitHub ID: @Wes-Reid
* Business Email Address: Wes.Reid@quartech.com
* Organization: Quartech
* Project Role: developer
* OpenShift Projects/Namespaces: 
jhnamn-tools, jhnamn-dev, jhnamn-test, jhnamn-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
This user have access to openshift console already. namespace admin can further invite him.
