### ISSUE TITLE
AG/PSSG OpenShift Access Request - https://justice.gov.bc.ca/jira/browse/VS-2305

### ISSUE THREAD

**Issue by rloisell** [BCDevOps/devops-requests#209]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

PROVIDED IN EMAIL TO PATHFINDER@GOV.BC.CA
Captured in https://justice.gov.bc.ca/jira/browse/VS-2305

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
user already in bcgov org.

**Comment by rloisell** [comment]
User needs BCDevOps access for access to OpenShift @ShellyXueHan

**Comment by ShellyXueHan** [comment]
added

**Comment by rloisell** [comment]
@ShellyXueHan - thank you
