### ISSUE TITLE
Request for BCGOV GitHub Organization Membership

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevOps/devops-requests#21]
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

* Project Name: BCDevExchange website
* GitHub Org: bcgov 
* Full Name: Parul Mishra Dubedy
* GitHub ID: @parulmishra
* GitHub Account 2FA Confirmed: yes
* Email address: Parul.Dubedy@gov.bc.ca
* Organization: BC Developers' Exchange
* Project Role: Full-Stack Developer
* GitHub Team to Join (if exists): N/A
* Existing GitHub Repo: not yet, will be creating new

**Comment by ShellyXueHan** [comment]
once Parul has accepted the invite, she will be able to create repo there.
