### ISSUE TITLE
Request OpenShift access for user

### ISSUE THREAD

**Issue by NicoledeGreef** [BCDevOps/devops-requests#212]
## Step 0
**Are you the product owner or project admin?**
Yes

**Do you have a GitHub account?**
@NicoledeGreef

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Dave Kelsey
* GitHub ID: @dkelsey
* Business Email Address: David.Kelsey@gov.bc.ca
* Organization: Sr. System Architect
* Project Role: OpenShift Admin
* OpenShift Projects/Namespaces: 
Project set created as wvmyix-tools, wvmyix-dev, wvmyix-test, wvmyix-prod.

**Comment by caggles** [comment]
@dkelsey should already have access to Openshift! If you're looking to give him access to the projects in question, please speak to the relevant project team - they'll be able to grant him the appropriate rights!
