### ISSUE TITLE
User Access - Data BC Namespaces

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [BCDevOps/devops-requests#214]
## Step 0
My name is Steve Chapman (steve.chapman@gov.bc.ca) - I'm the PO for the DataBC projects that use OpenShift.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Our following staff members cannot access their authorized OpenShift namespaces:
* Caroline Tansley
* John Churchill

On login to the OCP console, they both receive this message:
![OCP_Error](https://user-images.githubusercontent.com/36771389/75931311-7bafa480-5e29-11ea-89b0-4e6581f028ef.png)

**Comment by caggles** [comment]
hi @SteveChapmanBCDX  - please provide the github usernames for both of these users.

**Comment by SteveChapmanBCDX** [comment]
Hi @caggles - thanks for quick reply.  I should have provided you with that information on the original requeset.

GitHub usernames:
* Caroline Tansely - @catansle
* John Churchill - @jachurchill
