### ISSUE TITLE
DataBC - Admin Access to DataBC Namespaces

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [BCDevOps/devops-requests#215]
## Step 0
My name is Steve Chapman (steve.chapman@gov.bc.ca) and I am the PO for the DataBC projects that use OCP.

We have had recent staff turnover within our branch that requires our Infrastructure Team Lead (Caroline Tansley) to have admin access to all DataBC namespaces.

Thanks for your assistance with this one - let me know if you have any questions.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2

* Full Name: Caroline Tansley
* GitHub ID: @catansle
* Business Email Address: caroline.tansley@gov.bc.ca
* Organization: Data Systems and Services Branch
* Project Role: Infrastructure Team Lead
* OpenShift Projects/Namespaces: 
3aa7ll-dev
3aa7ll-prod
3aa7ll-test
3aa7ll-tools
apaczn-dev
apaczn-prod
apaczn-test
apaczn-tools
cddi-dlt-dev
cddi-dlt-test
cddi-dlt-tools
databcdc
dbc-bcdc-dev
dbc-bcdc-prod
dbc-bcdc-test
dbc-bcdc-tools
dbc-cms-vis-dev
dbc-cms-vis-prod
dbc-cms-vis-test
dbc-cms-vis-tools
dbc-kirk-dev
dbc-kirk-prod
dbc-kirk-test
dbc-kirk-tools
dbc-konga-dev
dbc-konga-prod
dbc-konga-test
dbc-konga-tools
dbc-mapsdk-dev
dbc-mapsdk-prod
dbc-mapsdk-test
dbc-mapsdk-tools
dbc-oem-tools
dbcols
devops-2016
fp1bxb-dev
fp1bxb-prod
fp1bxb-test
fp1bxb-tools
geopaas
hmg6pw-dev
hmg6pw-prod
hmg6pw-test
hmg6pw-tools
ido-bceala-dev
ido-bceala-prod
ido-bceala-test
ido-bceala-tools
ido-bcols-dev
ido-bcols-prod
ido-bcols-test
ido-bcols-tools
ll-realm
oaujjs-deploy
oaujjs-tools
rejspb-dev
rejspb-prod
rejspb-test
rejspb-tools
wlev6y-dev
wlev6y-prod
wlev6y-test
wlev6y-tools

**Comment by caggles** [comment]
Hi @SteveChapmanBCDX - normally this group isn't directly involved in administering access to individual namespaces. Is there no one available at DataBC with the appropriate access who can grant her the required rights?

**Comment by SteveChapmanBCDX** [comment]
> Hi @SteveChapmanBCDX - normally this group isn't directly involved in administering access to individual namespaces. Is there no one available at DataBC with the appropriate access who can grant her the required rights?

Hi @caggles - I'll see if we can do it on our end - if we can't, I'll get back in touch.  Probably best to close this issue now, as it can be reopened if we can't sort this out on our own.
