### ISSUE TITLE
Issue: Request for OpenShift Project Set

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevOps/devops-requests#22]
**Are you the product owner or technical lead?**
I'll be the acting PO for this, and @parulmishra will the the technical lead.

**Have you had an alignment meeting?**
Yes, just met with Todd this afternoon.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: BCDevExchange 
* Product Short Name: devexchange-web
* Product Full Name: BCDevExchange website
* Product Description: New website/web app for the the BCDevExchange
* Desired Environments: tools, dev, test, prod
* Product Technical Steward
  - GitHub ID: @parulmishra
  - Business Email Address: Parul.Dubedy@gov.bc.ca
  - RocketChat Account Username: parul.dubedy
* Product Owner
  - Business Email Address: Mark.Wilson@gov.bc.ca
  - RocketChat Account Username: mark.wilson
* GitHub Repository: Haven't created yet

**Comment by ShellyXueHan** [comment]
@parulmishra @mark-a-wilson Project set created as `ifttgq-tools`, `ifttgq-dev`, `ifttgq-test`, `ifttgq-prod`. `parulmishra` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.

**Comment by caggles** [comment]
sorry,  i didn't mean to reopen this, my bad!
