### ISSUE TITLE
Security Programs Division - eCRC OpenShift Project request. 

### ISSUE THREAD

**Issue by rloisell** [BCDevOps/devops-requests#221]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: Security Programs Division (SPD) - AG/PSSG
* Product Short Name: SPD eCRC
* Product Full Name: Security Programs Division Electronic Criminal Record Check 
* Product Description: SPD eCRC application 
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/jag-ecrc

**Comment by rloisell** [comment]
Alignment meeting has been held / OK'd by @kelpisland

**Comment by rloisell** [comment]
@caggles / @ShellyXueHan - any ETA on this project spaces? We are trying to request this project into this space to enable a path to production by March 31st.

**Comment by gov-dan** [comment]
Spoke to @caggles  and she is waiting for approval from @kelpisland (Todd).

@rloisell - is Todd waiting for anything from you? Do I need to schedule a meeting with Adriana (PO), yourself and Todd? I was assuming that we did not need a meeting because of Adriana's involvement in SPICE.

**Comment by kelpisland** [comment]
@caggles I can’t change the pending label on my phone, can you change to approved?

**Comment by kelpisland** [comment]
Never mind - I figured it out, landscape works 😉
