### ISSUE TITLE
Human Help: Disable Sonarcloud Spam Feature

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#224]
Could someone with permission please follow https://jira.sonarsource.com/browse/SCCOMM-19 and toggle `Administration / General Settings / Pull Requests / Integration with GitHub / Enable summary comment` to `OFF` please?

This is reported using the wrong template, per #223
https://chat.pathfinder.gov.bc.ca/channel/devops-how-to?msg=SuG6ETnAQ8RSRvo6Z

Re-posting here because thread in #devops-how-to was ignored
@Maralsotoudehnia if we can get this landed, the spam reduction will improve our team efficiency

**Comment by Maralsotoudehnia** [comment]
@caggles @ShellyXueHan any chance someone could help us out with this? I don't have access. Many thanks in advance!

**Comment by ShellyXueHan** [comment]
@wenzowski this doesn't seem to be an organization admin action but a project scope instead. Please confirm that if you are admin of your repos on sonar. If yes, are you not able to see the admin tab?

**Comment by wenzowski** [comment]
<img width="1280" alt="Screen Shot 2019-11-04 at 9 39 26 AM" src="https://user-images.githubusercontent.com/597920/76258804-86937c00-6211-11ea-8055-8bcfcdbc4a1b.png">
@ShellyXueHan sadly I cannot see repository admin tab

<img width="568" alt="Screen Shot 2020-03-09 at 2 25 08 PM" src="https://user-images.githubusercontent.com/597920/76258960-d40fe900-6211-11ea-97d1-c84ebaa50a0f.png">
...nor can I see org admin tab.

I suspect this means I'm not the admin of any BC Gov repos on Sonar...if that's something you can adjust I expect that admin rights of our own repos will allow our team to fix this issue ourselves.

**Comment by ShellyXueHan** [comment]
I've set your account to be the project admin, try now. (I thought this was done when the project was created but obviously not... one more step to add)

**Comment by wenzowski** [comment]
@matthieu-foucault done!
<img width="1277" alt="Screen Shot 2020-03-10 at 9 24 50 AM" src="https://user-images.githubusercontent.com/597920/76335084-3cfa6e00-62b1-11ea-8d0d-d31d50b2ad3f.png">

@ShellyXueHan thanks, you're the best :)
