### ISSUE TITLE
New OpenShift Project - Telemetry - BCTW

### ISSUE THREAD

**Issue by tdekens** [BCDevOps/devops-requests#225]
## Step 0
**Are you the product owner or technical lead?**
Product Owner

**Have you had an alignment meeting?**
Meeting booked with Todd Wilson.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: ENV
* Product Short Name: BCTW
* Product Full Name: BC Telemetry Warehouse
* Product Description: A front end application to display telemetry GPS collar data for regional staff collecting the data
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): 

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by victorchong** [comment]
I (victorchong) am having problems logging into the OpenShift console. I am getting the "Authentication error" message. My GitHub account is 2FA enabled. Can you confirm that I'm listed as an administrator or technical steward on this project set?

![Authentication error](https://user-images.githubusercontent.com/62109882/77088593-e92f0980-69c1-11ea-9282-1a089168e1b6.png)

**Comment by ShellyXueHan** [comment]
Hi @victorchong you are not the originally requested tech lead for this project. So no access will be given as part of this project set request. You will need to ask @tdekens to start OpenShift user access request for the rest of the team.

**Comment by caggles** [comment]
@ShellyXueHan can this ticket be closed now? It seems like the other necessary tickets have been made already?

**Comment by ShellyXueHan** [comment]
yes. see #251 for details
