### ISSUE TITLE
Increase b7cg3n-deploy persistentvolumeclaims=20

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/devops-requests#228]
## Step 0
**Are you the product owner or technical lead?**
Yes.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Best Effort (compute-best-effort-quota)
- [ ] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)

## Step 3
Add details about your quota request here:
We have one shared deployment namespace to support several Fider and LimeSurvey deploys; they are short-lived (months rather than years) are are cycled through.  Please increase from the current 20 to 30.

*ex: Please increase number of PVCs that can be provisioned to 30.*

## Step 4
Please explain here the reasons for requesting your quota change.
Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

This is to support one shared deployment namespace.  This request may be rescinded in 4 months, as we'll be asking teams to deploy to THEIR OWN namespace.  Once I have the `netapps-block` all changed to `netapp-file` (even for DB's) I can delete 4 of these test-only deployments.  Thanks!

**Comment by caggles** [comment]
Hi @garywong-bc - I'm just about to get started on this. Just FYI, I will mark this as completed once my part of this task is done. It may take a little more time for things to actually show up as updated on your namespace. And please let me know if there was anything unclear about filling in the template :)
