### ISSUE TITLE
Issue: Request for adding or removing OpenShift access

### ISSUE THREAD

**Issue by mark-a-wilson** [BCDevOps/devops-requests#23]
## Step 0
**Are you the product owner or project admin?**
Yes, I'll be the acting PO for this, and @parulmishra will be the technical lead.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Parul Mishra Dubedy
* GitHub ID: @parulmishra
* Business Email Address: Parul.Dubedy@gov.bc.ca 
* Organization: BC Developers' Exchange
* Project Role: Full-Stack Developer
* OpenShift Projects/Namespaces:

**Comment by ShellyXueHan** [comment]
Parul has been invited to join `BCDevOps` GitHub organization, this will grant her access to Openshift Console.
