### ISSUE TITLE
Complete steps for approved percy.io trial

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#230]
Looks like #130 got closed before @matthieu-foucault was able to confirm it was installed correctly. 

Huge thanks @caggles for taking this on, and for enabling us to run the test.
How can we get that closed ticket actually landed? Are there other issues on the Percy side preventing a successful test?

repo: [@bcgov/cas-ciip-portal](https://github.com/bcgov/cas-ciip-portal)

caggles commented 20 days ago:
> Percy has been approved. I still wanna have that meeting though - we would like to know how you guys are using it once you've had a chance to get it working for a while. Let us know when :)

matthieu-foucault commented 20 days ago:
> caggles thanks! unfortunately, it looks like something did not work on Percy's end. Maybe the user that connects the Percy org to the Github one has to be an admin of both. I contacted the Percy team and I'll get back to you on that.
> So far we have been taking snapshots on our "develop" branch only, but when the integration works we will be able to use them as part of the peer-review process. The snapshots are publicly visible here (I believe it asks you to login if it detects a github cookie), which also makes it a great tool to share application screenshots with the govt business area.

**Comment by wenzowski** [comment]
from percy team via @matthieu-foucault:
> Hello! Unfortunately you'll have to unlink the integration and have an admin set it up from the beginning. This is a known issue that we're aware of where the integration gets stuck if an admin approves it but did not initiate the request.

**Comment by wenzowski** [comment]
@Maralsotoudehnia is Percy still needed?

**Comment by Maralsotoudehnia** [comment]
@wenzowski I think we're trying out Happo. cc @matthieu-foucault in case there's anything to add?

**Comment by matthieu-foucault** [comment]
We're currently trying out using Happo.io instead of Percy. I will report back in a week or so once we've merged a few PRs using Happo, but it's promising so far. The good news is that the Happo GitHub integration does not require an org admin to be enabled, so this mean that, once I confirm the switch to Happo is final:
1. @caggles does not need to do anything to enable our use of Happo.
1. The Percy integration can be removed from the bcgov

**Comment by matthieu-foucault** [comment]
@caggles , @ShellyXueHan : we successfully switched to using Happo.io for our end-to-end screenshots. The Percy integration can be removed from the bcgov org.
