### ISSUE TITLE
Add new user to openshift project

### ISSUE THREAD

**Issue by jhamidi** [BCDevOps/devops-requests#232]
## Step 0
**Are you the product owner or project admin?**
YES

**Do you have a GitHub account?**
YES

**Do you have 2-factor-authentication enabled with your GitHub account?**
YES

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Samuel Amos
* GitHub ID: @ samuel-amos
* Business Email Address: samuel-amos@maximusbc.ca
* Organization: Maximus
* Project Role: Developer
* OpenShift Projects/Namespaces: 
gcpe-mygovbc-msp-tools
gcpe-mygovbc-msp-dev
gcpe-mygovbc-msp-test
gcpe-mygovbc-msp-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by jhamidi** [comment]
Is there a separate request needed to add him to the bcgov group?

**Comment by caggles** [comment]
@jhamidi yes there is - please submit one of those as well, if you haven't done so already :)

**Comment by jhamidi** [comment]
Samuel cannot log into openshift still.

**Comment by ShellyXueHan** [comment]
@jhamidi @samuel-amos please refer to the message sent by requestron below. There is the pending invitation from BCDevOps GitHub organization for Samuel. After join the org the user will be able to login to Openshift console.

> This issue has now been closed. It has been completed, unless a comment indicates otherwise.
> 
> The user in question should receive an invitation to the BCDevOps organization on GitHub. They must accept this invitation before they will be able to access Openshift.The invitation will show up in the inbox of whatever email address is listed as their primary address in their github profile.
> 
> If you have additional problems or questions, please feel free to ask the community on RocketChat on the `#devops-howto` channel!

**Comment by ShellyXueHan** [comment]
@jhamidi as mentioned that no BCDevOps invitation has been received, I've resent the invitation to Samuel. Please check again.
