### ISSUE TITLE
Please add user to openshift project

### ISSUE THREAD

**Issue by jhamidi** [BCDevOps/devops-requests#234]
## Step 0
**Are you the product owner or project admin?**
YES

**Do you have a GitHub account?**
YES

**Do you have 2-factor-authentication enabled with your GitHub account?**
YES

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Cyril Bravo
* GitHub ID: @ cyrilbravo
* Business Email Address: cyril.bravo@maximusbc.ca 
* Organization: Maximus
* Project Role: Developer
* OpenShift Projects/Namespaces: 
gcpe-mygovbc-msp-tools
gcpe-mygovbc-msp-dev
gcpe-mygovbc-msp-test
gcpe-mygovbc-msp-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by jhamidi** [comment]
Is there a separate request needed to add him to the bcgov group?

**Comment by caggles** [comment]
@jhamidi yep! please submit one of those too!

**Comment by caggles** [comment]
Looks like cyril is already in the BCDevOps org. If he's having problems getting onto the platform, ask about it on rocketchat (#devops-how-to is a good place to start)
