### ISSUE TITLE
KeyCloak Realm for FOI Request Download

### ISSUE THREAD

**Issue by f-w** [BCDevOps/devops-requests#236]
## Step 0
**Are you the product owner or project admin/team lead?**
Yes

**Do you have an IDIR account?**
Yes

**Are you requesting for Identity Provider Update?**
Not sure about the question.

## Step 1
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**. There will show a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this stpe, he/she will not be granted the role for the realms._

## Step 2
Field the following information.

* Project Name: FOI Request Download
* For existing KeyCloak realm update only:
  - Realm ID: 
  - Identity Provider to add: IDIR 

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by caggles** [comment]
hi @f-w - it looks like you haven't followed Step 1 yet. Please do so, and then we can proceed with this task!

**Comment by f-w** [comment]
@caggles, I did and saw the forbidden message. I am also the admin for existing 2 realm sets so my name should be registered. But just in case, I did again.

**Comment by caggles** [comment]
@f-w it looks like you may have done this only with github credentials - you need to sign in with idir!

**Comment by f-w** [comment]
@caggles , I logged in through CLP so it's IDIR. And for the 3rd time, I logged in again.
btw, recent Redhat SSO release added an execution called *Automatically Link Brokered Account*, with the execution there is no need to ask user to first login. Instead, you can create the user beforehand. I used this feature in my realms to avoid convoluted process.

**Comment by ShellyXueHan** [comment]
That sounds good! We will take a look. For the access issue you are having, are you referring to realm `5k8dbl4h`? If so, the admin user is assigned to Matthew's IDIR account. By default, only admin user have access.

**Comment by f-w** [comment]
@ShellyXueHan , The realm that I should be the requester/admin is gde0rjxl. The realm that I used *Automatically Link Brokered Account* is gde0rjxl.
