### ISSUE TITLE
Create a private repository for BEC Analysis development

### ISSUE THREAD

**Issue by whmacken** [BCDevOps/devops-requests#24]
## Step 0
Will MacKenzie product owner & technical lead.
## Step 1
GitHub Repository Request:

## Step 2
Are you requesting to:
- [] transition existing private repo in `bcgov-c` GitHub organization to public repo in `bcgov` GitHub organization
- [x ] create a temporary private repo in `bcgov-c` GitHub organization

## Step 3
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
OK

## Step 4
Fill out the following fields

* Project (Desired or existing repo name): BEC_Analysis-private
* Project Description: Development of formal data structure and standardized analysis for BEC
* Approver: @whmacken
* Repo Owner GitHub ID: @whmacken
* Rationale for being closed source: research project for journal publication. To become open upon publication
* Approval from Enterprise DevOps branch leadership: @

## Step 5:
Make the GitHub User Access Requests for your team members.

**Comment by ShellyXueHan** [comment]
@whmacken Hey Will, could you provide more information on the project (for example what's BEC)? I see that it's a research project, but which part of your code base that cannot be public? We have very limited space in private organization so we do need to filter by the nature of your project. In addition, please provide the expected date to go public. Thanks!

**Comment by whmacken** [comment]
This is the first of several research repositories that we have planned. Typically journals do not wish research results to be made available until they are published. We would not be loading large data files to GitHub but just the scripts so the size would be minimal. Expected date? Always hard a bit hard to say but ~ 1year.

**Comment by ShellyXueHan** [comment]
To clarify, is BEC referring to the program here https://www.for.gov.bc.ca/hre/becweb/ ? On our side, it's the private GitHub organization seats that's limited, not the code (there's no limit on that on GitHub). However, we do not expect any sensitive data/sensitive data structure to live on the repo. In addition, when your repo is created, we will set an expiry date in a year of time. You will need to make another request if your project can't go public by then. Is that okay with you?

**Comment by whmacken** [comment]
Sorry, yes this is the program.  Where I have several research projects should I consider putting them all under one repo then to save seats then?

**Comment by ShellyXueHan** [comment]
Combining into one repo and having your team (if you have other developers) joining a GitHub team could be helpful for us managing the org. Repo is created here: https://github.com/bcgov-c/BEC_Analysis You are made the admin of the repo. If you have other team members that need to collaborate, please make a GitHub user access. As admin user, you are responsible for any further user management in your repo.
