### ISSUE TITLE
Request to add STAGE namespace to BCDC project set. 

### ISSUE THREAD

**Issue by craigrigdon** [BCDevOps/devops-requests#241]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: DataBC
* Product Short Name:  dbc-bcdc-stage
* Product Full Name:  BC Data Catalog (stage)
* Product Description: BCDC Catalog Stage Environment
* Desired Environments: stage
* GitHub Repository (if exists): https://github.com/bcgov/ckanext-bcgov,https://github.com/bcgov/ckan-ui

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: craigrigdon
  - Business Email Address: craig.rigdon@gov.bc.ca
  - RocketChat Account Username: craig.rigdon
* Product Owner
  - Business Email Address: Steve.Chapman@gov.bc.ca
  - RocketChat Account Username: 
  - Organization Code:CITZ
  - Organization Unit Code: DSS-DS - Data Systems & Services - Data & Services
  - (refer to https://dir.gov.bc.ca/)

* BC Government Security Contact Information
  - Ministry Chief Information Officer: Chris.Hauff@gov.bc.ca
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer: Garry Mierzuak
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer: Heather Dunlop
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by kelpisland** [comment]
Hi @craigrigdon  - can you clarify - this looks like you need a staging environment for the data catalog. Is that right?

**Comment by craigrigdon** [comment]
yes you are correct, we have a project in place, we just need a staging environment for the data catalog. 
currently have ..

`dbc-bcdc-dev       BC Data Catalog (dev)                               Active
dbc-bcdc-prod      BC Data Catalog (prod)                              Active
dbc-bcdc-test      BC Data Catalog (test)                              Active
dbc-bcdc-tools     BC Data Catalog (tools)                             Active`

**Comment by kelpisland** [comment]
in that case, we strongly encourage  you to use your test or prod namespaces for multiple deployments. The name space labels are a construct for segmentation but not a limit on usage. Most teams on open shift now deploy test, staging and demo to their test space. The only reason this pattern presents problems is is the resource quotas or default claims are to constraining.

**Comment by kelpisland** [comment]
check out:
https://docs.openshift.com/container-platform/3.11/dev_guide/deployments/advanced_deployment_strategies.html

**Comment by craigrigdon** [comment]
Thanks Todd .. our concern is the resource quotes and PS claims as we test and scale to match our prod demand.

**Comment by kelpisland** [comment]
OK - understood, is scaling down UAT while you load test possible? Ideally, balancing load in the test name space is the "happy path". Other wise if you start to hit a resource constraint we can look at adjusting quota. A bespoke namespace in project is a last resort but if you get there we can have the conversation.

**Comment by craigrigdon** [comment]
Understood, thanks for clarifying Todd.  If we identify any issues along the way we will re-approach this conversation to have a separate namespace created.

**Comment by kelpisland** [comment]
👍
