### ISSUE TITLE
Request access to Sonar Cloud

### ISSUE THREAD

**Issue by asanchezr** [BCDevOps/devops-requests#242]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** 

    Our team (PIMS) is implementing SonarQube quality gate for static code analysis. We could stand-up our own SonarQube server but best-practice around the Exchange Lab is to use a SaaS-based instance shared by all BCGov projects (https://sonarcloud.io/organizations/bcgov-sonarcloud/projects).

    We need access to such instance for our project:
    https://github.com/bcgov/PIMS

2. **Why should this be a new request type?** 
This is something that could be automated and most likely new teams will start requesting more and more. Only the Platform Services team can grant access to the SonarCloud instance.

3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!

    PIMS GitHub repo: https://github.com/bcgov/PIMS
    PIMS Openshift namespace: jcxjin-dev, jcxjin-test, jcxjin-prod, jcxjin-tools

4. **What is the end result?** 

    A member of our team gets access to configure the PIMS project within SonarCloud. I'm the one tasked with configuring it.

**Comment by asanchezr** [comment]
@ShellyXueHan I see that the new requirements to request access is to be an admin of the GitHub repo. I myself am not so I'll have the admin of our team send a new request on our behalf. 
I believe this ticket could be closed then as no further action will be taken, correct?

**Comment by ShellyXueHan** [comment]
Yes The request has been started already. Good to close this one.
