### ISSUE TITLE
admin access to create new and manage exisiting databc realms

### ISSUE THREAD

**Issue by craigrigdon** [BCDevOps/devops-requests#243]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Do you have an IDIR account?**
We use IDIR authentication for realm admin users, so you *must* have one in order to become a realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 2.

## Step 1
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**. There will show a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this stpe, he/she will not be granted the role for the realms._

## Step 2
Field the following information.

* Project Name:databc
* For existing KeyCloak realm update only:
  - Realm ID:
  - Identity Provider to add: IDIR 

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: crigdon
* Admin user's Business Email Address: craig.rigdon@gov.bc.ca

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@craigrigdon what are the existing realms for databc? Is there a specific reason for a separate realm instead of using the same realm?

**Comment by craigrigdon** [comment]
Hi Shelly,

I am aware of databc realm in sso-dev, which i will need admin access to.  
In addition we will also need to have the additional request made as well..not unless they already exist. 

- Create Realm "databc" in https://sso-test.pathfinder.gov.bc.ca/
- Aquire Admin Access to Realm "databc" in https://sso-test.pathfinder.gov.bc.ca/

- Create Realm "databc" in https://sso.pathfinder.gov.bc.ca/
- Aquire Admin Access to Realm "databc" in https://sso.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@craigrigdon You will need to ask the current realm admin user to grant you access there. We don't manage application realms. Once you have access to the dev realm, please let us know, I'll then be able to create the other test and prod realms for your team.

**Comment by craigrigdon** [comment]
As far as I am aware no one on my team has admin access.  A team member has recently left our branch and we are sorting access.  Are you able to tell me who in databc is listed as an admin?

**Comment by ShellyXueHan** [comment]
Which team are you on? I can try to look up the admin group there. However, the admin role should be transferred before team member leaves. Is the previous team member still available to reach out?

**Comment by craigrigdon** [comment]
Im on the infrastructure team in Databc if that helps.

**Comment by ShellyXueHan** [comment]
I'm updating my keycloak scripts, will create test and prod realms once done.

**Comment by ShellyXueHan** [comment]
keeping this ticket open for now as more support will be needed case.

**Comment by craigrigdon** [comment]
Databc Team has discovered and now has appropriate access to the following realms thanks to Shelly.   
 
https://sso-dev.pathfinder.gov.bc.ca/auth/admin/databc/console/ 
https://sso-test.pathfinder.gov.bc.ca/auth/admin/ido-all/console/
https://sso-test.pathfinder.gov.bc.ca/auth/admin/ido-idir/console/
https://sso.pathfinder.gov.bc.ca/auth/admin/ido-idir/console/

Our Team has decided to NOT create anymore new realms at this time.  We wiill reach out at a later time once a new one is required. 

This ticket can now be closed.  Thanks again.

**Comment by SteveChapmanBCDX** [comment]
@ShellyXueHan - On behalf of DataBC, thanks for your help with this one!

**Comment by craigrigdon** [comment]
Reopen after talk with Team and Shelly to move forward to create 2 new realms that will be specific for BCDC new UI.

**Comment by craigrigdon** [comment]
completed realm-o-matic request

**Comment by ShellyXueHan** [comment]
Realms created, pending approval from IDIM. Closing ticket.
