### ISSUE TITLE
PIMS - SonarCloud Request

### ISSUE THREAD

**Issue by Fosol** [BCDevOps/devops-requests#246]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have install SonarCloud on `bcgov` GitHub Organization for application teams to use. If your repo is not on bcgov, please migrate first.

**Are you the admin user of the GitHub repositories?**
The setup process require a repo admin level access. You will be assigned as the admin of your SonarCloud repos.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects For debugging, please check if you are a member of bcgov GitHub Organization.

## Step 2
Fill out the following fields

* Project Name: PIMS
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/pims

***Note:*** Find out more instruction here: https://github.com/BCDevOps/sonarqube/blob/96aba33afef20c1c9003a2c9670206c28f4482ca/README.md#sonarcloud

**Comment by Fosol** [comment]
https://sonarcloud.io/projects

**Comment by ShellyXueHan** [comment]
I've added in the repo, see: https://sonarcloud.io/project/configuration?id=bcgov_PIMS @Fosol you are made the admin of the sonarcloud pims project. You could further invite the rest of your team (as long as they are a member of bcgov).

**Comment by ShellyXueHan** [comment]
see here for details on configuring: https://github.com/BCDevOps/sonarqube/blob/96aba33afef20c1c9003a2c9670206c28f4482ca/README.md#sonarcloud

Find a group of teams using sonarcloud here: https://chat.pathfinder.gov.bc.ca/channel/sonarqube-sonarcloud

**Comment by Fosol** [comment]
@ShellyXueHan I'm unable to add team members.

**Comment by ShellyXueHan** [comment]
can you see `adminstration -> permissions` page? If so, are there any Github users you could find there?

**Comment by Fosol** [comment]
I can see the page, but I'm unable to find `asanchezr`, even though he is part of the `bc gov` organization.

**Comment by ShellyXueHan** [comment]
I see, looks like that all users need to login to the sonarcloud console first, then the account will exist in the list. @asanchezr could you try it out?

**Comment by asanchezr** [comment]
I had previously created my own org (is free to try) to play around with settings etc. I have now signed out of that org and signed back in via the link https://sonarcloud.io/project/configuration?id=bcgov_PIMS

Still no dice. @Fosol doesn't see me in the users list

**Comment by asanchezr** [comment]
@ShellyXueHan any chance you can add me directly? @Fosol and I have tried multiple things and nothing works

**Comment by ShellyXueHan** [comment]
I don't see you there either. Could you try again to logout and log back in?

**Comment by ShellyXueHan** [comment]
try this link: https://sonarcloud.io/organizations/bcgov-sonarcloud/projects

**Comment by ShellyXueHan** [comment]
pleas also make sure that you give all the permission requested by sonarcloud on your github account.

**Comment by asanchezr** [comment]
This is what I've done:

- I logged out of both GitHub and SonarCloud
- Logged back in GitHub
- Revoked the SonarCloud OAuth token
- Opened the link: https://sonarcloud.io/organizations/bcgov-sonarcloud/projects
- Accepted the sonarcloud permission request on my github account
- I was then redirected to the bcgov link above

Do you see my user now?

**Comment by asanchezr** [comment]
![image](https://user-images.githubusercontent.com/24322224/76898310-b4507480-6852-11ea-9c05-5db4bab9c529.png)

**Comment by asanchezr** [comment]
![image](https://user-images.githubusercontent.com/24322224/76898329-be727300-6852-11ea-8499-789dcfc29e35.png)

**Comment by ShellyXueHan** [comment]
still no. try go to https://sonarcloud.io/account/organizations and switch to the bcgov organization if exists.

**Comment by asanchezr** [comment]
Nope I only see the org I created yesterday...

![image](https://user-images.githubusercontent.com/24322224/76898644-56705c80-6853-11ea-887e-f249c8a1f43b.png)

**Comment by asanchezr** [comment]
I could delete my account/org with SonarCloud and start over but that seems unnecessary...

**Comment by asanchezr** [comment]
Okay, I have deleted both my org and my user account on SonarCloud. Starting over....

![image](https://user-images.githubusercontent.com/24322224/76899053-1362b900-6854-11ea-8fdb-b73f15611a55.png)

**Comment by ShellyXueHan** [comment]
@Fosol now that Alejandro's account exists in sonarcloud already, you could go ahead and assign project roles for him.
