### ISSUE TITLE
Request OpenShift access for @junminahn

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#249]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Junmin Anh
* GitHub ID: [@junminahn](https://github.com/junminahn)
* Business Email Address: junmin@button.is
* Organization: Button Inc (for Climate Action Secretariat)
* Project Role: Backend Dev
* OpenShift Projects/Namespaces: wksv3k-dev

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by Maralsotoudehnia** [comment]
Hi @caggles and @ShellyXueHan -- this is just to say the PO approves this request. Please let me know if you have any questions.

**Comment by wenzowski** [comment]
I've already added him to the namespace; once he's been added to the bcdevops org I can add him to the @BCDevOps/cas team.
