### ISSUE TITLE
Request for private "bctw-db" GitHub repository

### ISSUE THREAD

**Issue by victorchong** [BCDevOps/devops-requests#253]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Please note that **new users may not request access for themselves**. If you are not a member already, please talk to whoever that performed the onboarding/introduction of the BCGov DevOps Platform and BCDevExchange, and ask that contact to create this request for you.
_Yes_

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.
_2020Mar23: Yes, but confirming with project sponsor and MISO. **Please hold request.**_

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. Please include a firm date by which you will move your repository to the open organization.
_2025Apr01_

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
_No duplicate requests._

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: BC Telemetry Warehouse
* GitHub Org: private
* Details on choosing private repo: The security of data related to species-at-risk (such as caribou) is a top priority for the Ministry of Environment. Both the telemetry data and the data model itself (i.e. database structure) for species-at-risk is protected by a privacy/data security agreement. This repository needs to be private in order to respect that privacy/data security agreement.
* Preferred name for repo: bctw
* Expected date to move to public: 04/2025
* GitHub ID for repo owner: @victorchong
* GitHub Account 2FA Confirmed: yes
* Email address: Victor.Chong@gov.bc.ca
* Organization: IIT
* Project Role: Technical Steward
* GitHub Team to Join (if exists): none

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
hi @victorchong - please answer all the questions in Step 0 before we can proceed!

**Comment by victorchong** [comment]
> hi @victorchong - please answer all the questions in Step 0 before we can proceed!

Comments have been added!

**Comment by victorchong** [comment]
@caggles - the request has been updated!

**Comment by victorchong** [comment]
No response yet from project sponsor or MISO. Will re-open this request if necessary.
