### ISSUE TITLE
Need to switch membership from old ID to this one

### ISSUE THREAD

**Issue by hannahgov** [BCDevOps/devops-requests#258]
Hi Everyone,

My old ID was attached to my now dead email (craig.sloat@gov.bc.ca) and I now need to be added to my new ID: hannah.sloat@gov.bc.ca (hannahgov). Do I still need my team lead to do this or is this good enough?

Cheers,

Hannah

* Project Name: Cost Containment Project
* GitHub Org: BCDevOps
* Full Name: Hannah Sloat
* GitHub ID: hannahgov
* GitHub Account 2FA Confirmed: yes
* Email address: hannah.sloat@gov.bc.ca
* Organization: IITD
* Project Role: Service Design Analyst
* GitHub Team to Join (if exists): Open Shift
* Existing GitHub Repo: unsure

**Comment by caggles** [comment]
Hi @hannahgov - is this a whole new github account that needs to be added? if that's so, can you please give me the account name of your old one as well, so we can remove it from the org?

**Comment by hannahgov** [comment]
I believe it was craig.sloat or heyasuki. I can't remember >_< and it's attached to a dead email.

**Comment by caggles** [comment]
hey @hannahgov  - i found a @craigsloat in BCDevOps, but not in bcgov. Are you sure it's bcgov membership you want/need? BCDevOps is the one that gets you into Openshift.

**Comment by hannahgov** [comment]
I'm sorry I meant to type BCDevOps not bcgov. Good catch =]

**Comment by caggles** [comment]
okay, apologies for the delay on this one - your new account has been added and the old one removed. Remember to speak to any appropriate tech leads to get added to the appropriate projects with your new account :)

**Comment by hannahgov** [comment]
TYVM!
