### ISSUE TITLE
"GitHub Repo Request" missing

### ISSUE THREAD

**Issue by victorchong** [BCDevOps/devops-requests#260]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
GitHub Repo Request

2. **Why should this be a new request type?**
Because the documentation at https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation says to create a request of this type.

3. **What information is required to fulfill this request?**
GitHub Repository Request:
- Project: Govvapp-private
- Project description: the temporary repo for the Govvapp project, for bla
- Approver: @Todd.Wilson
- Repo Owner GitHub ID: govviemcgovster

4. **What is the end result?**
That a public repository for the project is created. Or, this process is incorrect, to update the documentation at https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation.

**Comment by caggles** [comment]
Hey @victorchong ! It's actually that that document is out of date - you don't need us to make a repo for you. Once you have membership in the bcgov org, you can make repos yourself. Please go to that doc page, scroll down to the bottom and click "make an issue" - that will lead you straight to a github issue in the openshift-wiki repo and explain that the doc is out of date. That way, it will enter our queue and we can fix that asap!
