### ISSUE TITLE
IIT/NRM - IRS

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/devops-requests#263]
## Step 0
**Are you the product owner or technical lead?** yes
If not, you will need to ask one of those two people to make this request.

**Have you had an alignment meeting?** sort of. For different apps (SPI), and we have more replatform apps
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name:  IIT
* Product Short Name: IRS
* Product Full Name: Infrastructure Reporting System
* Product Description: IRS is an application utilized by the Information Management Branch that tracks infrastructure and application dependencies, and participants. It also provides a reporting mechanism for infrastructure and application outages and can create notifications for distribution if an infrastructure component or application is unavailable.
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists):  not yet

## Step 5
Sent via e-mail

Please note that we will only start processing your request when the email has been received.

**Comment by caggles** [comment]
hi @cvarjao 
i'm just wondering how you got to this template - i'm not sure how you made the issue without any labels or assignments, and i'm wondering if perhaps you followed a link somewhere rather than coming through the list of issues?

**Comment by cvarjao** [comment]
I went to this repository [main page](https://github.com/BCDevOps/devops-requests), and clicked on "OpenShift Project Set"

**Comment by caggles** [comment]
oh jeez, that explains so much, thank you very much clecio!

**Comment by ShellyXueHan** [comment]
Project set created as `ywinub-tools`, `ywinub-dev`, `ywinub-test`, `ywinub-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Platform-Services-Security/Developer-Guide-to-Zero-Trust-Security-Model-on-the-Platform
