### ISSUE TITLE
Enterprise Dispute Management System - from Residential Tenancy Branch

### ISSUE THREAD

**Issue by rkmclay** [BCDevOps/devops-requests#267]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
No. I'm Richard McLay, Director, Innovation & Continuous Improvement.....esquire. ;-) I lead the innovation program and team that is remaking BC's Residential Tenancy Branch into a digital service. 

**Are you sure you need to have your project code close-sourced?**
Yes. This is an in-flight build, 500,000+ lines of code. Needs proper refactoring, documentation, genericization, etc. before any debutantes ball...however, I would like it in a BCGOV repo in the mean time. 

**What date will you move your project to open-source?**
I cannot provide a "firm" date at this time. Target range is Q1-Q2 of FY 2021-22....thus between: April 2021 and Sept 2021. I refer you to Todd Wilson if you have concerns. If this time frame can't be supported we will forgo the BCGOV Repo until the time frame works.  

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3

Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: RTB Dispute Management System
* GitHub Org: bcgov or [**private**]
* Details on choosing private repo: See above
* Preferred name for repo: 1dash2dot_2dash_3dot (would mean a lot to the team, thanks)
* Expected date to move to public: 09/2021
* GitHub ID for repo owner: @mikeharlow (GitHub user #33070520)
* GitHub Account 2FA Confirmed: yes
* Email address: mikeharlow@hive1-cs.com
* Organization: Hive One Collaborative Solutions (multi-year dev ops contract to RTB) 
* Project Role: Senior Solution Architect
* GitHub Team to Join (if exists): n/a

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@rkmclay @mikeharlow private repo has been created: https://github.com/bcgov-c/RTB-Dispute-Management-System
