### ISSUE TITLE
TimeMachine: Request for OpenShift project set.

### ISSUE THREAD

**Issue by acoard-aot** [BCDevOps/devops-requests#269]
## Step 0
**Are you the product owner or technical lead?**
Yes, I am the technical lead.

**Have you had an alignment meeting?**
Not yet.  Have spoken to Zach Woodward about it (he is the product owner).  We do meet all the criteria for an OpenShift project.  We already have an OpenShift BCGov repo, are following agile methodologies,  and furthermore I've used OpenShift on other projects and have been following best practices.

This is a time-sensitive  request.  Ideally we would like  to have the environments setup by the beginning of next week.  I have reached out to Zach Woodward about the alignment meeting, but if possible I would respectfully request waiving the meeting requirement for now.  

## Step 1
Instructions visited.

## Step 2
No duplicates exist.

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: TimeMachine
* Product Short Name: TimeMachine
* Product Full Name: Project-and-time-tracker
* Product Description: A time tracking application for the 
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/Project-and-time-tracker

## Step 5

I will send an email shortly with the information requested.

**Comment by ZachWoodward** [comment]
* Full Name:  Adam Coard
* GitHub ID: @acoard
* Business Email Address: adam.coard@aot-technologies.com
* Organization:  AoT Technologies
* Project Role: Technical Lead
* OpenShift Projects/Namespaces: TimeMachine

**Comment by caggles** [comment]
@zachwoodward the github id provided isn't the same as the person making this request - can you please clarify?

**Comment by acoard-aot** [comment]
Apologies, please use my @acoard-aot account.

@acoard is my personal account, but my work (AoT Technologies) has a policy
that we must use our work GitHub accounts.

**Comment by ZachWoodward** [comment]
Acoard is my lead developer
I am the Product Owner.
Apologies if that is causing the confusion.

Regards,
Zachary Woodward

**Comment by mitovskaol** [comment]
@ZachWoodward At this moment, we only accept new projects that are not looking to go to production before the new Openshift 4 Platform is available in summer 2020 in the effort to keep the load on the current Openshift 3 Platform that is now a home to a number business critical applications , at the level where we can safely handle load spikes due to COVID-19 related activities. However, exceptions can be made if necessary. While I am approving your request to have dev, test and tools namespaces provisioned , lets have an alignment meeting to help me understand you production launch timelines before the Platform Services team can commit to support your in production.

**Comment by mitovskaol** [comment]
@caggles @ShellyXueHan  Zach's project is approved for onboarding on the Platform for all 4 environments including prod. The application is of small size and won't be generating a high load on the Platform.

**Comment by caggles** [comment]
okay, i canceled acoard's invitation to the BCDevOps org and sent a new one to acoard-aot. I'll work on this project set later this morning after my meetings are finished.

**Comment by acoard-aot** [comment]
I've accepted with the acoard-aot account, thanks.

**Comment by caggles** [comment]
Looks like the description has a typo in it - if @zachwoodward or @acoard-aot could please let me know what that's supposed to say, I'll get to work on this task :)

**Comment by acoard-aot** [comment]
Oops you're right, it got truncated.  Here's the description, let me know if you want a longer one:

A project and time-tracking app for the Procurement Services branch.
