### ISSUE TITLE
Request for New OpenShift Project Set: CHEFS

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#271]
New Project Request:
* Short Team/Organization Name: NR Showcase / IITD
* Product Short Name: CHEFS
* Product Full Name: Common Hosted Form Service
* Product Description: Create, edit and publish forms (powered by form.io)
* Product Technical Steward: TimCsaky / tim.csaky@gov.bc.ca / tim.csaky
* Product Owner: Matthew Hall / matthew.hall@gov.bc.ca / matthewhall78
* Desired Environments: tools, dev, test, prod
* GitHub Repository: https://github.com/bcgov/common-hosted-form-service

**Comment by ShellyXueHan** [comment]
@TimCsaky Please reach out to Olena @mitovskaol  to schedule an alignment meeting with your team. If your project is urgent (based on your email), let her know your project situation. We can help with provisioning once that's done.

**Comment by ShellyXueHan** [comment]
Project set created as `vmvfjv-tools`, `vmvfjv-dev`, `vmvfjv-test`, `vmvfjv-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Platform-Services-Security/Developer-Guide-to-Zero-Trust-Security-Model-on-the-Platform
