### ISSUE TITLE
Request for New KeyCloak Realm

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#272]
* Project Name: Common Hosted Form Service
* OpenShift Namespace: vmvfjv (Common Hosted Form Service - created 14th Apr. 2020)
* Admin user's IDIR account: tcsaky
* Admin user's Business Email Address: tim.csaky@gov.bc.ca

**Comment by ShellyXueHan** [comment]
@TimCsaky Hi Tim, after your project set has been created, please update the info above. Then we can proceed with this request. Thx!

**Comment by TimCsaky** [comment]
Thank you @ShellyXueHan for setting up the openshift namespace. I've added the namespace to the description in this ticket.

**Comment by ShellyXueHan** [comment]
@TimCsaky you should be able to login to https://realm-o-matic.pathfinder.gov.bc.ca/ with your idir account to start the realm provisioning there.
