### ISSUE TITLE
Private BCGOV repo access request

### ISSUE THREAD

**Issue by fwkendall** [BCDevOps/devops-requests#276]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Yes

**Are you sure you need to have your project code close-sourced?**
Yes

**What date will you move your project to open-source?**
This month

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: TBD
* GitHub Org: bcgov
* Details on choosing private repo: Speak to our PO for details
* Preferred name for repo: enhanced-travel-screening
* Expected date to move to public: 04/2020
* GitHub ID for repo owner: @fwkendall
* GitHub Account 2FA Confirmed: yes
* Email address: kendall@freshworks.io
* Organization: FreshWorks
* Project Role: Scrum master, developer
* GitHub Team to Join (if exists): N/A

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
Todd has created the repo last night. @fwkendall and @ashtonmeuser are made repo admin and write access. If any new team members need to collaborate on this repo, please request for private GitHub organization access.
