### ISSUE TITLE
Please add user to bcgov

### ISSUE THREAD

**Issue by jhamidi** [BCDevOps/devops-requests#277]
## Step 0
Yes.

**Are you the admin of your project's BCGOV GitHub Repository?**
Yes.

## Step 1
Visit DevHub for detailed instruction on creating a request:
Ok

## Step 2
Make sure no duplicated request exists, search here:
Ok

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: MyGovBC-MSP
* GitHub Org: bcgov
* Full Name: Steve Adams
* GitHub ID: @ steve-adams-maximus
* GitHub Account 2FA Confirmed: yes
* Email address: steve.adams@maximusbc.ca
* Organization: Maximus
* Project Role: Developer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo:  MyGovBC-MSP

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@jhamidi if Steve does not need to create repo in bcgov GitHub org, then you could invite him to work on your repo as Collaborator.
