### ISSUE TITLE
Add BCeID to Keycloak Realm v0t8loh2 

### ISSUE THREAD

**Issue by tschia** [BCDevOps/devops-requests#279]
## Step 0
**Are you the product owner or project admin/team lead?**
Yes

**Do you have an IDIR account?**
Yes

**Are you requesting for Identity Provider Update?**
Yes - we would like to add BCeID to our realm

## Step 1
NA - IDP Update only

## Step 2
Field the following information.

* Project Name: moh-iam
* For existing KeyCloak realm update only:
  - Realm ID: moh_idp (v0t8loh2)
  - Identity Provider to add: BCeID

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
BCeID has been enabled for your dev and test realms. Please start an approval process with IDIM team at IDIM.Consulting@gov.bc.ca for production BCeID.
