### ISSUE TITLE
Request: OpenShift Project Set for COVID-19 Essential Services

### ISSUE THREAD

**Issue by esune** [BCDevOps/devops-requests#280]
## Step 0
**Are you the product owner or technical lead?**
- [X] Yes, I am the technical lead

**Have you had an alignment meeting?**
- [X] Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project
- [X] Done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
- [X] Done

## Step 3
Are you requesting to:
- [x] Create a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: **BCDTS**
* Product Short Name: **COVID-19-ES**
* Product Full Name: **COVID-19 Essential Services**
* Product Description: **Initiative to showcase the use of Digital Credentials for COVID-19 Essential Services coordination support**
* Desired Environments: **tools, dev, test, prod**
* GitHub Repository (if exists): **T.B.D. (I will create it)**

## Step 5
Submit this ticket and email us the contact information.
- [X] Done

**Comment by esune** [comment]
_C.C.:_ @jljordan42 @swcurran @WadeBarnes

**Comment by WadeBarnes** [comment]
@mitovskaol, @caggles, @ShellyXueHan, This is a time sensitive request.  We're hoping to get this out for next week.  Apologies for the rush.

**Comment by mitovskaol** [comment]
Approved.

**Comment by jljordan42** [comment]
Thanks!

**Comment by ShellyXueHan** [comment]
Project set created as `bztwou-tools`, `bztwou-dev`, `bztwou-test`, `bztwou-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.

**Comment by WadeBarnes** [comment]
@mitovskaol, @caggles, @ShellyXueHan, Thank-you so much for the quick turnaround.
