### ISSUE TITLE
OpenShift Access Request - Add User

### ISSUE THREAD

**Issue by Fosol** [BCDevOps/devops-requests#281]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Goeme Nthomiwa
* GitHub ID: @goemen
* Business Email Address: gnthomiwa@gmail.com
* Organization: Quartech
* Project Role: Developer
* OpenShift Projects/Namespaces: 
jcxjin-tools, jcxjin-dev, jcxjin-test, jcxjin-prod

**Comment by Fosol** [comment]
@ShellyXueHan regrettably Goeme still is unable to login to OpenShift.  He apparently has not received an invitation.

**Comment by goemen** [comment]
<img width="612" alt="Screen Shot 2020-04-14 at 9 20 10 AM" src="https://user-images.githubusercontent.com/4842061/79249010-7df61d00-7e31-11ea-8519-a88797b72165.png">
I am expecting bcgov to have a checkmark but it is showing with a red cross. That could be what's causing the error. Any ideas?

**Comment by goemen** [comment]
Never mind, I got access now. I was able to find the invitation to the DevOps and I guess that resolves it @Fosol
