### ISSUE TITLE
Request for CPUI increase for hdhclr-prod

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#282]
## Step 0
**Are you the product owner or technical lead?**  YES
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here: No duplicates
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Best Effort (compute-best-effort-quota)
- [X ] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)

I am not 100% sure what the difference is.

## Step 3
Add details about your quota request here:

Please increase number CPU quota from 16 to 20.

## Step 4
I am fast-tracking the usage of a new app for Travel plans program as per the Minister Announcement. We will have 30 staff working on the weekend in the app. I haven't had a chance to load test or analyse usage requirements for Camunda (Java application). I don't believe I will need it but if I do, it would be on Saturday as the staff start handling requests.

Yes, I am being overly cautious. Currently, I am running a stateful set with one pod but I can scale as needed.

**Comment by gil0109** [comment]
Please note this is for a COVID related project

**Comment by caggles** [comment]
The updated resources should be available as of now!
