### ISSUE TITLE
Request for Production Keycloak Setup

### ISSUE THREAD

**Issue by ZachWoodward** [BCDevOps/devops-requests#283]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Do you have an IDIR account?**
We use IDIR authentication for realm admin users, so you *must* have one in order to become a realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 2.

## Step 1
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**. There will show a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 2
Field the following information.

* Project Name: 
* OpenShift Project Set/s if exists: 
* For existing KeyCloak realm update only:
  - Realm ID: 
  - Identity Provider to add: IDIR or BCeID or GitHub

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ZachWoodward** [comment]
Project Name: Time Machine
    OpenShift Project Set/s if exists:
    For existing KeyCloak realm update only:
        Realm ID:
        Identity Provider to add: IDIR or BCeID or GitHub

**Comment by ShellyXueHan** [comment]
@ZachWoodward you've requested for timemachine realm already at https://realm-o-matic.pathfinder.gov.bc.ca/Request/33 Is this for another project?

**Comment by ZachWoodward** [comment]
Request for IDIR and Github if possible (if not, then jsut IDIR)

**Comment by ZachWoodward** [comment]
It’s the same project, I thought I had messed something up.

Regards,
Zachary Woodward

**Comment by ShellyXueHan** [comment]
@ZachWoodward had a chat with Adam and got things figured out:
- there are realms created for time-machine already as `b9xip88d` in dev/test/prod keycloak (you can see it in realm-o-matic)
- your IDIR account is made the admin for all three
- if anyone else in the team needs to be an admin/(other level of access), you could grant them the access. (to do so, ask the team member to login first which creates the access in KeyCloak, then you will be able to find them in the `Users` section in the realm)

Please verify if the realm is setup for you alright.

**Comment by ShellyXueHan** [comment]
Onboarding completed. Closing
