### ISSUE TITLE
KeyCloak realm for 

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/devops-requests#284]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Do you have an IDIR account?**
We use IDIR authentication for realm admin users, so you *must* have one in order to become a realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 2.

## Step 1
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**. There will show a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 2
Field the following information.

* Project Name: Cloud Pathfinder
* OpenShift Project Set/s if exists:  tnfhhm-* 
* For existing KeyCloak realm update only:
  - Realm ID: 
  - Identity Provider to add: IDIR or BCeID or GitHub

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@sheaphillips you should have access to realm-o-matic now with the idir account.

**Comment by sheaphillips** [comment]
Hi friendly Platform Services team (and bots).

Per RC conversation with @ShellyXueHan I'd like to have the VC IDP(s) added to the realms created as a result of actioning this ticket some months ago.  We decided re-opening this ticket to track this request made sense.

Thanks!!!

**Comment by caggles** [comment]
hey @sheaphillips - is there anything specific that me or shelly would need to action on this? if not, i'm gonna just move it to another stream in zenhub :)

**Comment by sheaphillips** [comment]
This can be (re)closed - Shelly set things up for me perfectly. Thanks!!!
