### ISSUE TITLE
Platform-wide Change

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/devops-requests#285]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
Platform-wide Change

2. **Why should this be a new request type?** A good rule of thumb: Is this task straightforward (or something that could be automated)? Does it involve something you don't have the permissions to do? If the answer to both questions is yes, you're probably good to go ahead!
Every now and then we need to request platform-wide changes. For instance, the motivation behind this is that I wanted to request to disable namespace ownership for route as to enable multiple namespaces to use the same base domain.

3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
This is very open. Maybe just "What" , and "Why"?

4. **What is the end result?** Please provide plenty of details about what the end result should look like.
Having a conversation around the change being requested and provide a resolution (accepting the  request or not)

**Comment by wenzowski** [comment]
Can we also have included in this which platform we're asking for the platform-wide change on? Pathfinder is obviously one, but perhaps cloud-wide (eg. GCP, Azure, Terraform Cloud), or github-wide changes might fall under this type of request as well?

**Comment by caggles** [comment]
This request is being closed because a devops-request issue is not the appropriate place to have a discussion about platform-wide changes. The platform team is discussing the formalization of a process for such requests, but we're not convinced it's necessary - please just start up a conversation on Rocketchat and/or book a meeting with appropriate members of the platform team to discuss such things!
