### ISSUE TITLE
Private Repository for new product due to be launched on Sunday!

### ISSUE THREAD

**Issue by fresh-rachit** [BCDevOps/devops-requests#292]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. Please include a firm date by which you will move your repository to the open organization.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: Temporary Foreign Farm Workers Permitting System
* GitHub Org: bcgov-c (https://github.com/bcgov-c)
* Details on choosing private repo: 
* Preferred name for repo: tfw-permitting-system
* Expected date to move to public: TBD
* GitHub ID for repo owner: @fresh-rachit
* GitHub Account 2FA Confirmed: yes
* Email address: rachit@freshworks.io
* Organization: FreshWorks
* Project Role: Delivery Manager
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
@fresh-rachit  Please provide responses to the questions listed in Step 0

**Comment by fresh-rachit** [comment]
Sure thing:
Are you a member of the private BCGOV GitHub Organization already?
Yes, I'm a member of https://github.com/bcgov-c

Are you sure you need to have your project code close-sourced?
Yes.

What date will you move your project to open-source?
TBD

**Comment by ShellyXueHan** [comment]
https://github.com/bcgov-c/Foreign-Farm-Workers-Permitting-System
