### ISSUE TITLE
EDUC Services

### ISSUE THREAD

**Issue by sharifreer** [BCDevOps/devops-requests#293]
## Step 0
**Are you the product owner or technical lead?**

Peter Holland is the product owner and technical lead.
peter.holland@gov.bc.ca / Phollan

**Have you had an alignment meeting?**
Yes.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project
## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: EDUC
* Product Short Name: EDUC Services
* Product Full Name:  Education Common Services
* Product Description: Provide common services to EDUC OpenShift applications
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/EDUC-STUDENT-API 

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created

* Product Technical Steward
  - GitHub ID:  sharifreer
  - Business Email Address: shari.freer@gov.bc.ca
  - RocketChat Account Username: shari.freer
* Product Owner
  - Business Email Address: peter.holland@gov.bc.ca
  - RocketChat Account Username: peter.holland
  - Organization Code: EDUC
  - Organization Unit Code: Application Services Management

* BC Government Security Contact Information
  - Ministry CIO:  Sally.Barton@gov.bc.ca / Eleanor.Liddy@gov.bc.ca (acting for Sally)
  - Ministry Information Security Officer:  John.Chow@gov.bc.ca
  - Ministry Privacy Officer:  EDUC.InformationSecurityandPrivacy@gov.bc.ca

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
Project set created as `mvubjx-tools`, `mvubjx-dev`, `mvubjx-test`, `mvubjx-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.g
