### ISSUE TITLE
New public GitHub repository request for HMCR

### ISSUE THREAD

**Issue by jamesmunro-BCGOV** [BCDevOps/devops-requests#3]
## Step 0

**Are you a product owner or technical lead for a project?**
Product Owner: Nadia Yatsenko
Technical Lead: James Munro (jamesmunro-BCGOV)
Lead Developer: Neal Li (BcGovNeal)

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Are you requesting to create a:
- [x] public repo in `bcgov` GitHub organization
- [ ] transition existing private repo in `bcgov-c` GitHub organization to public repo in `bcgov` GitHub organization
- [ ] temporary private repo in `bcgov-c` GitHub organization

## Step 3
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Fill out the following fields

* Project (Desired or existing repo name): HMCR  (Highway Maintenance and Contractor Reporting)
* Project Description: Build a system that contractors can upload their activity for highway maintenance, validate the GPS locations, provide summary reports.  The system is to reject invalid uploads.
* Approver: James Munro @jamesmunro-BCGOV
* Repo Owner GitHub ID: James Munro @jamesmunro-BCGOV

**Comment by ShellyXueHan** [comment]
@jamesmunro-BCGOV https://github.com/bcgov/HMCR
