### ISSUE TITLE
Requesting new GitHub Repo - moh-eRx 

### ISSUE THREAD

**Issue by ninosamson** [BCDevOps/devops-requests#302]
## Step 0

**Are you a member of the BCDevOps GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure this is the appropriate organization?**
The vast majority of devops work in the BC Government should have its home in the bcgov organization, which members can create repos in without requiring a request.
This org is exclusively for the use of platform services. If you are not asking for a repo that directly serves the platform itself, your request will almost certainly be denied.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: Ministry of Health e-Prescribing 
* Details on repo: This repository will be used to develop the strategic architecture and components to enable electronic prescribing in British Columbia. 
* Preferred name for repo: moh-eRx
* GitHub ID for repo owner: @ninosamson
* GitHub Account 2FA Confirmed: yes 
* Email address: nino.samson@gov.bc.ca
* Organization: Ministry of Health, BC Government
* Project Role: Temporary Product Owner 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ninosamson** [comment]
Hi - is there an update on this issue?

**Comment by mitovskaol** [comment]
@ninosamson I've approved the request Nino, I apologize for the delay.

**Comment by ShellyXueHan** [comment]
@ninosamson are you requesting for a private repo in bcgov-c? If so please indicate the `Expected date to move to public: MM/YYYY`. If you are only looking for a public repo in bcgov, you should be able to go ahead and create it.

**Comment by ninosamson** [comment]
Thanks @mitovskaol @ShellyXueHan. 

This is not a private repo.

**Comment by ShellyXueHan** [comment]
yea there's no need to make the request for public repo. Closing ticket.
