### ISSUE TITLE
Request: OpenShift Project Set for Supreme Court Viewer

### ISSUE THREAD

**Issue by WadeBarnes** [BCDevOps/devops-requests#303]
## Summary
- Short team/organization name:
  - CSB

- Product short name:
  - SCSS-SCV

- Product full name:
  - Supreme Court Scheduling System - Supreme Court Viewer

- Product description:
  - Initiative to provide Supreme Court resources with more efficient and effective access to case details.

- Desired environments:
  - `tools`, `dev`, `test`, `prod`

- GitHub repo:
  - To be determined (I'll take care of that).

## Step 0
**Are you the product owner or technical lead?**
- [x] Yes, I am the technical lead

**Have you had an alignment meeting?**
- [x] Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

- [x] Done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

- [x] Done

## Step 3
Are you requesting to:
- [x] Create a project set

## Step 4
Fill out the following fields
* Short Team/Organization Name: 
* Product Short Name: 
* Product Full Name: 
* Product Description: 
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): 

- [x] Done, see Summary

## Step 5
- [x] Submit this ticket and email us the contact information.

**Comment by ShellyXueHan** [comment]
Project set created as `ovjbim-tools`, `ovjbim-dev`, `ovjbim-test`, `ovjbim-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Platform-Services-Security/Developer-Guide-to-Zero-Trust-Security-Model-on-the-Platform
