### ISSUE TITLE
Access RTB (Residential Tenancy Branch) OpenShift Container

### ISSUE THREAD

**Issue by romanovska** [BCDevOps/devops-requests#305]
## Step 0
**Are you the product owner or project admin?** - **YES**

Preferably, someone who is already a member of the BCDevOps Github org should request access for you. 
Consider asking someone to submit this ticket in your name in order to ensure that it is processed quickly.

If you do not have access to a team lead or other org member to ask for membership on your behalf, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed.

**Do you have a GitHub account?** - YES
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Sasha (Oleksandra) Romanovska; + Mansun Lui
* GitHub ID: @romanovska (Product Manager/Product Owner); + @PirateTed (Business Solutions Analyst)
* Business Email Address: oleksandra.romanovska@gov.bc.ca; + mansun.lui@gov.bc.ca 
* Organization: Residential Tenancy Branch, MAH
* Project Role: Product Manager
* OpenShift Projects/Namespaces: 
<Residential Tenancy Branch (RTB)>

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@romanovska I've double checked, you are still the admin of the OpenShift project set. You can find them after logging in to https://console.pathfinder.gov.bc.ca:8443 with your GitHub account. I've also invited @PirateTed to join BCDevOps GitHub org, which will grant access to OpenShift console. After Mansun has logged in, Sahas you could then invite the user to the your namespaces/projects.

**Comment by romanovska** [comment]
@ShellyXueHan thank you so much! I've been inactive for more than 6 months, so I thought I need to re-request the access. Can you remind me how to invite the user to my project? Thank you for your support.

**Comment by romanovska** [comment]
Thank you Shelly!
