### ISSUE TITLE
Enable BCeID Production Integration

### ISSUE THREAD

**Issue by GregFPoirier** [BCDevOps/devops-requests#309]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console -- Done
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console -- Done
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console -- Done

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: Electronic Contract Administration System (ECAS)

* OpenShift Project Set/s Info
  - Project set name:ECAS
  - Namespace ID:pvpywj

* For existing KeyCloak realm update only
  - Realm ID: yskdol9u
  - Identity Provider to Add
    - [X] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation: 
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
prod bceid enabled.

**Comment by GregFPoirier** [comment]
Hi, I'm going to make an assumption that there is more to be one to make this work properly.  right now when I try and log into our application it is pointing to sso-dev.pathfinder.gov.bc.ca and I'm getting a Client Disabled error.

I also am not able to use the realm-o-matic as I don't have permission.

Could you please assist?

Thanks, Greg
