### ISSUE TITLE
Add Tatsuya Morikawa to OpenShift

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/devops-requests#310]
## Step 0
**Are you the product owner or project admin?** I AM ROOT!

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Tatsuya Morikawa
* GitHub ID: @tmorik
* Business Email Address: Tatsuya.Morikawa@dxcas.com
* Organization: DXC Advanced Solutions
* Project Role: MCS Team member
* OpenShift Projects/Namespaces: N/A (I'll be granting cluster-admin)

**Comment by ShellyXueHan** [comment]
user invited.
