### ISSUE TITLE
Tatsuya Morikawa

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/devops-requests#311]
## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* GitHub Org: bcgov-c
* Full Name: Tatsuya Morikawa
* GitHub ID: @tmorik
* GitHub Account 2FA Confirmed: yes
* Business Email Address: Tatsuya.Morikawa@dxcas.com
* Organization: DXC Advanced Solutions
* Project Role: MCS Team member
* GitHub Team to Join (if exists): 
  * https://github.com/orgs/BCDevOps/teams/platform-operations/members
  * https://github.com/orgs/bcgov-c/teams/devops-platform-operations/members

**Comment by ShellyXueHan** [comment]
user invited

**Comment by sbarre-esit** [comment]
@ShellyXueHan looks like he hasn't been added to the teams. Do I need a separate request for that?

**Comment by ShellyXueHan** [comment]
ops missed that part. should be all good now, try again?

**Comment by sbarre-esit** [comment]
Success!
