### ISSUE TITLE
Add OpenShift Access for OCP 4 OPS labs (Paul Fischer)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/devops-requests#313]
## Step 0
**Are you the product owner or project admin?**
I am a project admin for some platform service namespaces, requesting on behalf of Paul Fischer (Arctiq Employee)

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* **Full Name:** Paul Fischer
* **GitHub ID:** @pfischer8989
* **Business Email Address:** paul.fischer@arctiq.ca
* **Organization:** Arctiq
* **Project Role:** Platform Ops and Service consultant
* **OpenShift Projects/Namespaces:** 
  - No access is required for production (OCP 3) projects
  - Access to OCP 4 Lab clusters as Cluster-Admin is requested to enable network testing and configuration validations.

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
invited to BCDevOps GitHub org.
