### ISSUE TITLE
New GitHub Repo for SPD BCSC authentication service

### ISSUE THREAD

**Issue by kevinji1** [BCDevOps/devops-requests#314]
## Step 0

**Are you a member of the BCDevOps GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure this is the appropriate organization?**
The vast majority of devops work in the BC Government should have its home in the bcgov organization, which members can create repos in without requiring a request.
This org is exclusively for the use of platform services. If you are not asking for a repo that directly serves the platform itself, your request will almost certainly be denied.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: Ministry of Attorney General - eCRC
* Details on repo: A BC Service Card authentication service component using OpenID Connect API was developed as part of eCRC application (GitHub repo - jag-ecrc). SPD would like the component to be separated out so it can be used as a shared service for other SPD client applications. This repository is used for this shared authentication service component.
* Preferred name for repo: spd-bcsc-auth-service
* GitHub ID for repo owner: @ag-pssg-isb-sa
* GitHub Account 2FA Confirmed: yes
* Email address: Kevin.1.Ji@gov.bc.ca
* Organization: Security Programs Division, Ministry of Public Safety and Solicitor General
* Project Role: Technical Lead

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by kevinji1** [comment]
Please grant the same access as bcgov/jag-ecrc repo. Thanks.

**Comment by caggles** [comment]
hi @kevinji1  - how come this repo is being requested for BCDevOps and not the bcgov org?

**Comment by kevinji1** [comment]
sorry @caggles. I might have submitted the request in wrong place. Do I need to follow a separate process to get this bcgov repo created? Thanks.

**Comment by caggles** [comment]
hi @kevinji1 - you actually don't need a request to make a bcgov repo! Assuming you (or someone else on your team) has membership in the bcgov org, you can do that yourself :)
If you need membership in the bcgov org because you don't have it yet, there's a template for that as well!

**Comment by kevinji1** [comment]
Thanks @caggles BCGOV GitHub repo is now being provisioned by Justice ISB Service Transition group via a JIRA ticket request. ISB wants ownership of the repo so we can't create the repo our-self.
