### ISSUE TITLE
Create new private repo for landing zones

### ISSUE THREAD

**Issue by ActionAnalytics** [BCDevOps/devops-requests#316]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Yes

**Are you sure you need to have your project code close-sourced?**
Yes, approved by @kelpisland 

**What date will you move your project to open-source?**
Never

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
Pathfinding work, no dups

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca
Done, see email

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ActionAnalytics** [comment]
Email sent with link to this ticket thank you!

**Comment by caggles** [comment]
@sheaphillips please tag me or shelly directly in the comments when you decide, just to help make sure we don't miss this if there's something that we still need to action!

**Comment by sheaphillips** [comment]
@caggles @ShellyXueHan gonna close this as we've dealt with it ourselves.  thanks!
