### ISSUE TITLE
Request Keycloak Realm for Wally

### ISSUE THREAD

**Issue by LindsayMacfarlane** [BCDevOps/devops-requests#317]
## Step 0
**Are you the product owner or project admin/team lead?**
Yes. I'm the Product Owner for the Water Team, responsible for the GWELLS and Wally applications.

**Does the Admin User have an IDIR account?**
Yes.
Lindsay Macfarlane = LMACFARL
Steve Hillier = STEPHHIL
Daine Trinidad = DATRINID

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.
No

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 
No, we have implemented in our previous GWELLS application.

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._
Completed

## Step 3
Field the following information.

* Project Name: WALLY

* OpenShift Project Set/s Info
  - Project set name: WALLY
  - Namespace ID: bfpeyx-*

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
Steve Hillier = STEPHHIL now has the access to fill in the form of the realm request here: https://realm-o-matic.pathfinder.gov.bc.ca/

Please note that the admin user IDIR field should only contain one user and just the username as `STEPHHIL`.
