### ISSUE TITLE
BCGOV access for Mike McGuinness

### ISSUE THREAD

**Issue by GregFPoirier** [BCDevOps/devops-requests#318]
## Step 0

**Are you a member of the BCGOV GitHub Organization already?**

Preferably, someone who is already a member of the BCGOV Github org should request access for you. 
Consider asking someone to submit this ticket in your name in order to ensure that it is processed quickly.

If you do not have access to a team lead or other org member to ask for membership on your behalf, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed!

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

**Are you the admin of your project's BCGOV GitHub Repository?**
If not, you need to ask your project repo's admin to make this request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Capital Asset Planning System
* GitHub Org: bcgov
* Full Name: Mike McGuinness
* GitHub ID: @mmcguinness
* GitHub Account 2FA Confirmed: yes
* Email address: mmcguinness@level-up.ca
* Organization: ITK (Ministry of Education)
* Project Role: Developer
* GitHub Team to Join (if exists): EDUC-CAPS-ITK
* Existing GitHub Repo: EDUC-CAPS

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by GregFPoirier** [comment]
Hi, the developer would like to use a different email address.  mike.mcguinness@itk.email

Thanks, Greg.

**Comment by caggles** [comment]
hi @GregFPoirier - the dev will receive the invite to whatever email address is associated with his github account!

**Comment by mmcguinness** [comment]
Hi Greg, I am able to see the repositories, but I can’t upload to either:

https://github.com/bcgov/EDUC-CAPS
https://github.com/bcgov/EDUC-ISFS

Getting:

Uploads are disabled.
File uploads require push access to this repository.

Thanks,
Mike

[cid:image001.png@01D63D96.FEBFF4F0]
Mike McGuinness
Power Platform Solutions Architect
ITK Consulting
m:
604-812-8363
w:
itk-inc.com<mailto:itk-inc.com>
e: mike.mcguinness@itk.email<mailto:mike.mcguinness@itk.email>
[cid:image002.png@01D63D96.FEBFF4F0]<https://www.facebook.com/itkconsultinginc/>

**Comment by GregFPoirier** [comment]
This should now be resolved.

**Comment by GregFPoirier** [comment]
This should now be resolved.

**Comment by mmcguinness** [comment]
Thanks!

Thanks,
Mike

[cid:image001.png@01D63DB5.648BD970]
Mike McGuinness
Power Platform Solutions Architect
ITK Consulting
m:
604-812-8363
w:
itk-inc.com<mailto:itk-inc.com>
e: mike.mcguinness@itk.email<mailto:mike.mcguinness@itk.email>
[cid:image002.png@01D63DB5.648BD970]<https://www.facebook.com/itkconsultinginc/>
