### ISSUE TITLE
Please invite Travis (seeker25) to the BCDevOps and BCGov Organizations

### ISSUE THREAD

**Issue by WadeBarnes** [BCDevOps/devops-requests#322]
## Step 0
**Are you a member of the BCGOV GitHub Organization already?**
- Yes I am

**Do you actually need the team member to be a member of the organization?**
- Yes.  This team member will be assisting with OpenShift work.

**Are you the admin of your project's BCGOV GitHub Repository?**
- Yes I am.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation
- [x] Done

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
- [x] Done

## Step 4
Are you requesting to:
- [x] Invite a user

## Step 5
Fill out the following fields

* Project Name:
  - SCSS - Supreme Court Viewer
* GitHub Org:
  - bcgov
  - bcdevops
* Full Name:
  - Travis Semple 
* GitHub ID:
  - @seeker25
* GitHub Account 2FA Confirmed:
  - Yes
* Email address:
  - travis8814@gmail.com
  - Travis.Semple@Quartech.com
* Organization:
  - Quartech
* Project Role:
  - Developer
* GitHub Team to Join (if exists):
  - I can handle the team membership once he's added.
* Existing GitHub Repo: 
  - I can handle the repo membership once he's added.

**Comment by caggles** [comment]
Note that this ticket _normally_ only provides access to the bcgov org and that there is another ticket for BCDevOps - however, since you were clear about asking for both in this request, I already added him to BCDevOps and you don't need to create another ticket :)
