### ISSUE TITLE
Update on CPU for hdhclr-prod

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#323]
## Step 0
**Are you the product owner or technical lead?** YES
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here: Confirmed
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ X] CPU: Best Effort (compute-best-effort-quota)
- [ X] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)

## Step 3
Add details about your quota request here:

We require an additional 2 cores per stateful set pod.  So an increase in 6 cores.  Please note we are using the request to be set at 1 core and Max allocated at 5 cores to accommodate the monday spikes.

During COVID, on Monday's we receive a large amount of Isolation Plan workflow forms and staff signing into our system.  As such the primary Patroni master pod is exceeding 3 Cores. Optimization dropped the load from 7 cores to 4cores.   As such, I need to increase our quote to accomodate for this.

After COVID, this demand will not be needed.

## Step 4
Please explain here the reasons for requesting your quota change.
Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

During COVID, on Monday's we receive a large amount of workflow forms and users signing into our system.  As such the primary Patroni master pod is exceeding 3 Cores. Optimization dropped the load from 7 cores to 4cores.   As such, I need to increase our quote to accomodate for this.

After COVID, this demand will not be needed.

We are actively looking at ways to reduce the CPU load.

**Comment by sbarre-esit** [comment]
```console
$ oc -n hdhclr-prod describe resourcequota/compute-long-running-quota
Name:       compute-long-running-quota
Namespace:  hdhclr-prod
Scopes:     NotBestEffort, NotTerminating
 * Matches all pods that have at least one resource requirement set. These pods have a burstable or guaranteed quality of service.
 * Matches all pods that do not have an active deadline. These pods usually include long running pods whose container command is not expected to terminate.
Resource         Used     Hard
--------         ----     ----
limits.cpu       19750m   30
limits.memory    42496Mi  64Gi
pods             17       100
requests.cpu     5450m    10
requests.memory  19188Mi  32Gi
```

**Comment by ShellyXueHan** [comment]
Thank you Steven!
