### ISSUE TITLE
Please Import EDUC-PEN-DEMOG-API Repo on SonarCloud

### ISSUE THREAD

**Issue by andyyang** [BCDevOps/devops-requests#324]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** Yes
We have install SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** Yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/blob/96aba33afef20c1c9003a2c9670206c28f4482ca/README.md#sonarcloud

## Step 2
Fill out the following fields

* Project Name: EDUC-PEN-DEMOG-API
* GitHub repositories to add to SonarCloud: https://github.com/bcgov/EDUC-PEN-DEMOG-API
- 
- 

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
repo included: https://sonarcloud.io/project/configuration?id=bcgov_EDUC-PEN-DEMOG-API @andyyang you are the admin of it.
