### ISSUE TITLE
Human Rights Tribunal - request for KeyCloak Realm

### ISSUE THREAD

**Issue by r-draper-pwc** [BCDevOps/devops-requests#325]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

- Yes

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

- Yes

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

- No

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

- New to it, yes.

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: Human Rights Tribunal

* OpenShift Project Set/s Info
  - Project set name: Human Rights Tribunal
  - Namespace ID: qjtfov

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@r-draper-pwc Hi Ryan, please login to https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console as well. I would need your account created there first. And here's the wiki page: https://github.com/bcgov/ocp-sso/wiki/1.1-OnBoarding.md

**Comment by r-draper-pwc** [comment]
Hi @ShellyXueHan I logged in with github and got this error: Forbidden
You don't have access to the requested resource.

**Comment by ShellyXueHan** [comment]
Please login with your IDIR account. And `Forbidden ` is fine, it's just create your account record so I can grand the role.

**Comment by r-draper-pwc** [comment]
@ShellyXueHan I just logged in with IDIR (finally...after verifying my email :) ) Let me know if it worked, still got the forbidden message

**Comment by ShellyXueHan** [comment]
you are all set, you should now have access to https://realm-o-matic.pathfinder.gov.bc.ca
