### ISSUE TITLE
Add DEV ONLY to Keycloak BCEID realm to vtkayq4c 

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#326]
## Step 0
**Are you the product owner or project admin/team lead?**YEs
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?** YES
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?** 
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)?No

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: TheQ

* OpenShift Project Set/s Info
  - Project set name: TheQ
  - Namespace ID:  servicebc-cfms-dev & others

* For existing KeyCloak realm update only
  - Realm ID: vtkayq4c 
  - Identity Provider to Add
    - [X ] BCeID
    - [ ] GitHub
    - [ X] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - karim.gillani@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: kgillani
* Admin user's Business Email Address: idir\kgillani 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@gil0109 looks like your realm in dev KeyCloak has been deleted. I've recreated the dev realm according to the settings in test. If the realm deletion is unintentional, to prevent that from happening again, you could remove the role from all other admin users. Currently it's got IDIR and BCeID integrations. You'll need to contact IDIM team for BCSC integration.
