### ISSUE TITLE
GitHub Repo request (new user new org) - Robert Kobenter, CITZ IMB

### ISSUE THREAD

**Issue by CITZ-rwk** [BCDevOps/devops-requests#331]
GitHub Repo Request :
- Project Name:  CITZ-IMB-Playbook
- GitHub Org: bcgov
- Full name: Robert Kobenter
- Prefered name for repo: CITZ-IMB-Playbook
- GitHub ID: CITZ-rwk
- Email address: robert.w.kobenter@gov.bc.ca
- Organization: CITZ, IMB
- Project role: Product Owner
- New GitHub Repo: https://github.com/bcgov/CITZ-IMB-Playbook

**Comment by ShellyXueHan** [comment]
@CITZ-rwk you are a member of bcgov org, closing this ticket
