### ISSUE TITLE
New Git Hub repo request - CITZ -IMB

### ISSUE THREAD

**Issue by CITZ-rwk** [BCDevOps/devops-requests#332]
GitHub Repo Request :
- Project Name:  CITZ-IMB-Playbook-Solution
- GitHub Org: bcgov
- Full name: Grant Graham
- Prefered name for repo: CITZ-IMB-Playbook
- GitHub ID: Harpalus
- Email address: internet_mail@shaw.ca
- Organization: CITZ, IMB
- Project role: Technical Steward
-New GitHib Repo: https://github.com/bcgov/CITZ-IMB-Capstone2020

**Comment by ShellyXueHan** [comment]
Hi @CITZ-rwk, are you looking to create a public GitHub repo? If so, I've invited you to bcgov GitHub org. After joining the org, you will be able to create repo there.

**Comment by ShellyXueHan** [comment]
@Harpalus have access to create repos as well. Closing this ticket.
