### ISSUE TITLE
Requesting a new OS Project Set - CITZ-IMB-Capstone

### ISSUE THREAD

**Issue by CITZ-rwk** [BCDevOps/devops-requests#334]
Request for OpenShift Project Set
- [X] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.
- [x] Create a project set
- Short Team/Organization Name: CITZ-IMB 
-Product Short Name: CITZ-IMB-Capstone2020
-Product Full Name:  CITZ IMB Capstone 2020 Playbook Exemplar
-Product Description: An OpenShift hosted responsive web solution demonstrating the use of telemetry to validate the CITZ IMB Solution Playbook
-Desired Environments: tools, dev, test, prod
-GitHub Repository: https://github.com/bcgov/CITZ-IMB-Capstone2020

-Product Technical Steward
  		-GitHub ID: Harpalus
  		- Business Email Address: grant.graham@gov.bc.ca
  		- RocketChat Account Username:  *TBD*
-Product Owner
  		- Business Email Address: robert.w.kobenter@gov.bc.ca
  		- RocketChat Account Username:  CITZ-rwk
  		- Organization Code: CITZ
  		- Organization Unit Code: CITZ-IMB
  		- Ministry Chief Information Officer: Chris Hauff
  		- Ministry Information Security Officer: Gary Mierzuak
  		- Ministry Privacy Officer: Heather Dunlop

**Comment by ShellyXueHan** [comment]
Project set created as `xordpe-tools`, `xordpe-dev`, `xordpe-test`, `xordpe-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Platform-Services-Security/Developer-Guide-to-Zero-Trust-Security-Model-on-the-Platform

**Comment by Harpalus** [comment]
Hello, I received an authentication issue when accessing the Openshift portal for our project.
![Error](https://user-images.githubusercontent.com/4804635/81597237-48821800-937a-11ea-9bb0-cb4c6b145875.png)

**Comment by ShellyXueHan** [comment]
@Harpalus you will need to first accept the invitation to join BCDevOps GitHub organization. After that you will be able to login to OpenShift.

**Comment by Harpalus** [comment]
Hi, I already accepted the invitation and I see the org in my Github organizations profile

**Comment by ShellyXueHan** [comment]
No, you are only in `bcgov` github org but not `BCDevOps`. Please double check on invitation email and try again. (bcgov is where the repo lives, BCDevOps gives you access to OpenShift)

**Comment by Harpalus** [comment]
Okay, can the invitation be resent?

**Comment by ShellyXueHan** [comment]
resent. try now?

**Comment by Harpalus** [comment]
Thanks Shelly, no email received yet...

**Comment by Harpalus** [comment]
No email received yet ...

**Comment by ShellyXueHan** [comment]
I've cancelled the original one and resent.

**Comment by Harpalus** [comment]
You are now a member of Province of British Columbia DevOps!

**Comment by CITZ-rwk** [comment]
No problem I know the issue is in good hands, as long as we have it by Wednesday….

**Comment by Harpalus** [comment]
Worked, now to check access to OpenShift

**Comment by Harpalus** [comment]
I'm in!

Thanks Shelly. :)

**Comment by CITZ-rwk** [comment]
I’d like to say that was easy…

**Comment by ShellyXueHan** [comment]
Nice! So now you will see four namespaces there. You can invite the rest of the team to your namespaces, and make a request here for them to access the cluster.

**Comment by Harpalus** [comment]
Awesome. Can you add the following names to the cluster:
JoshDueck
Murphy316
marchKellyj
Harpalus (admin)
CITZ-rwk (admin)

**Comment by ShellyXueHan** [comment]
@Harpalus please start a new request with type `Request for adding or removing OpenShift access`, we need more info before proceeding. Feel free to combine all users into one ticket. In addition, we only give users access to the cluster, after that, you will need to further invite them to your namespace with a role.
