### ISSUE TITLE
Request for New OpenShift Project Set: RPAS

### ISSUE THREAD

**Issue by TimCsaky** [BCDevOps/devops-requests#335]
New Project Request:

    Short Team/Organization Name: NR Showcase / IITD
    Product Short Name: RPAS
    Product Full Name: RPAS Self Assessments
    Product Description: A Drone Operator Privacy Assessment Form (powered by form.io)
    Product Technical Steward: TimCsaky / tim.csaky@gov.bc.ca / tim.csaky
    Product Owner: Matthew Hall / matthew.hall@gov.bc.ca / matthewhall78
    Desired Environments: tools, dev, test, prod
    GitHub Repository: https://github.com/bcgov/forms-flow-ai

**Comment by ShellyXueHan** [comment]
Project set created as `ebiqwr-tools`, `ebiqwr-dev`, `ebiqwr-test`, `ebiqwr-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Platform-Services-Security/Developer-Guide-to-Zero-Trust-Security-Model-on-the-Platform

**Comment by TimCsaky** [comment]
@ShellyXueHan and @mitovskaol 
Thank you for this.
