### ISSUE TITLE
Revoke access from Jared Burck from Red Hat

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/devops-requests#336]
## Step 0
**Are you the product owner or project admin?** Yup

## Step 1
Are you requesting to:
- [ ] grant user access
- [x ] remove user access

## Step 2
Fill out the following fields

- Full Name: Jared Burck
- GitHub ID: @JaredBurck
- Business Email Address: jared.burck@gmail.com
- Organization: Red Hat
- Project Role: Performing a validation of the cluster health
- OpenShift Projects/Namespaces: N/A bcgov-c/devops-platform-operations-docs#27

Health check is over, closing out #304

**Comment by ShellyXueHan** [comment]
I've removed user from BCDevOps github org. Please remove any namespace/cluster specific access if any.
