### ISSUE TITLE
Authentication Error accessing OpenShift  Main Page

### ISSUE THREAD

**Issue by Harpalus** [BCDevOps/devops-requests#337]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2

* Full Name: Grant Graham
* GitHub ID: @Harpalus
* Business Email Address: Grant.Graham@gov.bc.ca
* Organization: CITZ
* Project Role: Technical Steward
* OpenShift Projects/Namespaces: 
xordpe-tools, xordpe-dev, xordpe-test, xordpe-prod

Also DevOps issue request :
https://github.com/BCDevOps/devops-requests/issues/334
![Error](https://user-images.githubusercontent.com/4804635/81598966-f2fb3a80-937c-11ea-8f95-0ea5ec0b586d.png)

**Comment by ShellyXueHan** [comment]
issue resolved. closing
