### ISSUE TITLE
Adjust Platform Operations team

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/devops-requests#338]
Adjust the team https://github.com/orgs/BCDevOps/teams/platform-operations/members

- Please ADD
  - `tbaker1313`
- Please REMOVE
  - `sincljos`
  - `kelpisland`
- Unsure if we should also remove
  - `sheaphillips`
  - `dkelsey`

**Comment by ShellyXueHan** [comment]
I've add/removed the first three users. The rest would be a question for @mitovskaol ^^^

**Comment by mitovskaol** [comment]
@ShellyXueHan  Please remove `dkelsey` but keep `sheaphillips`

**Comment by ShellyXueHan** [comment]
okay done. I'll remove `kelpisland` as part of his off-boarding.
