### ISSUE TITLE
Request for dormant-site-reclamation-program private repo

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/devops-requests#339]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
YES

**Are you sure you need to have your project code close-sourced?**
Yes, very sure.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: Dormant Site Reclamation Program
* GitHub Org: private 
* Details on choosing private repo: 
* Preferred name for repo: dormant-site-reclamation-program
* Expected date to move to public: 05/2020
* GitHub ID for repo owner: @garywong-bc 
* GitHub Account 2FA Confirmed: yes
* Email address:  Gary.T.Wong@gov.bc.ca
* Organization:  BC Gov
* Project Role: DevOps Chapter Lead
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
https://github.com/bcgov-c/dormant-site-reclamation-program
