### ISSUE TITLE
Create KeyColak Realm for HMR (Highway Maintenance Reporting) development

### ISSUE THREAD

**Issue by ychung-mot** [BCDevOps/devops-requests#34]
## Step 0
**Are you the product owner or project admin/team lead?**
Yes. Young-Jin Chung - Technical Lead

**Do you have an IDIR account?**
Yes

**Are you requesting for Identity Provider Update?**
No

## Step 1
Login to each of the following links using your IDIR credentials. You will and see a the "_Forbidden_" message, but this is expected behaviour and will actually create your initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/idir/console

## Step 2
Fill out the following fields:

* Project Name: Highway Maintenance Reporting
* Admin of Realm (IDIR username + email): 
ychung
young-jin.chung@gov.bc.ca

## Step 3
Once you submit your issued and we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

## Step 4
Only fill out the following fields if you have an realm and need to add an IDP:

* Project Name: 
* Realm ID: 
* Admin of Realm (IDIR username + email): 
* Identity Provider: IDIR or BCeID or GitHub

**Comment by ShellyXueHan** [comment]
@ychung-mot could you also login to this link with your IDIR account to create the user https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console/#

**Comment by ychung-mot** [comment]
@ShellyXueHan Done and I got Forbidden error.

**Comment by ShellyXueHan** [comment]
I've grant your GitHub account `ychung-mot` access to https://realm-o-matic.pathfinder.gov.bc.ca/ Now you could start KeyCloak realm request there.
