### ISSUE TITLE
Add team members to emerging bcgov-c private repo

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/devops-requests#340]
## Step 0

**Are you the Technical Lead?**
YES

**Do you actually need the team member to be a member of the organization?**
YES, as they are not members of bcgov-c, although they are all already members of bcgov

## Step 1
Visit DevHub for detailed instruction on creating a request:

Done.

## Step 2
Make sure no duplicated request exists, search here:

Done

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: dormant-site-reclamation-program
* GitHub Org: private
* Full Name: Dormant Site Reclamation Program
* GitHub ID: @garywong-bc
* GitHub Account 2FA Confirmed: yes or no
* Email address: Gary.T.Wong@gov.bc.ca
* Organization: BC Government
* Project Role: DevOps Chapter Lead
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: 

Eleven Users are:

- bcgov-dsrp
- exzizt
- jhtapia
- JustinMacaulay
- loneil
- nayr974
- pdittaro
- mmumby
- klefler
- Jsyro
- pdittaro

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by garywong-bc** [comment]
Hi, I'm just following up on this request.. the devs were *hoping* that it would get all sorted out this morning.. can we get an ETA please @ShellyXueHan ?? thanks

**Comment by garywong-bc** [comment]
.. and note that the number of devs has been increased.. we're pivoting to a fuller team.

**Comment by ShellyXueHan** [comment]
all users invited.
