### ISSUE TITLE
Adding Users to BCDEvOps

### ISSUE THREAD

**Issue by Harpalus** [BCDevOps/devops-requests#341]
## Step 0
Project Technical Steward

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Josh Dueck, Murphy Li, Kelly Marcheluzzo, Robert Kobenter
* GitHub ID: @JoshDueck, @Murphy316, @marchKellyj, @CITZ-rwk
* Business Email Address: 
* Organization: CITZ
* Project Role: Edit, Edit, Edit, Admin respectively
* OpenShift Projects/Namespaces: 
xordpe-tools, xordpe-dev, xordpe-test, xordpe-prod

Each user is getting authentication error on login to our project namespace..

I think these team members don't have access to the BCDevOps domain. Please add them by sending the invite. After that, I can add them to each of our namespaces.

**Comment by CITZ-rwk** [comment]
Thank you

**Comment by ShellyXueHan** [comment]
users invited.
