### ISSUE TITLE
Request for import GitHub repository ZEVA on SonarCloud

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#342]
## Step 0
**Is your repository on `bcgov` GitHub Organization?** Yes
We have install SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?** Yes
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/blob/96aba33afef20c1c9003a2c9670206c28f4482ca/README.md#sonarcloud

## Step 2
Fill out the following fields

* Project Name: ZEVA
* GitHub repositories to add to SonarCloud:
-- https://github.com/bcgov/zeva.git

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
imported now at: https://sonarcloud.io/dashboard?id=bcgov_zeva @kuanfandevops is the admin.
