### ISSUE TITLE
Private repo for GitOps

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/devops-requests#346]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Yes

**Are you sure you need to have your project code close-sourced?**
Yes; this is for private cluster configuration that could be sensitive. 

**What date will you move your project to open-source?**
Never. This is a GitOps repo for system configuration management that should not be open sourced. 

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
https://github.com/bcgov-c/platform-services-gitops
