### ISSUE TITLE
Access to SSO Prod

### ISSUE THREAD

**Issue by GregFPoirier** [BCDevOps/devops-requests#347]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: Electronic Contract Administration System

* OpenShift Project Set/s Info
  - Project set name: ECAS
  - Namespace ID: yskdol9u

* For existing KeyCloak realm update only
  - Realm ID: yskdol9u
  - Identity Provider to Add
    - [ x] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@GregFPoirier just for a bit more clarity: I saw your comment at https://github.com/BCDevOps/devops-requests/issues/309 about sso-dev not working. While this ticket is for prod. Please specify all the issues you are having.

**Comment by GregFPoirier** [comment]
@ShellyXueHan #309 was my initial assessment. I worked with some experts via rocket chat and we  found that there was some configuration tweaks required. We are now at a point where our production portal gets a Client not found error.   


![image](https://user-images.githubusercontent.com/45373249/82352994-a84c7480-99b3-11ea-96ee-cf4f9c92e5a2.png)

**Comment by ShellyXueHan** [comment]
What's the url you are trying out?

The settings is looking all good to me, BCeID has also been enabled for your prod realm on both sides.

The way to test out BCeID integration with your realm could be done via the realm admin portal: https://sso.pathfinder.gov.bc.ca/auth/admin/yskdol9u/console/#

You could try login with a BCeID there and see if it works. But please note that the BCeID account will not have access to your realm as it's not granted, so you'll see a forbidden error message. Try that and let me know if it's working for you.

**Comment by GregFPoirier** [comment]
Trying workwitheducation.gov.bc.ca
When I attempt the link above I get
![image](https://user-images.githubusercontent.com/45373249/82355016-7ee11800-99b6-11ea-8e91-d49890b4f9fe.png)

then I get the forbidden error

**Comment by ShellyXueHan** [comment]
okay so three things:
- the BCeID integration is working all good as it hits siteminder and comes back
- the `account already exists` error is related to default unique email settings, see https://github.com/bcgov/ocp-sso/issues/68 for details and how to config your realm
- For the error you got from workwitheducation.gov.bc.ca (your application), it's related to the app's client setup in your realm. Have you successfully setup sso for you application in dev/test? Please make sure you have the correct configs on both keycloak client and application. For any further questions, try asking on #sso channel on RockatChat, and please provide details configuration there so the team could help with.

**Comment by GregFPoirier** [comment]
Thanks, good news on BCeID,  Yes we have the application set up for Dev/Test but not with the workwitheducation.gov.bc.ca url, 

Does all the set up happen in sso-dev?  I would have thought that I'd need sso.pathfinder for production?   I don't have access to sso.pathfinder if that is the case

**Comment by ShellyXueHan** [comment]
yea production application should be using the prod sso.pathfinder.gov.bc.ca. I see your IDIR account is the admin of the production realm. What do you see when logging in there?

**Comment by GregFPoirier** [comment]
When I try to log into sso.pathfinder.gov.bc.ca/auth/realms/yskdol9u and click on IDIR as the account I get the Account already exists screen and can't get past that.  My username becomes grpoiri@idir but keeps failing

**Comment by ShellyXueHan** [comment]
I see! there are two IDIR accounts from you and they are conflicting. Did you recently update it or you have 2? Let's move this convo to RocketChat.
