### ISSUE TITLE
Request for BCGOV GitHub Organization Membership - cnburnett

### ISSUE THREAD

**Issue by cnburnett** [BCDevOps/devops-requests#348]
## Step 0

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request. This role should be a member of the BCGOV Github org as part of the team onboarding process.

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed!

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Community Energy & Emissions Database (CEED) Documentation Site
* GitHub Org: bcgov or private
* Full Name: Charles Burnett
* GitHub ID: @cnburnett
* GitHub Account 2FA Confirmed: yes
* Email address: charles.burnett@gov.bc.ca
* Organization: Ministry of Energy, Mines & Petroleum Resources
* Project Role: Technical Lead
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: yes, private - https://github.com/cnburnett/ceeddocs - Jekyl site with instructions for using CEED (a Dynamics 365 Cloud application for managing clean energy grant applications; 9 user seats from EMPR and MIRR) - we are following suggestions from the EPIC team to do documentation/instructions better via OpenShift.

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
hi @cnburnett - we don't generally permit people to request access for themselves. Please see Step 0!

**Comment by cnburnett** [comment]
hi caggles, Step 0 says the following so I submitted a request:

"If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed!"

Happy to talk to someone from PET. thx

**Comment by caggles** [comment]
I see - we will clarify the language there then, as it helps a lot if the request includes an explicit mention that you're looking for a meeting :)
Have you had an onboarding meeting with Olena during the process of making a project set request?

**Comment by caggles** [comment]
hi @cnburnett - have you been able to schedule a meeting with Olena for this yet?

**Comment by mitovskaol** [comment]
I've added cnburnett to bcgov org.
