### ISSUE TITLE
AG/PSSG BCGov-C and BCDevOps Organization Membership Request

### ISSUE THREAD

**Issue by rloisell** [BCDevOps/devops-requests#349]
## Step 0

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request. This role should be a member of the BCGOV Github org as part of the team onboarding process.

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed!

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

Sent via email to pathfinder@gov.bc.ca - #533 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by rloisell** [comment]
Hello, in addition to BCGov-C membership, can this request also add BCDevOps membership. 

CC: @ShellyXueHan  @caggles

**Comment by ShellyXueHan** [comment]
invited to BCDevOps as well.
