### ISSUE TITLE
Request New User Access to OpenShift

### ISSUE THREAD

**Issue by rturgano** [BCDevOps/devops-requests#35]
## Step 0
**Are you the product owner or project admin?**
 **YES**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?** 
**The user does have one.**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?** 
**I believe the user has it enabled using Dashlane to generate the token.**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Barrett Falk
* GitHub ID: @barrfalk
* Business Email Address: bfalk@salussystems.com
* Organization: Salus Systems Ltd.
* Project Role: Contractor
* OpenShift Projects/Namespaces: 
zffq6u-tools, zffq6u-dev, zffq6u-test, zffq6u-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by rturgano** [comment]
This new system is cool.

**Comment by caggles** [comment]
hi @rturgano - we're glad you think so :)
brett should have an email arriving in his inbox shortly, all he needs to do is accept his invitation to the BCDevOps github org, and he'll be able to log in!
