### ISSUE TITLE
Please add the following projects to SonarCloud

### ISSUE THREAD

**Issue by arcshiftsolutions** [BCDevOps/devops-requests#354]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have install SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: 
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/EDUC-PEN-REQUEST-SAGA-API
- https://github.com/bcgov/EDUC-STUDENT-PROFILE-SAGA-API
- https://github.com/bcgov/EDUC-STUDENT-PROFILE-API
- https://github.com/bcgov/EDUC-STUDENT-PROFILE
- https://github.com/bcgov/EDUC-STUDENT-PROFILE-EMAIL-API
- https://github.com/bcgov/EDUC-PEN-REQUEST-EMAIL-API
- https://github.com/bcgov/EDUC-PEN-DEMOG-API
- https://github.com/bcgov/EDUC-STUDENT-API
- https://github.com/bcgov/EDUC-PEN-REQUEST
- https://github.com/bcgov/EDUC-PEN-REQUEST-API
- https://github.com/bcgov/EDUC-SERVICES-CARD-API
- https://github.com/bcgov/EDUC-STUDENT-ADMIN
- https://github.com/bcgov/EDUC-SOAM-API
- https://github.com/bcgov/EDUC-DIGITALID-API

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.
- mishraomp -> Omprakash Mishra
- mightycox -> John Cox
- andyyang -> Mingwei Yang
- sharifreer -> Shari Freer

**Comment by ShellyXueHan** [comment]
all repos added, @arcshiftsolutions is the admin.

**Comment by arcshiftsolutions** [comment]
Thanks @ShellyXueHan !
