### ISSUE TITLE
New Workspace request: Redhat Workflow Application

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#357]
## Step 0
**Are you the product owner or technical lead?** YES
If not, you will need to ask one of those two people to make this request.

If you are one of these two people, please ensure that you also request Openshift access if you don't have it already. This request does NOT grant you access to the platform itself - you will find a separate request for that on the issues page of this repo!
However, you may submit both requests at the same time - there's no need to wait until that request has been completed to submit this one.

**Have you had an alignment meeting?** Yes
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

Read through the Platform Onboarding Guide before continue with this request. This helps to get clear expectations of the platform and how to collaborate with the Platform community alone the journey:
https://developer.gov.bc.ca/Welcome-to-our-Platform-Community!

- [X ] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Make sure no duplicated request exists, search here: Confirmed
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: Strategic Initiatives/ServiceBC
* Product Short Name: SBC_BPMS
* Product Full Name: Service BC Service Workflow
* Product Description: Business Process Management Solution for Service BC
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): Not yet.  RedHat deployment.  Will add to SBC_DIVAPPS if fun

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
Project set created as `nzpnbz-tools`, `nzpnbz-dev`, `nzpnbz-test`, `nzpnbz-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
