### ISSUE TITLE
Request to add InvasivesBC (lucy-web) project to SonarCloud

### ISSUE THREAD

**Issue by andrea-williams** [BCDevOps/devops-requests#359]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have install SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: 
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/lucy-web
- 

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
@andrea-williams please ask one of the repo admin to response to this ticket. I'll need someone with admin access to be assigned as the admin on sonarcloud.

**Comment by andrea-williams** [comment]
hi @ShellyXueHan I am a repo admin for lucy-web. The other admin for it is @micheal-w-wells

**Comment by ShellyXueHan** [comment]
@andrea-williams I don't see you in the github org so made @micheal-w-wells the admin on sonarcloud.
