### ISSUE TITLE
Access Request for Cloud Pathfinder

### ISSUE THREAD

**Issue by juhewitt** [BCDevOps/devops-requests#361]
## Step 4
Are you requesting to:
- [x] Invite a user(s)

Per my email to the pathfinder inbox, subject: Cloud Pathfinder GitHub Access Request

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@ActionAnalytics all three users invited to three GitHub orgs and corresponding team for cluster access. Please note that to create repo in bcgov-c, you will need to request for the repo separately.

**Comment by ActionAnalytics** [comment]
Thank you Shelly!
