### ISSUE TITLE
Request for import of Predictive Services Unit repositories on SonarCloud

### ISSUE THREAD

**Issue by Sybrand** [BCDevOps/devops-requests#365]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have install SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Yes.**

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

**Yes**

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

**Done**

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Wildfire Predictive Services Unit
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/wps
- https://github.com/bcgov/wps-api
- https://github.com/bcgov/wps-web

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
repos added, @Sybrand is admin for all three.
