### ISSUE TITLE
AG/PSSG OpenShift Project Set Request - EMBC EAF

### ISSUE THREAD

**Issue by rloisell** [BCDevOps/devops-requests#366]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

If you are one of these two people, please ensure that you also request Openshift access if you don't have it already. This request does NOT grant you access to the platform itself - you will find a separate request for that on the issues page of this repo!
However, you may submit both requests at the same time - there's no need to wait until that request has been completed to submit this one.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

Read through the Platform Onboarding Guide before continue with this request. This helps to get clear expectations of the platform and how to collaborate with the Platform community alone the journey:
https://developer.gov.bc.ca/Welcome-to-our-Platform-Community!

- [x] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4

submitted via email to pathfinder@gov.bc.ca

## Step 5

submitted via email to pathfinder@gov.bc.ca

Please note that we will only start processing your request when the email has been received.

**Comment by rloisell** [comment]
https://justice.gov.bc.ca/jira/browse/EMISBC-285

**Comment by ShellyXueHan** [comment]
@rloisell please go through Step 1 and provide the confirmation, thx!

**Comment by rloisell** [comment]
@ShellyXueHan  - done!

**Comment by rloisell** [comment]
@mitovskaol @caggles @ShellyXueHan - any ETA on this Project Set? This project team is now stalled and this effort was high priority in response to COVID-19. 

CC: @juhewitt

**Comment by mitovskaol** [comment]
@rloisell I apologize for the delay. We will process the request first thing Monday morning.

**Comment by ShellyXueHan** [comment]
@rloisell Project set created as `cysswk-tools`, `cysswk-dev`, `cysswk-test`, `cysswk-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
