### ISSUE TITLE
Request for BCGOV GitHub Organization Membership

### ISSUE THREAD

**Issue by marklise** [BCDevOps/devops-requests#368]
## Step 0

**Are you the Technical Lead?**
Yes

**Do you actually need the team member to be a member of the organization?**
Yes

## Step 1
Done

## Step 2
Done

## Step 4
- [x] Invite a user

## Step 5
GitHub User Access Request:
- Project: BCMI
- GitHub Org: bcgov
- Full name: Morgan Thompson
- GitHub ID: mtCarto
- Email address: Morgan.Thompson@gov.bc.ca
- Organization: IITD
- Project role: Full-stack Developer
- Existing GitHub Repo: https://github.com/bcgov/nrpti, https://github.com/bcgov/eagle-api, https://github.com/bcgov/eagle-admin, https://github.com/bcgov/eagle-public, ....

GitHub User Access Request:
- Project: BCMI
- GitHub Org: bcgov
- Full name: Dylan Hemsworth
- GitHub ID: dhlevi
- Email address: Dylan.Hemsworth@gov.bc.ca
- Organization: Vivid Solutions
- Project role: Full-stack Developer
- Existing GitHub Repo: https://github.com/bcgov/nrpti, https://github.com/bcgov/eagle-api, https://github.com/bcgov/eagle-admin, https://github.com/bcgov/eagle-public, ....

GitHub User Access Request:
- Project: BCMI
- GitHub Org: bcgov
- Full name: Kit Armstrong
- GitHub ID: Kit.Armstrong
- Email address: Kit.Armstrong@gov.bc.ca
- Organization: NTTData
- Project role: Full-stack Developer
- Existing GitHub Repo: https://github.com/bcgov/nrpti, https://github.com/bcgov/eagle-api, https://github.com/bcgov/eagle-admin, https://github.com/bcgov/eagle-public, ....

**Comment by caggles** [comment]
hi @marklise - github tells me there is no such github user named Kit.Armstrong - can you please double check the username and get back to me? thank you!

**Comment by marklise** [comment]
> hi @marklise - github tells me there is no such github user named Kit.Armstrong - can you please double check the username and get back to me? thank you!

Apologies!  I put a . in there by accident.  `KitArmstrong` is the correct user.
