### ISSUE TITLE
Gluster Block quota for perrsi-tools

### ISSUE THREAD

**Issue by vesalink** [BCDevOps/devops-requests#369]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Best Effort (compute-best-effort-quota)
- [ ] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
- [x ] Storage: Gluster Block (storage-gluster-block-quota)

## Step 4
Temporary, while netapp-block storage having issues

**Comment by sbarre-esit** [comment]
```
$ oc -n perrsi-tools describe quota storage-gluster-block-quota
Name:                                                             storage-gluster-block-quota
Namespace:                                                        perrsi-tools
Resource                                                          Used  Hard
--------                                                          ----  ----
gluster-block.storageclass.storage.k8s.io/persistentvolumeclaims  9     20
gluster-block.storageclass.storage.k8s.io/requests.storage        70Gi  200Gi
```

I still need to document this in https://github.com/bcgov-c/platform-ops/tree/master/playbooks/run/quota-applyer/quotas

**Comment by sbarre-esit** [comment]
We believe the `netapp-block-standard` provisioning is fixed now. At your leisure please give it a test in your dev namespaces and let us know if you find any issues in #devops-operations.
