### ISSUE TITLE
Gluster Block quota for perrsi-dev

### ISSUE THREAD

**Issue by vesalink** [BCDevOps/devops-requests#371]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Best Effort (compute-best-effort-quota)
- [ ] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [x ] Storage: Gluster Block (storage-gluster-block-quota)

## Step 3
Add details about your quota request here:

*ex: Please increase number of PVCs that can be provisioned to 30.*

## Step 4
Temporary, while netapp-block storage having issues

**Comment by sbarre-esit** [comment]
```
$ oc -n perrsi-dev describe quota storage-gluster-block-quota
Name:                                                             storage-gluster-block-quota
Namespace:                                                        perrsi-dev
Resource                                                          Used  Hard
--------                                                          ----  ----
gluster-block.storageclass.storage.k8s.io/persistentvolumeclaims  0     20
gluster-block.storageclass.storage.k8s.io/requests.storage        0     200Gi
```

**Comment by sbarre-esit** [comment]
We believe the `netapp-block-standard` provisioning is fixed now. At your leisure please give it a test in your dev namespaces and let us know if you find any issues in #devops-operations.
