### ISSUE TITLE
Gluster Block quota for wlev6y-tools

### ISSUE THREAD

**Issue by ll911** [BCDevOps/devops-requests#372]
## Step 0
**Are you the product owner or technical lead?**
yes

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Best Effort (compute-best-effort-quota)
- [ ] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
- [x] Storage: gluster-block

## Step 3
please increase gluster-block to 50gb until storage-netapp-block back to normal

## Step 4
INC0036698 MCS - NetApp block provisioning failing due to LUN ID

**Comment by sbarre-esit** [comment]
Done.

**Comment by sbarre-esit** [comment]
We believe the `netapp-block-standard` provisioning is fixed now. At your leisure please give it a test in your dev namespaces and let us know if you find any issues in #devops-operations.
