### ISSUE TITLE
Gluster Block quota for tbiwaq-*

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#378]
## Step 0
**Are you the product owner or technical lead?** Yes
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Best Effort (compute-best-effort-quota)
- [ ] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
- [ X] Storage: Gluster-block

## Step 3
Add details about your quota request here:

*ex: Please increase number of gluster-block that can be provisioned to max number 10 and max size 27G

## Step 4
Please explain here the reasons for requesting your quota change.
Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.
here is how I calculater the max number 10 and size 27G
dev: 6 pull request, each takes 2G
test: 1 pull request, takes 5G
prod: 1 pull request takes 10G

**Comment by sbarre-esit** [comment]
Done.

@ShellyXueHan can you rename this to be for tbiwaq-* ?
