### ISSUE TITLE
Gluster block storage request for CAS GGIRCS

### ISSUE THREAD

**Issue by Maralsotoudehnia** [BCDevOps/devops-requests#380]
## Step 0
**Are you the product owner or technical lead?** 
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [X ] GLUSTER BLOCK STORAGE
- [ ] CPU: Best Effort (compute-best-effort-quota)
- [ ] CPU: Long Running (compute-long-running-quota)
- [ ] CPU: Time Bound (compute-time-bound-quota)
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)

## Step 3
Add details about your quota request here: 

Per a discussion with Platform Services, IITD, and CAS, I'd like to request 200gb of storage-gluster-block-quota and 20 PVCs for each of the following namespaces: 

- wksv3k-tools
- wksv3k-dev
- wksv3k-test
- wksv3k-prod

*ex: Please increase number of PVCs that can be provisioned to 30.*

## Step 4
Please explain here the reasons for requesting your quota change.
Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

Per discussion on June 03 2020 at 9:30AM about netapp/gluster with Platform Services, IITD, and CAS, we are following a resolution path recommended by DevOps and IITD technical leads. CC @sbarre-esit

**Comment by sbarre-esit** [comment]
Done!
