### ISSUE TITLE
: DevOps Openshift Platform Maintenance Schedule Changes

### ISSUE THREAD

**Issue by langerhayes** [BCDevOps/devops-requests#382]
the following resources are Tech Leads on projects with OpenShift architecture.  I would like to have them added to the distribution list advising of any changes or information related to OpenShift.

rafael.poncedeleon@quartech.com                OpenShift Architect  EMBC project and Pill Press AMS
Colin.bales@quartech.com                               Technical Lead - EMBC project
George.Walker@quartech.com                       Sr. OpenShift and DevOps Architect LCRB, SPICE, CSU
Manivakis.anjupoju@quartech.com                SR, Dynamics Architecht - Victims Services

What annotations/labels need to be changed? (Select all that apply)
- [ ] Product Owner
- [ X] Technical Steward
- [ ] Security Contacts

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Link to the GitHub ticket you just created

*Project Set Info*
  - Namespaces:

*Product Technical Steward*
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username:
   
*Product Owner*
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

*BC Government Security Contact Information*
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)
  
  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by caggles** [comment]
hi @langerhayes - please provide the actual namespace names that need to be updated!

**Comment by langerhayes** [comment]
Hi there,

I don’t actually want them to receive notification via GitHub I would like them to receive the email that is sent out.

Please see attached.

Thank you



[Title: Quartech Logomark - Description: Quartech Logomark]<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.quartech.com_&d=DwMFAg&c=09aR81AqZjK9FqV5BSCPBw&r=UouipknnT6eniGrOOUG0F2prjZNwNQWDDmDpDFGuJmg&m=R8P-zxqgRFbkuy1wI-vPRlOIXVLYLEC8hmRDBKiKMZw&s=G8Lz0rNXLDldUreZd4AalOE5izASx8r9MJDbSRPUaLI&e=>
Janys Hayes
Account Executive
janys.hayes@quartech.com<mailto:janys.hayes@quartech.com>
Quartech Victoria Office: 200 – 1012 Douglas Street, Victoria BC  V8W 2C3 (250) 380-9686 | www.Quartech.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.quartech.com_&d=DwMFAg&c=09aR81AqZjK9FqV5BSCPBw&r=UouipknnT6eniGrOOUG0F2prjZNwNQWDDmDpDFGuJmg&m=R8P-zxqgRFbkuy1wI-vPRlOIXVLYLEC8hmRDBKiKMZw&s=G8Lz0rNXLDldUreZd4AalOE5izASx8r9MJDbSRPUaLI&e=>
IMPORTANT: This email is sent on behalf of Quartech Systems Ltd. and may be privileged, proprietary or confidential. If you are not the intended recipient or a person responsible for delivering this email to the intended recipient, you may not disclose, copy or distribute this email or take any action in reliance on it. If you received this email in error, please notify us immediately by calling (604) 291-9686 and please delete this email and any associated attachments. Thank you.

**Comment by caggles** [comment]
hi @langerhayes - the mailing list isn't manually updated. The list of recipients for it is drawn from a list of annotations we apply to specific namespaces. All the namespaces on the cluster have annotations that tell us who the associated product owners and technical leads are. We will need to add these names as technical leads to the correct projects and, from there, their emails will automatically be included in the mailing list. So I need the namespaces for which they are technical leads in order to add them!

**Comment by caggles** [comment]
hi @langerhayes please provide the namespaces so we can add these people as technical contacts for the mailing lists!
