### ISSUE TITLE
Access Request for afanrasool on PESCI namespaces

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/devops-requests#383]
## Step 0
**Are you the product owner or project admin?**

The team lead is @jeremy-vernon-bcgov

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Afan Rasool
* GitHub ID: @afanrasool
* Business Email Address: afan.rasool@arctiq.ca 
* Organization: Arctiq Inc.
* Project Role: OpenShift Consultant (Read access only)
* OpenShift Projects/Namespaces: 
whamor-tools
whamor-dev
whamor-test
whamor-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by stewartshea** [comment]
@jeremy-vernon-bcgov @afanrasool ^

**Comment by stewartshea** [comment]
@caggles @afanrasool  is not able to see the requested projects, can you please advise?

**Comment by afanrasool** [comment]
@caggles Any update on this? I'm still waiting for access to the projects.
