### ISSUE TITLE
Provision new Openshift Space Family Law Act File Submission

### ISSUE THREAD

**Issue by akroon3r** [BCDevOps/devops-requests#390]
## Step 0
**Are you the product owner or technical lead?**
No - Emailing pathfinder@gov.bc.ca with contact info

If you are one of these two people, please ensure that you also request Openshift access if you don't have it already. This request does NOT grant you access to the platform itself - you will find a separate request for that on the issues page of this repo!
However, you may submit both requests at the same time - there's no need to wait until that request has been completed to submit this one.

**Have you had an alignment meeting?**
No - currently in the process of booking an alignment meeting with Olena Mitovkska

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

Read through the Platform Onboarding Guide before continue with this request. This helps to get clear expectations of the platform and how to collaborate with the Platform community alone the journey:
https://developer.gov.bc.ca/Welcome-to-our-Platform-Community!

- [x] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: NTT Data
* Product Short Name: FLAFS
* Product Full Name: Family Law Act File Submission
* Product Description: Generic File Submission API (to be used by the Family Law Act Application at first)
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/jag-file-submission

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

- [x] Email sent

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
@akroon3r  Project set created as `qzaydf-tools`, `qzaydf-dev`, `qzaydf-test`, `qzaydf-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
