### ISSUE TITLE
Request for private repo

### ISSUE THREAD

**Issue by bluemel-gov** [BCDevOps/devops-requests#392]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Yes.

**Are you sure you need to have your project code close-sourced?**
Yes, this is a temporary limited requested by the cloud platform provider's legal department while they determine how to handle landing zone deployments. 

**What date will you move your project to open-source?**
Aiming for early 2021, pending legal and contract agreement with vendor.

## Step 1
Make sure no duplicated request exists, search here:
DONE.

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: aws-landing-zone
* GitHub Org: private
* Details on choosing private repo: 
* Preferred name for repo: aws-landing-zone
* Expected date to move to public: 01/2021
* GitHub ID for repo owner: @ActionAnalytics 
* GitHub Account 2FA Confirmed: yes 
* Email address: Julian.subda@gov.bc.ca
* Organization: OCIO Cloud Pathfinder
* Project Role:  Product Owner
* GitHub Team to Join (if exists): n/a

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
repo created and access sorted out already. CLosing.

**Comment by ActionAnalytics** [comment]
The repo was already there as of April.  Looks like we've got everything sorted out, thanks everyone.
