### ISSUE TITLE
Request to remove a duplicate user from KeyCloak

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#394]
## Step 0
**Are you the KeyCloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account? 
   Due to a name change the user's IDIR account was changed from bkaines to bwahl back in March, 2020.  The current KeyCloak account username still has the old IDIR account.

- What result of debugging have you obtained that lead you to request an account removal?
I deleted the current KeyCloak account from SSO realm vtkayq4c and had the user login to our application.  The KeyCloak account that was created still uses the old IDIR account (bkaines@idir) for the username.

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from KeyCloak
    If possible please remove the account from KeyCloak before 8:30am as this is when the Service BC office opens in which the user works.

## Step 3
Field the following information.

* Username to be removed: bkaines@idir
* Realm ID where user is having problem login:   vtkayq4c

**Comment by jhmccoll** [comment]
Hi Shelly
 Yes please remove the account.

Thank you
John

**Comment by ShellyXueHan** [comment]
okay user removed from KeyCloak.
