### ISSUE TITLE
Add team as admin to repo

### ISSUE THREAD

**Issue by SteveMHoward** [BCDevOps/devops-requests#395]
Are you requesting to:
- [x] Invite a team
- [ ] Remove a user

* Project Name: bcgov-looker-snowplow
* GitHub Org: bcgov
* Full Name: bcgov-looker-snowplow
* GitHub ID: @SteveMHoward
* GitHub Account 2FA Confirmed: yes
* Email address: Steve.M.Howard@gov.bc.ca
* Organization: GDX
* Project Role: Owner
* GitHub Team to Join (if exists): GDX Engagement (Admin)
* Existing GitHub Repo: https://github.com/bcgov/bcgov-looker-snowplow

The template seems to be missing what I need... Please make the team "GDX Engagement (Admin)" as full admin for the repo https://github.com/bcgov/bcgov-looker-snowplow.

I just transferred this repo to the "bcgov" GitHub org, and told it to add our team as admin, but it didn't for some reason...

**Comment by ShellyXueHan** [comment]
@SteveMHoward seemed that it's because you were not the admin of the repo, instead you only got write access. So I've made you the admin there, you should now be able to invite the GH team.
