### ISSUE TITLE
Request to change member role change for GJLAWRAN and DKELSEY to Owner for BCGOV AND BCGOV-C

### ISSUE THREAD

**Issue by gjlawran** [BCDevOps/devops-requests#396]
## Step 0

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request. This role should be a member of the BCGOV Github org as part of the team onboarding process.

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed! **Please indicate in this ticket if you need to schedule this meeting.** 
If you've already had a meeting as part of a request for an Openshift Project, please indicate that in the ticket as well.

**Do you actually need the team member to be a member of the organization?**

We have multiple repositories and teams as part of the bcgov and bcgov-c organizations that we need manage membership for and update ownership of. 
e.g. https://github.com/orgs/bcgov/teams?query=databc 

The persons who had Owner role privileges have moved into a new Ministry.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user - DKELSEY to BCGOV-C
- [X] Change member roles for both DKELSEY and GJLAWRAN to owner in both organizations
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: 
* GitHub Org: bcgov  and bcgov-c
* Full Name:  
* GitHub ID: @ gjlawran and dkelsey
* GitHub Account 2FA Confirmed: yes 
* Email address:  greg.lawrance@gov.bc.ca
* Organization: Data Systems and Services Branch - DataBC
* Project Role: Director of Technology
* GitHub Team to Join (if exists): -multiple
* Existing GitHub Repo:  - multiple

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hello @gjlawran - can you please clarify what it is you're looking for? Ownership of the bcgov organizations is generally reserved for those working in platform services. Is this actually what you're looking for, or have I misunderstood?

**Comment by caggles** [comment]
Closing as per our meeting today - another ticket should be opened outlining the necessary permission changes to specific repos.

Note also that the current repo admins can change your role to admin as well, if that would be faster than getting their approval.
