### ISSUE TITLE
Remove - zcd4ou-*** - Registration of Benefit Companies

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#398]
- [x] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 3
Are you requesting to:
- [ ] ~~Create a project set~~
- [x] Remove a project set

## Step 4
Fill out the following fields:

I don't know these values, but I have checked that no current team or users are using this namespace. I have also removed everything from these namespaces so they should be all empty.

* Short Team/Organization Name: 
* Product Short Name: 
* Product Full Name: 
* Product Description: 
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists):

**Comment by ShellyXueHan** [comment]
@thorwolpert thank you for the request. Project set deleted.
