### ISSUE TITLE
InvasivesBC SonarCloud request - separate projects for front & back end

### ISSUE THREAD

**Issue by andrea-williams** [BCDevOps/devops-requests#399]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have install SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Yes**.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

**Yes**.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: InvasivesBC (aka SEISM)
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/lucy-web

We already have 1 project space on SonarCloud for our GitHub repo, but we're hoping to be able to set up a second project space so that we can separate out the analysis & test coverage of our front-end vs our back-end. The code for our front- & back-ends are both in the same GH repo. Is it possible to have 2 separate projects in SonarCloud for the same repo?

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
@andrea-williams I don't see any admin action for that. Looks like projects and repos are 1-1. Have you done some researches on this? If you find something that could need admin access, please reopen this ticket. Thank you!
