### ISSUE TITLE
Getting namespaces for ExchangeLabOps repos

### ISSUE THREAD

**Issue by thegentlemanphysicist** [BCDevOps/devops-requests#4]
## Step 0
**Are you the product owner or technical lead?**
I am the technical lead
If not, you will need to ask one of those two people to make this request.

**Have you had an alignment meeting?**
No, but I have chatted with Shea about setting this up.
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: ExLO
* Product Short Name: ExchangeLabOps
* Product Full Name: Exchange Lab Ops
* Product Description: Resource for those seeking information about the services offered by the exchange lab.
* Desired Environments: tools, dev, test, prod
* Product Technical Steward
  - GitHub ID: @thegentlemanphysicist 
  - Business Email Address: Jonathan.Sharman@gov.bc.ca
  - RocketChat Account Username: jsharman
* Product Owner
  - Business Email Address: Heather.Remacle@gov.bc.ca
  - RocketChat Account Username: heather.remacle
* GitHub Repository: https://github.com/bcgov/ExchangeLabOps

**Comment by kelpisland** [comment]
@thegentlemanphysicist - let's have a chat today. Want to understand what connections to bedevexchange.org and devhub are part of the vision.

**Comment by thegentlemanphysicist** [comment]
@kelpisland  I'm flexing today, but we could chat Tuesday if you're in.

**Comment by kelpisland** [comment]
Good to go 💯

**Comment by ShellyXueHan** [comment]
@thegentlemanphysicist Project set created as `fpgket-tools`, `fpgket-dev`, `fpgket-test`, `fpgket-prod`. `thegentlemanphysicist` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.

**Comment by thegentlemanphysicist** [comment]
> @thegentlemanphysicist Project set created as `fpgket-tools`, `fpgket-dev`, `fpgket-test`, `fpgket-prod`. `thegentlemanphysicist` is the admin of all four namespaces.
> Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
> For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.

Thanks Shelly!
