### ISSUE TITLE
Temporary private repo to house CMS site

### ISSUE THREAD

**Issue by micheal-w-wells** [BCDevOps/devops-requests#402]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. Please include a firm date by which you will move your repository to the open organization.

ASAP - Soon as we have time to filter the project down to what can be open sourced.  This is just a place to put the raw file transfer provided by the vendor who previously managed the site.  The repo (and it's issues to track the work) already exist at https://github.com/bcgov/IRIS

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: IRIS
* GitHub Org:  private
* Details on choosing private repo: temp place to house code/project handed over from vendor
* Preferred name for repo: IRIS-private
* Expected date to move to public: 09/2020
* GitHub ID for repo owner: @micheal-w-wells 
* GitHub Account 2FA Confirmed: yes 
* Email address: micheal.w.wells@gov.bc.ca
* Organization: bcgov
* Project Role: Lead dev
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@micheal-w-wells  https://github.com/bcgov-c/IRIS-private
