### ISSUE TITLE
NR-MALS-Ministry-of-Agriculture-Licensing-System New Openshift Project Request

### ISSUE THREAD

**Issue by webgismd** [BCDevOps/devops-requests#403]
## Step 0
**Are you the product owner or technical lead?**

If not, you will need to ask one of those two people to make this request.

If you are one of these two people, please ensure that you also request Openshift access if you don't have it already. This request does NOT grant you access to the platform itself - you will find a separate request for that on the issues page of this repo!
However, you may submit both requests at the same time - there's no need to wait until that request has been completed to submit this one.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

Read through the Platform Onboarding Guide before continue with this request. This helps to get clear expectations of the platform and how to collaborate with the Platform community alone the journey:
https://developer.gov.bc.ca/Welcome-to-our-Platform-Community!

- [ ] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: NR
* Product Short Name: MALS
* Product Full Name: Ministry of Agriculture Licensing System
* Product Description: The Ministry of Agriculture Licencing System (MALS) was created with intent of being a single licensing application, replacing various disparate Animal Industry Branch licensing applications. 
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): none (needs to be created)

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

**Comment by MikeLyttle** [comment]
I'm the technical lead and will be following up with the contact information in an email.

**Comment by ShellyXueHan** [comment]
@MikeLyttle Project set created as `bsoszr-tools`, `bsoszr-dev`, `bsoszr-test`, `bsoszr-prod`.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
