### ISSUE TITLE
Request for BCGOV GitHub Organization Membership - henry_ngo

### ISSUE THREAD

**Issue by henry-ngo** [BCDevOps/devops-requests#404]
## Step 0

>**Are you the Technical Lead?**
>If you do not have access to a Technical Lead to ask for membership on your behalf, or the >Technical Lead has not yet obtained the membership, a member of the Platform Experience team >will contact you about your request once you have submitted it.
>We will need to discuss your needs in a quick meeting before this request can be processed! >**Please indicate in this ticket if you need to schedule this meeting.** 

**I am the technical lead but no one on our team has membership. I would like to request a meeting as per the instructions above to figure out how to proceed**

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: see note below
* GitHub Org: bcgov 
* Full Name: Henry Ngo
* GitHub ID: @henry_ngo
* GitHub Account 2FA Confirmed: yes
* Email address:  Henry.Ngo@gov.bc.ca
* Organization: Ministry of Health / Office of the Provincial Health Officer
* Project Role:  Technical lead
* GitHub Team to Join (if exists): new team
* Existing GitHub Repo: see note below

Note: I'm not quite sure what to fill in for these fields. I am trying to apply for membership in the BCGov GitHub organization and this will be followed by some repository requests for various projects by our team. The first repository/project I hope to put on GitHub is:

epi.branch.sim: An R package to simulate evolution of infectious diseases through a branching process

We started this process a few months ago and with advice from some people here, we were told to follow the Open Content Assessment. The processes on that list hasn't been developed yet for our Ministry so in the past few months, we've worked with the privacy, security and legal branches of HLTH to develop these processes. So this will be hopefully the first repo from our team on GitHub, with plans for more in the future. (So I am not sure if the project should just be this one repository or everything in general?)

**Comment by ShellyXueHan** [comment]
Hi @henry-ngo are you going to deploy applications on the OpenShift Platform or just use GitHub to host some codes?

**Comment by henry-ngo** [comment]
Hi @ShellyXueHan ! For now, just use GitHub to host some code. Our team is interested in OpenShift but we are not sure if we can get the right approvals from our Ministry yet. Thanks!

**Comment by ShellyXueHan** [comment]
@henry-ngo usually we don't proceed with self-requested tickets and `bcgov` repositories are meant for application teams who's working on OpenShift platform. But since your team might be moving to the platform, let's involve our platform product owner Olena here and discuss about this case. @mitovskaol could you like to have a quick on-boarding meeting with Henry?

**Comment by henry-ngo** [comment]
Thanks!

@mitovskaol: Would love to chat this week on Wed or Thurs. I'll be taking a few days off starting Friday and won't be back until July 2. If one of the times in the next 2 days won't work, then hope to catch you in early July :)

**Comment by mitovskaol** [comment]
@henry-ngo I am familiar with the work that your team is doing. I am going to approve the request, no need for the alignment meeting.

**Comment by henry-ngo** [comment]
Thanks @mitovskaol !

**Comment by ShellyXueHan** [comment]
sounds good. @henry-ngo I've invited you to `bcgov` GH org.
