### ISSUE TITLE
GitHub Repository request

### ISSUE THREAD

**Issue by merwynp** [BCDevOps/devops-requests#406]
## Step 0

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request. This role should be a member of the BCGOV Github org as part of the team onboarding process.

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed! **Please indicate in this ticket if you need to schedule this meeting.** 
If you've already had a meeting as part of a request for an Openshift Project, please indicate that in the ticket as well.

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: CIT
* GitHub Org: bcgov
* Full Name: Merwyn Pereira
* GitHub ID: @merwynp
* GitHub Account 2FA Confirmed: yes
* Email address: merwyn.pereira@gov.bc.ca
* Organization: BC Public Service - Ministry of Jobs, Economic Development and Competitiveness
* Project Role: Business Analyst
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by merwynp** [comment]
Any update on this ticket? @caggles @ShellyXueHan

**Comment by ShellyXueHan** [comment]
Hi @merwynp do you have a team on OpenShift platform already? Is the product owner to technical lead available to jump onto this request? As mentioned in the request template, we are expecting the PO or tech lead to make access requests for the team members.

**Comment by stephenrphillips** [comment]
@ShellyXueHan @caggles I have been tapped as the PO for this project.  Do I need to submit a new request for setting up a repo for our CIT project?

**Comment by ShellyXueHan** [comment]
Hi @stephenrphillips does your team have an OpenShift project set (namespaces) already? If so, please list the namespaces. `bcgov` repository are normal meant for teams who are on the OpenShift platform. Does that apply to your team or are you just looking for a place for version control?  Thanks!

**Comment by stephenrphillips** [comment]
Hi @ShellyXueHan the team does not have an OpenShift project set at the moment.  The plan is to use Azure but OpenShift is likely the fallback

**Comment by stephenrphillips** [comment]
And it's so we have version control for the project yes

**Comment by ShellyXueHan** [comment]
Sounds good @stephenrphillips! So basicallyI just need to make sure you and your team have had an on-boarding meeting with our platform product owner Olena ( @mitovskaol ). If not yet, please go ahead and get in contact with her. Once that's done I'll go ahead and invite the team to work on bcgov GitHub org!

**Comment by mitovskaol** [comment]
@caggles and myself had a meeting with Merwyn and based in the information about the project that was shared in the meeting, we made a decision to approve this request.

**Comment by caggles** [comment]
hi @merwynp ! I have added you to the bcgov github organization. Once you accept the invitation, you will be able to create a repo there yourself, and will be able to add the vendor team as collaborators on that repo. Please let us know if you need anything further!

**Comment by merwynp** [comment]
Thanks @mitovskaol  and @caggles.
