### ISSUE TITLE
Update product owner and technical steward for BC Open Route Planner

### ISSUE THREAD

**Issue by mraross** [BCDevOps/devops-requests#407]
## Step 0
**Are you the product owner or technical lead?**
Yes I am the product owner.

If not, you will need to ask one of those two people to make this request.

If you're looking to update the product owner or technical lead information, the person *currently* listed as product owner or technical lead needs to make this request, rather than the new person.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What annotations/labels need to be changed? (Select all that apply)
- [x] Product Owner
- [x] Technical Steward
- [ ] Security Contacts

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Link to the GitHub ticket you just created

*Project Set Info*
  - Namespaces:

*Product Technical Steward*
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username:
   
*Product Owner*
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

*BC Government Security Contact Information*
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)
  
  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
@mraross we haven't received an email with a reference to this ticket yet. Please double check.

**Comment by dkelsey** [comment]
I thought this was done.  I'll look into it next week. 
when is run `oc describe namespace 3aa7ll-prod` is see

```
...
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"openshift.io/description":"BC Route Planner Next Gen (prod)","openshift.io/display-na...
              openshift.io/description=BC Open Location Service - Route Planner Next Gen (prod)
              openshift.io/display-name=BC Open Location Service - RoutePlanner (prod)
...
...
              product-lead=david.kelsey@gov.bc.ca; craig.rigdon@gov.bc.ca
              product-lead-rc-contact=dave.kelsey; craig.rigdon
              product-owner=michael.ra.ross@gov.bc.ca; caroline.tansley@gov.bc.ca
```

**Comment by dkelsey** [comment]
Technical contacts and product owner contacts are correct, however they are missing some information such as github id for example.

## Technical Lead Contacts

Name  | GitHub ID | Rocket Chat ID | Email 
-------|-----------|----------------|-------
|Dave Kelsey | dkelsey | dave.kelsey | David.Kelsey@gov.bc.ca |
|Craig Rigdon| crigdongov | craig.rigdon | Craig.Rigdon@gov.bc.ca |

## Product Owners
Name | Business Email Address | RocketChat Username| Organization Code | Organization Unit Code
------|-------------------------|-----------------------|--------------------|------------------------
| Michael Ross | Michael.ra.ross@gov.bc.ca | NONE | CITZ | DPD-DSS-T - Data Systems & Services - Technology |
| Caroline Tansley| Caroline.Tansley@gov.bc.ca| caroline.tanslety | CITZ | DPD-DSS-T - Data Systems & Services - Technology |
