### ISSUE TITLE
9xrnfn-prod :: SCJOB (prod)

### ISSUE THREAD

**Issue by GovtRyan** [BCDevOps/devops-requests#408]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

If you're looking to update the product owner or technical lead information, the person *currently* listed as product owner or technical lead needs to make this request, rather than the new person.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What annotations/labels need to be changed? (Select all that apply)
- [X] Product Owner
- [X] Technical Steward
- [] Security Contacts

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

*Project Set Info*
  - Namespaces: 9xrnfn-prod :: SCJOB (prod)

*Product Technical Steward*
  - GitHub ID:  ll-scj-gov
  - Business Email Address: Lorne.Lovett@bccourts.ca
  - RocketChat Account Username: @lorne.lovett
   
*Product Owner*
  - Business Email Address: GovtRyan
  - RocketChat Account Username: @ryan.wirth
  - Organization Code: Superior Courts Judiciary 
  - Organization Unit Code: SCJ
  - bccourts.ca

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
project set metadata updated.
