### ISSUE TITLE
grant access to BCdevops and bcgov org

### ISSUE THREAD

**Issue by BruceBell1271** [BCDevOps/devops-requests#41]
## Step 0

**Are you a member of the BCGOV GitHub Organization already?**
Please note that **new users may not request access for themselves**. If you are not a member already, please talk to whoever that performed the onboarding/introduction of the BCGov DevOps Platform and BCDevExchange, and ask that contact to create this request for you.

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

**Are you the admin of your project's BCGOV GitHub Repository?**
If not, you need to ask your project repo's admin to make this request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: 
* GitHub Org: bcgov and BCDevops
* Full Name: Bruce Bell
* GitHub ID: @BruceBell1271
* GitHub Account 2FA Confirmed: yes
* Email address: bruce.Bell@gov.bc.ca
* Organization: IIT
* Project Role: Data Architect
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
hey @brucebell1271 - you actually can't request access for yourself! Please speak to whoever onboarded you and have them submit an access request on your behalf!
