### ISSUE TITLE
Cleanup old project namespace.

### ISSUE THREAD

**Issue by GeorgeWalker** [BCDevOps/devops-requests#410]
I don't see any option that is a good match for clean up old project namespace - we no longer require the lclb-* set.  Everything has been moved to the new project space for LCRB.

I had heard that this was done recently, and I no longer see them in my OpenShift console, but for some reason there is still communication occurring and questions being asked about these old namespaces, which are now empty.

Thanks,

George Walker.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
2. **Why should this be a new request type?** A good rule of thumb: Is this task straightforward (or something that could be automated)? Does it involve something you don't have the permissions to do? If the answer to both questions is yes, you're probably good to go ahead!
3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
4. **What is the end result?** Please provide plenty of details about what the end result should look like.

**Comment by ShellyXueHan** [comment]
@GeorgeWalker looks like `lclb-*` namespaces have been deleted already. For your reference, to remove an OpenShift project set, start with the type `Request for OpenShift Project Set`. It includes creation and removal. Thank you!
