### ISSUE TITLE
akpalw-prod :	Concierge (prod)

### ISSUE THREAD

**Issue by ZachWoodward** [BCDevOps/devops-requests#413]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

If you're looking to update the product owner or technical lead information, the person *currently* listed as product owner or technical lead needs to make this request, rather than the new person.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What annotations/labels need to be changed? (Select all that apply)
- [X ] Product Owner
- [ ] Technical Steward
- [ ] Security Contacts

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Link to the GitHub ticket you just created

*Project Set Info*
  - Concierge (prod)
*Product Technical Steward*
  - GitHub ID: dhruvio
  - Business Email Address: dhruv@realfolk.io
  - RocketChat Account Username: Dhruv.dang
   
*Product Owner*
  - Business Email Address: (BCGov employee) zachary.woodward@gov.bc.ca
  - RocketChat Account Username: Zachary Woodward
  - Organization Code: CITZ 
  - Organization Unit Code: comm - Procurement Services
  - (refer to https://dir.gov.bc.ca/)

*BC Government Security Contact Information*
  - Ministry Chief Information Officer: Bobbi Sadler
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)
  
  - Ministry Information Security Officer: Gary Perkins
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer: Heather Dunlop
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
Hi @ZachWoodward are you both the product owner and tech lead? I don't see that you have access to all namespaces for this project.

**Comment by ZachWoodward** [comment]
Im really just the product owner, our tech lead for Concierge is Dhruv Dang and Andrew Sutherland from Realfolk.

Regards,
Zachary Woodward

**Comment by ShellyXueHan** [comment]
@ZachWoodward Hi Zach, could you please update your request here to include the tech lead contact information? Thanks!

**Comment by ShellyXueHan** [comment]
metadata updated.
