### ISSUE TITLE
Update PO and Steward for moe-gwells-*

### ISSUE THREAD

**Issue by stephenhillier** [BCDevOps/devops-requests#415]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
Yes

If you're looking to update the product owner or technical lead information, the person *currently* listed as product owner or technical lead needs to make this request, rather than the new person.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What annotations/labels need to be changed? (Select all that apply)
- [ x ] Product Owner
- [ x ] Technical Steward
- [ ] Security Contacts

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
updated. Thanks!
