### ISSUE TITLE
GitOps Private Repo Requests

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/devops-requests#416]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Yes

**Are you sure you need to have your project code close-sourced?**
Yes, cluster manifests may contain private information

**What date will you move your project to open-source?**
N/A

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Sent.

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
https://github.com/bcgov-c/platform-gitops

**Comment by j-pye** [comment]
Hey @ShellyXueHan,
This request had 2 repos in the email I believe. There should be a second repo named `platform-gitops-gen`
Would you like a separate request for that or can we continue on with this one? Thanks

**Comment by ShellyXueHan** [comment]
ops I thought that's another naming option.... here you go: https://github.com/bcgov-c/platform-gitops-gen
