### ISSUE TITLE
Please remove duplicate user (NGANESH) from KeyCloak 

### ISSUE THREAD

**Issue by pwei1018** [BCDevOps/devops-requests#417]
## Step 0
**Are you the KeyCloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
This user have a new idir account with the same name. 
- What result of debugging have you obtained that lead you to request an account removal?
We removed IDIR user profile from our realm. The Keycloak account that was created still uses the old IDIR account.

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [* ] Confirm that user is ready to have the account removed from KeyCloak

## Step 3
Field the following information.

* Username to be removed:  NGANESH 
* Realm ID where user is having problem login:  Fcf0kpqr

**Comment by ShellyXueHan** [comment]
@pwei1018 I've removed the account from IDIR realm. You could now remove it from you application realm for a clean start.
