### ISSUE TITLE
User access request

### ISSUE THREAD

**Issue by stephenhillier** [BCDevOps/devops-requests#422]
## Step 0
**Are you the product owner or project admin?**
yes

Preferably, someone who is already a member of the BCDevOps Github org should request access for you. 
Consider asking someone to submit this ticket in your name in order to ensure that it is processed quickly.

If you do not have access to a team lead or other org member to ask for membership on your behalf, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

**note: Github account was re-created with the same username.**

- Full name: Manasa Challa
- GitHub ID: mchalla13
- Email address: Manasa.Challa@gov.bc.ca
- Organization: IITD, Natural Resource Ministries
- Project role: Data Architect
- OpenShift projects: moe-gwells-test 

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
Hi @stephenhillier there is a user with ID `mchalla13-zz`. Could you confirm with Manasa if these two accounts are pointing to the same person? Thx!

**Comment by mchalla13** [comment]
@stephenhillier @ShellyXueHan mchalla13-zz is not my user account. Thanks

**Comment by stephenhillier** [comment]
@ShellyXueHan  Manasa is still having an issue logging onto OpenShift:  `An authentication error has occurred`.  Could this be because she already had an account on our platform called `mchalla13`?  Her GitHub account was deleted and re-created with the same username as her old account.

**Comment by ShellyXueHan** [comment]
@stephenhillier @mchalla13 it seems that Manasa has not yet accepted the BCDevOps GitHub organization invitation. There should be an email sent to your GitHub email address already. Please make sure you have accepted that first and that should grant you access to openshift console.

**Comment by mchalla13** [comment]
@ShellyXueHan I did accept the invitation when it was sent but it didn't fix the access issues with Open Shift. I could have probably not set my account properly. When I go back to the email the invitation link is expired. Can you please resend the invitation, I can retry?

**Comment by ShellyXueHan** [comment]
@mchalla13 okay pls try again now!

**Comment by mchalla13** [comment]
I accepted the invitation. Tried to access Gwells Open Shift container, I am still getting the authorization error. I used incognito and a new browser.

**Comment by ShellyXueHan** [comment]
have you granted the access for the app to read your github org information? can you share screenshot of the error message?

**Comment by ShellyXueHan** [comment]
@sbarre-esit Hi Steven! Manasa has had her GitHub account @mchalla13 updated and now she's getting errors when login to OpenShift console as `could not create user`. Could it be something that got messed up between the account linkage? I can see her account on openshift but don't have the access to manage it. Can you help to delete the OpenShift user `mchalla13`?

**Comment by wmhutchison** [comment]
@ShellyXueHan Will take a look at this in a little bit, stay tuned.

**Comment by wmhutchison** [comment]
@ShellyXueHan The requested user `mchalla13` has been deleted from within Openshift, should be able to try again.

**Comment by mchalla13** [comment]
@ShellyXueHan this issue can now be closed. I am able to access ocp now. Thanks
