### ISSUE TITLE
Add user to BCGov GitHub

### ISSUE THREAD

**Issue by ActionAnalytics** [BCDevOps/devops-requests#427]
## Step 0

**Are you the Technical Lead?**
Yes

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed! **Please indicate in this ticket if you need to schedule this meeting.** 
If you've already had a meeting as part of a request for an Openshift Project, please indicate that in the ticket as well.

**Do you actually need the team member to be a member of the organization?**
Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation
DONE

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
DONE

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Cloud Pathfinder
* GitHub Org: bcgov
* Full Name: Genevieve Lambert
* GitHub ID: @glam-bert
* GitHub Account 2FA Confirmed: Confirmed
* Email address: genevieve.lambert@gov.bc.ca
* Organization: OCIO
* Project Role: Portfolio Owner
* GitHub Team to Join (if exists): Cloud Pathfinder
* Existing GitHub Repos: bcgov/cloud-pathfinder-technology-and-ux  and bcgov/cloud-pathfinder-business-process

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ActionAnalytics** [comment]
2FA confirmed, Good to Go!

**Comment by ShellyXueHan** [comment]
user in org already. Closing ticket
