### ISSUE TITLE
Request for OpenShift Project Set for ZEVA

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#43]
## Step 0
**Are you the product owner or technical lead?**
I'm the devops specialist of the ZEVA project.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.
Yes, we completed the meeting with Todd Wilson at Nov 27.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project
Completed

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
No duplicates.

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: mem (Ministry of Energy, Mines & Petroleum Resources)
* Product Short Name: zeva
* Product Full Name: Zero-Emission Vehicles Act
* Product Description: Facilitates online Zero-Emission Vehicle (ZEV) sales reporting by regulated parties (automakers), plus issuance and transfer of ZEV credits. This is to support compliance with the ZEV Act regulations that require increasing sales of ZEVs to reduce GHG emissions from vehicles in the province.
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/zeva

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: 
  - RocketChat Account Username: 

Please note that we will only start processing your request when the email has been received.

**Comment by kuanfandevops** [comment]
we are trying to figure out a proper product description and the will send out email.

**Comment by kuanfandevops** [comment]
Updated product description, will email shortly

**Comment by kuanfandevops** [comment]
Email has been sent out

**Comment by ShellyXueHan** [comment]
@kuanfandevops Project set created as `tbiwaq-tools`, `tbiwaq-dev`, `tbiwaq-test`, `tbiwaq-prod`. `kuanfandevops` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.
