### ISSUE TITLE
Temporary home for BC MSA app (until switch to Open Source and on OpenShift)

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/devops-requests#430]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
YES

**Are you sure you need to have your project code close-sourced?*
YES - this is temporary until we can ensure no IP, credentials or other sensitive information prior to publishing on github.com/bcgov

**What date will you move your project to open-source?**
We will do a CodeWithUs procurement so most likely in the fall 2020.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: 
* GitHub Org: bcgov or private
* Details on choosing private repo: 
* Preferred name for repo: 
* Expected date to move to public: MM/YYYY
* GitHub ID for repo owner: @
* GitHub Account 2FA Confirmed: yes or no
* Email address: 
* Organization: 
* Project Role: 
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
https://github.com/bcgov-c/agri-nmp-msa
