### ISSUE TITLE
Request for removing a GitHub App

### ISSUE THREAD

**Issue by wenzowski** [BCDevOps/devops-requests#433]
This is a followup to #130 and #230 

Installation of Percy was never completed so we now have a dangling authorization on bcgov for an app that will never be used by anyone, since they can't. Can we remove it?

**Comment by ShellyXueHan** [comment]
app uninstalled. please close the relevant tickets as fit.

**Comment by wenzowski** [comment]
thanks @ShellyXueHan all prior tickets closed
