### ISSUE TITLE
Request for KeyCloak Realm creation for ZEVA project.

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#44]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.
Answer: I'm the devops specialist of ZEVA team.

**Do you have an IDIR account?**
We use IDIR authentication for realm admin users, so you *must* have one in order to become a realm admin.  
Answer: yes, I do.

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 2.
Answer: ZEVA is a brand new project, we request to create new realms.
We request IDIR, BCeID and GitHub for dev and test, IDIR and BCeID for prod.

## Step 1
Login to each of the following links using your **IDIR credentials**. You will then see a "_Forbidden_" message, but this is expected behaviour and will actually create your initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console
Answer: I completed these three items, but I think my idir account should exist in KeyCloak already as I worked for previous TFRS project.

## Step 2
Field the following information.

* Project Name: 
* For existing KeyCloak realm update only:
  - Realm ID: 
  - Identity Provider to add: IDIR or BCeID or GitHub

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by kuanfandevops** [comment]
Email has been sent out.

**Comment by ShellyXueHan** [comment]
Hey Kuan, I don't see your account in the following realm yet:
https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console
Could you double check to login again?

**Comment by kuanfandevops** [comment]
Hi Shelly,

I just tried dev, test and prod links and all received following response.

Forbidden
You don't have access to the requested resource.
Go to the home page »<https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console/>


Thanks
Kuan

**Comment by ShellyXueHan** [comment]
@kuanfandevops I still don't see your account in the devhub realm, could you double check if you have logged in to this link yet https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console?

**Comment by kuanfandevops** [comment]
Hi Shelly,

I tried to login with my both idir and github account and  all get same forbidden page.

Thanks
Kuan

**Comment by ShellyXueHan** [comment]
I only see your github account there, but I need the IDIR account, could you try again at https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console ?

**Comment by kuanfandevops** [comment]
Done. This time I received email and clicked the link…

Thanks
Kuan

**Comment by ShellyXueHan** [comment]
all good! now you could request the realm at https://realm-o-matic.pathfinder.gov.bc.ca with IDIR account.
