### ISSUE TITLE
NRM namespaces PO/Tech Lead updated info

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/devops-requests#441]
What annotations/labels need to be changed? (Select all that apply)
- [x ] Product Owner
- [x ] Technical Steward
- [ ] Security Contacts

Please update the NRM's namespaces below with the new info for PO and Tech Leads contacts as specified in the email
Namespace
--
3aa7ll-dev
3aa7ll-prod
3aa7ll-test
3aa7ll-tools
databcdc
dbc-bcdc-dev
dbc-bcdc-prod
dbc-bcdc-test
dbc-bcdc-tools
dbc-cms-vis-dev
dbc-cms-vis-prod
dbc-cms-vis-test
dbc-cms-vis-tools
dbc-kirk-dev
dbc-kirk-prod
dbc-kirk-test
dbc-kirk-tools
dbc-konga-dev
dbc-konga-prod
dbc-konga-test
dbc-konga-tools
dbc-mapsdk-dev
dbc-mapsdk-prod
dbc-mapsdk-test
dbc-mapsdk-tools
dbc-oem-tools
dbcols
devops-2016
fp1bxb-dev
fp1bxb-prod
fp1bxb-test
fp1bxb-tools
geopaas
hmg6pw-dev
hmg6pw-prod
hmg6pw-test
hmg6pw-tools
ido-bceala-dev
ido-bceala-prod
ido-bceala-test
ido-bceala-tools
ido-bcols-dev
ido-bcols-prod
ido-bcols-test
ido-bcols-tools
ll-realm
oaujjs-deploy
oaujjs-tools
wlev6y-dev
wlev6y-prod
wlev6y-test
wlev6y-tools

**Comment by ll911** [comment]
`ll-realm` and `geopaas` still used by me

**Comment by ll911** [comment]
@dkelsey can update the rest slug annotations.

**Comment by ShellyXueHan** [comment]
@dkelsey we have not yet received details on the PO/Tech Lead update for above namespaces. Please you provide the information with the fields and send to pathfinder@gov.bc.ca:

*Project Set Info*
  - Namespaces:
 
*Product Technical Steward*
  - GitHub ID:
  - Business Email Address:
  - RocketChat Account Username:
   
*Product Owner*
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username:
  - Organization Code:
  - Organization Unit Code:
  - (refer to https://dir.gov.bc.ca/)
 
*Other Critical Contacts*
  - Business Email Address:

**Comment by dkelsey** [comment]
Thanks @ShellyXueHan 
I did follow up with this when the issue was brought to my attention. 
It was dealt with by @SteveChapmanBCDX and @catansle 

I'll follow-up with them again.

**Comment by caggles** [comment]
Hello!  I'm a little confused about the status of this ticket - are we still waiting on the email with the contact information so we can action this, or is this ticket finished?

**Comment by dkelsey** [comment]
I did follow up with this 8 days ago.  There was some info Steve needed to collect.  I've asked @SteveChapmanBCDX to comment.  He may be on a flex day.

**Comment by SteveChapmanBCDX** [comment]
I set an email to @ShellyXueHan on August 31 with the relevant information.  Find below the spreadsheet that I attached to my email:
[openshift_LabModRequest_Aug2020.xlsx](https://github.com/BCDevOps/devops-requests/files/5188525/openshift_LabModRequest_Aug2020.xlsx)

**Comment by ShellyXueHan** [comment]
I must have missed your email @SteveChapmanBCDX Will take a look now and continue on the ticket!

**Comment by SteveChapmanBCDX** [comment]
@ShellyXueHan - No problem - thanks for your help!

**Comment by ShellyXueHan** [comment]
@SteveChapmanBCDX most of the namespace annotations have been updated. `geopass` is the one outstanding, I was not able to find it. Can you double check if the namespace(s) exist? And if the service account `openshift / bcdevops-admin` has the admin role there?

**Comment by SteveChapmanBCDX** [comment]
@ShellyXueHan - Great - thanks for making all those changes.  As requested, I'll check up on the `geopass` namespace.  You can probably close this issue if you want to.

**Comment by ShellyXueHan** [comment]
Okay you can always post updates about that namespace on this ticket.

**Comment by SteveChapmanBCDX** [comment]
@ShellyXueHan  - I misspelled that namespace - it should be `geopaas` rather than `geopass`.  Are you able to find it now?

**Comment by ShellyXueHan** [comment]
kk done!
