### ISSUE TITLE
Request to increase backup storage for new backup strategy.

### ISSUE THREAD

**Issue by MaxWardle** [BCDevOps/devops-requests#442]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Long Running (compute-long-running-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [x] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [x] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
iarjfo-tools
**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.
Need to go from 5Gi -> 25Gi
*ex: Please increase number of PVCs that can be provisioned to 30.*

## Step 5
Please explain here the reasons for requesting your quota change.
Need to make room for new backup PVCs. 
Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by ShellyXueHan** [comment]
@MaxWardle Hi Max, I don't see that any nfs quota has been used in iarjfo-tools. Please provide more context for this request, thx!

**Comment by MaxWardle** [comment]
Hey @ShellyXueHan, I'm setting up our database backups for this project using the [bcdevops db backups](https://github.com/BCDevOps/backup-container). I need 20GB for the  main backup PVC and 5Gb for the restore PVC. Although now that I'm thinking about it again, I don't think I want nfs storage for the restore PVC. Could you just increase it to 20GB for the backup storage please?

**Comment by ShellyXueHan** [comment]
@MaxWardle you are right, no need for nfs for verifying the backup. But still I have two more questions for your backup plan:
- what are the app data that you are backing up? prod or both dev/test/prod? Have you consider having the backups in the corresponding namespace instead?
- How big are the zipped backups now? Please note that only small database are expected to live on openshift and when they grow big, the team should start to considering moving to somewhere designed for db. So usually the namespace nfs quota are sufficient for a 1week per day + 1 month per week backup schedule (default for backup-container if I recall correctly)

**Comment by MaxWardle** [comment]
Aah okay, after compression the backups went down to ~30MB, and I think the storage over the three namespaces should be enough for that, I hadn't considered doing it that way. Thanks Shelly.

**Comment by ShellyXueHan** [comment]
Sounds good! I'll close the ticket now.
