### ISSUE TITLE
Colin Mahony

### ISSUE THREAD

**Issue by cmahony** [BCDevOps/devops-requests#443]
## Step 0

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request. This role should be a member of the BCGOV Github org as part of the team onboarding process.

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed! **Please indicate in this ticket if you need to schedule this meeting.** 
If you've already had a meeting as part of a request for an Openshift Project, please indicate that in the ticket as well.

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: CMIP5EnsembleApp
* GitHub Org: bcgov
* Full Name: Colin Mahony
* GitHub ID: @cmahony
* GitHub Account 2FA Confirmed: yes
* Email address: colin.mahony@gov.bc.ca
* Organization: CCIPB (FLNRORD)
* Project Role: Lead
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@cmahony Hi Colin, as specified in the guide for GitHub access request, we do not handle self-request. In addition, please note that bcgov repos are for OpenShift teams. Are you from a team on OpenShift? If so, please have the technical lead to request access for you. If not, have you had alignment/onboarding meeting with our Product Owner Olena (@mitovskaol ) yet?

**Comment by cmahony** [comment]
@ShellyXueHan @mitovskaol Hi Shelly and Olena, I'm not on an OpenShift team. I’m a new government employee and have an R Shiny web app that I have developed to accompany a guidance document. Andy Teucher (ENV) has agreed to host the app, but I am trying to figure out the process of hosting the code on the bcgov GitHub org. The documentation available has left me feeling a bit lost and I could definitely use a roadmap to getting this done. Olena, is this something you can help with? thanks!

**Comment by mitovskaol** [comment]
@cmahony can you please reach out to me next week to discuss this. Thanks!

**Comment by cmahony** [comment]
@mitovskaol i just got back from vacation. i'm free to talk anytime this week.

**Comment by mitovskaol** [comment]
@cmahony  can you please send me a meeting invite for the time that work you and is available in my calendar. This week and the beginning of the next week is a bit busy as we are preparing for the Sprint Review, so the mid or late next week would work better. Thanks!

**Comment by mitovskaol** [comment]
@caggles @ShellyXueHan Can you please help Colin to get access to the bcgov org so that he can create a repo for this application.

**Comment by cmahony** [comment]
Thanks @caggles @ShellyXueHan @mitovskaol @cvarjao ! I have this app in a personal repo https://github.com/cmahony/CMIP5-ensemble-app. hopefully we can just move it over to bc gov?

**Comment by caggles** [comment]
Hey @cmahony - you've been invited as a member of the org, so you should be able to move your personal repo over to the bcgov org without any further action from us (just as soon as you accept the invite). Please give us a shout if you need anything further!
