### ISSUE TITLE
Increase PRIME project maximum PVC Count to 40

### ISSUE THREAD

**Issue by poggdogg** [BCDevOps/devops-requests#447]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
**Yes**

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
**No**

## Step 2
What quotas need to be changed? (Select all that apply)
- [X] General Storage Quota (storage-quota)
   - [X] Number of PVCs

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
**dqszvc-dev**

## Step 4
Add details about your quota request here.
**Please increase number of PVCs that can be provisioned to 40.**

## Step 5
Please explain here the reasons for requesting your quota change.
**We're using the emptydir{} in our branch PR templates and are doing our best to use ephemeral for PR builds but still get PVCs counted.  We have unified PVCs between containers and pods as possible as well.**

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by ShellyXueHan** [comment]
@poggdogg Hi Paul, I see that you are doing github flow so understand you have lots of deployments in dev. But could you provide some more details on the PVC/PV usages, like what are the cases that you would need it to be persistent?

**Comment by poggdogg** [comment]
That's the thing; there aren't a lot of persistent PVCs but we're hitting
the limit pretty often.  We have had more than 20 open PRs at times and
this causes us to trip the limit.  Theoretically the emptydir shouldn't
count but it looks like it was being counted towards our quota.

**Comment by ShellyXueHan** [comment]
yes if you are using emptydir then there's no need to create a PVC. So please look into your configurations in dev to check for it, and see if it's still creating PVCs but not using them. In addition, I'd like to know how big is your team, 20 open PRs at a time is not quite normal. Please feel free to book a meeting with Cailey @caggles and myself to discuss in more details if needed.

**Comment by poggdogg** [comment]
I have verified we are using emptydir in our dev space.  Our team is pretty
large (8 developers alone, lots of stakeholders).  We have had over 20 PRs
at a time and are using emptydir but still got blocked on deployments
regardless.

**Comment by sbarre-esit** [comment]
```console
$ oc get pvc -n dqszvc-dev -o=custom-columns=NAME:.metadata.name --no-headers
backup-data
document-manager-develop-backend-pvc
document-manager-develop-migrate-pvc
document-manager-develop-pvc
document-manager-pr-689-backend-pvc
document-manager-pr-689-migrate-pvc
document-manager-pr-706-pvc
document-manager-pr-708-pvc
document-manager-pr-710-pvc
document-manager-pr-713-pvc
document-managerpr-708-pvc
postgresql-develop
postgresqlpr-708
```

Those don't look like `emptyDir` to me.

**Comment by ShellyXueHan** [comment]
I saw that you are using emptydir volumes in your deployments, and that's why I'm asking you to check into the template/configuration to see if you are still creating un-used PVCs. And if there are deployments that need to be persistent in dev, please share the reason/cases. I'm basically trying to understand why you need 40 PVCs, that's a large number.

**Comment by poggdogg** [comment]
Develop is supposed to be static.  It looks like those other ones are aged out.  I'll clean them up.
I'll reopen the issue if this occurs again.

**Comment by poggdogg** [comment]
Verified - we're using emptydir and it's still an issue
      volumes:
        - emptyDir: {}
          name: document-manager-pr-706-pvc

**Comment by ShellyXueHan** [comment]
I looked into your dc template and here's the PVC creation: https://github.com/bcgov/moh-prime/blob/feature/PRIME-892-obfuscated-webhook-url/openshift/document-manager.dc.yaml#L52-L65

In `document-manager` DeploymentConfig, you are using empty dir volume already. There's no need for the PVC to be created in dev namespace when going with ephemeral settings.

**Comment by poggdogg** [comment]
Right, but that's my static config.  We use a different DC for ephemeral (https://github.com/bcgov/moh-prime/blob/feature/PRIME-892-obfuscated-webhook-url/openshift/document-manager-ephemeral.dc.yaml)
We use the static for develop (branch, not PRs), test, prod.

**Comment by ShellyXueHan** [comment]
in your ephemeral template, it's still creating PVC: https://github.com/bcgov/moh-prime/blob/feature/PRIME-892-obfuscated-webhook-url/openshift/document-manager-ephemeral.dc.yaml#L52-L65 So the idea here is that in dev namespace deploy ephemeral instance that does not require PVC and in the deployment mount empty dir. I think you have the basic setups correct already. The issue is just that part of the template is still creating unused PVCs. Considering this, you don't need a 40 PVC quota in this namespace.

**Comment by poggdogg** [comment]
Thanks, not sure how we missed that.
