### ISSUE TITLE
Request for realms for APS Team

### ISSUE THREAD

**Issue by crigdongov** [BCDevOps/devops-requests#458]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: API Management

* OpenShift Project Set/s Info
  - Project set name: API Management
  - Namespace ID:

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@crigdongov Do you have exiting keycloak realms or requesting for brand new ones? What's the OpenShift namespace ID? Also does your team need an onboarding meeting, here's a reference doc: https://github.com/bcgov/ocp-sso/wiki/1.1-OnBoarding.md

**Comment by crigdongov** [comment]
@ShellyXueHan, no need for a onboard meeting.  These Realms will be used by the APS team for the API management Project.

 qwzrwc-dev - API Management for DBC (dev)
 qwzrwc-prod - API Management for DBC (prod)
 qwzrwc-test - API Management for DBC (test)
 qwzrwc-tools - API Management for DBC (tools)

**Comment by ShellyXueHan** [comment]
@crigdongov I see, you have an ongoing request there so you won't be able to request a new set of realm at the moment. Please provide a team member to submit the request instead. It'll have to be an IDIR account holder, and please have this team member complete step 2 in the template.

**Comment by crigdongov** [comment]
@ShellyXueHan regarding our last request under my idir, that was completed.  We decided to not continue with the BCID and notified them as required. Is there away to clear that from your side.

**Comment by ShellyXueHan** [comment]
@crigdongov thank you for the update. Please forward me the relevant email from IDIM team. We can go from there.

**Comment by crigdongov** [comment]
@ShellyXueHan FWD email to you from my PO to IDIM. Thanks again for your help on this.

**Comment by ShellyXueHan** [comment]
@crigdongov I have not received any email yet. Can you double check and resend?

**Comment by crigdongov** [comment]
@ShellyXueHan FWD email to you from my PO to IDIM.  Please confirm.

**Comment by crigdongov** [comment]
Thanks @ShellyXueHan for your work on this. Realm-o-matic ran successfully, we have our new realms in hand.
