### ISSUE TITLE
Sprint 15 Ops Effort 

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/devops-requests#461]
Number of tickets: 30
Average time to close: 7 days, 18 hours, 15 minutes, 15 seconds

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/463

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/464

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/465

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/466

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/467

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/468

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/469

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/470

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/471

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/472

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/473

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/474

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/475

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/476

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/477

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/478

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/479

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/480

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/481

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/482

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/483

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/484

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/485

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/486

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/487

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/488

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/489

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/493

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/494

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/495

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/497

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/498

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/499

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/500

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/501

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/502

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/503

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/504

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/505

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/506

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/507

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/508

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/509

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/510

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/511

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/512

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/513

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/514

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/515

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/516

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/517

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/518

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/519

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/520

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/521

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/522

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/523

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/524

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/525

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/526

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/527

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/528

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/529

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/530

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/531

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/532

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/534

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/535

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/536

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/537

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/538

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/539

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/540

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/541

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/542

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/543

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/544

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/545

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/546

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/547

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/548

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/549

**Comment by caggles** [comment]
https://github.com/BCDevOps/devops-requests/issues/550
