### ISSUE TITLE
Gluster Block Quota for bsoszr-*

### ISSUE THREAD

**Issue by MikeLyttle** [BCDevOps/devops-requests#466]
## Step 0
**Are you the product owner or technical lead?**

Yes.

## Step 1
**Make sure no duplicated request exists, search here:**
https://github.com/BCDevOps/devops-requests/issues

✔️

## Step 2
**What quotas need to be changed? (Select all that apply)**
- [ ] CPU: Long Running (compute-long-running-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [x] Storage: Gluster Block (storage-gluster-block-quota)
   - [x] Number of PVCs
   - [x] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
**Please provide the namespace(s) to which these quota changes need to be applied:**

bsoszr-dev, bsoszr-test, bsoszr-prod

## Step 4
**Add details about your quota request here.**

We need a minimum of 1 PVC and 1 Gi space for bsoszr-dev and 2 PVCs and 2 Gi space for bsoszr-test.

The needs for bsoszr-prod are yet to be finalized but should be on a similar scale.

## Step 5
**Please explain here the reasons for requesting your quota change.**

We're attempting to set up a Postgres database using Patroni and we currently have a storage-gluster-block-quota of 0 PVCs and 0 storage.

**Comment by sbarre-esit** [comment]
Hello @MikeLyttle 

`gluster-block` is the old storage class and is being phased out. The new preferred option for DBs is `netapp-block-standard`. Please use that for your Patroni.

More details at https://developer.gov.bc.ca/Persistent-Storage-Services

**Comment by caggles** [comment]
hi @MikeLyttle - i'm going to close this ticket on the assumption that using netapp works for you. If not, please submit another ticket which includes details about why you require gluster in specific.

**Comment by MikeLyttle** [comment]
Thanks, we've switched to a newer template which is using netapp-block-standard.
