### ISSUE TITLE
Request to add user to repos

### ISSUE THREAD

**Issue by gjlawran** [BCDevOps/devops-requests#469]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
No duplicates.

## Step 2
Please answer the following questions about the new request type:

1. **What is it?**
Add user to requested repos - per RC conversation with @caggles 2020-08-05.

2. **Why should this be a new request type?** A good rule of thumb: Is this task straightforward (or something that could be automated)? Does it involve something you don't have the permissions to do? If the answer to both questions is yes, you're probably good to go ahead!
I don't know if it should be a new request type - I don't know how often this is requested of the DevOps group.

3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
A user needs to be added to 3 code repositories - as specified in RC request.
 
4. **What is the end result?** Please provide plenty of details about what the end result should look like.
The repos will able to be managed by the API Program Services team.

**Comment by gjlawran** [comment]
@caggles  @ShellyXueHan  can this please be escalated - the discussion we had via MS Teams is now 7 days ago. Still do not have access to repos reference - will follow up with Rocket Chat request  also. Thanks.

**Comment by caggles** [comment]
as per the follow-up discussion on teams, you should already have access to the repos in question - we'll need to chat further to troubleshoot any issues if you don't.
