### ISSUE TITLE
OpenShift Access to Nutrient Management Program for Navatha Mundru

### ISSUE THREAD

**Issue by CodingVelocista** [BCDevOps/devops-requests#47]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Navatha Mundru
* GitHub ID: @NavathaMundru2019
* Business Email Address: Navatha.Mundru@quartech.com
* Organization: Quartech Systems
* Project Role: Developer
* OpenShift Projects/Namespaces: agri-nmp-dev, agri-nmp-test, agri-nmp-prod, agri-nmp-tools

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
Invitation has been send to the GitHub account.
