### ISSUE TITLE
OpenShift Access request (Melissa Stanton & Amit Chaurasia) openshift-access

### ISSUE THREAD

**Issue by pwei1018** [BCDevOps/devops-requests#470]
## Step 0
**Are you the product owner or project admin?**

Preferably, someone who is already a member of the BCDevOps Github org should request access for you. 
Consider asking someone to submit this ticket in your name in order to ensure that it is processed quickly.

If you do not have access to a team lead or other org member to ask for membership on your behalf, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Melissa Stanton
* GitHub ID: @mstanton1
* Business Email Address: Melissa.Stanton@gov.bc.ca
* Organization: BC Registries
* Project Role: Business Analysis
* OpenShift Projects/Namespaces: 
    1rdehl-dev
    1rdehl-prod
    1rdehl-test
    1rdehl-tools
    l4ygcl-dev
    l4ygcl-prod
    l4ygcl-test
    l4ygcl-tools

* Full Name: Amit Chaurasia
* GitHub ID: @amit4610
* Business Email Address: Amit.Chaurasia@gov.bc.ca
* Organization: BC Registries
* Project Role: Business Analysis
* OpenShift Projects/Namespaces: 
    1rdehl-dev
    1rdehl-prod
    1rdehl-test
    1rdehl-tools
    l4ygcl-dev
    l4ygcl-prod
    l4ygcl-test
    l4ygcl-tools

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
@pwei1018 just fyi, melissa is already a member of the org - please check in with her and let us know if she's unable to access openshift!

**Comment by pwei1018** [comment]
@caggles Hi, it seems Melissa's account still have issue. I gave her 1rdehl-dev and l4ygcl-dev access but she can't see them after login. 
![Clipboard - August 12, 2020 9-47 AM](https://user-images.githubusercontent.com/44277752/90043898-a546e480-dc81-11ea-8b5b-6c9c38c1468e.png)
