### ISSUE TITLE
V. Shankar - Request to join BCGOV GitHub Organization

### ISSUE THREAD

**Issue by var0101** [BCDevOps/devops-requests#471]
Note: I see that new users cannot request access for themselves, but I am the Product Owner and the project does not have a Technical Lead. Please e-mail me if you have questions. I am not able to make the request in devops-requests on RocketChat - the channel shows up as read-only. 

Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

Fields

* Project Name: Technology Code of Practice
* GitHub Org: BCGOV
* Full Name: Vardhman Shankar
* GitHub ID: @var0101
* GitHub Account 2FA Confirmed: yes
* Email address: Vardhman.Shankar@gov.bc.ca
* Organization: CITZ OCIO
* Project Role: Product Owner
* GitHub Team to Join (if exists):
* Existing GitHub Repo: Will move to BCGOV once added: https://github.com/var0101/Technology-Code-of-Practice

**Comment by caggles** [comment]
Hi @var0101 - can you please contact @mitovskaol and go through our new project onboarding if you haven't done so already? That's normally how POs for a new project are added to the various orgs!
