### ISSUE TITLE
Aaron DeJong (Arctiq) openshift access

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/devops-requests#472]
## Step 0
**Are you the product owner or project admin?**
I am the technical lead.

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Aaron DeJong
* GitHub ID: @funixz
* Business Email Address: aaren.dejong@arctiq.ca
* Organization: Arctiq
* Project Role: Devops Consultant
* OpenShift Projects/Namespaces: N/A (will have manual access granted to Lab projects as needed.

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by funixz** [comment]
@caggles would you please re-send the github org invite? Mine expired.
