### ISSUE TITLE
Provide access to OpenShift project - HETS for account BCG-B

### ISSUE THREAD

**Issue by jamesmunro-BCGOV** [BCDevOps/devops-requests#475]
## Step 0

**Are you the Technical Lead?**
YES-I am the Technical Lead for HETS

**Do you actually need the team member to be a member of the organization?**
Barry needs to be a member of the BCGov Github organization in order to gain access to the OpenShift environment

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: HETS
* GitHub Org: bcgov 
* Full Name:  Barry Jin
* GitHub ID: @ BCG-B
* GitHub Account 2FA Confirmed: yes 
* Email address: Barry.Jin@gov.bc.ca
* Organization: Ministry of Transportation and Infrastructure
* Project Role: Contributer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
hi @jamesmunro-BCGOV - this user is already a member of BCDEVOPS (the org that provides access to Openshift). Please give me as shout on rocketchat if the user is still unable to access the platform despite having membership in the org.
