### ISSUE TITLE
Update Backup Quota for BC Wildfire Predictive Services

### ISSUE THREAD

**Issue by sidtobias** [BCDevOps/devops-requests#476]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
 
Sid Tobias is temporary Product Owner while our regular PO, Joanna Wand, is away on leave.
 
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
 
No duplicates.
 
## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [x] Total Storage
 
 
## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
 
auzhsi-prod
 
 
## Step 4
Add details about your quota request here.
 
Please increase our total storage to 150 GB.
 
## Step 5
Please explain here the reasons for requesting your quota change.
 
Our current backup storage quota is for 5 GB, which we have already reached. Over the next few years of the project, we anticipate our database size growing to approx. 1.2 TB. This project requires a large database because the application is focused on data analysis and makes use of data that is not persistently stored in any other third-party source.
 
Taking into consideration the DevExchange's planned migration to OpenShift 4, we have made the assumption that for now it is only necessary to acquire sufficient backup storage quota for the next 6 months. We've calculated our backup needs for the next 6 months to be approx. 150 GB.
 
While we have identified the possibility of "optimizing" our database storage by only storing quantitative summaries of the raw data (e.g., percentiles and averages for data over an extended period of time) and deleting the raw data itself, this option is not ideal as it precludes the project from implementing any machine learning or data mining applied to precise weather data throughout the province. During project inception, some of the key visions identified for the project was the ability to model predictions for active wildfires in the province, and heavy involvement in fire behaviour-related research with academic institutions and other bodies of government. Having the ability to store and access as much collected BC fire weather data as possible is fundamental to the success of these visions.

**Comment by caggles** [comment]
hi @sidtobias - since this is only a temporary thing, we do have the option of adding multiple people to the PO slot now, so would it make more sense for me to just add you in addition to joanna instead of replacing?

**Comment by caggles** [comment]
hey @sidtobias - i just want to confirm that we have seen this, but i'm just discussing an appropriate way forward with the rest of the team at the moment.

**Comment by sbarre-esit** [comment]
> we anticipate our database size growing to approx. 1.2 TB.

How big of a pod are you going to need to support that much data? CPU / RAM

**Comment by jowand** [comment]
Hello, just letting the team here know I have taken over PO from Sid Tobias. I see the last comment on this ticket was Aug 27, is there an update on the progress of this request since then?
Cheers

**Comment by caggles** [comment]
Hi @jowand! I just have a couple of remaining questions about this ticket. 
1. Can you please confirm that 150G is still an appropriate size for your needs?
2. If your project is going to continue growing and you still project that you'll need much more than the 200G limit, we'll probably want to have a meeting to discuss further options. If you feel that's necessary, please book something with me and @mitovskaol!

**Comment by jowand** [comment]
Hi @caggles , thanks for reaching out:
1. 150G is perfect for our development plans for the next year
2. In the future we will need more than the 200GB limit, but this is a year or more away.

I'll book a meeting with you anyway so that I'm aware of requirements and can plan for a >200GB request in the future.

thanks!

**Comment by caggles** [comment]
Hi @jowand - I apologize for the delayed response here. I misread your last comment and thought you were asking me to wait on actioning any update to your backup size until the new year. I realize now that that's not what this says, so that's my bad.

I am planning to action this request ASAP, but I don't see any namespace names anywhere in this ticket. If you could provide those (or just one, if you're just talking about prod?), I will submit the change!

**Comment by jowand** [comment]
Thanks @caggles - our name is: auzhsi-prod

Cheers,
Jo

**Comment by sbarre-esit** [comment]
@jowand this has now been applied to your project.
