### ISSUE TITLE
Change PO for EMBC Emergency Support Services Portal 

### ISSUE THREAD

**Issue by JEWALKER911** [BCDevOps/devops-requests#480]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

If you're looking to update the product owner or technical lead information, the person *currently* listed as product owner or technical lead needs to make this request, rather than the new person.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What annotations/labels need to be changed? (Select all that apply)
- [X ] Product Owner
- [ ] Technical Steward
- [ ] Security Contacts
- [ ] Other Critical Contacts (contact info for other stakeholders such as members of IMB, Architecture, Privacy, etc groups that are interested in receiving comms related to this project sets.
- [ ] Product Group (an optional label that can be used to group together OpenShift Project Sets that share a business function (e.g. Platform Services project sets are labeled as part of "Platform Services" product group.  The value for this label should be determined by the organization/ministry/branch/team that owns the Project Set)

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Link to the GitHub ticket you just created

*Project Set Info*
  - Namespaces:
  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)

*Product Technical Steward*
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username:
   
*Product Owner*
  - Business Email Address: (BCGov employee) jennifer.7.walker@gov.bc.ca
  - RocketChat Account Username: ~
  - Organization Code: unknown
  - Organization Unit Code: unknown
  - (refer to https://dir.gov.bc.ca/)

*Other Critical Contacts*
  - Business Email Address:

*BC Government Security Contact Information*
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)
  
  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

*Product Group Name*

Please note that we will only start processing your request when the email has been received.

**Comment by caggles** [comment]
hi @jewalker911 - there doesn't seem to be an email in the pathfinder inbox with the information detailing what annotations should be updated. Can you please resend?

**Comment by JEWALKER911** [comment]
Hi and apologies, but I’m not sure what action is needed here, nor how to do it.

Business Owner for this Project is me - Jennifer Walker
Product Owner is Graeme Godfrey

Please advise if additional info is needed.

Best,

Jen Walker

Jennifer Walker PhD, RPBio
A/Director, Emergency Support Services

Emergency Management BC<http://www.gov.bc.ca/emergency-preparedness-response-recovery>
Block A – Suite 200, 2261 Keating Cross Rd
Saanichton, BC CANADA V8M 2A5

Mobile: 250-882-6304 UC: 778-698-4974
24 Hour Emergency Reporting: 1-800-663-3456

For ESS News subscribe here<https://www2.gov.bc.ca/gov/content?id=F5674CDAE86D45D2B4505E55892D7931> and follow us on Twitter @EmergencyInfoBC<http://twitter.com/emergencyinfobc> or @PreparedBC<https://twitter.com/PreparedBC>

**Comment by caggles** [comment]
Hi @jewalker911 - please provide the namespace names and both the appropriate email address and rocketchat username for the new product owner. It looks like you're aiming to set yourself up as PO, in which case you will also need to get the current PO to sign off on this change (just have them comment here with permission). If you are unsure who the current PO is, please provide me with the project set names and I will be able to check.

**Comment by JEWALKER911** [comment]
Hello Cailey,

Just to be clear, I am setting up GRAEME GODFREY as product owner. I am the business owner.

Please see below and attached for Graeme’s details and the former product owner (Brian Daszko’s) endorsement, respectively.

              namespace name – does not have one
rocketchat username - Graeme.Godfrey
email Graeme.Godfrey@gov.bc.ca<mailto:Graeme.Godfrey@gov.bc.ca>

Best,

Jen Walker

Jennifer Walker PhD, RPBio
A/Director, Emergency Support Services

Emergency Management BC<http://www.gov.bc.ca/emergency-preparedness-response-recovery>
Block A – Suite 200, 2261 Keating Cross Rd
Saanichton, BC CANADA V8M 2A5

Mobile: 250-882-6304 UC: 778-698-4974
24 Hour Emergency Reporting: 1-800-663-3456

For ESS News subscribe here<https://www2.gov.bc.ca/gov/content?id=F5674CDAE86D45D2B4505E55892D7931> and follow us on Twitter @EmergencyInfoBC<http://twitter.com/emergencyinfobc> or @PreparedBC<https://twitter.com/PreparedBC>

**Comment by caggles** [comment]
This all looks good! The only thing is that the namespaces must have names - they were assigned names as part of the provisioning process. They will have the form `a1b2c3-tools` `a1b2c3-dev` `a1b2c3-test` and `a1b2c3-prod` except that the six digits at the front will be a different set of random digits. Please provide those, and we'll be able to proceed!

**Comment by JEWALKER911** [comment]
Oh for Pete’s sake, we have been trying to resolve this for weeks and have no additional info to provide. We are not aware of any ‘namespace’ names.


This all looks good! The only thing is that the namespaces must have names - they were assigned names as part of the provisioning process. They will have the form a1b2c3-tools a1b2c3-dev a1b2c3-test and a1b2c3-prod except that the six digits at the front will be a different set of random digits. Please provide those, and we'll be able to proceed!
Can a human please connect with me. Thank you.
Jen Walker 250 882-6304

**Comment by caggles** [comment]
As per our conversation on Teams, the primary contact for this task is going to shift to a member of the original development team, so they can provide the missing information! I'm closing this ticket for now - please have the team open a new one once they have the necessary information :)
