### ISSUE TITLE
New project - BioHub BC

### ISSUE THREAD

**Issue by tdekens** [BCDevOps/devops-requests#484]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

If you are one of these two people, please ensure that you also request Openshift access if you don't have it already. This request does NOT grant you access to the platform itself - you will find a separate request for that on the issues page of this repo!
However, you may submit both requests at the same time - there's no need to wait until that request has been completed to submit this one.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

Read through the Platform Onboarding Guide before continue with this request. This helps to get clear expectations of the platform and how to collaborate with the Platform community alone the journey:
https://developer.gov.bc.ca/Welcome-to-our-Platform-Community!

- [x ] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4.1
To address current capacity issues related to the limited Platform CPU, we’ve made the difficult decision to temporarily prioritize new project requests, based on the following criteria, please check the ones that apply to your project.

- [ ] Your project addresses the needs of an urgent COVID-19 response
- [x ] Your project has been designated as high business priority
- [x ] You have the DevOps capacity in place to support the development of resilient architecture suitable for multi-node deployment

This is a temporary situation only, which will be resolved when we migrate to OpenShift 4 (OCP 4) in Fall 2020. Our OCP 4 expansion more than doubles current CPU capacity with new production clusters, plus an additional Azure Cloud offering. 

## Step 4.2
Fill out the following fields

* Short Team/Organization Name: ENV-KMB
* Product Short Name: BioHub BC
* Product Full Name: BiodiversityHub BC
* Product Description: The BioHub BC System will be the source of BC’s species and habitat inventory field data for both internal and external stakeholders of ENV & FLNRORD.
* Product Group Name (if exists, used to group together OpenShift Project Sets that are related to each other): 
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): 

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)
* Other Critical Contacts
  - (this could be a member of IMB, Architecture, Privacy, etc groups)
  - Email Address:
* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by mitovskaol** [comment]
@tdekens  Hi Tammy, due to the capacity restrictions on the Platform at this moment, we can only accomodate requests for COVID-19 related new applications. All other projects will be onboarded onto the Openshift 4 Platform when it becomes available in the next several weeks - we are doing estimation and planning at this moment to come up with a migration date for early adopter applications. There will be a sign up sheet sent out next week and if you would like to be added as an early adopter to get access to the Openshift 4 Silver cluster (first prod cluster that will be available in OCP 4 Platform) , I encourage you to register. Please let me know if you have any quesitons.

**Comment by caggles** [comment]
I'm going to close this ticket, as we are not planning to create this project set in 3.11. We are working on a different process for requesting new project sets for OCP 4 - you'll hear more about it in the coming weeks!
