### ISSUE TITLE
Request for Access for: bruce-tonkin

### ISSUE THREAD

**Issue by franTarkenton** [BCDevOps/devops-requests#485]
## Step 0

**Are you the Technical Lead?**
I think I am?

**Do you actually need the team member to be a member of the organization?**
- Bruce works at DataBC,, and has the requirement to be able to create repo's in the github bcgov org.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation
* Done!

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
* Done!

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: 
* GitHub Org: bcgov
* Full Name: Bruce Tonkin
* GitHub ID: @bruce-tonkin
* GitHub Account 2FA Confirmed: yes
* Email address: Bruce.Tonkin@gov.bc.ca
* Organization: DataBC
* Project Role: QA, DevOps
* GitHub Team to Join"
    * https://github.com/orgs/bcgov/teams/databc-map
    * https://github.com/orgs/bcgov/teams/databc
    * https://github.com/orgs/bcgov/teams/databc-write
* Existing GitHub Repo: 
    * N/A

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by bruce-tonkin** [comment]
Thanks Kevin,

Looks like I now have access.

Thanks,
________________________________________________________________
Bruce Tonkin | DataBC |
PHONE... 250-952-6845

**Comment by franTarkenton** [comment]
Hey Brucey!

Haha, thanks for the thanks, but I think you speak to soon.  I’m pretty sure you don’t have access yet.

The issue is still open and you are not showing up as a member of the bcgov organization:
https://github.com/orgs/bcgov/people?query=tonkin

Cheers

Kevin

**Comment by franTarkenton** [comment]
Hmmm, I might be missing something here, but I don't think Bruce got added to BCGOV.  If he did shouldn't BCGOV show up in his member orgs on this page: https://github.com/bruce-tonkin

Currently it shows him as a member of bcdevops but not bcgov.   Was also hoping that bruce could be added to these bcgov teams:

    https://github.com/orgs/bcgov/teams/databc-map
    https://github.com/orgs/bcgov/teams/databc
    https://github.com/orgs/bcgov/teams/databc-write

Again apologies if I'm missing something here, please and thank you!

**Comment by ShellyXueHan** [comment]
I've invited but Bruce has not yet accepted yet.

**Comment by franTarkenton** [comment]
ahhh Thanks Shelly!  Cheers!

**Comment by bruce-tonkin** [comment]
I have logged in, all looks good.

Thanks,
________________________________________________________________
Bruce Tonkin | DataBC |
PHONE... 250-952-6845
