### ISSUE TITLE
S3 Object Store (for InvasivesBC Photos)

### ISSUE THREAD

**Issue by micheal-w-wells** [BCDevOps/devops-requests#487]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** InvasivesBC needs to save photos, one of our devs suggested we move forward with the object store.  We do not know who to engage to get this going and are looking for help from you guys.
2. **Why should this be a new request type?** Didn't see it in the list.
3. **What information is required to fulfill this request?** Just tell us where to start and we will provide whatever info you need.
4. **What is the end result?** Access to an S3 object store with storage limits that meet our needs.

**Comment by caggles** [comment]
Hey @micheal-w-wells! The platform services team is actually not the group you'll want to speak to about getting your own S3 namespace in the government object store. That's an iStore thing (for now, anyway). You can start up your own iStore order a namespace of your own and, if you have any questions, you can contact david.button@gov.bc.ca for more information!
