### ISSUE TITLE
Artifactory Repos for BCRegistry Assets (Personal Property and Mobile Homes Registry)

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#49]
- [x] Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Using-Artifactory
- [x] Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
- [x] Step 3
Ensure that you have already logged into Artifactory at least once via Keycloak to create your personal account name:
https://artifacts.developer.gov.bc.ca

## Step 4
Fill out the following fields

* Requester: thorwolpert@github
* Team Name: assets
* Repo Type: npm, pypi, docker, mvn
* Repo Location: local
   - Please add to the bcr-*-virtual s
* Repo Description: to hold project level and vendor specific artifacts
* Primary OpenShift Project: zwmtib-tools
* (if virtual) List of Related Repos:

**Comment by caggles** [comment]
> Please add to the bcr-*-virtual s

I assume this means you'd like me to create any of the appropriate virtual repos that don't already exist as well?

**Comment by thorwolpert** [comment]
yes please

**Comment by caggles** [comment]
oh, sorry, one more question - can you please update the ticket to provide the list of repos you want included in those virtual ones? I assume you'll want the new local repo and some of the caching repos in each, but i'm not sure which caching repos (especially for maven, since there are a lot).

**Comment by thorwolpert** [comment]
I think just maven.org to start will be ok.

**Comment by caggles** [comment]
@thorwolpert why is the team name "assets" - isn't the team called BCR?

**Comment by thorwolpert** [comment]
maybe a hyphen bcr-assets, it's the only asset registry in gov't

**Comment by caggles** [comment]
I already called them all bcrassets - do you want me to go back and change them, or is this okay?

**Comment by thorwolpert** [comment]
could we have jcenter also added to the maven virtual repo? sorry for the last minute add
