### ISSUE TITLE
grant OpenShift Project set access to new dev

### ISSUE THREAD

**Issue by ll911** [BCDevOps/devops-requests#491]
## Step 0
yes

Preferably, someone who is already a member of the BCDevOps Github org should request access for you. 
Consider asking someone to submit this ticket in your name in order to ensure that it is processed quickly.

If you do not have access to a team lead or other org member to ask for membership on your behalf, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed.

**Do you have a GitHub account?**
yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: 
* GitHub ID: @WhitneyDluhosh
* Business Email Address: whitney.dluhosh@gov.bc.ca
* Organization: SDPR-ELMSD-EWT
* Project Role: dev
* OpenShift Projects/Namespaces: 
`rpjtzt-prod rpjtzt-test rpjtzt-dev rpjtzt-tools`

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
WhitneyDluhosh is already a member of the bcdevops org and should have access to the openshift console already! If you're looking to provide access to a specific namespace, anyone with admin privileges on that namespace can do that for you!
