### ISSUE TITLE
Request for Membership

### ISSUE THREAD

**Issue by arcticweb** [BCDevOps/devops-requests#494]
- [x] Invite a user
- [ ] Remove a user

* Project Name: OpenShift 4 platform migration to the new  ARO Pathfinder cluster 
* GitHub Org: private (I'm with Telus on contract to PSA)
* Full Name: Warren Christian
* GitHub ID: arcticweb
* GitHub Account 2FA Confirmed: yes
* Email address: warren.christian1@telus.com
* Organization: Telus (on contract with PSA)
* Project Role: Developer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: 

I have been asked by Olena Mitovska <Olena.Mitovska@gov.bc.ca> to submit my request for membership.

I see in the documentation that I am not supposed to make this request myself, but I am submitting as directed by Olena. Please let me know if I need to have it re-submitted by someone else, or if I've selected the wrong request type.

**Comment by caggles** [comment]
Just confirming with Olena - if that goes down as expected, then I'll add you to the org!
