### ISSUE TITLE
ARO Cluster Request - JAG ISB Splunk Chatops

### ISSUE THREAD

**Issue by akroon3r** [BCDevOps/devops-requests#497]
## Step 0
**Are you the product owner or technical lead?**

Technical Lead: ✔️ 

**Have you had an alignment meeting?**

The ARO Pilot meeting on August 28, 2020

## Step 1
Visit DevHub for detailed instruction on creating a request:

Read through the Platform Onboarding Guide before continue with this request. This helps to get clear expectations of the platform and how to collaborate with the Platform community alone the journey:
https://developer.gov.bc.ca/Welcome-to-our-Platform-Community!

- [x] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Make sure no duplicated request exists, search here:

✔️ 

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4.1
To address current capacity issues related to the limited Platform CPU, we’ve made the difficult decision to temporarily prioritize new project requests, based on the following criteria, please check the ones that apply to your project.

- [x] Your project addresses the needs of an urgent COVID-19 response
- [x] Your project has been designated as high business priority
- [x] You have the DevOps capacity in place to support the development of resilient architecture suitable for multi-node deployment

This is a temporary situation only, which will be resolved when we migrate to OpenShift 4 (OCP 4) in Fall 2020. Our OCP 4 expansion more than doubles current CPU capacity with new production clusters, plus an additional Azure Cloud offering. 

## Step 4.2
Fill out the following fields

* Short Team/Organization Name: NTT Data
* Product Short Name: JISCO
* Product Full Name: Jag ISB Splunk Chatops
* Product Description: Chatops interface that takes json webHook alerts and pushes notifications to government chat platforms
* Product Group Name (if exists, used to group together OpenShift Project Sets that are related to each other): Jag ISB Splunk Chatops
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/jag-isb-splunk-chatops/

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)
* Other Critical Contacts
  - (this could be a member of IMB, Architecture, Privacy, etc groups)
  - Email Address:
* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by akroon3r** [comment]
@patricksimonian wasn't able to assign to you as directed

**Comment by mitovskaol** [comment]
Assigning to @patricksimonian and @stewartshea for processing

**Comment by akroon3r** [comment]
Email sent to pathfinder@gov.bc.ca, let me know if anything needs to be fixed :)

**Comment by stewartshea** [comment]
I've completed the tasks on my end and handed over to @patricksimonian and @j-pye for confirmation

**Comment by patricksimonian** [comment]
I've forwarded the information to @j-pye :)

**Comment by patricksimonian** [comment]
@akroon3r your projects have been provisioned! Please login to ARO Pathfinder (link in rc) and check it out with `oc projects`
