### ISSUE TITLE
Digital Marketplace - OpenShift project set

### ISSUE THREAD

**Issue by sutherlanda** [BCDevOps/devops-requests#5]
## Step 0
**Are you the product owner or technical lead?**
I am the technical lead (Andrew Sutherland), with Zachary Woodward being the product owner. 

**Have you had an alignment meeting?**
Yes, we had an alignment meeting with Todd Wilson on Nov. 7.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: Ministry of Citizen's Services - DEVEX
* Product Short Name: DIG_MKT
* Product Full Name: Digital Marketplace
* Product Description: The intent of this development is to build a product that will support digital procurement needs for the BC Government including services such as, but not limited to, Sprint With Us, Code With Us, The Procurement Concierge.
* Desired Environments: tools, dev, test, prod
* Product Technical Steward
  - GitHub ID: @sutherlanda
  - Business Email Address: andrew.l.sutherland@gov.bc.ca
  - RocketChat Account Username: andrew.sutherland
* Product Owner
  - Business Email Address: zachary.woodward@gov.bc.ca
  - RocketChat Account Username: Zachary.Woodward
* GitHub Repository: TBD (will submit a separate request)

**Comment by caggles** [comment]
@sutherlanda your new project name is xzyxml
