### ISSUE TITLE
Request to remove idir user cbowler from Keycloak

### ISSUE THREAD

**Issue by sumesh-aot** [BCDevOps/devops-requests#508]
## Step 0
**Are you the KeyCloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account? 
Due to an administrative error in another part of Service BC idir was accidentally deleted and restored later.
Now upon trying to login to our Dev, Test and PROD Env, he is prompted with 
'User with username **cbowler** already exists'

- What result of debugging have you obtained that lead you to request an account removal?
Tried removing the user from the realm (**fcf0kpqr**), with no luck.

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from KeyCloak

## Step 3
Field the following information.

* Username to be removed:  cbowler
* Realm ID where user is having problem login: fcf0kpqr

**Comment by sumesh-aot** [comment]
FTI : @cameron-freshworks

**Comment by ShellyXueHan** [comment]
@sumesh-aot IDIR user removed from dev and test sso.  But the account does not exist in prod. Please double check with user on login now.

**Comment by sumesh-aot** [comment]
@ShellyXueHan Thank you. In prod all looks good, sorry for causing some confusion.

**Comment by ShellyXueHan** [comment]
np Sumesh! I'll close the ticket now.
