### ISSUE TITLE
Request to remove a duplicate user from KeyCloak

### ISSUE THREAD

**Issue by mmumby** [BCDevOps/devops-requests#509]
## Step 0
**Are you the KeyCloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
"User with username sjavaher already exists. How do you want to continue?" error
There is only one instance of her idir/email in our realm
- What result of debugging have you obtained that lead you to request an account removal?
https://github.com/bcgov/ocp-sso/issues/68
We have gone through the steps in the above issue, The user has cleared her cache, attempted to login through an incognito window. 
We have searched through the users in our realms and she is the only user with this idir and email (sana.javaheri@gov.bc.ca)

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [X] Confirm that user is ready to have the account removed from KeyCloak

## Step 3
Field the following information.

* Username to be removed: sjavaher
* Realm ID where user is having problem login: mds

**Comment by ShellyXueHan** [comment]
@mmumby user removed from IDIR SSO prod and test already, please ask the user to double check now.

**Comment by mmumby** [comment]
@ShellyXueHan That worked, Thank you!
