### ISSUE TITLE
Request for BCGOV GitHub Organization Membership (@pbastia)

### ISSUE THREAD

**Issue by matthieu-foucault** [BCDevOps/devops-requests#516]
Requesting to:
- [x] Invite a user
- [ ] Remove a user

* Project Name: CAS
* GitHub Org: bcgov
* Full Name: Pierre Bastianelli
* GitHub ID: @pbastia
* GitHub Account 2FA Confirmed: yes
* Email address: pierre.bastianelli@gov.bc.ca
* Organization: BC Gov
* Project Role: Fullstack developer
* GitHub Team to Join (if exists): CAS, CAS Developers
* Existing GitHub Repo: N/A (access managed via GitHub teams)

**In addition, Pierre should be added to the CircleCI CAS security context**
Thanks,

Matthieu

**Comment by matthieu-foucault** [comment]
@caggles looks like @pbastia was not added to the CAS security context on CircleCI. AFAIK that can only be done by admins of the bcgov org.

**Comment by matthieu-foucault** [comment]
cc @Maralsotoudehnia

**Comment by Maralsotoudehnia** [comment]
@caggles @mitovskaol any chance you could help us out by granting @pbastia access to the above? Many thanks in advance!

**Comment by Maralsotoudehnia** [comment]
cc @dianadec

**Comment by ShellyXueHan** [comment]
`CAS` github team is part of the "Groups listed are able to execute this context on a workflow." Looks like as long as @pbastia join the gh team, he would have access to circleCI. Let me know if that's not true and how to actually add the user to the CAS security context on CircleCI. Thx!

**Comment by matthieu-foucault** [comment]
@pbastia was added to the CAS team last week https://github.com/orgs/bcgov/teams/cas/members but was not authorized to start the tasks that require the security context (see https://app.circleci.com/pipelines/github/bcgov/cas-ciip-portal?branch=feature%2Fpierre_test_ci_security)

**Comment by ShellyXueHan** [comment]
I wouldn't find a place to manage individual access on circleCI. All the permission I see are associated with the Github team only. Do you have circleCI instructions on how to do that for @pbastia ? How were the other CAS team members granted access before? Any chance @caggles did that for your team, as I don't recall about this.

**Comment by matthieu-foucault** [comment]
@wenzowski mentioned a CircleCI connector that could have been deleted from the bcgov org, preventing the GitHub team and CircleCI security context from synchronizing. Could that be the case?

**Comment by ShellyXueHan** [comment]
I need more details. but if that's just a github app, you can request to install it directly. We'll receive the notification and review.

**Comment by matthieu-foucault** [comment]
@Shellyhan looks like @pbastia now is able to start the jobs requiring the security context. Sounds like the synchronization just took a while, as indicated here https://circleci.com/docs/2.0/contexts/#making-changes-to-context-restrictions.
No further actions required, thanks!

**Comment by Maralsotoudehnia** [comment]
Thanks everyone and @caggles @ShellyXueHan @mitovskaol for your continued help with all the things!
