### ISSUE TITLE
Request for Dev/Test/PROD for agri-nmp-*

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/devops-requests#518]
## Step 0
**Are you the product owner or project admin/team lead?**
Yes.

**Does the Admin User have an IDIR account?**
Yes, IDIR/GARYWONG

**Are you requesting for Identity Provider Update?**
No

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? 
No

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: 
Nutrient Management Project

* OpenShift Project Set/s Info
  - Project set name:  
agri-nmp-dev
agri-nmp-test
agri-nmp-prod

  - Namespace ID:
agri-nmp-dev
agri-nmp-test
agri-nmp-prod

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@garywong-bc you should be able to start the form for realms on https://realm-o-matic.pathfinder.gov.bc.ca/ now.
