### ISSUE TITLE
MOH IAM documize public space

### ISSUE THREAD

**Issue by sleroy1016** [BCDevOps/devops-requests#521]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

## Step 1
Login to Documize with either an IDIR or GitHub account to create a Documzie user record:
http://docs.pathfinder.gov.bc.ca/

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a Space
- [ ] Remove a Space

## Step 4
Fill out the following fields

* Ministry:  Ministry of Health
* Short Team/Organization Name:  MOH IAM
* Team and Product Description:  MOH Identity and Access Management 
* Space Visibility: Public / Protected (only invited users could see) Public

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Space Admin User
  - GitHub or IDIR account:
  - Business Email Address: 
  - RocketChat Account Username: 

Please note that we will only start processing your request when the email has been received.

## Step 6
Once we create the space for you, you will have full control over the space, including:
- space settings
- user access
- content management

Reference: https://docs.documize.com/

**Comment by ShellyXueHan** [comment]
@sleroy1016 please login to documize with your IDIR account first (in step 1)

**Comment by sleroy1016** [comment]
Hi,

I am logged in at http://docs.pathfinder.gov.bc.ca/ with my IDIR ( SJLLEROY)

See below..

[cid:image001.jpg@01D685E4.30B00CD0]

Stephane Leroy | Enterprise Architect | Health IT Strategy, HSIMT Division | T 778.974.2666

Warning: This email is intended only for the use of the individual or organization to whom it is addressed. It may contain information that is privileged or confidential. Any distribution, disclosure, copying, or other use by anyone else is strictly prohibited. If you have received this in error, please telephone or e-mail the sender immediately and delete the message.

**Comment by ShellyXueHan** [comment]
okay space created: https://docs.pathfinder.gov.bc.ca/s/btbulslcdt55g9dl07d0/moh-iam?category=

**Comment by sleroy1016** [comment]
thanks

Stephane Leroy | Enterprise Architect | Health IT Strategy, HSIMT Division | T 778.974.2666

Warning: This email is intended only for the use of the individual or organization to whom it is addressed. It may contain information that is privileged or confidential. Any distribution, disclosure, copying, or other use by anyone else is strictly prohibited. If you have received this in error, please telephone or e-mail the sender immediately and delete the message.
