### ISSUE TITLE
MOH IAM integration guide public repo

### ISSUE THREAD

**Issue by sleroy1016** [BCDevOps/devops-requests#522]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. Please include a firm date by which you will move your repository to the open organization.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name:  MOH IAM Integration guide
* GitHub Org: bcgov or private  bcgov
* Details on choosing private repo: 
* Preferred name for repo:  MOH-integration-guide
* Expected date to move to public: MM/YYYY
* GitHub ID for repo owner: @sleroy1016
* GitHub Account 2FA Confirmed: yes or no yes
* Email address: stephane.leroy@gov.bc.ca
* Organization: MOH
* Project Role: technical lead
* GitHub Team to Join (if exists): bcgov/moh-iam

NOTE: I could not find a request to create a public repo but noticed you could chose bcgov in the private repo request. Sorry if there was a simpler way to make the request...

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
@sleroy1016  When do you plan to move the code to a public repo?  re: "Expected date to move to public" field in the request

**Comment by sleroy1016** [comment]
Hi,

If fact it can be a public repo. As per my note in the request, I could not find a issue request to ask for a public repo in bcgov but noticed you could select bcgov in the request for a private repo.

If there is a simpler way, my apologies and please redirect me to the correct process,

Thanks,
Stephane Leroy | Enterprise Architect | Health IT Strategy, HSIMT Division | T 778.974.2666

Warning: This email is intended only for the use of the individual or organization to whom it is addressed. It may contain information that is privileged or confidential. Any distribution, disclosure, copying, or other use by anyone else is strictly prohibited. If you have received this in error, please telephone or e-mail the sender immediately and delete the message.

**Comment by ShellyXueHan** [comment]
@sleroy1016 if you are a member of `bcgov` GitHub org, then you can create a public repo there. If not, start with the request `Request for BCGOV GitHub Organization Membership`.

**Comment by sleroy1016** [comment]
Ok, I believe I am already a member of bcgov but I could not create a bcgov repo. Am I missing something?

[cid:image001.jpg@01D685F6.BBBD1B30]

Stephane Leroy | Enterprise Architect | Health IT Strategy, HSIMT Division | T 778.974.2666

Warning: This email is intended only for the use of the individual or organization to whom it is addressed. It may contain information that is privileged or confidential. Any distribution, disclosure, copying, or other use by anyone else is strictly prohibited. If you have received this in error, please telephone or e-mail the sender immediately and delete the message.

**Comment by ShellyXueHan** [comment]
I don't see you in the members list. btw I can't seem to open the image link. Try commenting on GitHub directly and attached the image?

**Comment by sleroy1016** [comment]
I Shelly, 
Attached the screenshot.
![create_repo](https://user-images.githubusercontent.com/59711441/92620987-24770a80-f278-11ea-82da-6a19fbd8468c.JPG)

I created a ticket to get bcgov membership then. see #https://github.com/BCDevOps/devops-requests/issues/524 
Thanks,
Stephane

**Comment by sleroy1016** [comment]
Sorry, just confirmed that I am not a member of bcgov. Thought I was but I am a member of bcgov-c and BCDevOps but not bcgov ( oustide collaborator). you can close this ticket  and focus on #524. I see it's been assigned to a sprint, when can I expect it to be completed?
![member](https://user-images.githubusercontent.com/59711441/92759672-d54adb80-f344-11ea-8a4c-8a0107b8f3da.JPG)

**Comment by caggles** [comment]
Closed as requested - I'm working my way through the ticket queue and should come to the other ticket soon :)
