### ISSUE TITLE
bcgov membership for sleroy1016

### ISSUE THREAD

**Issue by sleroy1016** [BCDevOps/devops-requests#524]
## Step 0

**Are you the Technical Lead?**
If not, you need to ask your team's Technical Lead role to make this request. This role should be a member of the BCGOV Github org as part of the team onboarding process.

If you do not have access to a Technical Lead to ask for membership on your behalf, or the Technical Lead has not yet obtained the membership, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed! **Please indicate in this ticket if you need to schedule this meeting.** 
If you've already had a meeting as part of a request for an Openshift Project, please indicate that in the ticket as well.

**Do you actually need the team member to be a member of the organization?**
- Often, it works just fine to have a team member as a Collaborator on your repository, without them being a member of the `bcgov` GitHub organization. Before submitting this request, consider whether you could simply invite your team member to contribute as a Collaborator.  
  Instructions [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository).

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: MOH IAM 
* GitHub Org: bcgov or private  bcgov
* Full Name: Stephane Leroy
* GitHub ID: @sleroy1016
* GitHub Account 2FA Confirmed: yes or no    yes
* Email address: stephane.leroy@gov.bc.ca
* Organization: Ministry of Health 
* Project Role: Technical lead
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: bcgov/moh-iam

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @sleroy1016 ! We don't action requests for access for self. If you have a team lead who can submit a request for you, that would work, or you can chat up @mitovskaol and she can give an exception :)

**Comment by sleroy1016** [comment]
Could I ask the MOH product owner to comment on this ticket to confirm he approves this request ( instead of asking him to create a new ticket to request the same?)

**Comment by sleroy1016** [comment]
I realize it may not be possible for my colleague to comment on the issue so I'll ask him to create a new ticket or duplicate this one so that the request comes from someone else than myself.

Thanks.

**Comment by ninosamson** [comment]
Hi @caggles 
Can you accept my request on this or would you like me to create a new ticket? 

Nino

**Comment by caggles** [comment]
Hey @ninosamson - this is fine! I will action this in just a few minutes 😄

**Comment by sleroy1016** [comment]
Hi Cailey,

On Friday you seemed to be ready to action this but I am still a collaborator on BCGOV. Do you plan to do it today? 

Thanks,
Stephane

**Comment by sleroy1016** [comment]
Hi Cailey,

When I look at my organization, I am still a collaborator ( see below after new login), could you please double check.
![github_member_stephane](https://user-images.githubusercontent.com/59711441/93268127-8c8a8c80-f761-11ea-86f8-9bb52854d06a.JPG)
thanks

**Comment by caggles** [comment]
Hi @sleroy1016  please make sure you have accepted the invitation - it should be in your email inbox!

**Comment by sleroy1016** [comment]
Of course!

Thanks and sorry for not noticing.

Stephane Leroy | Enterprise Architect | Health IT Strategy, HSIMT Division | T 778.974.2666

Warning: This email is intended only for the use of the individual or organization to whom it is addressed. It may contain information that is privileged or confidential. Any distribution, disclosure, copying, or other use by anyone else is strictly prohibited. If you have received this in error, please telephone or e-mail the sender immediately and delete the message.
