### ISSUE TITLE
Moodle

### ISSUE THREAD

**Issue by warrenchristian1telus** [BCDevOps/devops-requests#526]
- [X] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4.1
To address current capacity issues related to the limited Platform CPU, we’ve made the difficult decision to temporarily prioritize new project requests, based on the following criteria, please check the ones that apply to your project.

- [ ] Your project addresses the needs of an urgent COVID-19 response
- [ ] Your project has been designated as high business priority
- [ ] You have the DevOps capacity in place to support the development of resilient architecture suitable for multi-node deployment

This is a temporary situation only, which will be resolved when we migrate to OpenShift 4 (OCP 4) in Fall 2020. Our OCP 4 expansion more than doubles current CPU capacity with new production clusters, plus an additional Azure Cloud offering. 

## Step 4.2
Fill out the following fields

* Short Team/Organization Name: BC Gov Moodle
* Product Short Name: Moodle
* Product Full Name: Moodle
* Product Description: Trial setup of open-source project
* Product Group Name (if exists, used to group together OpenShift Project Sets that are related to each other): 
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): 

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca
 
* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: warrenchristian1telus
  - Business Email Address: warren.christian1@telus.com
  - RocketChat Account Username: warren.christian
* Product Owner
  - Business Email Address: Ian.Hennem@gov.bc.ca
  - RocketChat Account Username:
  - Organization Code: PSA
  - Organization Unit Code: CMT - Contract Management
  - (refer to https://dir.gov.bc.ca/)
* Other Critical Contacts
  - (this could be a member of IMB, Architecture, Privacy, etc groups)
  - Email Address: FuXing.Li@TELUS.COM
* BC Government Security Contact Information
  - Ministry Chief Information Officer: CJ Ritchie
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)
 
  - Ministry Information Security Officer: Caleb Shortt
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)
 
  - Ministry Privacy Officer: Jennifer O'Neill - Email:  Jennifer.L.ONeill@gov.bc.ca
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

**Comment by mitovskaol** [comment]
The project set should be provisioned in the **ARO Pathfinder cluster**  Adding @patricksimonian  to this ticket to take care of the namespace provisioning in ARO .

**Comment by patricksimonian** [comment]
The project set has been provisioned! Please log into https://console-openshift-console.apps.pathfinder.aro.devops.gov.bc.ca/ to find your namespaces :) @warrenchristian1telus
