### ISSUE TITLE
Access Request to Existing Private Repo (bcgov-c/mhsu-virtual-clinic)

### ISSUE THREAD

**Issue by pksmith744** [BCDevOps/devops-requests#527]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?** Yes
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?** Yes
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?** Estimated move timeline is 6-8 months from the current date
All projects in the private organization are required to be there temporarily. This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. Please include a firm date by which you will move your repository to the open organization.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to: access an existing private repo
- [ ] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Project Name: eMHSU Project
GitHub Org: private
Details on choosing private repo: inherited historical and contractual requirement
Preferred name for repo: bcgov-c/mhsu-virtual-clinic
Expected date to move to public: 07/2021
GitHub ID for repo owner: @ pksmith744
GitHub Account 2FA Confirmed: yes or no: yes
Email address: pam.k.smith@gov.bc.ca
Organization: Ministry of Health
Project Role: Director
GitHub Team to Join (if exists): N/A

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @pksmith744 - normally, an existing admin would be able to grant you the necessary privileges in an existing repo. Is there a reason you can't have them grant you the access in question?

**Comment by pksmith744** [comment]
Hi Cailey,

The team structure has changed (and in hindsight, for the original request, the project should probably have considered other options for what it needed to do).  With that in mind and the recent changes to the project/team, and in line with the other private repos that we recently stood up for this project, I’m looking to be granted admin so that we can at least re-purpose this existing repo for the dev team.

Hope that helps.

Thanks,
Pam

**Comment by caggles** [comment]
Hey @sleroy1016 - looks like you're the one who currently has admin on this repo. Can you please confirm that this change is expected?

**Comment by sleroy1016** [comment]
Hi Cailey,

I don't think Pam realized I had admin access as we're on the same team. I've granted her admin access so it should be good.

NOTE: Could you please action my other ticket #524 so that I can be a BCGOV member, I am waiting for it to create a public GitHub repo. Thanks!
