### ISSUE TITLE
Request for new private bcgov-c repo

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/devops-requests#534]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. Please include a firm date by which you will move your repository to the open organization.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: Red Hat CoreOS Ignition Builder
* GitHub Org: bcgov-c private
* Details on choosing private repo: Contains sensitive system information
* Preferred name for repo: rhcos-ignition-builder
* Expected date to move to public: MM/YYYY
* GitHub ID for repo owner: @sbarre-esit
* GitHub Account 2FA Confirmed: yes
* Email address: steven.barre@dxcas.com
* Organization: DXCAS
* Project Role: Playbook to assist in building Ignition files for CoreOS
* GitHub Team to Join (if exists): devops-platform-operations

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by sbarre-esit** [comment]
This is per https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/582
