### ISSUE TITLE
Request new keycloak realms for Sheriff Scheduling project.

### ISSUE THREAD

**Issue by devinleighsmith** [BCDevOps/devops-requests#535]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

I'm going to be acting as a project admin for this project. However, I am making this request on the behalf of Wade Barnes.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin. 

my IDIR account is devinsmi 

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

This is my first time requesting realms. Previously that was handled for my by my team leads on PIMS and CASS. However I have worked with Keycloak as a developer and done some basic realm configuration. My team lead, Wade Barnes, is very experienced.

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

I have visited the above urls and received the expected Forbidden messages.

## Step 3
Field the following information.

* Project Name: sheriff scheduling

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - Namespace ID:jag-shuber (tools/dev/test/prod)

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by devinleighsmith** [comment]
@ShellyXueHan @caggles Sorry to be annoying, but what can I expect for a rough ETA on this? Hoping to provide some expectations to my team.

**Comment by ShellyXueHan** [comment]
@devinleighsmith you should now be able to start with https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by devinleighsmith** [comment]
Thanks @ShellyXueHan !

**Comment by devinleighsmith** [comment]
Sorry @ShellyXueHan I just logged into https://realm-o-matic.pathfinder.gov.bc.ca/ using my devinsmi IDIR. I get this message:

You do not have the correct permission to request a realm
Please contact the DevHub team for access here.

**Comment by ShellyXueHan** [comment]
Please try again now. So far you've completed the form and get the realms created, please update here and let me know. As we are currently undergoing the introduction of new SSO service name, your new realms will need some manual update.

**Comment by devinleighsmith** [comment]
I've created the realm-o-matic request, will let you know once the realms have been created.

**Comment by ShellyXueHan** [comment]
it should be good now. You'll notice that in sso-dev, the redirects happen with dev.oidc.gov.bc.ca. This is in progress and you can see the details here: https://chat.pathfinder.gov.bc.ca/channel/sso?msg=foX3rStJDwpm99ShX

**Comment by devinleighsmith** [comment]
Are there still some manual steps I need to follow? the provisioned environments seem to be working as expected.

**Comment by ShellyXueHan** [comment]
@devinleighsmith that's it. Your realms should be working all good now.
