### ISSUE TITLE
Request for two private repositories

### ISSUE THREAD

**Issue by DonnaHaga** [BCDevOps/devops-requests#537]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
Yes, I am a member

**Are you sure you need to have your project code close-sourced?**
Yes, it needs to be close-sourced. The Air Quality Section uses R scripts to generate air quality advisories and smoky skies bulletins in pdf format when air quality is or is expected to be poor. The pdfs are posted to the Ministry's website and distributed by email and sms with a subscription service. Contact information and logos for the relevant health authorities is included in the advisory. The data reported on in the advisories is publicly available.  Examples of existing bcGov github repositories that access the same data include envair, rcaaqs, and air-zone-reports. The Air Quality Section periodically makes updates to the language included in the advisories based on recommendations from the health authorities and the BC Centre for Disease Control. Although the pdf that is generated is widely distributed in the public domain, a private repository is requested to protect modifications to the R script that is used to generate the pdfs.

**What date will you move your project to open-source?**
It is not anticipated this project can be moved to open-source.

## Step 1
- [x] Make sure no duplicated request exists

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Names: aq-advisory and smoky-skies-bulletin 
* GitHub Org: bcgov
* Details on choosing private repo: to protect modification to air quality advisories and smoky skies bulletins
* Preferred name for repo: aq-advisory and smoky-skies-bulletin
* Expected date to move to public: never
* GitHub ID for repo owner: @DonnaHaga
* GitHub Account 2FA Confirmed: yes
* Email address: Donna.Haga@gov.bc.ca
* Organization: ENV, Environmental Protection Division, Regional Operations Branch, Monitoring Assessment and Stewardship, Air Quality Section (Assessments)
* Project Role: lead
* GitHub Team to Join (if exists): N/A

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@mitovskaol has the team reached out to you about this private repo request? Any decision made so far?

**Comment by mitovskaol** [comment]
@DonnaHaga I need to get more information about your request for a private repo. We typically only accept request for temporarily hosting code in a private repo before the team is ready to move it to a public repo. If you are not going to ever make your code open source, GitHub might not be an appropriate location for the code .

**Comment by mitovskaol** [comment]
@caggles  I had a meeting with @DonnaHaga and we agreed that she would engage with the Ministry's MISO to get his recommendation for a permanent location for the app code. Meanwhile, I approve the request with a note that the team has 12 month to find a new location for the code - either move it to a public repo or to an GitHub Enterprise repo once GitHub Enterprise is built in the BC Gov.
