### ISSUE TITLE
Increase PV quota for ixhmbm-prod

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/devops-requests#542]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
Ttechnical lead

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
no duplicate.

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Long Running (compute-long-running-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [x] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [x] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
ixhmbm-prod

**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.
Increase the max request storage size from 200Gi to 400Gi

## Step 5
Please explain here the reasons for requesting your quota change.
As per conversation with Olena, this is to allow the NR team to continue expanding use cases while waiting for access to OCIO/SIEM stack. This is a short to medium term solution, and we expect that it will move to OCIO/SIEM stack when ready.

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by caggles** [comment]
Hey @mitovskaol can you approve this please?

**Comment by sbarre-esit** [comment]
```console
$ oc -n ixhmbm-prod describe quota storage-netapp-block-standard-quota storage-quota
Name:                                                                     storage-netapp-block-standard-quota
Namespace:                                                                ixhmbm-prod
Resource                                                                  Used  Hard
--------                                                                  ----  ----
netapp-block-standard.storageclass.storage.k8s.io/persistentvolumeclaims  0     20
netapp-block-standard.storageclass.storage.k8s.io/requests.storage        0     400Gi


Name:                   storage-quota
Namespace:              ixhmbm-prod
Resource                Used  Hard
--------                ----  ----
persistentvolumeclaims  0     20
requests.storage        0     400Gi
```
