### ISSUE TITLE
Request to add bcgov-c/wally to SonarCloud

### ISSUE THREAD

**Issue by dainetrinidad** [BCDevOps/devops-requests#543]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
No :(

**Are you the admin user of the GitHub repositories?**
Yes

## Step 1
Done

## Step 2
Fill out the following fields

* Project Name: Wally (Water Allocation)
* GitHub repositories to add to SonarCloud:
  - https://github.com/bcgov-c/wally

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by ShellyXueHan** [comment]
@dainetrinidad I see that this private repo started 2019 June (from first commit https://github.com/bcgov-c/wally/commits/master?after=bffda898665fc5c77310526800a0b0dcd91d900b+2900&branch=master). Please note that all private repos are meant to be temporary and we expect teams to turn it to public asap (longest time to be one year period). 
However this repo does not have a date set yet as you mentioned that it's still waiting for direction from executives. Please connect with Olena @mitovskaol on detailed plans for this repo turning to public. Once you've settle with an expected date, I'll configure sonarcloud settings for you.
