### ISSUE TITLE
Request to add Lawrence Lau to OpenShift

### ISSUE THREAD

**Issue by Fosol** [BCDevOps/devops-requests#544]
## Step 1
- [x] grant user access

## Step 2
* Full Name: Lawrence Lau
* GitHub ID: @LawrenceLau2020
* Business Email Address: Lawrence.Lau@gov.bc.ca
* Organization: IMB
* Project Role: Developer
* OpenShift Projects/Namespaces: jcxjin-tools, jcxjin-dev, jcxjin-test, jcxjin-prod

**Comment by LawrenceLau2020** [comment]
I've accepted, thank you!
