### ISSUE TITLE
Request for additional Cloud Pathfinder Realms

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/devops-requests#553]
## Step 0
**Are you the product owner or project admin/team lead?**

Yes.

**Does the Admin User have an IDIR account?**

Yes.

**Are you requesting for Identity Provider Update?**

No.

## Step 0
We are currently planning on SSO service name migration, which will affect **all** existing teams on KeyCloak. If you are new to our SSO service or KeyCloak, we recommend you to wait for the migration to complete before starting the request. If you are experienced with KeyCloak integration and ready to work with us during the migration, feel free to continue on.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: Cloud Pathfinder

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - Namespace ID: tnfhhm-dev & tnfhhm-test & tnfhhm-prod

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by sheaphillips** [comment]
@caggles confirming you have what you need to action this?

**Comment by ShellyXueHan** [comment]
@sheaphillips realm-o-matic is currently under maintenance. Will be reopened tomorrow and you can start the request by then.

**Comment by ShellyXueHan** [comment]
@sheaphillips could you explain the reason for this extra realm for cloud pathfinder? Thanks!
also please note that realm-o-matic is now moved to https://realm-o-matic.developer.gov.bc.ca

**Comment by sheaphillips** [comment]
Hi @sheaphillips 

> @sheaphillips could you explain the reason for this extra realm for cloud pathfinder? Thanks!

We are deploying a new cloud landing zone and we need to have a distinct realm for each zone, so we can't use the same one we already have.

**Comment by ShellyXueHan** [comment]
@sheaphillips you should now be able to start the request form with IDIR account on  https://realm-o-matic.developer.gov.bc.ca
