### ISSUE TITLE
New SBC user requires removal IDIR from Keycloak to permit access to realm vtkayq4c

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#555]
## Step 0
**Are you the KeyCloak Realm Admin?** Yes  (John McColl jhmccoll)
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?  Access to realm vtkayq4c for IDIR nsobchak Nikki Sobchak
- What result of debugging have you obtained that lead you to request an account removal?
    
    We received a rocketchat feedback from Senior User regarding access for a new CSR.
    Username: cilling
    Office: Powell River
    Ticket Number: not available

  Message: We have a new CSR, nsobchak that previously worked with OCIO - she is encountering an unfamiliar log in when 
   trying to access the Q

  After determination of where the access was failing it appears that the IDIR account was directing to a different realm.  As such 
  this will require removal of the IDIR from Keycloak.  Here is part of the diagnostics that took place after analyzing the access 
  failure:

- karim.gillani
- Ahh.. ok that requires a delete request for Keycloak from Dev/Ops Requests in Github
- karim.gillani
- johnhmccoll knows the process. Please have him start that process.
- karim.gillani
- so when she left, her GUID changed.. now the system is confused 😉
- karim.gillani
- We need to remove her old IDIR GUID from keycloak

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [Y] Confirm that user is ready to have the account removed from KeyCloak

## Step 3
Field the following information.

* Username to be removed:  nsobchak  Nikki Sobchak   
* Realm ID where user is having problem login: vtkayq4c

**Comment by patricksimonian** [comment]
@caggles are we good to remove this? I can do it

**Comment by patricksimonian** [comment]
She has been deleted from keycloak :) have her re-login and create a new account
