### ISSUE TITLE
setup keycloak realms for esm-dev + esm-test

### ISSUE THREAD

**Issue by mtCarto** [BCDevOps/devops-requests#556]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 0
We are currently planning on SSO service name migration, which will affect **all** existing teams on KeyCloak. If you are new to our SSO service or KeyCloak, we recommend you to wait for the migration to complete before starting the request. If you are experienced with KeyCloak integration and ready to work with us during the migration, feel free to continue on.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

EPIC namespace was only setup with a prod SSO, we want to setup proper dev and test SSO realms for our environments now as well.

* Project Name: EPIC

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)

    *  esm-dev, esm-test

  - Namespace ID:

   * EPIC (dev), EPIC (test)

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@mtCarto what's your realm ID in prod? Could you also explain why there's only the prod realm but not dev/test? Thanks!

**Comment by mtCarto** [comment]
@ShellyXueHan  Realm Id is **eagle**. To my knowledge it was due to the Eagle project being started fairly early on in OCP3, and possibly expediency to get EPIC out the door.

**Comment by mtCarto** [comment]
Any updates on this ticket?

**Comment by ShellyXueHan** [comment]
@mtCarto we have not yet receive an email from you with admin user information. Once that's done I can create the dev/test realms that match the production eagle realm.

**Comment by ShellyXueHan** [comment]
@mtCarto dev and test realms created. Your IDIR account is the admin now.
