### ISSUE TITLE
remove IDIR kjohns from keycloak for user Kessiah Johnstone

### ISSUE THREAD

**Issue by neilz0r** [BCDevOps/devops-requests#563]
## Step 0
**Are you the KeyCloak Realm Admin?** Yes  NEBICKER
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?  Access to realm vtkayq4c for IDIR kmjohnst Kessiah Johnstone
- What result of debugging have you obtained that lead you to request an account removal?
user previously worked for service BC with a different IDIR kjohns - please remove kjohns from Keycloak

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from KeyCloak

## Step 3
Field the following information.

* Username to be removed: kjohns 
* Realm ID where user is having problem login: vtkayq4c

**Comment by ShellyXueHan** [comment]
user removed.
