### ISSUE TITLE
Issue with Duplicate email address

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#565]
## Step 0
**Are you the KeyCloak Realm Admin?** YEs
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?  User with username fshabeeb already exists. How do you want to continue?
- What result of debugging have you obtained that lead you to request an account removal?
Options: Review Profile and add to existing account.  Neither option helps.

I need to know what id's are associated with: Faiz.Shabeeb@gov.bc.ca

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!
- [x ] Confirm that user is ready to have the account removed from KeyCloak
--> Not currently in my keycloak realm.

## Step 3
Field the following information.

* Username to be removed: Unsure maybe fshabeeb?? or orther??
* Realm ID where user is having problem login: 296gqjn5

**Comment by ShellyXueHan** [comment]
@gil0109 from IDIR realm it's `fshabeeb@idir` that has the email address. But you can check from your realm users to see who else have this duplicate email address.

**Comment by ShellyXueHan** [comment]
@gil0109 is this issue resolved already? Any updates?

**Comment by gil0109** [comment]
No it's not.  I need help.

I can not find the user in my realm yet he gets the duplicate warning.  His email associated with fshabeeb is: Faiz.Shabeeb@gov.bc.ca

**Comment by ShellyXueHan** [comment]
@gil0109 we'll need the user to login again and double check on the email mapping. Sometimes there are IDIR accounts without an email, null values are considered duplicate as well.

**Comment by gil0109** [comment]
Resolved, thank you.
