### ISSUE TITLE
PharmaCare Special Authority Transformation

### ISSUE THREAD

**Issue by marklise** [BCDevOps/devops-requests#569]
## Step 1
- [x] By checking it I confirm that I have read and understood the roles and responsibilities as described in the Onboarding Guide.

## Step 2
Done

## Step 3
Are you requesting to:
- [x] Create a project set

## Step 4.1
To address current capacity issues related to the limited Platform CPU, we’ve made the difficult decision to temporarily prioritize new project requests, based on the following criteria, please check the ones that apply to your project.

- [ ] Your project addresses the needs of an urgent COVID-19 response
- [x] Your project has been designated as high business priority
- [ ] You have the DevOps capacity in place to support the development of resilient architecture suitable for multi-node deployment

## Step 4.2
Fill out the following fields

* Short Team/Organization Name: MoH-SAT
* Product Short Name: Special Authority
* Product Full Name: PharmaCare Special Authority Transformation
* Product Description: Transform delivery of Ministry of Health Special Authority program using Salesforce and electronic forms.
* Product Group Name (if exists, used to group together OpenShift Project Sets that are related to each other): N/A
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/MoH-SAT

## Step 5
Submit this ticket and email us the contact information.
Email sent.

**Comment by mitovskaol** [comment]
@marklise  Can you please reach out to me to discuss this request. We currently do not onboard new projects to the OCP 3.11 Platform that do not meet all requirements from the above mentioned criteria. However, exceptions are possible and this is why we need to talk. Also, the early access to the new OCP 4 Platform has launched on Oct 14 and all applications are expected to migrate off the OCP 3.11 and onto the OCP 4 by the end of Feb 2021. So you might want to start new development on the new Platform from the start and save yourself a migration later.

**Comment by marklise** [comment]
Hi @mitovskaol, I'm @mark in RC we can discuss there?

**Comment by caggles** [comment]
hey @marklise ! Yes, Olena can be found on RC, please make a comment here with the outcome of that conversation once it's done :)

**Comment by marklise** [comment]
@caggles yup we got in touch - we're working on other issues atm (getting the request successfully submitted for ocp4)

**Comment by mitovskaol** [comment]
Closing the request as the team will be getting a project set on the OCP 4 Platform.
