### ISSUE TITLE
CRD Bike Counts

### ISSUE THREAD

**Issue by jdou** [BCDevOps/devops-requests#57]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
Yes
**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.
Yes
## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
Yes

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: CRD
* Product Short Name: crdbikecounts
* Product Full Name: CRD Bike Counts
* Product Description: CRD Bike Count Data Visualization
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/jdou/CRD-BikeCount

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
The original project set was deleted by mistake, this request is to recreate a new set.

Project set created as `gvzrts-tools`, `gvzrts-dev`, `gvzrts-test`, `gvzrts-prod`. `jdou` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.

@jdou As confirmed that application has been setup, closing this thicket now.
