### ISSUE TITLE
Realm for Court Interpreter Scheduling

### ISSUE THREAD

**Issue by will-freshworks** [BCDevOps/devops-requests#573]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 0
We are currently planning on SSO service name migration, which will affect **all** existing teams on KeyCloak. If you are new to our SSO service or KeyCloak, we recommend you to wait for the migration to complete before starting the request. If you are experienced with KeyCloak integration and ready to work with us during the migration, feel free to continue on.

## Step 1
Are you new to RedHat Single Sign-On (KeyCloak)? If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will actually create the initial account on KeyCloak.

- https://dev.oidc.gov.bc.ca/auth/admin/idir/console
- https://test.oidc.gov.bc.ca/auth/admin/idir/console
- https://oidc.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: Court Interpreter Scheduling

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - Namespace ID:(OCP4) 1a7b16-dev, 1a7b16-test, 1a7b16-prod

* For existing KeyCloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.developer.gov.bc.ca/

**Comment by ShellyXueHan** [comment]
@will-freshworks is it the first time working on KeyCloak/RedHat SSO? If so let's book an onboarding meeting.

**Comment by will-freshworks** [comment]
Hi @ShellyXueHan. I've done quite a bit with Keycloak already, including [spinning a temporary one up on OCP4](https://court-interpreter-scheduling.apps.silver.devops.gov.bc.ca/auth/) so we could get our app into UAT without being blocked on getting an official BCDevExchange realm.

However, I would still love to book an onboarding meeting so I could learn how you'd like us to administer the realm - things like internal best practices.

If the meeting is 30mins I have time at:
Today (2nd) 10am, 10:30am, 4pm
Tomorrow (3rd) 9am, 10am, 4pm 
Wednesday (4th) 10:30am, 12pm, 2pm

I also have other times if these don't work.

**Comment by ShellyXueHan** [comment]
@will-freshworks Sounds great! Let's try today at 4pm then. My email is shelly.han@gov.bc.ca. Thx!

**Comment by ShellyXueHan** [comment]
@will-freshworks  you should now be able to start SSO realm request at https://realm-o-matic.developer.gov.bc.ca with your IDIR account.
