### ISSUE TITLE
OCP4 Storage Quote increase e69aae-prod

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#578]
## Step 0
**Are you the product owner or technical lead?** Yes
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Long Running (compute-long-running-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [x ] General Storage Quota (storage-quota)
   - [1 ] Number of PVCs
   - [ 5Gi] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied: e69aae-prod

**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.

Please increase storage quote from 50 Gi to 60 Gi. 

## Step 5
Please explain here the reasons for requesting your quota change.

This is to accommodate the current volume for COVID Isolation plan and Temporary Foreign worker space requirement.  We do plan to migrate to EDB when it's ready and can reduce at that time.

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by mitovskaol** [comment]
Quota increases for OCP 4 willl be handled by the Project Registry (and not by devops-requests) and this feature is expected to be made available to the product teams by Dec 2. We will provide an update on the status of it in Early Access Weekly Touch points. When the feature is rolled out in Project Registry, POs/Tech Leads will be able to request a quota increase for a specific namespace by clicking on a project name in the dashboard. This request in devops-request will now be closed.
