### ISSUE TITLE
Change Requestron to add new devops-requests to Sprint Goal

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/devops-requests#580]
Update requestron to add 0.5 point estimate to each new devops-request issue and link it to the current Sprint DevOps Requests Ticket goal

- [x] add 0.5 estimate
- [x] change the current pattern from adding it as a comment to the current ticket to adding it as a ticket inside the epic.
  - [x] how to determine what the appropriate epic is? make a design decision about this.
- [x] remove the current step to add the ticket to the milestone.
- [ ] test against testing-repo
- [ ] go to production

**Comment by caggles** [comment]
Hey @lukegonis and @mitovskaol ! Heads up - I added the `ops-controller` label to the developer-experience repo. The bot will expect the SG for devops-requests tickets to be in developer-experience and to have that label - otherwise the tickets won't get added to the epic!
