### ISSUE TITLE
Storage quota increase for multiple namespaces

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#589]
## Step 0
**Are you the product owner or technical lead?** Yes
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Long Running (compute-long-running-quota)
   - [x ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [x ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:

5c0dde-prod
df1ee0-prod 

**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.

Resource Type
CPU (Request) |  8 cores
CPU (Limit) |  16 cores
Please increase Storage Quota by a min of 10-15Gib.  Preferably more as we are increasing transactions substantially during Covid.

## Step 5
Please explain here the reasons for requesting your quota change.

For our two applications workspaces.  Similar application but one is for Service BC and another is for SDPR.

Having Patroni HA, RabbitMQ HA, Digital Signage Video Storage, and backup container, the current quota doesn't meet our needs.

With the addition of the Citizen facing Booking application and increase staff to manage COVID video chat, we have had to double our API pods which increase CPU Usage.  Growth is projected.

See devops-ocp4-migration for diagram and explanation.

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by mitovskaol** [comment]
Quota increases for OCP 4 willl be handled by the Project Registry (and not by devops-requests) and this feature is expected to be made available to the product teams by Dec 2. We will provide an update on the status of it in Early Access Weekly Touch points. When the feature is rolled out in Project Registry, POs/Tech Leads will be able to request a quota increase for a specific namespace by clicking on a project name in the dashboard. This request in devops-request will now be closed.
