### ISSUE TITLE
org owner access for Pop

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/devops-requests#59]
## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: DevOps Platform Service
* GitHub Org: private org, ***Organization Owner privilege***
* Full Name: Pop Kanjanakantorn
* GitHub ID: _unknown yet, Pop will update here once GitHub account is ready_
* GitHub Account 2FA Confirmed: yes
* Email address: tbd
* Organization: bcdevex
* Project Role: billing manager
* GitHub Team to Join (if exists): no
* Existing GitHub Repo: no

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hey Pop! Once you've updated this ticket with your github ID, please tag me in a comment so I get a notification :)
