### ISSUE TITLE
Clecio needs cluster-reader in SILVER

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/devops-requests#592]
Making this request on behalf of @mitovskaol 

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Clecio Varjao
* GitHub ID: @cvarjao
* Organization: FLNR
* Cluster Role: cluster-reader

**Comment by ShellyXueHan** [comment]
@sbarre-esit looks like you've got the PR. closing this ticket now.
