### ISSUE TITLE
Request to change quotas for 5115cc-*

### ISSUE THREAD

**Issue by agahchen** [BCDevOps/devops-requests#595]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

Yes.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Yes.

## Step 2
What quotas need to be changed? (Select all that apply)
- [x] CPU: Long Running (compute-long-running-quota)
   - [x] CPU Limit
   - [x] Memory Limit
   - [ ] CPU Request
   - [x] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:

**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

5115cc-dev, 5115cc-test, 5115-prod

## Step 4
Add details about your quota request here.

*ex: Please increase number of PVCs that can be provisioned to 30.*

Please increase the following for the highlighted namespaces:
* limits.cpu: from 8 cores to 32 cores
* limits.memory: from 32Gi to 64Gi
* rquests.memory: from 16Gi to 32Gi

## Step 5
Please explain here the reasons for requesting your quota change.

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

* limits.cpu: from 8 cores to 32 cores - to provide more room for bursty workloads at start up.
* limits.memory: from 32Gi to 64Gi - same as the limit quota in OCP3; required based on current usage profile.
* rquests.memory: from 16Gi to 32Gi - same as the request quota in OCP3; required based on current usage profile.

Internal ref: JHI-1948.

**Comment by agahchen** [comment]
Hi @caggles, @sbarre-esit, @ShellyXueHan, do you have an ETA for this request?  This is a critical dependency for our Nov production deployment.   Thank you!

**Comment by mitovskaol** [comment]
Quota increases for OCP 4 willl be handled by the Project Registry (and not by devops-requests) and this feature is expected to be made available to the product teams by Dec 2. We will provide an update on the status of it in Early Access Weekly Touch points. When the feature is rolled out in Project Registry, POs/Tech Leads will be able to request a quota increase for a specific namespace by clicking on a project name in the dashboard. This request in devops-request will now be closed.
