### ISSUE TITLE
Increase quotas for BC Registries Agent OCP4 environments

### ISSUE THREAD

**Issue by WadeBarnes** [BCDevOps/devops-requests#596]
## Step 0
**Are you the product owner or technical lead?**
- Yes

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
- Done

## Step 2
What quotas need to be changed? (Select all that apply)
- [x] CPU: Long Running (compute-long-running-quota)
   - [x] CPU Limit
   - [x] Memory Limit
   - [x] CPU Request
   - [x] Memory Request
- [x] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [x] Total Storage
- [x] General Storage Quota (storage-quota)
   - [x] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
- 7cba16-dev
- 7cba16-test
- 7cba16-prod

## Step 4
Add details about your quota request here.

- CPU Limit: 16
- Memory Limit: 64
- CPU Request: 8
- Memory Request: 32
- storage-netapp-file-standard-quota: 200 Gi
- storage-quota: 200 Gi

*Or bump up to the standard quotas for environment of equivalent "sizing".  I can't recall the specifics of what was desided on for small, medium, large ocp4 environments.*

## Step 5
Please explain here the reasons for requesting your quota change.

I've already run into quota limits provisioning resources.  I'm unable to provision the PVCs required for all of the resources for the environment.  I'll start running into memory and CPU issues when we do load testing as the pods scale to fairly high levels.  Overall we'll need these new environments to be comparable to our ocp3 environments to function.  I'm not asking for as much CPU and RAM for this environment though, as I don't know if we'll need it.

**Comment by WadeBarnes** [comment]
Checking in to see where this is in the queue.

**Comment by caggles** [comment]
hey @WadeBarnes - there's a small delay on quota changes in ocp4 because we were not expecting to get so many requests for quota increases so quickly. it might be a bit before we're able to action this!

**Comment by WadeBarnes** [comment]
It's blocking environment migration and testing at this point.

**Comment by WadeBarnes** [comment]
Would it be an option to pick a project size when requesting the OCP project sets in the first place?

**Comment by WadeBarnes** [comment]
Just happens the two projects I needed to migrate first (to really test things out), are "extra large" currently.  The OCP3 project sets have expanded quotas on RAM, CPU, and PVC.

**Comment by caggles** [comment]
Hey @WadeBarnes - we do not plan to allow users to pick a larger size when provisioning, but the automated process for upgrading to larger quotas should be fairly fast, so it would be feasible for you to make the request for a larger quota very quickly after requesting your namespace.

**Comment by mitovskaol** [comment]
Quota increases for OCP 4 willl be handled by the Project Registry (and not by devops-requests) and this feature is expected to be made available to the product teams by Dec 2. We will provide an update on the status of it in Early Access Weekly Touch points. When the feature is rolled out in Project Registry, POs/Tech Leads will be able to request a quota increase for a specific namespace by clicking on a project name in the dashboard. This request in devops-request will now be closed.
