### ISSUE TITLE
Storage quota increase for e52f12-test and e52f12-prod

### ISSUE THREAD

**Issue by kuanfandevops** [BCDevOps/devops-requests#598]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.
I'm the devops for Zeva team.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Long Running (compute-long-running-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ X ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [x] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
e52f12-test
e52f12-prod

**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.
e52f12-test: 
    increase storage-netapp-block-standard-quota to 200Gi
    increase storage-nfs-backup-quota to 100Gi
e52f12-prod: increase storage-netapp-block-standard-quota to 250Gi
    increase storage-nfs-backup-quota to 200Gi

## Step 5
Please explain here the reasons for requesting your quota change.
Our database needs roughly 50G space. 3 replicas on prod and 2 on test, plus rabbitmq 2 pods on test and 2 on prod and plus minio.

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by kuanfandevops** [comment]
Request a status update on this request as we are planning the Openshift v4 migration next week.

**Comment by kuanfandevops** [comment]
Hopefully this request can be approved soon, we are starting the Dev migration tomorrow and may hit Test and Prod, late this week or early next week.

**Comment by mitovskaol** [comment]
Quota increases for OCP 4 willl be handled by the Project Registry (and not by devops-requests) and this feature is expected to be made available to the product teams by Dec 2. We will provide an update on the status of it in Early Access Weekly Touch points. When the feature is rolled out in Project Registry, **POs/Tech Leads will be able to request a quota increase for a specific namespace by clicking on a project name in the dashboard**. This request in devops-request will now be closed.
