### ISSUE TITLE
Requesting Quota Increases - Health Gateway 

### ISSUE THREAD

**Issue by ninosamson** [BCDevOps/devops-requests#599]
## Step 0
**Are you the product owner or technical lead?** Yes. 
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [x] CPU: Long Running (compute-long-running-quota)
   - [x] CPU Limit
   - [x] Memory Limit
   - [x] CPU Request
   - [x] Memory Request
- [x] CPU: Time Bound (compute-time-bound-quota)
   - [x] CPU Limit
   - [x] Memory Limit
   - [x] CPU Request
   - [x] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
0bd5ad-tools, 0bd5ad-dev, 0bd5ad-test, 0bd5ad-prod
**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.
Please double computing resources to match OCP3. 
*ex: Please increase number of PVCs that can be provisioned to 30.*

## Step 5
Please explain here the reasons for requesting your quota change.
We have 10 applications and a database all running in each namespace (save for tools). 

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by ninosamson** [comment]
@sslaws FYI

**Comment by ninosamson** [comment]
hi @caggles just following up on this request - we're unable to deploy without this quota bump. 

Thanks,
Nino

**Comment by caggles** [comment]
hey @ninosamson  - we are working on this, but have been caught a bit by surprise by the high number of such requests so quickly! we're working on this, especially since it's a big blocker for you!

**Comment by ninosamson** [comment]
Thanks for the update @caggles

**Comment by mitovskaol** [comment]
Quota increases for OCP 4 willl be handled by the Project Registry (and not by devops-requests) and this feature is expected to be made available to the product teams by Dec 2. We will provide an update on the status of it in Early Access Weekly Touch points. When the feature is rolled out in Project Registry, POs/Tech Leads will be able to request a quota increase for a specific namespace by clicking on a project name in the dashboard. This request in devops-request will now be closed.
