### ISSUE TITLE
Digital Marketplace - BCGov GitHub repo

### ISSUE THREAD

**Issue by sutherlanda** [BCDevOps/devops-requests#6]
## Step 0

**Are you a product owner or technical lead for a project?**
I am the technical lead (Andrew Sutherland), and Zachary Woodward is the product owner.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Are you requesting to create a:
- [x] public repo in `bcgov` GitHub organization
- [ ] transition existing private repo in `bcgov-c` GitHub organization to public repo in `bcgov` GitHub organization
- [ ] temporary private repo in `bcgov-c` GitHub organization

## Step 3
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Fill out the following fields

* Project (Desired or existing repo name): digital_marketplace
* Project Description: The intent of this development is to build a product that will support digital procurement needs for the BC Government including services such as, but not limited to, Sprint With Us, Code With Us, The Procurement Concierge.
* Approver: @ZachWoodward
* Repo Owner GitHub ID: @sutherlanda
* For Private Repo Only
  * Rationale for being closed source: 
  * Approval from Enterprise DevOps branch leadership: @

## Step 5:
Make the GitHub User Access Requests for your team members.

**Comment by caggles** [comment]
https://github.com/bcgov/digital_marketplace
