### ISSUE TITLE
BCR Virtual Repos

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#60]
- [x] Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Using-Artifactory
- [x] Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
- [x] Step 3
Ensure that you have already logged into Artifactory at least once via Keycloak to create your personal account name:
https://artifacts.developer.gov.bc.ca

## Step 4
Fill out the following fields

* Requester: thorwolpert@github
* Team Name: bcr-assets, bcr-entities, bcr-names, bcr-pay, bcr-auth
* Repo Type: npm, pypi, docker, mvn
* Repo Description: to hold project level and vendor specific artifacts
* Primary OpenShift Project: 
  For the locals 
   - bcr-assets: zwmtib-tools
   - bcr-entities: gl2uos-tools
   - bcr-names: servicebc-ne-tools
   - bcr-pay: l4ygcl-tools
   - bcr-auth: 1rdehl-tools
* (if virtual) List of Related Repos:
  Virtuals
    All under 1 namespace: d7eovc-tools
     - bcr-pypi-virtual: (pypi, bcr-assets-pypi-local, bcr-entities-pypi-local, bcr-names-pypi-local, bcr-pay-pypi-local, bcr-auth-pypi-local)
     - bcr-npm-virtual: (npm, bcr-assets-npm-local, bcr-entities-npm-local, bcr-names-npm-local, bcr-pay-npm-local, bcr-auth-npm-local)
     - bcr-mvn-virtual: (maven.org, jcenter, bcr-assets-mvn-local, bcr-entities-mvn-local, bcr-names-mvn-local, bcr-pay-mvn-local, bcr-auth-mvn-local)
     - bcr-docker-virtual: (hub.docker.com, redhat, bcr-assets-docker-local, bcr-entities-docker-local, bcr-names-docker-local, bcr-pay-docker-local, bcr-auth-docker-local)

**Comment by caggles** [comment]
hey @thorwolpert - pretty much all of those virtuals already exist. Do you want me to move them, then?

**Comment by thorwolpert** [comment]
yes please

**Comment by caggles** [comment]
sorry @thorwolpert  i missed your response here in the flood of other github notifications. i'm going to get on this right away!
