### ISSUE TITLE
Human Rights Tribunal Project

### ISSUE THREAD

**Issue by csherman-gov** [BCDevOps/devops-requests#61]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: Justice Services Branch
* Product Short Name: HRT
* Product Full Name: Human Rights Tribunal
* Product Description: The HRT system is one many projects being developed under the Tribunal Transformation Initiatve (TTI) project. The system will consist of back-end functionality built on the Salesforce platform and a front end built in the OpenShift platform.

* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): HRT

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by kelpisland** [comment]
@csherman-gov  - Have we had an alignment session with your team, I'm drawing a bit of a blank.
If "no" then please set up a 30min meeting with me and your team including product owner and we'll get rolling on this request.

**Comment by csherman-gov** [comment]
Hi Todd.

I’ve a had a couple of meetings with various people at ISB about getting this set up. Not sure if they would be considered alignment meetings or not. What would normally be covered in that meeting?

**Comment by kelpisland** [comment]
This meeting covers platform specific demystification, expectations and how best to interface with my team - so different from ISB chat you may have had already.

**Comment by csherman-gov** [comment]
Thanks.

I will get this scheduled.

I am also going to be the product owner for this.

**Comment by csherman-gov** [comment]
Hi Todd. Are ok if the meeting is moved to 2:30-3:00 from 2:00-2:30?

**Comment by csherman-gov** [comment]
@caggles Hi Cailey. Could you assist me with the next steps. Please give me a call at 778-974-5696. Thanks

**Comment by caggles** [comment]
namespace is called qjtfov
