### ISSUE TITLE
HealthGateway SonarCloud request

### ISSUE THREAD

**Issue by sslaws** [BCDevOps/devops-requests#612]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

- I'm not sure that my account is in the bcgov organization

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: Health Gateway
* GitHub repositories to add to SonarCloud: bcgov/healthgateway
- 
- 

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by sslaws** [comment]
@ninosamson FYI

**Comment by caggles** [comment]
I understand the team is currently working on getting a complete list of repos to be added to sonarcloud. Please comment on this ticket once you have collected the necessary info!

**Comment by ninosamson** [comment]
@sslaws Do we need to keep this open still?

**Comment by sslaws** [comment]
Sorry for the delay, I've finally been able to verify the approach and everything is working nicely.  Could you please remove the healthgateway project previously created and add the following:
hg-common
hg-database
hg-encounter
hg-immunization
hg-jobscheduler
hg-laboratory
hg-medication
hg-patient

Please leave the hg-webclient and the hg-adminwebclient as previously created.

Thanks

**Comment by sslaws** [comment]
Including previous RC discussion with regard to the request to create additional projects for the same repo: Hi Shelly, my scan is still running on the global code base but I think I found a way to have smaller chunks. When I logged into the SonarCloud.io dashboard you can click the + to add a new project and then over on the right is link for create a project manually. I believe you should be able to select the same Repo more than once.

**Comment by ShellyXueHan** [comment]
@sslaws which GitHub org are those `hg-xxx` repos from? I don't see them in `bcgov`. Please note that SonarCloud is only enabled on `bcgov`. Also can you list the repos that need to be removed from SonarCloud to confirm?

**Comment by sslaws** [comment]
@ShellyXueHan all of the hg- sonar cloud projects should be linked to the bcgov/healthgateway GitHub project.

**Comment by ShellyXueHan** [comment]
@sslaws new sonarcloud projects created and you are admin of them all.
