### ISSUE TITLE
Request to change smag_project repository to private

### ISSUE THREAD

**Issue by chrsuthe** [BCDevOps/devops-requests#615]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**
If not, you will need to request membership first. Return to the Issues page and fill out that request first.

**Are you sure you need to have your project code close-sourced?**
We highly recommend open source, secrets and any sensitive information should never be part of your code based. If you still think your code needs to be private, please provide the details in the request.

**What date will you move your project to open-source?**
All projects in the private organization are required to be there temporarily. This org is a staging area that permits teams to work on removing private information so that it can be made open-source at a later time. Please include a firm date by which you will move your repository to the open organization.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: smag_project
* GitHub Org: bcgov or private  bcgov
* Details on choosing private repo: Our automated installation packages will include code for our Common Logon Page (CLP) application.  Exposing this code for public consumption will create a substantial security risk to our authentication infrastructure as all users that access SiteMinder protected applications use CLP.  CLP is heavily integrated with our SiteMinder service to provide IDIR, BCeID and BCSC authentication through SAML, Forms based and IWA paths.
* Preferred name for repo: smag_project
* Expected date to move to public: 12/2022
* GitHub ID for repo owner: @chrsuthe
* GitHub Account 2FA Confirmed: yes
* Email address: christine.sutherland@gov.bc.ca
* Organization: bcgov
* Project Role: Technical Lead and project admin
* GitHub Team to Join (if exists): 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @chrsuthe! We will need to move your repo into the private org in order to facilitate this. I have two options for this:

1. We can create for you a separate repo in bcgov-c where you can store only those parts of your project which are private. This may make your pipeline look a little more complicated, however.
2. We can transfer the existing repo into bcgov-c. This will require that your devs have membership in bcgov-c already - if you do not, you'll need to let us know who to add first, or else you'll lose access to your repo as part of this process. If you choose this option, we should chat (probably over rocket.chat) about when you'd like this repo to be moved so we can make sure to avoid issues during the transfer.

Please let me know which you would prefer!

**Comment by chrsuthe** [comment]
Thanks Cailey,

I think in order to keep things simple(ish) the existing repo should be moved over to bcgov-c with my account set with access (chrsuthe).  I can then add the rest of the dev team.  I think we will be OK with moving the repo on Monday but I will have to check with my dev folks.

Thanks for your quick response 👍 

Chris

**Comment by caggles** [comment]
Hey @chrsuthe! Sorry, I wasn't around yesterday - if you'd like, it'd probably be faster for us to hash out a good time for your team over RC! Feel free to poke me about that whenever you've spoken to your team!

**Comment by chrsuthe** [comment]
Hi Cailey,

Thank you for your response and apologies for my delayed response.  I am on RC but have never used it 😊.  Please let me know what timing would work best for you.

Thanks again for your help.

Christine

Christine Sutherland
Senior Technical Analyst
Web Access Management
Information Security Branch
Office of the Chief Information Officer
PO Box 9412 | Stn Prov Govt | Victoria BC V8W 9V1
Email    christine.sutherland@gov.bc.ca<mailto:christine.sutherland@gov.bc.ca>
Cell       250.507.2968
[cid:image001.png@01D6C240.05CA7C60]

**Comment by caggles** [comment]
Hi @chrsuthe !

How do you feel about my actioning this on Friday morning? In the meantime, please check to ensure that you and your team all have membership in the bcgov-c org. If you don't have access, you may find that you won't be able to see your repo once it moves into the private org anymore!

If you don't have the appropriate access, please open another ticket - there's a template for asking for membership to our orgs!

**Comment by chrsuthe** [comment]
Hi Cailey,

Thank you for reaching out.  Friday will work perfectly 😊

Could you add me as the admin for the site in the new org?

Thank you

Christine
Christine Sutherland
Senior Technical Analyst
Web Access Management
Information Security Branch
Office of the Chief Information Officer
PO Box 9412 | Stn Prov Govt | Victoria BC V8W 9V1
Email    christine.sutherland@gov.bc.ca<mailto:christine.sutherland@gov.bc.ca>
Cell       250.507.2968
[cid:image001.png@01D6C7D2.9C215CA0]

**Comment by caggles** [comment]
Transfer is complete - it looks like you (and your team?) should still have all the appropriate access. Please feel free to poke me on rocket.chat if you have any issues!

**Comment by chrsuthe** [comment]
Hi Cailey,

I am new to GitHub and I noticed that all of the code in our repo for smag_project is still viewable on github if I am not signed in.  I checked the settings in my repo and the option to set the project to private is disabled.  Is there anything I need to do on my end?

thanks,

Christine
