### ISSUE TITLE
One Realm = One Application or One Realm = Many Applications?

### ISSUE THREAD

**Issue by dbayne** [BCDevOps/devops-requests#62]
## Step 0
I have a Step 0.5 request, I would like to know if the KeyCloak Realm must be set up for each SSO application, OR can a KeyCloak Realm be used across a program, like for example, BCParks, who may have a SaaS product, OpenSource product and other products that will use the one Realm?
Also, can I get access to request a realm through Realm-O-Matic?

**Comment by caggles** [comment]
Hi @dbayne! You can link multiple applications to one realm, so long as it is sensible to do so. If you still need one, please open another request!
