### ISSUE TITLE
Request for henry-ngo for bcgov-c 

### ISSUE THREAD

**Issue by henry-ngo** [BCDevOps/devops-requests#631]
## Step 0

**Are you a member of the private BCGOV GitHub Organization already?**

No, I am not. I was directed to this template by @mitovskaol but please let me know if I should fill out another separate issue too.

**Are you sure you need to have your project code close-sourced?**

Yes, this is a project that is currently tracked to move to the future Github Private Enterprise instance, but will live in bcgov-c while that is being set up.

**What date will you move your project to open-source?**

At this time, there is no plan to move to open-source (see above). 

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

No duplicates found.

## Step 2
Are you requesting to:
- [x] Create a private repo
- [ ] Remove a private repo and go public

## Step 3
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: BC Population Health Surveillance and Epidemiology Analysis Tools
* GitHub Org:  private (bcgov-c?)
* Details on choosing private repo: 

This repo will contain utility, analysis and convenience functions specific to our team of analysts and data scientists in HLTH so it will not be very useful to the public. In the future, we may decide that some portion of this package can be split off and made open source. If so, we will do that. We are developing this code repository according to all open content guidelines where possible, so that it will be easy to shift the eligible portions to open source if that choice is made in the future.

* Preferred name for repo: bcphser-analysis
* Expected date to move to public: N/A
* GitHub ID for repo owner: @henry-ngo
* GitHub Account 2FA Confirmed: yes
* Email address:  Henry.Ngo@gov.bc.ca
* Organization: HLTH / Office of the Provincial Health Officer
* Project Role: Lead
* GitHub Team to Join (if exists): 
none 

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

Extra note: followup from our call on Monday Nov 16: In total, we expect to have 8 members from our team (including me) with access to this private repository. Hope that is still a reasonable number, if not---we can work out something. Thanks!

**Comment by ShellyXueHan** [comment]
@henry-ngo repo created here: https://github.com/bcgov-c/bcphser-analysis you'll be the admin after joining `bcgov-c` org (invitation sent). for the other team members, please create a new request for bcgov-c membership for their GitHub accounts. Thx!

**Comment by henry-ngo** [comment]
Just to clarify: the request ticket for bcgov-c membership says that collaborators to a repo do not need organization membership, but the message above said I should request access for my team members. Do they need membership because this is a private repo? Thanks!
