### ISSUE TITLE
GitHub Access Request for @JessicaPenno

### ISSUE THREAD

**Issue by jongoetz** [BCDevOps/devops-requests#632]
## Step 0

**Are you the Technical Lead?**
Yes

**Do you actually need the team member to be a member of the organization?**
Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name:
* GitHub Org: bcgov
* Full Name: Jessica Penno
* GitHub ID: @JessicaPenno
* GitHub Account 2FA Confirmed: yes
* Email address: Jessica.Penno@gov.bc.ca
* Organization: ENV
* Project Role: Water Quality Science Specialist
* GitHub Team to Join (if exists): ENVWater
* Existing GitHub Repo: Several, including shinyrems

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
Re-added JessicaPenno to bcgov org.
