### ISSUE TITLE
Requesting storage quota increase for 6cdc9e-prod

### ISSUE THREAD

**Issue by JLWade** [BCDevOps/devops-requests#634]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [x] Total Storage
- [ ] Storage: Netapp Backup (storage-netapp-file-backup-quota)
   - [ ] Number of PVCs
   - [x] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:

`6cdc9e-prod`

**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.

- Please increase `netapp-file-standard` total storage quota to 250GB.  
- Please increase `netapp-file-backup` total storage quota to 250GB.

## Step 5
Please explain here the reasons for requesting your quota change.

Please see below breakdown of our storage usage:

**netapp-file-standard**
- Minio: 200GB
- MongoDB: 10GB
- Metabase: 10GB
- Temporary document storage: 2GB
- Backup verifications: 20GB

**netapp-file-backup**
- Minio backup: 200GB
- MongoDB and Metabase backup: 50GB

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by BcGovNeal** [comment]
I just want to clarify this request is for OCP4

**Comment by mitovskaol** [comment]
Quota increases for OCP 4 willl be handled by the Project Registry (and no in devops-requests) and this feature is expected to be made available to the team by Dec 2.  We will provide an update on the status of it in Early Access Weekly Touch point. when the feature is roll out in Project Registry, POs/Tech Leads will be able to request a quota increase for a specific namespace by clicking on a project name in the dashboard. This request will be closed.
