### ISSUE TITLE
Request to remove duplicate user IDIR AMACKAY from KeyCloak 

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#645]
## Step 0
**Are you the KeyCloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?

A new user is attempting to login to our application which uses Keycloak realm vtkayq4c.  This user is receiving an error page indicating "User with unsername amackay already exists."  I could not locate this IDIR in realm vtkayq4c when I did a search.

## Step 2
Deleting the user account from KeyCloak will also remove records with any other application using KeyCloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from KeyCloak
Yes this has been confirmed with user.

## Step 3
Field the following information.

* Username to be removed: AMACKAY
* Realm ID where user is having problem login: vtkayq4c

**Comment by jhmccoll** [comment]
This is for production keycloak.

**Comment by arcshiftsolutions** [comment]
@caggles @ShellyXueHan - I've removed user `AMACKAY` from the PROD IDIR realm and have asked @jhmccoll to ask the user to try again.
