### ISSUE TITLE
Quota Update

### ISSUE THREAD

**Issue by Kaineatthelab** [BCDevOps/devops-requests#651]
## Step 0
**Are you the product owner or technical lead?**
Yes

## Step 1
Make sure no duplicated request exists, search here:
- [x] https://github.com/BCDevOps/devops-requests/issues

## Step 2
What quotas need to be changed? (Select all that apply)
- [ ] CPU: Long Running (compute-long-running-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [x] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [x] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:
-> serviceBC-ne-prod
**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.
we need a 20 gb nfs storage

*ex: Please increase number of PVCs that can be provisioned to 30.*

## Step 5
Please explain here the reasons for requesting your quota change.
production database contains 800 mb of data, and grows every day and we can't lose any of it

Remember that OCP is a shared resource. Please be community-minded in making these requests and include thorough details about why your project's current resource usage cannot be reduced to adhere to the existing quota requirements.

**Comment by caggles** [comment]
hi @kaineatthelab! Am I correct in thinking that this request means you are using the nfs-backup storage type for your database? This may be easier to fix than via a quota request - you should consider using netapp-block-standard instead, which you will already have much more quota for.

**Comment by caggles** [comment]
Explanation as per the email thread:

More backup space, the daily backup is around 800 mb so the 5 gb is used up after 1 weeks worth of back ups. I am going to adjust the schedule so we do 5 daily, 1 weekly(4 per month) , 1 monthly(for 6 months) which will be about 15 gb.

**Comment by sbarre-esit** [comment]
@Kaineatthelab quota has now been increased!
