### ISSUE TITLE
 New Project set - Vector and Image Map Tile Server

### ISSUE THREAD

**Issue by jamesmunro-BCGOV** [BCDevOps/devops-requests#653]
New Project set - Vector and Image Map Tile Server 

Brief Description: Vector and Image Map Tile Server based on OpenStreet map.  This will provide core tile mapping functionality for a number of upcoming initiatives.
 
Product Owner - Jean Bishop 
Technical Lead - Volker Schunicht 
Security Contact - Dean Rodgers
Other contacts - James Munro, Iouri Atavine

Product Group - TRAN

Initial onboarding meeting with Olena Mitovska on November 18

**Comment by mitovskaol** [comment]
@jamesmunro-BCGOV Project Set provisioning request for OCP 4 should be submitted through the Project Registry https://registry.developer.gov.bc.ca/dashboard 
Closing this ticket.
