### ISSUE TITLE
Request for BCGOV GitHub Organization Membership

### ISSUE THREAD

**Issue by woongsoonjang** [BCDevOps/devops-requests#660]
## Step 0

Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Lodgepole Pine Foliar Nutrient Diagnosis and Fertilizer Advisory System
* GitHub Org: bcgov
* Full Name: Woongsoon Jang
* GitHub ID: @woongsoonjang
* GitHub Account 2FA Confirmed: yes
* Email address: woongsoon.jang@gov.bc.ca
* Organization: FLNRORD
* Project Role: Lead
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: woongsoonjang/PL_FERT_ADVISORY

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by cvarjao** [comment]
HI platform team, I've asked @woongsoonjang to create this ticket. He is not in OpenShift, or any team, they just need access to github to store code.

**Comment by caggles** [comment]
Thank you for the explanation, @cvarjao :)
