### ISSUE TITLE
New Project Request

### ISSUE THREAD

**Issue by Pahollan** [BCDevOps/devops-requests#67]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: Ministry of Education/DSSB
* Product Short Name: SACH
* Product Full Name: Student Achievement
* Product Description: The new student achievement applications to retire the OpenVMS Education application TRAX
* Desired Environments: tools, dev, test, uat, prod
* GitHub Repository (if exists): 

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: 
  - Business Email Address: 
  - RocketChat Account Username: 
* Product Owner
  - Business Email Address: (BCGov employee)
  - RocketChat Account Username: 
  - Organization Code:
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

* BC Government Security Contact Information
  - Ministry Chief Information Officer:
  - (refer to https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-technology/ocio/mcio_contact_list.pdf)

  - Ministry Information Security Officer:
  - (refer to https://intranet.gov.bc.ca/thehub/ocio/ocio-enterprise-services/information-security-branch/miso-contacts)

  - Ministry Privacy Officer:
  - (refer to https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/privacy/resources/privacy-officers)

Please note that we will only start processing your request when the email has been received.

**Comment by kelpisland** [comment]
Hi @Pahollan Let's set up a 30min alignment chat to get you rolling, ideally you whole team should attend. My calendar is up to date so find a time that works for your team.

**Comment by Pahollan** [comment]
I’m setting up a meeting for 3, sorry for the late notice, do you need to attend in person?

**Comment by caggles** [comment]
Hi @Pahollan! I sent you an RC message regarding the addition of a UAT environment to the standard set - please take a look at that, and once that gets cleared up, I'll continue with this request!

FYI @kelpisland

**Comment by caggles** [comment]
I've processed this request without the UAT environment as per my RC discussion with @Pahollan!
