### ISSUE TITLE
Learning Curator

### ISSUE THREAD

**Issue by dsandor716** [BCDevOps/devops-requests#672]
## Step 1
Are you requesting to:
- [x] grant user access 
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Kousthubha Marimganti
* GitHub ID: @Kousthubha-M 
* Business Email Address: kousthubha.marimganti@telus.com
* Organization: Telus
* Project Role: Open Shift technical consultant
* OpenShift Projects/Namespaces: 
a58ce1-dev
a58ce1-prod
a58ce1-test
a58ce1-tools

**Comment by Kousthubha-M** [comment]
I have been granted access but I am unable to see any projects in the console. Below are the namespaces I have been requested access for:

a58ce1-dev
a58ce1-prod
a58ce1-test
a58ce1-tools
