### ISSUE TITLE
Please update PO contact details for a OCP3 namespace

### ISSUE THREAD

**Issue by jleach** [BCDevOps/devops-requests#675]
Hey, I don't have much info on this project. I think I know who the PO is for the project as they are looking into how to migrate it. Better than nothing.

What annotations/labels need to be changed? (Select all that apply)
- [X] Product Owner
- [ ] Technical Steward
- [ ] Security Contacts
- [ ] Other Critical Contacts (contact info for other stakeholders such as members of IMB, Architecture, Privacy, etc groups that are interested in receiving comms related to this project sets.
- [ ] Product Group (an optional label that can be used to group together OpenShift Project Sets that share a business function (e.g. Platform Services project sets are labeled as part of "Platform Services" product group.  The value for this label should be determined by the organization/ministry/branch/team that owns the Project Set)

*Project Set Info*
- Namespaces: 6ni3xg-prod

*Product Technical Steward*
Unknown
   
*Product Owner*
  - Business Email Address: Shane.Passmore@gov.bc.ca
  - RocketChat Account Username: shane.passmore
  - Organization Code: CITZ
  - Organization Unit Code: IMB

**Comment by patricksimonian** [comment]
added the annotations and labels :) thanks Jason
