### ISSUE TITLE
OC 3 cluster access for PO

### ISSUE THREAD

**Issue by micheal-w-wells** [BCDevOps/devops-requests#676]
## Step 0
**Are you the product owner or project admin?**
Admin

Preferably, someone who is already a member of the BCDevOps Github org should request access for you. 
Consider asking someone to submit this ticket in your name in order to ensure that it is processed quickly.

If you do not have access to a team lead or other org member to ask for membership on your behalf, a member of the Platform Experience team will contact you about your request once you have submitted it.
We will need to discuss your needs in a quick meeting before this request can be processed.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
I'll follow up and make sure she does.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: 
* GitHub ID: @LisaMoore1
* Business Email Address:  Lisa.moore@gov.bc.ca
* Organization: BCGOV
* Project Role: PO
* OpenShift Projects/Namespaces: 
I can grant namespace specific accesses but the product is Myrange

It's temp OC access for the PO so she can port forward to a database tool.

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
HI Michael, what namespaces where you wanting Lisa to have access to? Also are you an admin of these namespaces?
