### ISSUE TITLE
BC Parks KeyCloak Realm request

### ISSUE THREAD

**Issue by dbayne** [BCDevOps/devops-requests#68]
## Step 0
**Are you the product owner or project admin/team lead?**
dbayne is the Portfolio Lead.

**Do you have an IDIR account?**
IDIR\dbayne

**Are you requesting for Identity Provider Update?**
No

## Step 1
Login to each of the following links using your **IDIR credentials**. You will then see a "_Forbidden_" message, but this is expected behaviour and will actually create your initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console
DONE.

## Step 2
Field the following information.
* Project Name: BCPARKS

## Step 3
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created: 
* Admin user's IDIR account: IDIR\dbayne
* Admin user's Business Email Address: david.bayne@gov.bc.ca

Please note that we will only start processing your request when the email has been received.

## Step 4
After we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by caggles** [comment]
@dbayne you should be able to use realm-o-matic now!
