### ISSUE TITLE
request to add collaborators to bcgov-c repo

### ISSUE THREAD

**Issue by henry-ngo** [BCDevOps/devops-requests#680]
## Step 0

**Are you the Technical Lead?**
Yes

**Do you actually need the team member to be a member of the organization?**
I was requested to add team members as per #631 . Perhaps because it's a private repo on bcgov-c instead of bcgov? Would prefer to not have to have everyone set up with 2FA if not needed.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

Complete.

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Complete.

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: bcphser-analysis
* GitHub Org: bcgov-c
* Full Name: [see table below]
* GitHub ID: @ [see table below]
* GitHub Account 2FA Confirmed: not everyone, see question above on whether adding them to bcgov-c is necessary to collaborate on a private repo on bcgov-c
* Email address: [see list below]
* Organization:  HLTH / Office of the Provincial Health Officer
* Project Role: [see table below]
* GitHub Team to Join (if exists): N/A
* Existing GitHub Repo: https://github.com/bcgov-c/bcphser-analysis

| Full name           | GitHub ID          | Project Role  | GitHub Account 2FA confirmed?  |
| :----------------  | :----------------- | :------------- | :-----------------------------------  |
| Reiko Okamoto | @reikookamoto | Developer    | yes                                                 |
| Ioana Sevcenco | @E2019              | Developer    | pending, if needed                       |
| Xibiao Ye           | @vicxb                | Collaborator | pending, if needed                       |
| Anders Erickson | @acerickson       | Collaborator | pending, if needed                       |
| Yao Nie             | @yaoGithub2018 | Collaborator | pending, if needed                       |
| Aanu Abayomi | @aanuaba            | Collaborator | pending, if needed                       |
| Yonabeth Nava de Escalante | @ynava004  | Collaborator | pending, if needed          |

(if organization membership and 2FA is necessary, I will update this table once I confirm 2FA status of our team members) Thanks!

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @henry-ngo - yes 2FA is required for all users. Please have them add 2FA to their accounts and we will proceed once you comment on this ticket to let us know that this has been done!

**Comment by henry-ngo** [comment]
Thanks! Is it necessary to add everyone at once? It may work better with getting our team onboarded if we start with the first two names and then add everyone else in January.

**Comment by caggles** [comment]
I can add whoever you'd like right now. I'll close the ticket once I'm done, and then you can open another ticket later, at your leisure, with the names of whoever you want added at that point :)

**Comment by caggles** [comment]
Okay,  first two people are added - please open another ticket later for the rest :)

**Comment by henry-ngo** [comment]
Thank you @caggles ! We'll follow up with the rest of the team members in the new year.
