### ISSUE TITLE
Request for Removal of Developers' Exchange Platform project set (ON HOLD)

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/devops-requests#684]
All pods in all 4 namespaces have been scaled down to 0. The data has not been backed up yet and I have not received a direction from the team owner if they need the data archived. 

**When you action this request, please back up the data before you remove the namespaces (just in case).**

## Step 0
**Are you the Product Owner or Technical Lead?** Submitting on behalf of Rumon who is the PO for this project.

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
This project will not be migrated.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Yes

## Step 2
Confirm that you are aware that you are requesting to:
- [x ] Remove a project set 

devex-platform-dev
devex-platform-test
devex-platform-tools
devex-platform-prod

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

**Comment by mitovskaol** [comment]
The bcdevexchange.org website will be migrated by @jleach  . This request is on hold until the migration to OCP 4 is complete.

**Comment by mitovskaol** [comment]
The BCDevExchange website content was contained in ifttgq project set that has already been migrated to OCP 4. The content in  devex-platform is obsolete and is no longer relevant, so this project set can be removed.

**Comment by ShellyXueHan** [comment]
@mitovskaol just to confirm, there are still PVCs in prod namespace, are they all good to be deleted?

**Comment by mitovskaol** [comment]
@ShellyXueHan  Can you please back them up and then delete them
