### ISSUE TITLE
Request to Provision Temporary S3 Bucket

### ISSUE THREAD

**Issue by BcGovNeal** [BCDevOps/devops-requests#685]
**Describe the issue**
Please create a temporary S3 bucket  for my team (Falcon) to test migrating data from Minio to S3 Object Storage.

Permissions needed:

- List, Create and Delete Objects
- Ability to generate download URLs
- Ability to alter Object permissions (ACL)

Bucket name and username can be anything.  We only need a single user.

**Additional context**
This bucket will be used to test the EPIC project that resides in the `6cdc9e` namespace

**Definition of done**
Bucket and user are created.

Thank you!

**Comment by caggles** [comment]
You will find the secret in 6cdc9e-tools! Let me know if there's anything more you need!
