### ISSUE TITLE
Code accessible on project in bcgov-c domain

### ISSUE THREAD

**Issue by chrsuthe** [BCDevOps/devops-requests#687]
**Describe the issue**
The smag_project repository was moved to the bcgov-c domain on Dec 4.  It appears that the project is still viewable and the code within still accessible to outside users on github.

**Additional context**
I was able to navigate to github and without logging in I was able to go to the smag_project and view the uploaded code.  I am new to github but when I went to settings for the repo to verify that it was set to private option was disabled.  Is there something I need to do on my end

**Definition of done**
Have the smag_project private from outside the domain

**Comment by caggles** [comment]
Hi @chrsuthe - it seems like what happened was that the transfer included the existing collaborators for the project, who had not been yet added to bcgov-c and for whom there were no available seats in the repo, so the visibility was not made private. I have added more seats for them and changed the visibility! Please let me know if you need anything further

**Comment by chrsuthe** [comment]
Thank you Cailey,

Everything is now working as expected 😊

Christine

Christine Sutherland
Senior Technical Analyst
Web Access Management
Information Security Branch
Office of the Chief Information Officer
PO Box 9412 | Stn Prov Govt | Victoria BC V8W 9V1
Email    christine.sutherland@gov.bc.ca<mailto:christine.sutherland@gov.bc.ca>
Cell       250.507.2968
[cid:image001.png@01D6D2F1.2EE46680]
