### ISSUE TITLE
Request to create openshift project for BCSC-BPS

### ISSUE THREAD

**Issue by kusingh6** [BCDevOps/devops-requests#69]
## Openshift Project request - BCSC-BPS

Please process the request for the openshift projects for BCSC-BPS. Please the required details as requested in the template. We will be sharing the email shortly with further information and also please let us know if any information required.

* Short Team/Organization Name: ServiceBC-IDIM
* Product Short Name: BCSC-BPS
* Product Full Name: BC Services Card for Broader Public Sector
* Product Description: Resources for broader public sector (bps) agencies to learn, discover and complete integration of the BC Services Card authentication component within bps online service.
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists): https://github.com/bcgov/BCSC-BPS

**Comment by caggles** [comment]
Hi @kusingh6 - please provide the missing information from the email as soon as you can. We will proceed with this request once you have done so. Please also make a comment here once you have provided that information. Thanks!

**Comment by kusingh6** [comment]
Hi @caggles - I just sent an email with additional information. Please review and let me know if anything else required.
Thanks!
