### ISSUE TITLE
Request to add user to BCDevOps

### ISSUE THREAD

**Issue by abschwenker** [BCDevOps/devops-requests#691]
## Step 0

**Are you the Technical Lead?** Yes

**Do you actually need the team member to be a member of the organization?** Required for OpenShift Access

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: SIMS
* GitHub Org: bcdevops
* Full Name: Andrew Signori
* GitHub ID: @andrewsignori-aot
* GitHub Account 2FA Confirmed: yes
* Email address: Andrew.signori@gov.bc.ca
* Organization: AEST (Contracted from CGI)
* Project Role: Developer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: https://github.com/bcgov/SIMS.git

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
@andrewsignori-aot has been invited to BCDevOps org.
