### ISSUE TITLE
decommission an SSO realm - 296gqjn5

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#694]
## Step 1
Make sure no duplicated request exists, search here: Yes.
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do. SSO Realm removal.
2. **Why should this be a new request type?** A good rule of thumb: Is this task straightforward (or something that could be automated)? Does it involve something you don't have the permissions to do? If the answer to both questions is yes, you're probably good to go ahead!
3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!

Hi Team, I would like to decommission a realm. I don't see that option in the issues area. Now that I figured out how to hide other IdPs, I can merge into using just one realm.

Please remove the following for dev/test/prod:

https://oidc.gov.bc.ca/auth/admin/296gqjn5/console/#/realms/296gqjn5

4. **What is the end result?** Please provide plenty of details about what the end result should look like.  REMOVE SSO REALM.

**Comment by ShellyXueHan** [comment]
@gil0109 new request type created as `Request for delete a KeyCloak Realm`. Please start it a new one, thank you!
