### ISSUE TITLE
Digital Marketplace - KeyCloak realm

### ISSUE THREAD

**Issue by sutherlanda** [BCDevOps/devops-requests#7]
## Step 0
**Are you the product owner or project admin/team lead?**
I am the technical lead (Andrew Sutherland), with Zachary Woodward being the product owner.

**Do you have an IDIR account?**
Yes, my IDIR is `ansuther`

## Step 1
Login to each the following links using your IDIR credentials. You will and see a the "_Forbidden_" message, but this is expected behaviour and will actually create your initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console
- https://sso.pathfinder.gov.bc.ca/auth/admin/idir/console

## Step 2
Fill out the following fields:

* Project Name: Digital Marketplace
* Admin of Realm (IDIR username + email): ansuther, andrew.l.sutherland@gov.bc.ca

## Step 3
Once you submit your issued and we have completed processing your request, you can proceed to creating a realm at Realm-O-Matic: https://realm-o-matic.pathfinder.gov.bc.ca/

**Comment by caggles** [comment]
request processed - please follow step 3!
