### ISSUE TITLE
Add 2 new developers to bcdevops for openshift access

### ISSUE THREAD

**Issue by itchison** [BCDevOps/devops-requests#705]
## Step 0

**Are you the Technical Lead?**
Yes
**Do you actually need the team member to be a member of the organization?**
Yes - for openshift access

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

Done.

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name:  moh-prime
* GitHub Org: bcdevops
* Full Name: Alan Leung
* GitHub ID: @neophyte57
* GitHub Account 2FA Confirmed: yes
* Email address:  Alan.Leung@nttdata.com
* Organization:  NTT Data
* Project Role:  Full stack developer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: moh-prime

* Project Name:  moh-prime
* GitHub Org: bcdevops
* Full Name: Johnny Liu
* GitHub ID: @johnnyl6
* GitHub Account 2FA Confirmed: yes
* Email address:  Johnny.Liu@nttdata.com
* Organization:  NTT Data
* Project Role:  Full stack developer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: moh-prime

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
Invitations have been sent to the GitHub IDs listed in the request.
