### ISSUE TITLE
Request for Removal of Identity Access Management Project Set

### ISSUE THREAD

**Issue by sharpedavid** [BCDevOps/devops-requests#713]
## Step 0
**Are you the Product Owner or Technical Lead?**

Yes

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**

No migration needed.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**

Yes.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**

Yes.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

OK.

## Step 2
Confirm that you are aware that you are requesting to:
- [x] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

**Comment by caggles** [comment]
Hey @sharpedavid - can you please provide the actual namespace names for this project set? They're the ones that look like `a1b2c3-tools` `a1b2c3-dev` `a1b2c3-test`and `a1b2c3-prod`

**Comment by sharpedavid** [comment]
Hi @caggles they are: `gogbvt-tools`, `gogbvt-dev`, `gogbvt-test`, and `gogbvt-prod`.
