### ISSUE TITLE
Create private "Performance" repo

### ISSUE THREAD

**Issue by freshjwarren** [BCDevOps/devops-requests#722]
Are you requesting to:
- [x] Create a private repo

* Project Name: Performance
* GitHub Org: private
* Details on choosing private repo: Change management issues - see email thread with Justin
* Preferred name for repo: performance
* Expected date to move to public: 03/2021
* GitHub ID for repo owner: @Travis-A-Clark
* GitHub Account 2FA Confirmed: yes
* Email address: Travis.Clark@gov.bc.ca
* Organization: Public Service Agency
* Project Role: Product Owner

**Comment by mitovskaol** [comment]
@freshjwarren  Can you please reach out to me in Teams or Rocketchat to discuss this request. Thanks!

**Comment by caggles** [comment]
apologies, i added the wrong person as admit - travis should have admin access to the repo now :)
