### ISSUE TITLE
Moodle Aro -repo and namespace

### ISSUE THREAD

**Issue by dsandor716** [BCDevOps/devops-requests#725]
Step 1
[x] grant user access

Step 2

Full Name: Kousthubha Marimganti
GitHub ID: @Kousthubha-M
Business Email Address: kousthubha.marimganti@telus.com
Organization: Telus
Project Role: Open Shift technical consultant
OpenShift Projects/Namespaces:
d9r6jk-dev
d9r6jk-prod
d9r6jk-test
d9r6jk-tools

**Comment by caggles** [comment]
Kousthubha already has access to the BCDevOps org (which is the one necessary for access to the openshift cluster). The namespace admin can then grant access to the appropriate namespaces!

**Comment by Kousthubha-M** [comment]
Do I have to request namespace admin to grant access to namespaces?

**Comment by dsandor716** [comment]
Hi Cailey

As product owner, I cannot see the screen below with namespaces which my team member Allan Haggett can see.  I get re-directed (see comment below).
Can you please assist with Allan and Kousthubha to provide access?
I’m away next week but Allan and Kousthubha are working.
thanks

https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects

[cid:image005.png@01D6D9E7.C271D0C0]
David cannot access above link; redirects to github issue template to remove OCP 3.11
Should be able to see dashboard, with Learning curator namespaces as well as Moodle ones:

d9r6jk-dev
d9r6jk-prod
d9r6jk-test
d9r6jk-tools


David Sandor, Director, Corporate Learning Development
The Learning Centre | People and Organizational Development | BC Public Service Agency
716 Courtney Street | Victoria, BC | V8W 1C2 | 250-216-1436
Click Here for Tips for Using the Learning System<https://gww.gov.bc.ca/groups/learning-bc-public-service/learning-system-resources-and-support>

[TopWorkUnit2020]

[cid:image007.png@01D6D9E7.C271D0C0]
