### ISSUE TITLE
Request for KeyCloak Realm - BCSC-BPS

### ISSUE THREAD

**Issue by kusingh6** [BCDevOps/devops-requests#73]
## Step 0
**Are you the product owner or project admin/team lead?**
Product Owner: idir/Zsamji
Technical Lead: idir/KUSINGH

**Do you have an IDIR account?**
idir/KUSINGH
idir/vmenon
idir/FSHABEEB
idir/chrobins

## Step 1
Login to each of the following links using your **IDIR credentials**. You will then see a "_Forbidden_" message, but this is expected behavior and will actually create your initial account on KeyCloak.
- https://sso-dev.pathfinder.gov.bc.ca/auth/admin/idir/console -`Performed by all IDIR accounts`
- https://sso-test.pathfinder.gov.bc.ca/auth/admin/idir/console - `Performed by all IDIR accounts`
- https://sso.pathfinder.gov.bc.ca/auth/admin/devhub/console - `Performed by all IDIR accounts`

## Step 2
Field the following information.

* Project Name: BCSC-BPS
  Keycloam Realm: New Account

**Comment by caggles** [comment]
Hi! I need to know which specific idir account will be using realm-o-matic - you'll be able to add the rest to your realm once it's made. I assume that KUSINGH is the correct one?

**Comment by caggles** [comment]
@kusingh6 you should have access to realm-o-matic now :)

**Comment by kusingh6** [comment]
Thanks @caggles !!
