### ISSUE TITLE
Removal of OCP 3.11 Project Set gcpe-notifybc-dev/tools

### ISSUE THREAD

**Issue by f-w** [BCDevOps/devops-requests#731]
## Step 0
**Are you the Product Owner or Technical Lead?**
Yes

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
Yes.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Yes.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
Yes.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
Confirmed.

## Step 2
Confirm that you are aware that you are requesting to:
- [x] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

**Comment by mitovskaol** [comment]
@f-w Can you please update the request with the answers to the questions in the template. Thanks!

**Comment by f-w** [comment]
Updated.

**Comment by caggles** [comment]
hey @f-w i just noticed that the title specifies only dev and tools. If you're actually only seeking the removal of those two, we would please just request that you wait until you're ready to delete all four namespaces before making a request! But if that's just a typo and you do mean to remove all four namespaces in the set, please let me know :)

**Comment by f-w** [comment]
@caggles, this project set only contains 2 ns.
