### ISSUE TITLE
Request for BCGOV GitHub Organization Membership

### ISSUE THREAD

**Issue by jeffds** [BCDevOps/devops-requests#736]
[x] Invite a user

Project Name: 
GitHub Org: bcgov
Full Name: Jeff Stewart
GitHub ID: @jeffds
GitHub Account 2FA Confirmed: yes
Email address: jeff.stewart@gov.bc.ca
Organization: GDX, CITZ
Project Role: Technical Analyst

Account previously existed, but had to be purged when 2FA authenticator failed and recovery codes were lost to time.

**Comment by caggles** [comment]
Hi @jeffds ! If I'm to understand this correctly, you had a *different* account that was a member of the org, but lost access to it, and are looking to add this new account? Can you please send me the name of your old account?

**Comment by jeffds** [comment]
Same id, @jeffds.  Github support was able to de-associate my email address from the account and then delete it so it could be re-created using the same id and email account.

**Comment by caggles** [comment]
@jeffds can you get your team lead or PO to approve this request? we don't normally allow people to request access for themselves.

**Comment by jeffds** [comment]
Thanks Cailey, PO is on vacation right now so once they're back we'll get that in.

**Comment by caggles** [comment]
@jeffds if there's someone else who already has membership in BCGOV who can comment their approval on this ticket, I would accept that as well. PO is usually just the easiest option :)

**Comment by SteveMHoward** [comment]
Hello @caggles ,

I approve of this request, Jeff is part of our team :)
