### ISSUE TITLE
 get access the OpenShift console for learning curator

### ISSUE THREAD

**Issue by dsandor716** [BCDevOps/devops-requests#750]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

**As admin for the learning curator, I want to be able to access the OpenShift console so I can allow others on my team access to the below noted namespaces
## Step 2
Fill out the following fields

* Full Name: David Sandor
* GitHub ID: @dsandor716
* Business Email Address: david.sandor@gov.bc.ca
* Organization: BC Public Service Agency
* Project Role:  Product Owner
* OpenShift Projects/Namespaces: Learning Curator
a58ce1-dev
a58ce1-prod
a58ce1-test
a58ce1-tools

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @dsandor716 ! You will have access to the console now, and should have access to your namespaces as well. Please let me know if that's not the case!
