### ISSUE TITLE
Provision OpenShift Project for "Performance"

### ISSUE THREAD

**Issue by freshjwarren** [BCDevOps/devops-requests#751]
Request to:
- [x] create OpenShift project

Full Name: Kousthubha Marimganti
GitHub ID: @Kousthubha-M
GitHub Account 2FA Confirmed: yes
Email address: kousthubha.marimganti@telus.com
Organization: Telus Employer Solutions
Project Role: Technical Lead

Proposed namespace: performance

**Comment by freshjwarren** [comment]
See related GitHub repo request #722

**Comment by mitovskaol** [comment]
@freshjwarren The requesting namespaces in OCP 4, we use OCP 4 Project Registry http://registry.developer.gov.bc.ca/ The request must be submitted by a Product Owner with a valid IDIR.  I am closing this ticket and will be waiting for the request coming through the Project Registry.
