### ISSUE TITLE
Grant User Access to OpenShift Project "performance"

### ISSUE THREAD

**Issue by freshjwarren** [BCDevOps/devops-requests#752]
- [x] grant user access

* Full Name: Kousthubha Marimganti
* GitHub ID: @Kousthubha-M
* GitHub Account 2FA Confirmed: yes
* Email address: kousthubha.marimganti@telus.com
* Organization: Telus Employer Solutions
* Project Role: Technical Lead
* OpenShift Projects/Namespaces: performance-*

**Comment by caggles** [comment]
Hello! @Kousthubha-M already has access to the openshift console. We don't control access to the individual projects - the project admin can do that for you!
