### ISSUE TITLE
Removal of OCP 3.11 - servicebc-cfms

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#758]
## Step 0
**Are you the Product Owner or Technical Lead?** Yes.
If not, you will need to ask one of those two people to make this request.

If you are one of these two people, please ensure that you also request Openshift access if you don't have it already. This request does NOT grant you access to the platform itself - you will find a separate request for that on the issues page of this repo!
However, you may submit both requests at the same time - there's no need to wait until that request has been completed to submit this one.

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?** YEs
If not, please do so before you submit the request. 

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?** Yes
If not, please do so before you submit the request.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
If not, please do so before you submit the request.

## Step 1
Make sure no duplicated request exists, search here: No.
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Confirm that you are aware that you are requesting to:
- [ X] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

**Comment by ShellyXueHan** [comment]
@gil0109 hi Karim, your prod namespace still have PVCs not deleted. Can you confirm the project set is all ready to be removed?

**Comment by gil0109** [comment]
Confirmed.  Sorry, just no time to delete all the items.  I did scale everything down.

I can delete them, but it may be a week or so..

Karim

**Comment by ShellyXueHan** [comment]
thanks Karim! no worries about the pvc then. project set removed.
