### ISSUE TITLE
Grant ZenHub access to BCGOV-C organization

### ISSUE THREAD

**Issue by Travis-A-Clark** [BCDevOps/devops-requests#763]
We recently tried to link ZenHub to our Performance repository in bcgov-c and are told that access to the organization is pending. Are there any additional steps we should take? Any idea how long authorization could take?

Thanks!
Travis

**Comment by caggles** [comment]
Hi @Travis-A-Clark - can you provide a little more information about what you did to link your repo to zenhub, and the specific message you got in response? I don't see any evidence that zenhub is awaiting permission to access the org or repo.

**Comment by freshjwarren** [comment]
@caggles: I believe Travis did this:
1. Went to https://app.zenhub.com/ and selected Try for Free for the web app
2. On the screen "Create a new ZenHub workspace" entered a name and selected +Add Repos
3. Selected the performance repo, then clicked Add and Save
4. ZenHub gave a message that the organization access was pending

Currently when Travis goes to https://github.com/settings/applications, he sees the attached.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/33360325/104521714-4da30100-55b2-11eb-8255-4d362481b8da.png)

**Comment by caggles** [comment]
fixed via teams call!
