### ISSUE TITLE
Digital.gov.bc.ca

### ISSUE THREAD

**Issue by HeatherRemacle** [BCDevOps/devops-requests#764]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

If you're looking to update the product owner or technical lead information, the person *currently* listed as product owner or technical lead needs to make this request, rather than the new person.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
What annotations/labels need to be changed? (Select all that apply)
- [X] Product Owner
- [X] Technical Steward
- [ ] Security Contacts
- [ ] Other Critical Contacts (contact info for other stakeholders such as members of IMB, Architecture, Privacy, etc groups that are interested in receiving comms related to this project sets.
- [ ] Product Group (an optional label that can be used to group together OpenShift Project Sets that share a business function (e.g. Platform Services project sets are labeled as part of "Platform Services" product group.  The value for this label should be determined by the organization/ministry/branch/team that owns the Project Set)

## Step 4
Submit this ticket and email us the contact information. 
Include the whole thing, but only fill out those sections pertaining the annotation you want updated.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

Link to the GitHub ticket you just created

Project Set Info
  - Namespaces: c0cce6-prod, c0cce6-test, c0cce6-dev, c0cce6-tools  

Product Technical Steward
  - GitHub ID: @parulmishra 
  - Business Email Address: Parul.Dubedy@gov.bc.ca
  - RocketChat Account Username: @parul.dubedy
   
Product Owner
  - Business Email Address: Mark.Wilson@gov.bc.ca
  - RocketChat Account Username: @mark.wilson
  - Organization Code: 
  - Organization Unit Code: 
  - (refer to https://dir.gov.bc.ca/)

**Comment by caggles** [comment]
Hi Heather! Looks like this is a request for changing the PO and tech lead of an OCP4 namespace. This is actually something you can do yourself with the project provisioner site! I will update this ticket to clarify that!
