### ISSUE TITLE
Retire and delete csnr-devops-lab-tools and csnr-devops-lab-deploy

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/devops-requests#765]
## Step 0
**Are you the Product Owner or Technical Lead?**
Ya bet'cha...

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
Definito... moved to `245e18-`.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Yuppers.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
Aye.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Affirmative.

## Step 2
Confirm that you are aware that you are requesting to:
- [X ] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

**Comment by caggles** [comment]
hey @garywong-bc ! there is still a pvc in the deploy namespace! please remove it and comment here to let me know when you're done!

**Comment by mitovskaol** [comment]
@garywong-bc Can you please confirm that the pvc has been removed and we will remove the projects set. Thanks!

**Comment by garywong-bc** [comment]
okay.. all PVC's have been removed thanks.
