### ISSUE TITLE
Request for Openshift Project for Traffic Courts Virtualization on OCP4

### ISSUE THREAD

**Issue by rantifamilusi** [BCDevOps/devops-requests#766]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.
We need OpenHhift namespace created for a new project - BC Traffic Courts Virtualization -on v4
2. **Why should this be a new request type?** 
I don't have access to creating this.
3. **What information is required to fulfill this request?** 
Project Name: BC Traffic Courts Virtualization
Business Contact:  **Stewart, Marti AG** - Marti.Stewart@gov.bc.ca / **Restall, Sylvia AG** - sylvia.restall@gov.bc.ca
Technical Lead: **Ranti Familusi** - ranti.familusi@nttdata.com - github account : @rantifamilusi , IDIR - BFAMILUS
DevOps Lead: **Paul Martin** - github account: @poggdogg , IDIR - PAULMART
Environments Required : Dev, Test & Prod
4. **What is the end result?** 
To have environment to deploy the solution we are developing.

**Comment by mitovskaol** [comment]
@rantifamilusi  We use OCP4 Project Registry for intake of the project set provisioning requests for OCP 4 http://registry.developer.gov.bc.ca/. However, the onboarding of the new project sets has temporarily been suspended as we ran out of capacity in the OCP 4 cluster and are waiting for the in-progress migrations to finish and remove their workloads from OCP 3 which will allow us to move the servers from OCP 3 to OCP 4 to increase the capacity in OCP 4. You can still submit the request and put it in the queue but it won;t processed at the moment. When the freeze is lifted we will give the priority to the requests for the apps migrating from OCP 3. Is this an existing OCP 3 app or a brand new project?

**Comment by rantifamilusi** [comment]
This is a new project and there is no existing namespace. 

Do you know when the freeze will be removed ?

**Comment by csherman-gov** [comment]
@mitovskaol @caggles Hi everyone. we need to get this expedited. This is a 2 million dollar project that needs to be delivered by the end of the year. There really isn't any room in the schedule to delay this. Thanks.

**Comment by juhewitt** [comment]
Hey @csherman-gov, can you please connect with @rloisell and we'll get this moving?  We can make this happen for you tomorrow (the 18th).  Incoming email.

**Comment by rloisell** [comment]
@juhewitt  - can we please have this issue deleted. There is now information in the public domain that shouldn't be.
