### ISSUE TITLE
OpenShift 4 Namespace to Migrate HRT from OCP 3

### ISSUE THREAD

**Issue by csherman-gov** [BCDevOps/devops-requests#767]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Please answer the following questions about the new request type:

What is it? Please provide an overview of what the request should do.
We need OpenShift 4 namespace created in order to migrate qjtfov-prod from OCP 3
Why should this be a new request type?
I don't have access to creating this.
What information is required to fulfill this request?
Project Name: HRT
Business Contact: Ryan Calbick - ryan.calbick@gov.bc.ca
Technical Lead: Arthur Newman - arthur-newman-belmar
DevOps Lead: Arthur Newman - arthur-newman-belmar
Environments Required : Dev, Test & Prod
What is the end result?
To have environment to deploy the solution we are developing.

**Comment by mitovskaol** [comment]
@csherman-gov  We use OCP4 Project Registry for intake of the project set provisioning requests for OCP 4 http://registry.developer.gov.bc.ca/. However, the onboarding of the new project sets has temporarily been suspended as we ran out of capacity in the OCP 4 cluster and are waiting for the in-progress migrations to finish and remove their workloads from OCP 3 which will allow us to move the servers from OCP 3 to OCP 4 to increase the capacity in OCP 4. You can still submit the request and put it in the queue but it won't be processed at the moment.
