### ISSUE TITLE
Access request for https://github.com/bcgov/CIT 

### ISSUE THREAD

**Issue by danielhirner** [BCDevOps/devops-requests#769]
Good afternoon,

I'm the PO for the Community Information Tool project.  We have recently changed vendors and our new vendors at NTT, Data Services require access to https://github.com/bcgov/CIT.  The previous govt admin Merwyn Pereira is on paternity leave. 

Can you please provide admin to myself (git: danielhirner) my govt email daniel.hirner@gov.bc.ca as well as our ScrumMaster Dan Wolfe (wit-dan)  Dan.1.wolfe@gov.bc.ca

Here is the list of folks that need write access: 

**Name | Idir | GitHub | BcGov Email |**  
Alex Joyeux | ajoyeux | **alexjoybc** | alex.joyeux@gov.bc.ca |  
Brendan Beach | bbeach | **BrendanBeachBC** | Brendan.Beach@gov.bc.ca
Dan Wolfe | dwolfe | **wit-dan** | Dan.1.wolfe@gov.bc.ca
Paul Dittaro | paulditt | **pdittaro** | Paul.A.Dittaro@gov.bc.ca
Sarah Hermsen | shermsen | **HypnoMama** | Sarah.Hermsen@gov.bc.ca
Marie Anik Paradis | MAAPARDA | **marieanik** | marieanik.1.paradis@gov.bc.ca
Justin Macaulay | JUMACAUL | **JustinMacaulay** |  
Adam Kroon | akroon | **akroon3r** | adam.kroon@gov.bc.ca

Thank you very much for your assistance!

-Dan 
(daniel.hirner@gov.bc.ca)

**Comment by caggles** [comment]
I have confirmation from dan's director that this request is legit, so we're going forward :)

**Comment by mitovskaol** [comment]
@danielhirner  Now that you have admin access, you can grant access to other users on the list.

**Comment by danielhirner** [comment]
@mitovskaol  Thank you!  I'm looking for where in https://github.com/bcgov/CIT to add users/grant access?  Apologies as it's been a few years since I've actively worked in git.  Isn't there normally a settings tab?

**Comment by mitovskaol** [comment]
@danielhirner  Yes, you can add individual GitHub users (must have bcgov org membership! ) in the repo's Settings -> Access (the link is below). 

   https://github.com/bcgov/CIT/settings/access
