### ISSUE TITLE
Remove Moodle from OCP 3.11 (d9r6jk)

### ISSUE THREAD

**Issue by warrenchristian1telus** [BCDevOps/devops-requests#771]
## Step 0
**Are you the Product Owner or Technical Lead?**
Yes.

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
I am still awaiting access to OCP 4, but as this is a new project, we're not concerned with migration tasks. We will rebuild in OCP 4.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Everything as been deleted.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
Yes.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 2
Confirm that you are aware that you are requesting to:
- [🗸] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

**Comment by ShellyXueHan** [comment]
@warrenchristian1telus I don't see a project set with `d9r6jk`, can you confirm what the namespace name is? Thx!

**Comment by mitovskaol** [comment]
@warrenchristian1telus  The namespaces for Moodle have been provisioned in OCP 4 2 weeks ago. The license plate is 950003. Allan or David can give you access to them as they are the admins for these namespaces.

**Comment by caggles** [comment]
hi @warrenchristian1telus - like shelly said above, we don't seem to have a project set called d9r6jk, so can you please confirm the name?

**Comment by warrenchristian1telus** [comment]
Hi @ShellyXueHan  and @caggles 

This was the previous route. Maybe it's already been removed. Deleted everything weeks ago.

moodle-route-d9r6jk-dev.apps.pathfinder.aro.devops.gov.bc.ca

I'm in OCP 4 now, so all good there.

**Comment by caggles** [comment]
hey @warrenchristian1telus - it looks like, based on the url listed here, your project was on the ARO cluster and not our local 3.11 cluster. Is that correct?

**Comment by warrenchristian1telus** [comment]
Yes @caggles - it was on Aro. I thought they were the same thing.

**Comment by warrenchristian1telus** [comment]
Should I just close this?

**Comment by mitovskaol** [comment]
Closing this as the namespaces will be removed automatically when the ARO Pathfinder cluster gets decommissioned in April/May.
