### ISSUE TITLE
BCGOV Github Access Request for tariq.chatur@gov.bc.ca 

### ISSUE THREAD

**Issue by Tariq-C** [BCDevOps/devops-requests#774]
I do not have a team member or a technical lead that can be associated with the project, however I have been tasked to move the source code for a project out of my personal Git to the government one. This is an odd situation and definitely will need to do the interview. 

Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

Fill out the following fields

* GitHub Org: bcgov 
* Full Name: Tariq Chatur
* GitHub ID: @Tariq-C
* GitHub Account 2FA Confirmed: yes
* Email address: tariq.chatur@gov.bc.ca
* Organization: ECS NCCS CITZ
* Project Role: Developer?

**Comment by caggles** [comment]
Hey @mitovskaol! Tariq has nobody to request access on their behalf - can you chat with them and approve this ticket please?
