### ISSUE TITLE
GitHub User Access Request - Jonathan Longe

### ISSUE THREAD

**Issue by jennifer-dowd** [BCDevOps/devops-requests#777]
GitHub User Access Request:
- Project: Road Safety Initiative
- GitHub org: bcgov-c
- Full name: Jonathan Longe
- GitHub ID: jonathan-longe
- Email address: Jonathan.Longe@gov.bc.ca
- Organization: PSSG, Road Safety BC
- Project role: Full stack developer
- Existing GitHub Repo: https://github.com/bcgov-c/jh-etk

**Comment by jonathan-longe** [comment]
In case it's a requirement, I have GitHub second-factor authentication enabled.

**Comment by jennifer-dowd** [comment]
Thank you.

**Comment by mitovskaol** [comment]
The access has been granted.
