### ISSUE TITLE
ALPAS - Application Logging & Performance Aggregation Services

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/devops-requests#79]
## Step 0
**Are you the product owner or technical lead?**
If not, you will need to ask one of those two people to make this request.

**Have you had an alignment meeting?**
If not, please set up a meeting with the Enterprise DevOps branch leadership prior to submitting a project request.

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-Request-a-New-OpenShift-Project

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: BCDEV
* Product Short Name: ALPAS
* Product Full Name: Application Logging & Performance Aggregation Services
* Product Description: Application Logging & Performance Aggregation Services
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists):  none (yet)

## Step 5
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* link to the GitHub ticket you just created
* Product Technical Steward
  - GitHub ID: cvarjao
  - Business Email Address:  clecio.varjao@gov.bc.ca
  - RocketChat Account Username: cvarjao

* Product Owner
  - Business Email Address: Wilson, Todd CITZ:EX <Todd.Wilson@gov.bc.ca>
  - RocketChat Account Username: todd.wilson
  - Organization Code: CITZ
  - Organization Unit Code: BCDEV

* BC Government Security Contact Information
  - Ministry Chief Information Officer: CITZ-IM
  - Ministry Information Security Officer: CITZ-IMBSPC
  - Ministry Privacy Officer: CITZ-IMBSPC

Please note that we will only start processing your request when the email has been received.

**Comment by ShellyXueHan** [comment]
Project set created as `ixhmbm-tools`, `ixhmbm-dev`, `ixhmbm-test`, `ixhmbm-prod`. `cvarjao` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.
