### ISSUE TITLE
Removal of ocio-pathfinder OCP 3 project set 

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/devops-requests#792]
## Step 0
**Are you the Product Owner or Technical Lead?** This is an obsolete project that does not have a PO.

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
This project will not be migrated

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Cailey, looking for your help with this as i dont have enough access.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
Cailey, looking for your help with this as i dont have enough access.

## Step 2
Confirm that you are aware that you are requesting to:
- [ x] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

**Comment by caggles** [comment]
@mitovskaol I can definitely deal with the scaling down and pvcs, but can you please confirm that it's okay for me to delete the pvcs?

**Comment by mitovskaol** [comment]
@caggles This is an abandoned app and no one is left around who has any interest in this app. However, to err on the side of caution, can you please back up the data in the pvcs and store it (on your local laptop for 3 months) before deleting them.

**Comment by caggles** [comment]
@mitovskaol i don't know what's in the pvc, so i wouldn't know how to ensure i got all the data. that's probably something better done by whoever developed the app originally.
