### ISSUE TITLE
Artifactory Nuget remote and virtual repo for FAMS3

### ISSUE THREAD

**Issue by pdittaro** [BCDevOps/devops-requests#80]
## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Using-Artifactory

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Ensure that you have already logged into Artifactory at least once via Keycloak to create your personal account name:
https://artifacts.developer.gov.bc.ca

## Step 4
Fill out the following fields

REPO 1:
* Requester: pdittaro@github
* Team Name: FAMS3 (though this should probably be for everyone)
* Repo Type: caching
* Repo Location: local
* Repo Description: Proxy repository for nuget.org 
* Primary OpenShift Project: frjeow-tools (though it should probably be used for all namespaces)
* (if virtual) List of Related Repos:

REPO2:
* Requester: pdittaro@github
* Team Name: FAMS3
* Repo Type: virtual
* Repo Location: virtual
* Repo Description: FAMS3 Virtual nuget repository for combining private local and nuget.org 
* Primary OpenShift Project: frjeow-tools (though it should probably be used for all namespaces)
* (if virtual) List of Related Repos:
- fams3-nuget-local
- REPO1

Description:
We are currently using the fams3-nuget-local repository to publish our private packages for the FAMS3 project. However, there doesn't seem to be a way with Dotnet Core 3.0 nuget to specify which specific packages you want to install from specific sources. As such, our build process is trying to download all of our non-private dependencies from fams3-nuget-local and failing.

I would like to request that a remote repository is set up to cache the default nuget repo at https://api.nuget.org/v3/index.json. I would also like to request that a virtual repo is created to front both this remote repo as well as the local fams3-nuget-local repository.

There is also a potential added advantage of caching the default remote nuget repository to speed up build times across all users of Artifactory.

**Comment by caggles** [comment]
@pdittaro just fyi, the caching repo won't be associated with your project or team - I have another way of adding those that will ensure everyone has shared access!

**Comment by pdittaro** [comment]
Thanks @caggles, thats what I was hoping would end up happening.
