### ISSUE TITLE
Org Access for Performance Repo Team Members

### ISSUE THREAD

**Issue by Travis-A-Clark** [BCDevOps/devops-requests#800]
Project Name: Performance
GitHub Org: bcgov-c

Full Name: Alison Buchanan
GitHub ID: @Abuchana
GitHub Account 2FA Confirmed: yes
Email address: alison.Buchanan@gov.bc.ca
Organization: Public Service Agency
Project Role: Scrum Master

Full Name: Kevin Best
GitHub ID: @kevindavidb
GitHub Account 2FA Confirmed: yes
Email address: kevin.Best@telus.com
Organization: Telus Employer Solutions
Project Role: Developer

Full Name: Jennifer Erickson
GitHub ID: @jenerick100
GitHub Account 2FA Confirmed: yes
Email address: Jennifer.Erickson@gov.bc.ca
Organization: Public Service Agency
Project Role: Change Manager

Full Name: Jared Warren
GitHub ID: @freshjwarren
GitHub Account 2FA Confirmed: yes
Email address: jwarren@freshworks.io
Organization: FreshWork Studio
Project Role: Agile Coach

**Comment by mitovskaol** [comment]
@Travis-A-Clark Can you please add these users to your projecty Team in bcgov-c (you can create one for the project if it doesn't exist yet)  after this request is processed.

**Comment by mitovskaol** [comment]
The users listed above have been sent the invites to join the bcgov-c org.
