### ISSUE TITLE
Users Unable to Access OpenShift 4 Console

### ISSUE THREAD

**Issue by freshjwarren** [BCDevOps/devops-requests#803]
When various users who should have OpenShift access go to [the console URL](https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/projects) they are briefly shown the console then redirected to [a GitHub login page](https://oidc.gov.bc.ca/auth/realms/kq56c126/protocol/openid-connect/auth?client_id=silver&redirect_uri=https%3A%2F%2Foauth-openshift.apps.silver.devops.gov.bc.ca%2Foauth2callback%2Fsso&response_type=code&scope=openid&state=Y3NyZj0yTUMwSVBQM0oyQTlKVmNuZmowR0pSaTVGQXVDd3hZbHlZZnlGc2g5RHVjJnRoZW49JTJGb2F1dGglMkZhdXRob3JpemUlM0ZjbGllbnRfaWQlM0Rjb25zb2xlJTI2cmVkaXJlY3RfdXJpJTNEaHR0cHMlMjUzQSUyNTJGJTI1MkZjb25zb2xlLmFwcHMuc2lsdmVyLmRldm9wcy5nb3YuYmMuY2ElMjUyRmF1dGglMjUyRmNhbGxiYWNrJTI2cmVzcG9uc2VfdHlwZSUzRGNvZGUlMjZzY29wZSUzRHVzZXIlMjUzQWZ1bGwlMjZzdGF0ZSUzRDg3NDEwNGZh). When they choose "Authenticate with GitHub", they are redirected to [the GitHub issue template for "Request for Removal of OCP 3.11 Project Set"](https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+mitovskaol%2C+ShellyXueHan&labels=openshift-project-set%2C+pending&template=openshift_project_request.md&title=). Returning to the console URL starts the sequence again.

Users experiencing this: @GHenuset, @Travis-A-Clark, @freshjwarren

These users have never been able to access the console, but received an email telling them that their OpenShift projects had been created.

**Comment by ShellyXueHan** [comment]
@freshjwarren we've got a wrong link setup in the redirect. It's just updated, now they should see a different DevOps request issue when redirected. And for your reference, it should be `openshift user access request` https://github.com/BCDevOps/devops-requests/issues/new?assignees=caggles%2C+ShellyXueHan%2C+patricksimonian&labels=openshift-access&template=openshift_user_access_request.md&title=
