### ISSUE TITLE
PO Request Access to OpenShift

### ISSUE THREAD

**Issue by Travis-A-Clark** [BCDevOps/devops-requests#804]
[x] grant user access

Full Name: Travis Clark
GitHub ID: @Travis-A-Clark
Business Email Address: Travis.Clark@gov.bc.ca
Organization: PSA
Project Role: Product Owner

**Comment by mitovskaol** [comment]
@Travis-A-Clark has been invited to BCDevOps org. Travis, once you accept the invite, you will be able to access the Openshift console
