### ISSUE TITLE
Two IDIR users can't log in, both with username collisions

### ISSUE THREAD

**Issue by stephenhillier** [BCDevOps/devops-requests#812]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
Yes

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?  Two users tried to log into our app and received an error that a user with their username already exists.
- What result of debugging have you obtained that lead you to request an account removal?  based on error message and help from the sso channel.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed:  sent separately
* Realm ID where user is having problem login: `gwells` and `iesymdnx`

**Comment by arcshiftsolutions** [comment]
We've removed the users from the IDIR realm. @stephenhillier is following up with the user to confirm.

**Comment by caggles** [comment]
okay, please let us know if there's anything further you require from us - if not, please close the ticket!

**Comment by stephenhillier** [comment]
I confirmed with both users that they are able to log in again.  Thank you!
