### ISSUE TITLE
Community Information Tool

### ISSUE THREAD

**Issue by danielhirner** [BCDevOps/devops-requests#814]
## Step 0
**Are you the product owner or project admin/team lead?**
YES

**Does the Admin User have an IDIR account?**
YES
Product Owner: Daniel Hirner (IDIR: dehirner)
Technical Lead: Paul Dittaro (IDIR: pdittaro)

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.
NO

## Step 0
We are currently planning on SSO service name migration, which will affect **all** existing teams on Keycloak. 
If you are new to our SSO service or Keycloak, we recommend you to wait for the migration to complete before starting the request. 
If you are experienced with Keycloak integration and ready to work with us during the migration, feel free to continue on.

## Step 1
Are you new to RedHat Single Sign-On (Keycloak)? 
If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

Our technical team is experienced with Keycloak integration. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will create the initial account on Keycloak.

- https://dev.oidc.gov.bc.ca/auth/admin/idir/console
- https://test.oidc.gov.bc.ca/auth/admin/idir/console
- https://oidc.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: Community Information Tool

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - Namespace ID:
 
  Not applicable, we are not looking to host our application on OpenShift at this time.

* For existing Keycloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ X] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by ShellyXueHan** [comment]
@danielhirner SSO service is currently undergoing OCP4 migration, thus we are not onboarding new teams. Migration will be completed by Feb 11th, we will revisit this when it's done! See details here: https://developer.gov.bc.ca/BC-Gov-SSO-Service-Migration

**Comment by danielhirner** [comment]
Thanks! Can we also include our lead dev @pdittaro in any updates related to this request.

**Comment by pdittaro** [comment]
@ShellyXueHan, are we able to prod this ticket?

**Comment by pdittaro** [comment]
We're also going to need IDIR integration for this request.

**Comment by ShellyXueHan** [comment]
@pdittaro @danielhirner sorry for the late update. We are currently having some restriction on SSO realm resources. Would you please connect with Vardhman ( SSO service production owner - Vardhman.Shankar@gov.bc.ca ) if you are in urgent need of SSO integration. Also feel free to cc me!

**Comment by nvunnamm** [comment]
@danielhirner, 
Would you mind setting up an onboarding meeting so that we can work on that?
Please include @patricksimonian or @ShellyXueHan  and me in the meeting.

**Comment by danielhirner** [comment]
Will book something immediately. Apologies for the delay. 

Dan

**Comment by nvunnamm** [comment]
@danielhirner I have provided access to ream-o-matic. Now you should be good to login with IDIR account. (link in step 5)

cc: @pdittaro

**Comment by danielhirner** [comment]
> @danielhirner I have provided access to ream-o-matic. Now you should be good to login with IDIR account. (link in step 5)
> 
> cc: @pdittaro

**Comment by danielhirner** [comment]
@nvunnamm  Can you also provide access to @pdittaro  He's our tech lead and I'm the PO.

**Comment by danielhirner** [comment]
@nvunnamm Apologies did not mean to close this issue.  👆

**Comment by nvunnamm** [comment]
@danielhirner For requesting a realm through realm-o-matic we usually give access to the product owner so that they can fill in the form and get a new realm provisioned. After realm is provisioned you will be the administrator of the realm and you can add the users as needed.

**Comment by pdittaro** [comment]
@nvunnamm and @ShellyXueHan , Dan's IDIR is out of commission due to ministry reshuffling, is there anyway we can get setup with mine as Tech lead?

**Comment by nvunnamm** [comment]
@pdittaro Have added you to realm-o-matic.. Please let me know if you have any issues.

**Comment by nvunnamm** [comment]
Closing this according to the comment in email that realm was setup successfully.
