### ISSUE TITLE
Prod Keycloak realm 35r1iman does not contain bceid as an identity provider

### ISSUE THREAD

**Issue by rstens** [BCDevOps/devops-requests#821]
https://oidc.gov.bc.ca/auth/admin/35r1iman/console/#/realms/35r1iman/identity-provider-settings
Both dev and test do and we need bceid added to prod as well.
This is for the BioHubBC project.

Thanks,

Roland Stens

**Comment by ShellyXueHan** [comment]
@rstens BCeID production integration is still under review from IDIM team. You can see the status here: https://realm-o-matic.developer.gov.bc.ca/home or contact IDIM directly at IDIM Consulting CITZ:EX <IDIM.Consulting@gov.bc.ca>
