### ISSUE TITLE
Request for BCGOV github org

### ISSUE THREAD

**Issue by marklise** [BCDevOps/devops-requests#828]
## Step 0
No

**Are you the Technical Lead?**
Yes
contact @mitovskaol (Olena Mitovska) with a link to the ticket so she can approve it.

**Do you actually need the team member to be a member of the organization?**
Yes

## Step 1
Done

## Step 2
Done

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: NRPTI
* GitHub Org: bcgov
* Full Name: Cameron Pettit
* GitHub ID: @cameronpettit
* GitHub Account 2FA Confirmed: yes
* Email address: cameron@digitalspace.ca
* Organization: Digitalspace
* Project Role: Fullstack Developer
* GitHub Team to Join (if exists): BCMI
* Existing GitHub Repo: https://github.com/bcgov/NRPTI.git

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
the invite to bcgov org has been sent to @cameronpettit
