### ISSUE TITLE
Issue: Request for adding OpenShift access

### ISSUE THREAD

**Issue by marklise** [BCDevOps/devops-requests#829]
## Step 0
Yes

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Cameron Pettit
* GitHub ID: cameronpettit
* Business Email Address: cameron@digitalspace.ca
* Organization: Digitalspace
* Project Role: Fullstack developer

**Comment by marklise** [comment]
Can we re-open this?  Link was expired.

**Comment by patricksimonian** [comment]
@marklise reopened!

**Comment by patricksimonian** [comment]
Cameron has been re-invited!
