### ISSUE TITLE
Artifactory Request for DPS Webmethods Replacements

### ISSUE THREAD

**Issue by akroon3r** [BCDevOps/devops-requests#83]
## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Using-Artifactory

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 3
Ensure that you have already logged into Artifactory at least once via Keycloak to create your personal account name:
https://artifacts.developer.gov.bc.ca

## Step 4
Fill out the following fields

* Requester: akroon3r@github
* Team Name: DPSWMR
* Repo Type: caching mvn artifacts
* Repo Location: local
* Repo Description: to hold project level and vendor specific artifacts
* Primary OpenShift Project: tools namespace created under issue #81 (https://github.com/BCDevOps/devops-requests/issues/81)
* (if virtual) List of Related Repos: None

**Comment by akroon3r** [comment]
Super green doing these requests. Please let me know if anything needs to be changed or if you need clarification! Thanks for your help!

**Comment by caggles** [comment]
Hey @akroon3r! A caching repo is different from a local repo - a caching repo is designed to cache commonly used packages from public repos on our local cluster to speed up build times. A local repo is a private place where your team can upload their own packages. Which one is it that you are asking for?

**Comment by akroon3r** [comment]
Definitely Caching. Sorry for the mixup!

**Comment by caggles** [comment]
closed because this ticket is for a team that hasn't been onboarded to artifactory yet!
