### ISSUE TITLE
BCDC Test Namespace - Request for additional resources

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [BCDevOps/devops-requests#831]
## Step 0
**Are you making this request for OCP4?**

No, this is for OCP3.

**Are you the product owner or technical lead?**
Yes, I am the product owner of the team that oversees the BC Data Catalogue (BCDC).

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Reviewed - no duplicate requests exist.

## Step 2
What quotas need to be changed? (Select all that apply)
- [ X] CPU: Long Running (compute-long-running-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ X] CPU Request => Increase to 12 cores from 8 cores
   - [ X] Memory Request => Increase to 48 GiB from 32 GiB
- [ ] CPU: Time Bound (compute-time-bound-quota)
   - [ ] CPU Limit
   - [ ] Memory Limit
   - [ ] CPU Request
   - [ ] Memory Request
- [ ] Storage: Netapp Block (storage-netapp-block-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Netapp File (storage-netapp-file-standard-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: NFS Backup (storage-nfs-backup-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster Block (storage-gluster-block-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] Storage: Gluster File (storage-gluster-file-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage
- [ ] General Storage Quota (storage-quota)
   - [ ] Number of PVCs
   - [ ] Total Storage

## Step 3
Please provide the namespace(s) to which these quota changes need to be applied:

The namespace is dbc-bcdc-test.

**Note: ensure you are providing the namespace name, not the project display name. It should be a string of 6 random alphanumeric characters, followed by -tools, -dev, -test or -prod.**

## Step 4
Add details about your quota request here.

* CPU Request - Please increase the cores to 12 (from 8); and
* Memory Request - Please increase memory to 48 GiB (from 32 GiB)

## Step 5
Please explain here the reasons for requesting your quota change.

In our BCDC Test namespace, we are running a containerized postgresql database.  This database is used for our test instance of the new version of the BC Data Catalogue.  We using this database to conduct extensive testing of the BC Data Catalogue during February and March 2021.

This database is pushing our existing resource allocation to the breaking point.  Currently, We are capped at 8 cores and 32Gi of memory.  We are currently running at 7.9 cores and 29Gi.  

Yesterday afternoon (February 8th), we ran out of resources and the DB went out of service.  It took our development team a total of 6 developer hours this morning to resolve the problem.  Additional delays would put our release schedule at risk.

If we are able to reallocate resources from other namespaces, we are happy to do so.  For instance, I am told that we could reallocate 4 cores and 16 GiB from our "dbc-bcdc-dev" namespace if required.

Additional information regarding our migration to OCP 4:
* We're planning to run our Beta testing in OCP 3 until on/about March 15th.
* We've migrated two applications to OCP 4 already.  We expect to migrate the remaining applications in the bcdc namespaces by March 22nd. 

Thanks for your help with this issue - we really appreciate your assistance!

**Comment by SteveChapmanBCDX** [comment]
@caggles, @patricksimonian, @ShellyXueHan  - Thanks for your help with this one.  

I'm not sure what the namespace name is here.  The project display name is `dbc-bcdc-test`.  I'll get the namespace name from our DevOps team and update as soon as possible.

**Comment by mitovskaol** [comment]
@caggles The increase request is for 1 namespace only, not for the entire project set. I talked to the team and am approving the request.

**Comment by StevenBarre** [comment]
@SteveChapmanBCDX the new quota has now been applied to your namespace

```console
$ oc -n dbc-bcdc-test describe quota compute-long-running-quota
Name:       compute-long-running-quota
Namespace:  dbc-bcdc-test
Scopes:     NotBestEffort, NotTerminating
 * Matches all pods that have at least one resource requirement set. These pods have a burstable or guaranteed quality of service.
 * Matches all pods that do not have an active deadline. These pods usually include long running pods whose container command is not expected to terminate.
Resource         Used     Hard
--------         ----     ----
limits.cpu       8800m    16
limits.memory    33280Mi  64Gi
pods             9        100
requests.cpu     6900m    12
requests.memory  25544Mi  48Gi
```

**Comment by SteveChapmanBCDX** [comment]
@StevenBarre - Fantastic - thanks for your help!
