### ISSUE TITLE
openshift access required for Andre Pestana

### ISSUE THREAD

**Issue by lmcclung** [BCDevOps/devops-requests#833]
## Step 0
**Are you the product owner or technical lead?**
Yes - PO for BCROS Entities Team

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
Andre's business github account is andrepestana-aot

**Do you have 2-factor-authentication enabled with your GitHub account?**
yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Andre Pestana
* GitHub ID:  andrepestana-aot
* Business Email Address: andre.pestana@aot-technologies.com
* Organization: CITZ -  BCROS - BC Registries and Online Services
* Project Role:  Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
Andre has been invited to bcgov and BCDevOps orgs.
