### ISSUE TITLE
Request for KeyCloak Realm - BC Identity Kit

### ISSUE THREAD

**Issue by esune** [BCDevOps/devops-requests#84]
- [x] Step 0

Are you the product owner or project admin/team lead?
Product Owner: idir/johjorda
Technical Lead: idir/esune

Do you have an IDIR account?
idir/esune

- [x] Step 1

Only DEV realm required for this application - users have already signed in to sso-dev

Step 2

Field the following information.

    Project Name: BC Identity Kit
    Keycloam Realm: New Account

**Comment by caggles** [comment]
I gave requester privileges to @esune - in the future, please be explicit about which account should be granted realm-o-matic access. Thank you :)
