### ISSUE TITLE
User access to private repository

### ISSUE THREAD

**Issue by rantifamilusi** [BCDevOps/devops-requests#840]
## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: FAMS3 Implementation
* GitHub Org: bcgov-c
* Full Name: Eduardo Silveira
* GitHub ID: @edsilveira
* GitHub Account 2FA Confirmed: yes
* Email address: Eduardo.Silveira@nttdata.com
* Organization: NTT Data
* Project Role: Software Developer
* GitHub Team to Join (if exists): @bcgov-c/ag-pssg-nttdata
* Existing GitHub Repo:  https://github.com/bcgov-c/fams3-openshift

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
The invite has been sent.
