### ISSUE TITLE
User access to existing OpenShift Namespace : FAMS3

### ISSUE THREAD

**Issue by rantifamilusi** [BCDevOps/devops-requests#841]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Eduardo Silveira
* GitHub ID: @edsilveira
* Business Email Address: Eduardo.Silveira@nttdata.com
* Organization: NTT Data
* Project Role: Developer
* OpenShift Projects/Namespaces: frjeow-tools, frjeow-dev, frjeow-test, frjeow-prod

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@rantifamilusi I've invited Eduardo to join BCDevOps GitHub organization. By accepting the membership, he will be able to login to openshift. The Project tech lead (namespace admin) would then grant access for the user to specific namespace.
