### ISSUE TITLE
GitHub Access Request for @SashaNasonova

### ISSUE THREAD

**Issue by gcperk** [BCDevOps/devops-requests#854]
**Are you the Technical Lead?**
Yes

**Do you actually need the team member to be a member of the organization?**
Yes

## Step 1
Visit DevHub for detailed instruction on creating a request:
https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-GitHub-user-access-or-repository-creation

## Step 2
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: FLNRORD Data Science 
* GitHub Org: bcgov
* Full Name: Sasha Nasonova
* GitHub ID: @SashaNasonova
* GitHub Account 2FA Confirmed: yes
* Email address: sasha.nasonova@gov.bc.ca
* Organization: FLNRORD
* Project Role: Remote Sensing Specialist
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: https://github.com/bcgov/bc_dtm_testing

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
The invite to the bgov org has been sent to @SashaNasonova.
