### ISSUE TITLE
Request for bcgov-c organization access

### ISSUE THREAD

**Issue by irfancharania** [BCDevOps/devops-requests#855]
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

* Project Name: Business Recovery Grant
* GitHub Org: private
* Full Name: Johnathan Storey
* GitHub ID: @jgstorey
* GitHub Account 2FA Confirmed: yes
* Email address: johnathan.storey@cgi.com
* Organization: CGI
* Project Role: Consultant
* GitHub Team to Join (if exists): business-recovery-grant
* Existing GitHub Repo: https://github.com/bcgov-c/stronger-bc

**Comment by mitovskaol** [comment]
the invite has been sent to @jgstorey

**Comment by irfancharania** [comment]
@mitovskaol: Can you also add @jgstorey to the https://github.com/orgs/bcgov-c/teams/business-recovery-grant/members team?
I don't have privileges to do so.
Thanks!

**Comment by mitovskaol** [comment]
Done :)
