### ISSUE TITLE
Request Admin rights on a GitHub repo

### ISSUE THREAD

**Issue by ateucher** [BCDevOps/devops-requests#857]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Add an existing bcgov GitHub member as admin on a repository
2. **Why should this be a new request type?** Sometimes a contractor will do their work in their own github account, and at some point you need to transfer the repository to the bcgov org. When this happens, there is no admin assigned to the newly transferred repo ([other than the bcgov org owners](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#repository-transfers-and-organizations)). An example: https://github.com/bcgov/rems2aquachem was recently transferred to the bcgov org, and no one on the team has admin rights on the repo.
3. **What information is required to fulfill this request?** The repository, and the github username of the bcgov GitHub org member(s) who should be admin on the repo
4. **What is the end result?** The repository has an administrator who is part of the bcgov org and the team responsible for the repo.

**Comment by patricksimonian** [comment]
@ateucher what repos and what users are you requesting admin access for?

**Comment by patricksimonian** [comment]
@caggles what do you think?

**Comment by ateucher** [comment]
Hi @patricksimonian. Can you please add @jongoetz as admin of https://github.com/bcgov/rems2aquachem?

Thanks!

**Comment by caggles** [comment]
@patricksimonian  I think it's probably a good idea to add this as a request type, since there are legit situations in which teams can lose access to a repo. However, we should be careful to be strict about how and when a team can make such a request - I don't want to encourage teams to ask us to change their admin access on repos when there are other members of their team who could do that for them instead.

**Comment by caggles** [comment]
Hey @ateucher - did that repo originally come from @jongoetz's account, then? If he was the one who transferred it to bcgov from his personal account, he should still have access. I see that he doesn't, and I'm just trying to determine why.

**Comment by ateucher** [comment]
Thanks @caggles. That repo originally came from a contractor's account. She isn't a bcgov member so she transferred it to my personal account, and I then transferred it to bcgov - at which point I also lost admin rights (which surprised me). @jongoetz should be admin because he is the github lead for the ENV water data science team. I was just helping out because I knew the repo transfer process the best. Sorry, I know that's a bit convoluted!

I wonder if a better approach in the future would be to clone the repo locally, create a new empty repo in bcgov, change the remote url (`git remote set-url origin https://github.com/bcgov/newrepo.git`) and push it there.

Ideally of course bcgov members should be creating the repo and adding contractors as collaborators, so it's in the bcgov org in the first place...

**Comment by caggles** [comment]
Okay @ateucher I gave you admin access again - you can add @jongoetz (and anyone else you like) now :)

I will leave this ticket open until we add the new ticket type to github, however!

**Comment by ateucher** [comment]
Brilliant, thanks so much @caggles!
