### ISSUE TITLE
New Request Type: Request Keycloak Audit Logs

### ISSUE THREAD

**Issue by seeker25** [BCDevOps/devops-requests#858]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** Please provide an overview of what the request should do.

Audit logs request for Keycloak

2. **Why should this be a new request type?** 

It's not in the list

3. **What information is required to fulfill this request?**

Date/time range, realm, environment

4. **What is the end result?** 

Password protected logs sent back to the requestor

**Comment by seeker25** [comment]
Can someone help me pull Keycloak Audit logs on 2/19/2021 between 8:22 AM and 8:40 AM PST - for Realm: tz0e228w, Environment: Prod?

A user with BCEID is trying to log in but they keep getting stuck ("We are sorry an internal server error has occured"). It's happened on multiple days.

**Comment by ShellyXueHan** [comment]
@seeker25 Hi Travis, if you need the SSO logs for now, please ask in RocketChat sso channel for quick help. We'll get back to you on this request later on!

@ConradBoydElliottGustafson @nvunnamm ^^^ 
in addition, do you have a preferred place to manage SSO request like this? let's have some discussion!

**Comment by seeker25** [comment]
Thanks alot Shelly. Wasn't sure if it was better to make a ticket or ask in RocketChat.

**Comment by ConradBoydElliottGustafson** [comment]
@ShellyXueHan We're following the current process but the UX team is working on incident management processes. Right now it's RocketChat OR Github correct?

**Comment by ShellyXueHan** [comment]
@ConradBoydElliottGustafson yes! Niran is helping Travis now on RC. We can look into this process when going over the general sso new team onboarding.

**Comment by nvunnamm** [comment]
Logs have been sent.

**Comment by caggles** [comment]
I'm going to close this ticket - it looks like the team has decided that this task is better served on rocketchat and not as a devops-requests ticket type.
