### ISSUE TITLE
Access to Openshift for Steph Rabbani (jordiwes)

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#866]
## Step 0
**Are you the product owner or technical lead?** Yes

**Do you have a GitHub account?** jordiwes
**Do you have 2-factor-authentication enabled with your GitHub account?** Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name:  Steph Rabbani
* GitHub ID: jordiwes
* Business Email Address: steph@daxiom.com
* Organization: bcregistry
* Project Role: developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
@thorwolpert @jordiwes has been invited to BCDevops. When he accepts the invite you can grant him the rolebindings he'll need for Openshift

**Comment by thorwolpert** [comment]
All good now, Thanks.
