### ISSUE TITLE
Request to add scott-curtis to OpenShift

### ISSUE THREAD

**Issue by cboreen** [BCDevOps/devops-requests#867]
## Step 0
**Are you the product owner or technical lead?**
We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name:  Scott Curtis
* GitHub ID: scott-curtis
* Business Email Address: scurtis@vividsolutions.com
* Organization: Vivid Solutions
* Project Role: DevOps Specialist

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
@mitovskaol is this request approved?

**Comment by mitovskaol** [comment]
@cboreen  Please respond to the question in Step 0 of the template.

**Comment by cboreen** [comment]
@mitovskaol I will first say Step 0 has always confused me...  There 3 questions in Step 0, none of which it looks like you are expecting an answer to in the form.

- Yes I am the Tech Lead for the BC Wildfire Project on OCP3.  I have invited other team members before.  Our project on OCP3 is "fytirg".  Scott will be helping us with our OCP4 migration.  
- Yes I have a github account(cboreen) and so does Scott (scott-curtis)
- Yes, they are both setup with 2 factor

**Comment by patricksimonian** [comment]
Scott has been invited into the BCDevops Github Org. Just make sure he checks his email for the invite. Once he is apart of the org you and whoever else has admin priv's may grant him access to your Openshift Namespaces! 
Thanks!

**Comment by scott-curtis** [comment]
@patricksimonian I did not receive an email invite. When I try to access OCP3 I get "An authentication error occurred."
When I try to access OCP4 I get redirected to: https://github.com/BCDevOps/devops-requests 

I confirmed with Chris Boreen that I'm setup as an admin in OCP3.
