### ISSUE TITLE
Request for OpenShift Access - Lorne Lovett

### ISSUE THREAD

**Issue by GovtRyan** [BCDevOps/devops-requests#868]
## **Step 0**
**Are you the product owner or technical lead?**
Yes, I am the product owner and project admin. Requesting for an existing team member

## Step 1
Are you requesting to:
- [x] grant user access

## Step 2
Fill out the following fields

* Full Name: Lorne Lovett
* GitHub ID: LL-scj-gov
* Business Email Address: lorne.lovett@bccourts.ca
* Organization: Superior Courts Judiciary
* Project Role: Project Admin

**Comment by patricksimonian** [comment]
@mitovskaol is this approved?

**Comment by patricksimonian** [comment]
@LL-scj-gov @GovtRyan . Invite has been sent out! Make sure Lorne watches for the invite email. Once Lorne's apart BCDevops org you may grant the rolebinding to get them into your desired OCP namespaces.
