### ISSUE TITLE
Request for Keycloak Realm for PSP Project

### ISSUE THREAD

**Issue by DarylTodosichuk** [BCDevOps/devops-requests#869]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. 
We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 0
We are currently undergoing management of SSO realm resources, as a result we will not onboard new teams for sometime.
Should you have urgent need for SSO/keycloak integration for your application, please connect with SSO Product Owner Vardhman at Vardhman.Shankar@gov.bc.ca

## Step 1
Are you new to RedHat Single Sign-On (Keycloak)? 
If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will create the initial account on Keycloak.

- https://dev.oidc.gov.bc.ca/auth/admin/idir/console
- https://test.oidc.gov.bc.ca/auth/admin/idir/console
- https://oidc.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: PSP

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - 3cd915-dev
  - 3cd915-test
  - 3cd915-prod
  - 3cd915-tools
  - Namespace ID:

* For existing Keycloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation: daryl.todosichuk@gov.bc.ca
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: IDIR\DTODOSIC
* Admin user's Business Email Address: daryl.todosichuk@gov.bc.ca

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by nvunnamm** [comment]
@DarylTodosichuk ,
Would you mind setting up an onboarding meeting so that we can work on that?
Please include @patricksimonian or @ShellyXueHan and me in the meeting.

**Comment by DarylTodosichuk** [comment]
Meeting as requested please let me know if this time doesn't work I can't see everyone's availability in the calendar.

Daryl Todosichuk

Senior Technical Systems Analyst | Information Management Branch | Ministry of Transportation and Infrastructure
Phone: 236-478-1157 | Mobile: 250-812-8392 | Email: Daryl.Todosichuk@gov.bc.ca<mailto:Daryl.Todosichuk@gov.bc.ca>

________________________________________________________________________________
Microsoft Teams meeting
Join on your computer or mobile app
Click here to join the meeting<https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzhjOGFhNGMtNDdjYi00M2NmLThmMDEtYzA2MTJiMjc5ZWFi%40thread.v2/0?context=%7b%22Tid%22%3a%226fdb5200-3d0d-4a8a-b036-d3685e359adc%22%2c%22Oid%22%3a%22730754e7-686e-4bfa-b646-16afda18661b%22%7d>
Learn More<https://aka.ms/JoinTeamsMeeting> | Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=730754e7-686e-4bfa-b646-16afda18661b&tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&threadId=19_meeting_MzhjOGFhNGMtNDdjYi00M2NmLThmMDEtYzA2MTJiMjc5ZWFi@thread.v2&messageId=0&language=en-US>
________________________________________________________________________________


_____________________________________________

**Comment by nvunnamm** [comment]
@DarylTodosichuk , We have provided access to ream-o-matic. Now should be good to login with IDIR account.

**Comment by DarylTodosichuk** [comment]
@ShellyXueHan @nvunnamm  Thank you :) consoles are working!
