### ISSUE TITLE
Add kkapoor-fresh to OpenShift

### ISSUE THREAD

**Issue by freshjwarren** [BCDevOps/devops-requests#870]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Kunal Kapoor
* GitHub ID: kkapoor-fresh
* Business Email Address: kunal@freshworks.io
* Organization: FreshWorks Studio
* Project Role: DevOps Engineer

**Comment by patricksimonian** [comment]
@freshjwarren @khapoor-fresh is already apart of BCDevops. Admin users of your namespaces can grant him access to Openshift.
