### ISSUE TITLE
Requesting OpenShift access to our projects

### ISSUE THREAD

**Issue by SteveMHoward** [BCDevOps/devops-requests#872]
Requesting access for our three developers to our two projects.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Alexander Wintschel
* GitHub ID: Baelx
* Business Email Address: Alexander.Wintschel@gov.bc.ca
* Organization: CITZ - GDX
* Project Role: Full Stack Developer
* OpenShift projects: e8b9ad-tools, e8b9ad-dev, e8b9ad-test, e8b9ad-prod, 23576a-tools, 23576a-dev, 23576a-test, 23576a-prod

* Full Name: Jeff Stewart
* GitHub ID: jeffds
* Business Email Address: Jeff.Stewart@gov.bc.ca
* Organization: CITZ - GDX
* Project Role: Full Stack Developer
* OpenShift projects: e8b9ad-tools, e8b9ad-dev, e8b9ad-test, e8b9ad-prod, 23576a-tools, 23576a-dev, 23576a-test, 23576a-prod

* Full Name: Shawn Turple
* GitHub ID: ShawnTurple
* Business Email Address: Shawn.Turple@gov.bc.ca
* Organization: CITZ - GDX
* Project Role: Full Stack Developer
* OpenShift projects: e8b9ad-tools, e8b9ad-dev, e8b9ad-test, e8b9ad-prod, 23576a-tools, 23576a-dev, 23576a-test, 23576a-prod

**Comment by patricksimonian** [comment]
@SteveMHoward if a team member has admin access to those Openshift Namespace, they can add users themselves. Keep in mind that on 3.11 cluster its just the github id whereas in 4.5 cluster it is `<githubid>@github`.

If you are unable to add them this would mean they are not apart of the `bcdevops` github org

**Comment by SteveMHoward** [comment]
@patricksimonian I have added them manually as admins in our projects, and they show up in the role bindings list as expected briefly, before disappearing again - like an automatic check/cron is in place that removes them after they have been added.

Would this be the expected behavior if they need to be added to the bcdevops org?

**Comment by patricksimonian** [comment]
Hmm no quite. To be clear you can add any user to Openshift. But if they are not apart of the bcdevops org. They will be getting 403 forbidden. The automatic removal thing sounds like the registry is syncing to ensure only tech lead and project lead have admin. Your developers shouldn't need admin access. It only allows them to add other users.

**Comment by patricksimonian** [comment]
Also additionally. I do see @jeffds-zz in BC Devops Org. Not @jeffds. 

Shawn and Alex are both in BcDevops Org.

**Comment by patricksimonian** [comment]
> Hmm no quite. To be clear you can add any user to Openshift. But if they are not apart of the bcdevops org. They will be getting 403 forbidden. The automatic removal thing sounds like the registry is syncing to ensure only tech lead and project lead have admin. Your developers shouldn't need admin access. It only allows them to add other users.

Im just double checking. You should be able to add users since you are an admin.

**Comment by SteveMHoward** [comment]
Thanks @patricksimonian , I should be able to add users but I have only tried with "admin" access since that is what they were granted in OCP 3.  What role binding should they have knowing that they will need to do pretty much everything (builds, deployments, storage, etc.)?

Also I checked with Jeff and he says @jeffds is his account, I can put in a separate request to get him added to bcevops org

**Comment by patricksimonian** [comment]
we have an issue to improve this experience here. https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/876

In the mean time what you could do is when you run your `oc policy` commands. Output them into yaml and modify the `metadata.name`. This is for adding 'admin' users. 

To answer your question `edit` access is all they'll need. I'd strongly suggest limiting admin access to your namespaces. Admin access allows total control of that namespace.

**Comment by patricksimonian** [comment]
I'd take a look at https://docs.openshift.com/container-platform/4.5/authentication/using-rbac.html#adding-roles_using-rbac 
for more info on rbac.

Are you the technical lead on the project(s)?

**Comment by SteveMHoward** [comment]
Perfect, thanks @patricksimonian! I can confirm "edit" works for adding users. Admin access hasn't been as big of a concern in the past because we are all permanent BC Gov employees who also all have admin access on traditional servers, but I hear you.

Yes, I am the tech lead and product owner for both of these projects.

Closing as my issue has been resolved :) Thanks again!
