### ISSUE TITLE
Add kkapoor-fresh to BCGov Org

### ISSUE THREAD

**Issue by freshjwarren** [BCDevOps/devops-requests#873]
## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Project Name: PECSF
Full Name: Kunal Kapoor
GitHub ID: @kkapoor-fresh
GitHub Account 2FA Confirmed: yes
Business Email Address: kunal@freshworks.io
Organization: FreshWorks Studio
Project Role: DevOps Engineer

**Comment by patricksimonian** [comment]
@freshjwarren @kkapoor-fresh has been invited. Please have him check his email! :)
