### ISSUE TITLE
Remove users form bcgov-c

### ISSUE THREAD

**Issue by Travis-A-Clark** [BCDevOps/devops-requests#874]
Please remove the following individuals from the bcgov-c organization. Our Performance repository is now public so they can access resources without need for bcgov-c membership. Thanks!

- [ ] Invite a user
- [x] Remove a user

Project Name: Performance
GitHub Org: bcgov-c

Full Name: Alison Buchanan
GitHub ID: @Abuchana
GitHub Account 2FA Confirmed: yes
Email address: alison.Buchanan@gov.bc.ca
Organization: Public Service Agency
Project Role: Scrum Master

Full Name: Kevin Best
GitHub ID: @kevindavidb
GitHub Account 2FA Confirmed: yes
Email address: kevin.Best@telus.com
Organization: Telus Employer Solutions
Project Role: Developer

Full Name: Jennifer Erickson
GitHub ID: @jenerick100
GitHub Account 2FA Confirmed: yes
Email address: Jennifer.Erickson@gov.bc.ca
Organization: Public Service Agency
Project Role: Change Manager

Full Name: Jared Warren
GitHub ID: @freshjwarren
GitHub Account 2FA Confirmed: yes
Email address: jwarren@freshworks.io
Organization: FreshWork Studio
Project Role: Agile Coach

**Comment by patricksimonian** [comment]
@Travis-A-Clark I was able to remove @Abuchana and @jenerick100. It doesn't appear that @freshjwarren or @kevindavidb are in that org. Are those user names spelled correctly?

**Comment by Travis-A-Clark** [comment]
@patricksimonian Thanks! There was a request put in to add them all (issue #800 ) but perhaps not everyone made it in. As long as we aren't costing the org any money in license fees, then all is well. Thanks!

**Comment by patricksimonian** [comment]
okay ill double check if thye have pending invites and remove those.

**Comment by patricksimonian** [comment]
thanks!
