### ISSUE TITLE
Request access to BCDevOps org for developer

### ISSUE THREAD

**Issue by SteveMHoward** [BCDevOps/devops-requests#879]
## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: Land Use Planning, GDX WordPress
* GitHub Org: BCDevOps
* Full Name: Jeff Stewart
* GitHub ID: @jeffds
* GitHub Account 2FA Confirmed: yes
* Email address: Jeff.Stewart@gov.bc.ca
* Organization: CITZ - GDX
* Project Role: Full stack developer

**Note** that the platform services team will be removing GitHub Org access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
@SteveMHoward since I do see a jeffdz-zz account in BCDevops. I'm considering removing it since its most likely the same Jeff Stewart :O . 

Regardless we'll need Olena's approval before going further. The issue template should have left instructions to get the approval.

**Comment by SteveMHoward** [comment]
@patricksimonian Apologies, I just came to check the status of this and saw some potentially outstanding questions for me.

Yes, the same Jeff Stewart so his old account (jeffds-zz) can be removed.

I read the template but it says approval is needed if you are the Team Lead requesting access for yourself. Since I am requesting access on behalf of Jeff i didn't think additional approval was needed, but it looks like @mitovskaol granted the approval so hopefully we are good to go.
