### ISSUE TITLE
Remove duplicate user for: RMCLANE - Regina McLane

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#881]
## Step 0
**Are you the Keycloak Realm Admin?** Yes
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account? User was auxillary prior and now came in as another ministry user.
- What result of debugging have you obtained that lead you to request an account removal?  Error from user stating duplicate user.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [X ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: RMCLANE 
* Realm ID where user is having problem login:  vtkayq4c - Production

**Comment by nvunnamm** [comment]
@gil0109, User has been removed please verify.

**Comment by gil0109** [comment]
Confirmed, thank you :)
