### ISSUE TITLE
request for adding OpenShift access

### ISSUE THREAD

**Issue by NicoledeGreef** [BCDevOps/devops-requests#884]
## Step 0
**Are you the product owner or technical lead?** Yes- I'm a Product Owner 

**Do you have a GitHub account?**
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Nicole de Greef
* GitHub ID:  NicoledeGreef
* Business Email Address:  Nicole.deGreef@gov.bc.ca
* Organization: Data Systems and Services Branch
* Project Role: Product Owner

**Comment by lmcclung** [comment]
Full Name: Chandra Kesana
GitHub ID: chandrasekhar786
Business Email Address: Chandrasekhar.kesana@gmail.com
Organization: BC Registries & Online services
Project Role: Developer

**Comment by patricksimonian** [comment]
@lmcclung this seems to be a seperate request. Do you mind making a new devops request for your github membership?
