### ISSUE TITLE
Remove PIMS OCP 3.11 Project Set

### ISSUE THREAD

**Issue by Fosol** [BCDevOps/devops-requests#892]
- [x] Remove a project set 
- projects; jcxjin-tools, jcxjin-dev, jcxjin-test, jcxjin-prod

**Comment by mitovskaol** [comment]
Hi @Fosol Can you please answer all the questions included in the issue template, we need this information for our records:

**Comment by Fosol** [comment]
Technical Lead - yes
Migrated OCP3.11 to OCP4 - yes
Scaled down all pods - yes
Deleted persistent volume claims - yes

**Comment by patricksimonian** [comment]
deleted!
