### ISSUE TITLE
OpenShift access for: Doug Lovett

### ISSUE THREAD

**Issue by thorwolpert** [BCDevOps/devops-requests#894]
## Step 0
**Are you the product owner or technical lead?** Yes

**Do you have a GitHub account?** doug-lovett

**Do you have 2-factor-authentication enabled with your GitHub account?** Done

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Doug Lovett
* GitHub ID: doug-lovett
* Business Email Address: doug@daxiom.com
* Organization: BCROS
* Project Role: PPR Developer, SRE Team

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
@mitovskaol is this approved?

**Comment by patricksimonian** [comment]
invitation sent!
