### ISSUE TITLE
Grant Access to Conor Brady

### ISSUE THREAD

**Issue by conbrad** [BCDevOps/devops-requests#895]
## Step 0
**Are you the product owner or technical lead?**
No -- but Sybrand Strauss has granted me access but I keep getting redirects to this PR page.

We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
Yes
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
Yes
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Conor Brady
* GitHub ID: conbrad
* Business Email Address: conor.brady@gov.bc.ca
* Organization: Predictive Services 
* Project Role: Full Stack Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by conbrad** [comment]
Oops, I was told this was granted already but it's still in process I think.

**Comment by mitovskaol** [comment]
@conbrad You should have now received 2 invites  - for bcgov and BCDevOps orgs in GitHub. Accept them both and you will be able to create repos in bcgov org and access the Openshift console. Please note you will still need to be granted access to individual namespaces in Openshfit by your team.

**Comment by conbrad** [comment]
Thanks Olena, I can access it now.
