### ISSUE TITLE
Project Set - Document GeneRation ShowCase (DGRSC)

### ISSUE THREAD

**Issue by matthewhall78** [BCDevOps/devops-requests#9]
## Step 0
**Are you the product owner?**
Yes

**Have you had an alignment meeting?**
Yes, but it was in the summer and at the time we only planned on building one part of the service. At that time we received one project set for the underlying Document Generation API.  we are now proceeding to make this API a common service and would like to build the showcase app for it in a separate project set, following the pattern we have used with CHES and MSSC (email messaging API and showcase app).

## Step 3
Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

## Step 4
Fill out the following fields

* Short Team/Organization Name: IITD
* Product Short Name:  DGRSC
* Product Full Name: Document Generation ShowCase
* Product Description: A showcase of the capabilities of the Common Document Generation Service
* Desired Environments: tools, dev, test, prod
* Product Technical Steward
  - GitHub ID: @cvarjao
  - Business Email Address: clecio.varjao@gov.bc.ca
  - RocketChat Account Username: cvarjao
* Product Owner
  - Business Email Address: matthew.hall@gov.bc.ca
  - RocketChat Account Username: matthewhall78 
* GitHub Repository: https://github.com/bcgov/document-generation-showcase

**Comment by caggles** [comment]
@matthewhall78 @cvarjao your new project name is wfezkf

**Comment by matthewhall78** [comment]
@caggles I don't see the project in my console.  did you not give me privileges?
