### ISSUE TITLE
Documize for BC Services Card

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#90]
Name requested: BC Services Card Self Service
Administrators: Zorin Samji (IDIR: Zsamji) and Bobbi Bjornholt (IDIR: bbjornh)

Please and thank you :)

**Comment by caggles** [comment]
hi @zsamji - please provide the following information:

* Ministry: 
* Short Team/Organization Name: 
* Team and Product Description: 
* Space Visibility: Public / Protected (only invited users could see)

**Comment by zsamji** [comment]
@caggles 
> * Ministry:Citizen Services 
> * Short Team/Organization Name: Service BC, IDIM Identity Information Management Program
> * Team and Product Description: Self Service for BPS
> * Space Visibility:  Protected (only invited users could see):
Question: For some of our work, we want to be protected wanted to know, is there a way to make certain pages, public so everyone can see?

**Comment by caggles** [comment]
> Question: For some of our work, we want to be protected wanted to know, is there a way to make certain pages, public so everyone can see?

I don't believe so - I think the public/private flag is by space rather than by page. I will make the space private, and then we can investigate the possibility of flagging specific pages as public. I suspect the likely solution will be to request two different spaces.

**Comment by caggles** [comment]
@zsamji I've just gone poking around a little more and can confirm that there isn't a way to make individual pages public in a private space. If you want to make a public space later, please request one!
