### ISSUE TITLE
Request for Removal of OCP 3.11 Project Set - bztwou

### ISSUE THREAD

**Issue by WadeBarnes** [BCDevOps/devops-requests#901]
## Step 0
**Are you the Product Owner or Technical Lead?**
Yes, I am the Technical Lead

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
Yes, all workloads have be migrated to OCP4 and confirmed working.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Yes, all resources have been deleted.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
Yes, all resources have been deleted.

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
- Done

## Step 2
Confirm that you are aware that you are requesting to:
- [x] Remove a project set

**Comment by patricksimonian** [comment]
namespaces deleted!
