### ISSUE TITLE
Remove ocio-isb-secnews project set

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/devops-requests#904]
## Step 0
**Are you the Product Owner or Technical Lead?** Submitting on behalf or Ryan Bluemel, the PO of the app.
If not, you will need to ask one of those two people to make this request.

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
This is an obsolete project and will NOT be migrated to OCP 4.

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
Please scale down all pods at the time of the project removal.

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
Please delete all PVCs at the time of the project removal. There is no need to back up any data in the namespaces.

## Step 2
Confirm that you are aware that you are requesting to:
- [ x] Remove a project set 

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

## Step 3
Please provide the names of the namespaces to be deleted in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.

ocio-isb-secnews-dev
ocio-isb-secnews-test
ocio-isb-secnews-tools
ocio-isb-secnews-prod

**Comment by patricksimonian** [comment]
deleted!
