### ISSUE TITLE
Request for OpenShift access for Leo Gharapetian (Arctiq)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/devops-requests#907]
## Step 0
**Are you the product owner or technical lead?**
Yes, as Tech Lead for Arctiq team, requesting initial access for Leo to be on-boarded with cluster access.  At this time, no specific namespace access is needed.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Leo Gharapetian
* GitHub ID: 037g
* Business Email Address: leo.gharapetian@arctiq.ca
* Organization: Arctiq
* Project Role: Technical Delivery

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
invited!
