### ISSUE TITLE
Request for Keycloak Realm: TRACKS

### ISSUE THREAD

**Issue by victorchong** [BCDevOps/devops-requests#909]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. 
We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 0
We are currently undergoing management of SSO realm resources, as a result we will not onboard new teams for sometime.
Should you have urgent need for SSO/keycloak integration for your application, please connect with SSO Product Owner Vardhman at Vardhman.Shankar@gov.bc.ca

## Step 1
Are you new to RedHat Single Sign-On (Keycloak)? 
If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will create the initial account on Keycloak.

- https://dev.oidc.gov.bc.ca/auth/admin/idir/console
- https://test.oidc.gov.bc.ca/auth/admin/idir/console
- https://oidc.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: **TRACKS**

* OpenShift Project Set/s Info
  - Project set name: **9d10cb-dev, 9d10cb-test, 9d10cb-prod**
  - Namespace ID: **9d10cb**

* For existing Keycloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by nvunnamm** [comment]
@victorchong, could you please set up some time for the onboarding session. So that we can go through SSO application and a brief overview of your application.

**Comment by victorchong** [comment]
@nvunnamm: Yes, no problem. I sent an email to pathfinder@gov.bc.ca last Thursday with my contact information. Thank-you!

**Comment by victorchong** [comment]
FYI team: I just re-sent my contact details to pathfinder@gov.bc.ca. The title of the e-mail is "Issue 909 - Request for Keycloak Realm: TRACKS". Thanks!

**Comment by nvunnamm** [comment]
@victorchong, could you please set up 30 minutes time for the onboarding session with me. So that we can go through SSO application and a brief overview of your application.

**Comment by victorchong** [comment]
@nvunnamm OK. How do we set up the onboarding session? Will you e-mail me or schedule something in my Outlook calendar? Thanks!

**Comment by nvunnamm** [comment]
@victorchong I currently don't have the ability to look at the calendar. Please let me know your available time and we can jump on teams link.
https://teams.microsoft.com/l/meetup-join/19%3ameeting_NGNlNDU3NDgtYjUwMC00MDkzLThjOWMtM2I5MmUxODcyN2U0%40thread.v2/0?context=%7b%22Tid%22%3a%22b9fec68c-c92d-461e-9a97-3d03a0f18b82%22%2c%22Oid%22%3a%22dcdf8148-ed09-48ae-b62c-ff80d3b1bcb9%22%7d

**Comment by victorchong** [comment]
@nvunnamm Understood. I have sent you a calendar invite to your @gov.bc.ca e-mail address. I've also included a screenshot of my calendar, in case the time slot I suggested does not work for you. Thanks!

**Comment by nvunnamm** [comment]
Access provided to access realm-o-matic. Please follow step 5.

**Comment by victorchong** [comment]
@nvunnamm Thank-you very much! Realm "srmm7sdn" has been created for TRACKS.
