### ISSUE TITLE
OpenShift access - vcschuni

### ISSUE THREAD

**Issue by jamesmunro-BCGOV** [BCDevOps/devops-requests#911]
## Step 0
**Are you the product owner or technical lead?**

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Volker Schunicht
* GitHub ID: vcschuni
* Business Email Address: volker.schunicht@gov.bc.ca
* Organization: Ministry of Transportation and Infrastructure
* Project Role: Lead Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
invited!
