### ISSUE TITLE
Grant access for Test Account

### ISSUE THREAD

**Issue by NickCorcoranTest** [BCDevOps/devops-requests#913]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Nick Corcoran
* GitHub ID: NickCorcoranTest
* Business Email Address: nick.corcoran@gov.bc.ca
* Organization: DPD, DevOps and Cloud Services, Platform Services
* Project Role: Security Architect - test account

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Teeeechnically you're not supposed to request access for yourself like this, but if you poke me on RC on whatever to confirm your identity, I'll resent the invite.
