### ISSUE TITLE
Request to grant OpenShift access for user Clark Van Oyen and  Julie Van Oyen

### ISSUE THREAD

**Issue by pwei1018** [BCDevOps/devops-requests#92]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

Full name: Clark Van Oyen
GitHub ID: countable
Email address: clark@countable.ca
Organization: Countable
Project role: Developer
Projects: sbc-auth-*
 
Full name: Julie Van Oyen
GitHub ID: jvanoyen
Email address: julie@countable.ca
Organization: Countable
Project role: UX Researcher/Designer
Projects: sbc-auth-*

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
hey @pwei1018! julie has been invited, and clark is already a member of the appropriate github org so he should already be able to access openshift.

please remember that julie will need to accept her email invite!
