### ISSUE TITLE
read access to all realms in oidc.gov.bc.ca for NickCorcoran

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/devops-requests#926]
## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues

Make sure you have read the [FAQ](https://github.com/BCDevOps/devops-requests/).

## Step 2
Please answer the following questions about the new request type:

1. **What is it?** 
read access to all realms in oidc.gov.bc.ca
2. **Why should this be a new request type?** A good rule of thumb: Does this involve something you don't have the permissions to do? If the answer yes, you're probably good to go ahead!
Not new, just didn't see where else to ask for it...
3. **What information is required to fulfill this request?** Do you best here - the Platform Services team can help if you're not sure!
4. **What is the end result?** Please provide plenty of details about what the end result should look like.
I can see all realms in KeyCloak prod...

**Comment by mitovskaol** [comment]
I give my endorsement to this request.

**Comment by ShellyXueHan** [comment]
@nvunnamm Hi Niran, any updates on this one? Thx!

**Comment by nvunnamm** [comment]
@ShellyXueHan working on it.. as most clients don't have view-realm, view-clients, view-users roles assigned to them.

**Comment by nvunnamm** [comment]
@NickCorcoran, You should now have access to view realms in DEV and PROD.. But I couldn't find you in TEST.
