### ISSUE TITLE
Delete SSO realm p8jhnzlo

### ISSUE THREAD

**Issue by loneil** [BCDevOps/devops-requests#927]
## Step 0
**Are you the product owner or project admin/team lead?**
**Admin**
If not, you will need to ask one of those two people to make this request for you. 
We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  
**loneil**

## Step 2
Field the following information.

* Project Name: 
**RPAS Self Assessments**

*  Keycloak realm
  - Realm ID: 
**p8jhnzlo**

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

**Comment by nvunnamm** [comment]
@loneil Could you please let me know which environment this needs to be done on..

**Comment by loneil** [comment]
Hi @nvunnamm , this would be for all of them for p8jhnzlo dev, test, and prod.

**Comment by nvunnamm** [comment]
@loneil realm p8jhnzlo has been deleted in all environments.
