### ISSUE TITLE
Request to remove a duplicate user from Keycloak - kesjohns 

### ISSUE THREAD

**Issue by jhmccoll** [BCDevOps/devops-requests#934]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.

  Yes I am a Keycloak Realm Admin for realm vtkayq4c.
 John McColl... jhmccoll 

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?
- What result of debugging have you obtained that lead you to request an account removal?

User just joined Service BC in the Ministry of Citizens' Services and is receiving a user with kesjohns already exists error message when she attempts to login to our application The Q.

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ ] Confirm that user is ready to have the account removed from Keycloak
 
 Yes the user is aware and the account kesjohns may be removed now.

## Step 3
Field the following information.

* Username to be removed: kesjohns
* Realm ID where user is having problem login: vtkayq4c

**Comment by nvunnamm** [comment]
@jhmccoll, Could you please let us the environment ?

**Comment by jhmccoll** [comment]
Sorry.. this is production realm vtkayq4c
Thanks
John

**Comment by nvunnamm** [comment]
User removed please verify.

**Comment by jhmccoll** [comment]
I just confirmed with the end user that she was able to successfully login to The Q in production.  Thanks so much for the fast turnaround on this.  Much appreciated!!!!
Regards
John
