### ISSUE TITLE
Request to remove duplicate user - "user already exists" error

### ISSUE THREAD

**Issue by stephenhillier** [BCDevOps/devops-requests#935]
## Step 0
**Are you the Keycloak Realm Admin?**
If not, you will need to ask one of the admin user in your realm to make this request instead.
**yes**

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account? **User seeing "username already exists" error when trying to log into our application**
- What result of debugging have you obtained that lead you to request an account removal?  **as above**

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed:  CMADATHI
* Realm ID where user is having problem login:  gwells

**Comment by nvunnamm** [comment]
@stephenhillier,
Could you please confirm step 2 and also let us know the environment.

**Comment by stephenhillier** [comment]
Hi @nvunnamm , the environment is prod. I've emailed the user to let them know that their account on SSO needs to be reset.

**Comment by nvunnamm** [comment]
@stephenhillier Are we ok with deleting the user?

**Comment by stephenhillier** [comment]
@nvunnamm  They are not part of our realm so from our team's perspective that's not an issue. I assume it will be up to your team to confirm with other realm admins that their user will be deleted.

**Comment by arcshiftsolutions** [comment]
User has now been removed from the IDIR realm. I've noted it to Lindsay in RocketChat for the user to try again.
