### ISSUE TITLE
Request to remove a duplicate user from Keycloak - "user already exists" error

### ISSUE THREAD

**Issue by james-hollinger** [BCDevOps/devops-requests#939]
## Step 0
**Are you the Keycloak Realm Admin?**
**I am the realm administrator for PRIME, although this issue is not specific to my realm.**

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account? 
**Attempting to log into my IDIR jholling results in a "user already exists" error. However, this error appears to occur in the _IDIR realm_, not my application's realm. I have tried logging into several different realms, all of which produce this error. As well, this error occurs before returning to my application's realm: my user information does not appear in my application at all.**

![image](https://user-images.githubusercontent.com/39168456/111234069-04b7fa80-85ab-11eb-95d7-7fe2941d52df.png)

**The IDIR in question was originally provisioned ~2 years ago. It has been recently re-enabled, but also transferred to another ministry's purview. Presumably, the IDIR was given a new UUID and now keycloak is prompting me to merge the profiles together. However, I do not have have access to the credentials associated with the original account.**

- What result of debugging have you obtained that lead you to request an account removal?
**As this issue seems to be at the IDIR realm level, I don't think there is any troubleshooting I can do on my own.**

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [ x] Confirm that user is ready to have the account removed from Keycloak
**This IDIR is my own, used as a developer, and not linked to any user data in any production systems.  Removing just the old IDIR Identity Provider link is likely also an option if I am able to re-link the account afterwards.**

## Step 3
Field the following information.

* Username to be removed: jholling
* Realm ID where user is having problem login: IDIR realm

**Comment by nvunnamm** [comment]
@james-hollinger User has been removed please verify.

**Comment by james-hollinger** [comment]
I am still seeing the same issue

**Comment by james-hollinger** [comment]
@nvunnamm not sure if I have to tag you to trigger the bot

**Comment by nvunnamm** [comment]
@james-hollinger We have deleted you from IDIR realm in prod.. Could you please let me know your realm so that we can confirm your user?
We saw that your user getting created in IDIR realm and seems like issue is within your realm.

**Comment by james-hollinger** [comment]
@nvunnamm I see now the issue, I was testing in develop. Could you please remove the same user from the develop and test IDIR Keycloak realms as well?

**Comment by nvunnamm** [comment]
@james-hollinger Removed from Dev and test too now please verify.

**Comment by james-hollinger** [comment]
@nvunnamm issue seems resolved now, thank you.
