### ISSUE TITLE
Request to grant OpenShift access for user akroon3r

### ISSUE THREAD

**Issue by akroon3r** [BCDevOps/devops-requests#94]
## Step 0
**Are you the product owner or project admin?**
If not, you will need to ask one of those two people to make this request for you. We can't process requests from individuals to have themselves granted access.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Adam Kroon
* GitHub ID: @akroon3r
* Business Email Address: adam.kroon@nttdata.com
* Organization: Sierra Systems
* Project Role: Devops
* OpenShift Projects/Namespaces: 
COR-DYN-API test and prod (wyck1k-test and wyck1k-prod I think)

I was previously provisioned access to dev and tools, but I'm supposed to be supporting test over the holidays. @ChrisHoban is the project admin on this I believe.

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by akroon3r** [comment]
@ChrisHoban hopefully you see this, but could you sign off on this request. @TayGov is gone until Jan.2  and was showing me how to support the test namespace rabbitmq service if it goes down, but I don't have access to it. Thanks!

**Comment by caggles** [comment]
@akroon3r  You already have access to Openshift. If you're looking for access to a specific project, you'll need to have the project admin grant you access!
