### ISSUE TITLE
Request Access for Sharala

### ISSUE THREAD

**Issue by Fosol** [BCDevOps/devops-requests#954]
## Step 0

**Are you looking for access to the Openshift Console?** - yes

**Are you the Technical Lead?** - yes

**Do you actually need the team member to be a member of the organization?** - yes

## Step 4
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

## Step 5
Fill out the following fields

* Project Name: PIMS
* GitHub Org: bcgov
* Full Name: PIMS
* GitHub ID: @Sharala-Perumal
* GitHub Account 2FA Confirmed: yes
* Email address: Sharala.Perumal@gov.bc.ca
* Organization: IMB
* Project Role: Developer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo: https://github.com/bcgov/pims

**Comment by patricksimonian** [comment]
invited!

**Comment by Fosol** [comment]
Thanks
