### ISSUE TITLE
Openshift Access required for Argus Chiu

### ISSUE THREAD

**Issue by lmcclung** [BCDevOps/devops-requests#955]
## Step 0
**Are you the product owner or technical lead?**  Product owner

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.
Yes

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.  Done

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: 
* GitHub ID: argush3
* Business Email Address: argus@highwaythreesolutions.com
* Organization: BC Registries
* Project Role: Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by patricksimonian** [comment]
@lmcclung since you are not a member of BCDevops org , this request will require approval! 

@mitovskaol

**Comment by lmcclung** [comment]
@patricksimonian who does the approval?  One of the devs in my team ie. Thor Wolpert or Richard Armitage?  Are PO's usually members of BCDevops?

**Comment by patricksimonian** [comment]
Olena does :) that being said. I've noticed that @argush3 is already apart of the org. Thor has probably already made a devops request. 

If you did want to make more requests on your own behalf. We can invite you to the bcdevops org with another request
