### ISSUE TITLE
BCGOV GitHub Organization Membership for @naomiaro

### ISSUE THREAD

**Issue by matthieu-foucault** [BCDevOps/devops-requests#958]
Are you requesting to:
- [x] Invite a user
- [ ] Remove a user

Fill out the following fields

* Project Name: CAS 
* GitHub Org: bcgov
* Full Name: Naiomi Aro
* GitHub ID: @naomiaro
* GitHub Account 2FA Confirmed: yes
* Email address: Naomi.Aro@gov.bc.ca
* Organization: BC gov (IITD)
* Project Role: Developer
* GitHub Team to Join (if exists): 
* Existing GitHub Repo:

**Comment by patricksimonian** [comment]
invited

**Comment by matthieu-foucault** [comment]
@patricksimonian , @naomiaro says she didn't receive her invitation, only the BCdevOps one (#959)
