### ISSUE TITLE
OpenShift access request for @naomiaro

### ISSUE THREAD

**Issue by matthieu-foucault** [BCDevOps/devops-requests#959]
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Naiomi Aro
* GitHub ID: @naomiaro
* Business Email Address: Naomi.Aro@gov.bc.ca
* Organization: BC goc (IITD)
* Project Role: Developer

**Comment by patricksimonian** [comment]
invited!
