### ISSUE TITLE
DevOps Verifiable Credentials Namespace

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/devops-requests#96]
**Are you the product owner or technical lead?** YES

**Have you had an alignment meeting?** YES

Are you requesting to:
- [x] Create a project set
- [ ] Remove a project set

* Short Team/Organization Name: Next Gen App Security Project
* Product Short Name: DevOps Verifiable Credentials
* Product Full Name: Verifiable Credentials for Privileged Users on the DevOps Platform
* Product Description: This project will test the use of Verifirable Credentials Technology piloted by the Verifiable Organization's team led by John Jordan, to issue and manage credentials for privileged users on the Platform, e.g. sys admin access to Platform Tools.
* Desired Environments: tools, dev, test, prod
* GitHub Repository (if exists):  bcgov/vc-authn-oidc

## Step 5
Submit this ticket and email us the contact information.

**Comment by ShellyXueHan** [comment]
Project set created as `admgjk-tools`, `admgjk-dev`, `admgjk-test`, `admgjk-prod`. `esune` is the admin of all four namespaces.
Please check at https://console.pathfinder.gov.bc.ca:8443/console/projects.
For network security policy setup, please refer to https://developer.gov.bc.ca/Trust-No-One.
