### ISSUE TITLE
Request to remove a duplicate user from Keycloak - IDIR ARCHIU

### ISSUE THREAD

**Issue by sumesh-aot** [BCDevOps/devops-requests#961]
## Step 0
**Are you the Keycloak Realm Admin?**
Yes

## Step 1
Provide some background on the user account issue.
User receiving user already exists from the idir master realm

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed: ARCHIU
* Realm ID where user is having problem login: fcf0kpqr

<img width="881" alt="Screen Shot 2021-03-19 at 4 47 54 PM" src="https://user-images.githubusercontent.com/32399922/111852083-e7e53500-88d2-11eb-9c5e-7ecc2e0daafb.png">

**Comment by sumesh-aot** [comment]
@argush3 FYI

**Comment by nvunnamm** [comment]
@sumesh-aot, Is it just in dev ?

**Comment by sumesh-aot** [comment]
@nvunnamm Issue is there in dev and prod. Works in test.

**Comment by nvunnamm** [comment]
In dev and prod, the email is associated with the user. Where as in test email is not attached to the user.

**Comment by nvunnamm** [comment]
Removed user in Dev and prod. Please try now.

**Comment by argush3** [comment]
@nvunnamm @sumesh-aot thanks.  this is working for me now.  i can get into DEV now and PRD properly shows me forbidden screen.
