### ISSUE TITLE
Openshift access for @daine

### ISSUE THREAD

**Issue by dainetrinidad** [BCDevOps/devops-requests#963]
Hi! I'm attempting to transition/merge my github accounts...
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
* Full Name:  Daine Trinidad
* GitHub ID: @daine
* Business Email Address: daine.trinidad@gov.bc.ca
* Organization: BC Gov (IIT)
* Project Role: Developer

Is this access request both for OCP3 and OCP4? Thanks!

**Comment by patricksimonian** [comment]
wow you managed to get an account id with just your first name. Thats awesome!
