### ISSUE TITLE
bcgov/databc-admin requires admin access to orphaned repos

### ISSUE THREAD

**Issue by crigdongov** [BCDevOps/devops-requests#967]
**What:** DATABC Requires admin access to below repos.  

Please add: @bcgov/databc-admin as "admin" to below repos.

https://github.com/bcgov/smk-actions
https://github.com/bcgov/smk-helms

**Reason:** original ,maintainer has left the branch.

tagging: @gjlawran

**Comment by mitovskaol** [comment]
@caggles  Can you please action this today. Thanks!

**Comment by mitovskaol** [comment]
@databc-admin  have been added as Admin to the 2 repos above.
