### ISSUE TITLE
Please remove plevirs from IDIR

### ISSUE THREAD

**Issue by gil0109** [BCDevOps/devops-requests#968]
## Step 0
**Are you the Keycloak Realm Admin?* Yes
If not, you will need to ask one of the admin user in your realm to make this request instead.

## Step 1
Provide some background on the user account issue.
- What is the issue with the user account?  Person change last name.
- What result of debugging have you obtained that lead you to request an account removal?

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [X ] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed:  plevirs
* Realm ID where user is having problem login: vtkayq4c

**Comment by nvunnamm** [comment]
@gil0109 Is the user facing issue in all environments?

**Comment by gil0109** [comment]
I am not sure they tried,  But I if you can remove in all environments, that would be appreciated.

**Comment by nvunnamm** [comment]
@gil0109 I couldn’t find user plevirs in any of the environments.

**Comment by gil0109** [comment]
Sorry @nvunnamm   Here old IDIR is: paigwang  please remove it so she can use the new IDIR :)

**Comment by nvunnamm** [comment]
Removed. Please verify.
