### ISSUE TITLE
Request for Keycloak Realm: MALS2

### ISSUE THREAD

**Issue by kamorel** [BCDevOps/devops-requests#969]
## Step 0
**Are you the product owner or project admin/team lead?**
If not, you will need to ask one of those two people to make this request for you. 
We can't process realm requests except from individuals in these roles.

**Does the Admin User have an IDIR account?**
We use IDIR authentication for Realm Admin Users, so make sure there's a *valid IDIR* for the assigned realm admin.  

**Are you requesting for Identity Provider Update?**
If so, you need to be the realm admin. Then proceed to Step 3.

## Step 0
We are currently undergoing management of SSO realm resources, as a result we will not onboard new teams for sometime.
Should you have urgent need for SSO/keycloak integration for your application, please connect with SSO Product Owner Vardhman at Vardhman.Shankar@gov.bc.ca

## Step 1
Are you new to RedHat Single Sign-On (Keycloak)? 
If so, please indicate that in Step 4, we will setup an meeting with you and your team for an on-boarding meeting. 

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.

When you login, you will see a "_Forbidden_" message, but this is expected behaviour and will create the initial account on Keycloak.

- https://dev.oidc.gov.bc.ca/auth/admin/idir/console
- https://test.oidc.gov.bc.ca/auth/admin/idir/console
- https://oidc.gov.bc.ca/auth/admin/devhub/console

_Please note that if the Realm Admin User has not completed this step, he/she will not be granted the role for the realms._

## Step 3
Field the following information.

* Project Name: Min of Ag Licensing System 2 (MALS2)

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - Namespace ID: 30245e-dev, 30245e-test, 30245e-prod

* For existing Keycloak realm update only
  - Realm ID: 
  - Identity Provider to Add
    - [ ] BCeID
    - [ ] GitHub
    - [ ] BCSC

## Step 4
Submit this ticket and email us the contact information.

For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Email to reach out for On-Boarding meeting invitation:
* link to the GitHub ticket you just created: 
* Admin user's IDIR account: 
* Admin user's Business Email Address: 

Please note that we will only start processing your request when the email has been received.

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by nvunnamm** [comment]
@kamorel, Could you please schedule 30mins for onboarding session based on your availability.

**Comment by kamorel** [comment]
@nvunnamm If it's possible for tomorrow, 11am? Or anytime in the afternoon I can make available.

**Comment by nvunnamm** [comment]
Yes, 11 am tomorrow works.

**Comment by kamorel** [comment]
Great. Thank you.

**Comment by nvunnamm** [comment]
@kamorel, If you don’t mind could you please send the link to the 11 am meeting ?

**Comment by kamorel** [comment]
@nvunnamm Apololgies. [Microsoft Teams meeting link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MmY0OTBjMTQtNmFhNy00OWE5LWIyNmQtNTcyOTNiNmM0MDA5%40thread.v2/0?context=%7b%22Tid%22%3a%220d413f05-310c-4aad-8859-8943f3ded1f0%22%2c%22Oid%22%3a%22960748eb-68dc-4d1e-a0e3-2e448d89253d%22%7d)

**Comment by nvunnamm** [comment]
@kamorel, Please let us know if you have decided against creating a new realm vs using an already existing realm as per discussion in the onboarding session. Thanks.

**Comment by kamorel** [comment]
@nvunnamm, at this time we are going with the existing realm with IITD. Thank you.
