### ISSUE TITLE
Kibana Access

### ISSUE THREAD

**Issue by parc-jason** [BCDevOps/devops-requests#97]
I have access to console.pathfinder.gov.bc.ca, and I can reach kibana.pathfinder.gov.bc.ca, but I cannot do anything in kibana.

`Error: no permissions for [indices:data/read/search] and User [name=parc-jason, roles=[gen_user_840a13c4d40da5504ae44f64e2a9433c48d1e8b6, gen_kibana_840a13c4d40da5504ae44f64e2a9433c48d1e8b6]]: [security_exception] no permissions for [indices:data/read/search] and User [name=parc-jason, roles=[gen_user_840a13c4d40da5504ae44f64e2a9433c48d1e8b6, gen_kibana_840a13c4d40da5504ae44f64e2a9433c48d1e8b6]]`

I need some roles and permissions.

**Comment by ShellyXueHan** [comment]
@parc-jason do you have access to the namespace? Kibana uses the same rbac from the namespaces. If you go to the logs of any of the deployments there, you will see the button `View Archive`. You could try again from there.

**Comment by parc-jason** [comment]
@ShellyXueHan  - looks like @wmhutchison got our team sorted out.
Thanks so much.
