### ISSUE TITLE
Request for BCDevOps Repo 

### ISSUE THREAD

**Issue by poornima-sivanand** [BCDevOps/devops-requests#970]
## Step 1
Are you requesting to:
- [x] Create a public repo in bcdevops org

## Step 2
Fill out the following fields. For security purpose, please provide the following contact information to the email address - pathfinder@gov.bc.ca

* Project Name: OpenShift Resource Research
* GitHub Org: bcdevops
* Details on choosing private repo: NA
* Preferred name for repo: openshift-quota-rec
* Expected date to move to public: NA
* GitHub ID for repo owner: @poornima-sivanand 
* GitHub Account 2FA Confirmed: yes 
* Email address: poornima.sivanand@gov.bc.ca
* Organization: BCDevExchange
* Project Role: Technical Lead
* GitHub Team to Join (if exists): NA

@ShellyXueHan : This is related to OpenShift Metrics research @juhewitt and I are working on.

**Comment by juhewitt** [comment]
@ShellyXueHan  bump.  Anything you need @poornima-sivanand and I to do?

**Comment by ShellyXueHan** [comment]
@mitovskaol 's approval :P

**Comment by juhewitt** [comment]
@mitovskaol 's approval...oh really... ?  ;). LOL>. Olena, can @poornima-sivanand and I please have this repo pretty please?  We're already working out of her own one... ;)

**Comment by ShellyXueHan** [comment]
just to confirm, do you need a public or private repo in bcdevops? public repos don't need a request, should be able to create it directly.

**Comment by ShellyXueHan** [comment]
okay my bad, turns out that in `bcdevops` we've disabled repo creation for members... Also confirmed with Poornima that only a public repo is needed. @poornima-sivanand here you go https://github.com/BCDevOps/openshift-quota-rec
