### ISSUE TITLE
Grant Labour Relations Board OpenShift namespace access for Lara Anderson

### ISSUE THREAD

**Issue by lara-anderson** [BCDevOps/devops-requests#972]
## Step 0
**Are you the product owner or technical lead?** Yes - product owner
We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?** yes
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?** yes
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Lara Anderson
* GitHub ID: lara-anderson
* Business Email Address: lara.anderson@lrb.bc.ca
* Organization: Labour Relations Board
* Project Role: Product Owner

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by caggles** [comment]
Hi @lara-anderson - you can't normally request membership for yourself without approval. I'll go ahead and mark this ticket as pending for approval, but if you have a team lead or somebody who can open a new ticket on your behalf, that might be faster!

**Comment by lara-anderson** [comment]
Thank-you,
I totally understand and I have forwarded the link to Olena Mitovska for approval (this is a brand new site and I am the product owner).  I hope that is sufficient and appreciate your getting back to me so quickly!

Thanks very much,

Lara
Tel: 604-623-6564

The Labour Relations Board acknowledges the traditional territories of the many diverse Indigenous Peoples in the geographic area we serve. With gratitude and respect, we acknowledge that the Board’s office is located on the traditional unceded territories of the Coast Salish peoples, including the territories of the xʷməθkʷəy̓əm (Musqueam), Skwxwú7mesh (Squamish), and səlil̓wətaʔɬ (Tsleil-Waututh) Nations

**Comment by patricksimonian** [comment]
Hi @lara-anderson i've invited you to the BCDevops org. This will allow you to login to Openshift. Do you have a technical lead that can invite you into your namespaces?

**Comment by caggles** [comment]
I'm going to assume all is well and that you're able to get the appropriate access to your namespace. If you can't, poke your technical lead, or jump onto rocketchat to ask about it in #devops-howto!

**Comment by rloisell** [comment]
@caggles / @patricksimonian - could you please re-open and re-send this request. It was sent while @lara-anderson  was on vacation and it had expired by the time she was able to respond to it.

**Comment by lara-anderson** [comment]
Hi @caggles / @patricksimonian - are you able to re-send the invite to BCDevops org?  I was out of the office when it was initially sent and the link had expired prior to my return.  Thanks so much
