### ISSUE TITLE
Request OCP4 Access - New PO

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [BCDevOps/devops-requests#974]
## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Terry Lanktree
* GitHub ID: @TerryLanktree
* Business Email Address: terry.lanktree@gov.bc.ca
* Organization: DataBC
* Project Role: PO

**Comment by patricksimonian** [comment]
invited!

**Comment by SteveChapmanBCDX** [comment]
@patricksimonian - great, thanks for that!
