### ISSUE TITLE
Request for User Access

### ISSUE THREAD

**Issue by ZachWoodward** [BCDevOps/devops-requests#976]
## Step 0
**Are you the product owner or technical lead?**
We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
If not, create one, setup your name and associate it with your business email address.

**Do you have 2-factor-authentication enabled with your GitHub account?**
If not, configure that first.

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: Adam Coard
* GitHub ID: acoard-aot
* Business Email Address: adam.coard@aot-technologies.com 
* Organization: AOT Technologies
* Project Role: Developer

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by mitovskaol** [comment]
@ZachWoodward   acoard-aot GitHub ID is already a member of BCDevOps org in GitHub which grants its members access to the Openshift 4 Console. In order for  acoard-aot to access your project in the Console, you, as a PO who has the admin access to the project namespaces, have to grant access to acoard-aot in **all 4 project namespaces - DEV, TEST, TOOLS and PROD.  Alternatively, your Tech Lead, who also has the admin access , can do that.
