### ISSUE TITLE
Request to remove a duplicate user from Keycloak - IDIR TRVSCNT6

### ISSUE THREAD

**Issue by ychung-mot** [BCDevOps/devops-requests#988]
## Step 0
**Are you the Keycloak Realm Admin?**
Yes

## Step 1
Provide some background on the user account issue.
User receiving user already exists error

## Step 2
Deleting the user account from Keycloak will also remove records with any other application using Keycloak that the user has logged into. So before proceeding with this request, make sure the user is aware of the consequences!

- [x] Confirm that user is ready to have the account removed from Keycloak

## Step 3
Field the following information.

* Username to be removed:  TRVSCNT6
* Realm ID where user is having problem login: kmas316h
* Environment in which you are facing issue: TEST

**Comment by nvunnamm** [comment]
user removed please verify.
