### ISSUE TITLE
Request for OpenShift access; Github Optimization Project

### ISSUE THREAD

**Issue by junminahn** [BCDevOps/devops-requests#990]
**Please provide answers to all the questions below to ensure your request is processed without any delays.** 

## Step 0
**Are you the product owner or technical lead?**
We do not allow users to request access for themselves.
Someone who is already a member of the BCDevOps Github org must request access for you, preferably your PO or technical lead.

If you are a PO or technical lead and are the first person on your team to request access, continue with opening this ticket, and then
contact @mitovskaol (Olena Mitovska) through RocketChat or BCGov email with the URL of the ticket so that she can approve this request.

**Do you have a GitHub account?**
**Yes.**

**Do you have 2-factor-authentication enabled with your GitHub account?**
**Yes.**

## Step 1
Are you requesting to:
- [x] grant user access
- [ ] remove user access

## Step 2
Fill out the following fields

* Full Name: **Junmin Ahn**
* GitHub ID: **junminahn**
* Business Email Address: **junmin@button.is**
* Organization: **Button Inc.**
* Project Role: **Technical lead**

**Note** that the platform services team will be removing OpenShift project access for users that are not active for six months. Once the access has been removed, a new `Access Request` has to be made by the product owner.

**Comment by ShellyXueHan** [comment]
@junminahn you should have access to openshift cluster now with the GitHub account.

**Comment by junminahn** [comment]
@ShellyXueHan  Thank you for taking my request.
Is it an access grant to an existing namespace or I will have a new namespace on OpenShift?

**Comment by ShellyXueHan** [comment]
no this is just to give you access to the openshift cluster, but not to any specific namespace. Are you also requesting for an OpenShift project set (namespaces)? If so, please select `OCP4 Project Set Requests, Annotation Updates, and Quota Changes.` from the issue templates.

**Comment by junminahn** [comment]
Thank you for the reply, It seems I need an IDIR account to request a new namespace on https://registry.developer.gov.bc.ca/public-landing. I will make a request once I have IDIR access.

**Comment by ShellyXueHan** [comment]
sure. if you have issue getting an IDIR account, pls have your product owner (who is expected be a gov employee) making the request on Registry instead.

**Comment by junminahn** [comment]
yes, I will contact the PO to get us the access, thanks again!
