### ISSUE TITLE
Request FOM repos on SonarCloud

### ISSUE THREAD

**Issue by basilv** [BCDevOps/devops-requests#992]
## Step 0
**Is your repository on `bcgov` GitHub Organization?**
We have installed SonarCloud on `bcgov` GitHub Organization for application teams to use. Only repositories inside the bcgov GitHub Organization are supported through this request.

**Are you the admin user of the GitHub repositories?**
The request requires a repository administrator to make the request. The requestor will be assigned as the SonarCloud repository admin. Requests from a non-admin user will be closed.

## Step 1
Login to SonarCloud console with your GitHub account https://sonarcloud.io/organizations/bcgov-sonarcloud/projects. Double check at https://sonarcloud.io/account/organizations to make sure `bcgov` GitHub organization is the current org. For debugging, please check if you are a member of bcgov GitHub Organization.

***Note:*** Find out more details and instructions here: https://github.com/BCDevOps/sonarqube/tree/master#sonarcloud

## Step 2
Fill out the following fields

* Project Name: 
* GitHub repositories to add to SonarCloud:
- https://github.com/bcgov/nr-fom-api
- https://github.com/bcgov/nr-fom-public
-  https://github.com/bcgov/nr-fom-admin

## Step 3
To invite other team members onto sonarcloud, make sure the users have completed Step 1. The SonarCloud repository admin user could further assign roles.

**Comment by basilv** [comment]
Project names in SonarCloud can just mirror the git repos with prefix "nr-"  if desired to scope to ministry: nr-fom-api, nr-fom-admin, nr-fom-public

**Comment by ShellyXueHan** [comment]
@basilv I've just invited you to `bcgov` Github organization.  pls accept the invite first so I can make you admin for the sonarCloud projects.

**Comment by basilv** [comment]
Thanks, I signed up.

**Comment by ShellyXueHan** [comment]
okay now you should be able to see the projects: https://sonarcloud.io/organizations/bcgov-sonarcloud/projects
