### ISSUE TITLE
Remove OCP3.11 BC Services Card Broader Public Sector Self Service

### ISSUE THREAD

**Issue by zsamji** [BCDevOps/devops-requests#994]
## Step 0
**Are you the Product Owner or Technical Lead?**
ZS: Yes - Product Owner

**Have you migrated all workloads including production from the OCP 3.11 namespaces to the OCP 4 Silver cluster?**
ZS: Yes

**Have you scaled down all pods to 0 in all 4 project set namespaces - dev, test, tools and prod ?**
ZS: Yes; 

**Have you deleted the persistent volume claims in all 4 project set namespaces - dev, test, tools and prod ?**
ZS: Yes; 

## Step 1
Make sure no duplicated request exists, search here:
https://github.com/BCDevOps/devops-requests/issues
ZS: No duplicate issues

## Step 2
Confirm that you are aware that you are requesting to:
Yes

**Note: There is no rollback or restore of the deployments once a namespace is deleted.

## Step 3
Please provide the names of the namespaces to be deleted in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.
ZS:
oultzp-dev
oultzp-tools
oultzp-prod
oultzp-test

**Comment by ShellyXueHan** [comment]
@zsamji there are still persistent volume claims not yet deleted. please make sure Step 0 is all completed! Thx!

**Comment by zsamji** [comment]
@ShellyXueHan Hi Shelly there was one persistent volume I removed. Can you tell me how many you see as remaining? If there's more, I will likely need a 15 minute with someone to help me make sure I removed correctly. Please advise :)

**Comment by ShellyXueHan** [comment]
@zsamji there are more and you would be able to see then with the admin access as well. see here: https://console.pathfinder.gov.bc.ca:8443/console/project/oultzp-prod/browse/storage for the list. lmk if you need help finding/deleting them!

**Comment by zsamji** [comment]
@ShellyXueHan Thanks that was super helpful. I think if deleted everything in all domains. keep me posted on what you need from me.
