### ISSUE TITLE
Request for an SSO Realm

### ISSUE THREAD

**Issue by SteveMHoward** [BCDevOps/devops-requests#998]
## Step 0
**Are you the product owner or project admin/team lead?**
Yes

**Does the Admin User have an IDIR account?**
Yes

## Step 1
Are you new to Single Sign-On (Keycloak)? 
No

## Step 2
Ask the Realm Admin User to login to each of the following links using the **IDIR credentials**.
Done

## Step 3
Field the following information.

* Project Name: GDX WordPress

* OpenShift Project Set/s Info
  - Project set name:  (please provide the namespace name in the form of a 6 character alphanumeric code followed by the environment, like so: a1b2c3-prod.)
  - Namespace ID: 23576a-prod, 23576a-test, 23576a-dev

* For existing Keycloak realm update only
  - Identity Provider to Add
    - [X ] BCeID (Basic, Business, Business and Basic)
    - [ ] GitHub
    - [ ] BCSC

## Step 5
After we have completed processing your request, you can proceed to creating a realm at [Realm-O-Matic](https://realm-o-matic.developer.gov.bc.ca)

**Comment by nvunnamm** [comment]
@SteveMHoward,
you should now have access to realm-o-matic please follow step 5.

**Comment by nvunnamm** [comment]
@SteveMHoward could you please provide me with Realm id for the project?

**Comment by SteveMHoward** [comment]
@nvunnamm 
bsloojh0

**Comment by nvunnamm** [comment]
@SteveMHoward could you please confirm which of the following type of BCeID should be applicable to your realm:
[ Basic BCeID only ]
[ Business BCeID only ]
[ Basic BCeID + Business BCeID combined ]

**Comment by nvunnamm** [comment]
Basic BCeID + Business BCeID combined IDp has been added to dev and test environment of the realm. Waiting for IDIM team's approval for proceeding onto Prod.
